### ISSUE TITLE
[Blitz FFA/16] Gladiators

### ISSUE THREAD

**Issue by Diamyx** [OvercastCommunity/CommunityMaps#101]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Gladiators

## Gamemode & Map Description  
16 players, 1v1 single elimination blitz

this map is really old but i think people kill each other then the winner steps into a portal to the next arena and their kit gets upgraded (leather->chain->iron->diamond)

no structure module required

## Team Sizes
16 lads ready and willing to fight to the death

## Screenshots
https://i.imgur.com/22zp1Kb.png

# XML
https://gist.github.com/Diamyx/c30f8de0027742fd6b243e8a18ebae4d

# Map Image
![map](https://user-images.githubusercontent.com/8431616/103486923-0e362100-4e0a-11eb-8ae4-0284aba17328.png)

# Download Link
http://www.mediafire.com/file/j2uuezjx71p78ku/Gladiators.zip/file

**Comment by CrazyisCreeps** [comment]
Seems like a cool map, I'll load it up to give it a try!

Seems like it's pretty much locked to the 1v1 format eh? Do you think there would be some other method to distinguishing who wins an arena if we wanted support for 2v2s or something?

**Comment by Diamyx** [comment]
@CrazyisCreeps could try with a hill per arena that can only be captured if there are no enemies on it

the biggest problem with this map is spawncamping if one player enter the next arena before his opponent, we'll try to figure out a fix for this

**Comment by CrazyisCreeps** [comment]
K forget trying to get more people to fit for the time being, it totally breaks if someone leaves, maybe there's an easy to way to fix that. 

Also yea spawn camping is an issue of course

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/c80fe87cb5afe961036a85707754658bcc9f3ef9 (before but history is lost)

**Comment by Cazadorian** [comment]
The map in its current state has the issue mentioned by Crazy of it breaking if someone leaves, and thus is unlikely to ever properly work on the server. As it seems like this won't ever be fixed I'll close this issue for now, but can reopen it in future if it does get fixed.
