### ISSUE TITLE
[CTW/40v40] Green Gem CTW

### ISSUE THREAD

**Issue by Jussssst** [OvercastCommunity/CommunityMaps#102]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x ] I have created an XML file
- [x ] I have created an map image
- [x ] I have uploaded the map zip file to a file sharing service
- [x ] The map has been tested locally to make sure it works

# Map Name
Green Gem CTW

## Gamemode & Map Description  
Green Gem is a large CTW map for a bigger rotation like the mega pool.
The woolrooms have a unique arrangement and the map uses different heights to hopefully assure fun gameplay.
We decided to stick with an very old fashioned building style by using blocks that are in the game for a long time and we hope it brings a nostalgic feeling to the players even though this is a new map. We started working on the map because we had the opinion that the MEGA pool doesnt have enough CTW maps and that there is a lack of CTW maps in that size.

## Team Sizes
There are 2 teams (lime and orange) and the map is made for 80 players in total (40v40)

## Screenshots
Here are some screenshots of the map: https://imgur.com/a/FTLyYir
And a video about a tnt feature: https://imgur.com/Thna1aw

# XML
Here is the XML download: https://www.dropbox.com/sh/nr4h3gvj2raoxkr/AADn58hGTaWh0o0e8EFdXnkoa?dl=0&preview=map.xml

# Map Image
![GreenGemCTW](https://user-images.githubusercontent.com/69433766/103492301-333a8c00-4e2a-11eb-8805-dcf9e8c3473f.png)

# Download Link
Here is the map download: https://www.dropbox.com/sh/nr4h3gvj2raoxkr/AADn58hGTaWh0o0e8EFdXnkoa?dl=0

**Comment by CrazyisCreeps** [comment]
Incase you missed this on discord, looks like some of the xml may be off https://discord.com/channels/86514356862320640/752217058112176308/796127116193955891

**Comment by rockymine** [comment]
> Incase you missed this on discord, looks like some of the xml may be off https://discord.com/channels/86514356862320640/752217058112176308/796127116193955891

Nope, we didn't 😄 I figured that this was an issue with the bedrock below the map: There were two rows of bedrock missing on the frontline, hidden by the outer blocks that were there (wasn't me who f'ked up). Anyways, here is a dropbox link: https://www.dropbox.com/s/vs05mih8v6sku9t/Green%20Gem%20CTW.zip?dl=0 The file however only contains the region information as I couldn't be bothered to add the xml in there as well.

**Comment by rockymine** [comment]
Ruediger updated the xml. Here is the new dl including the xml: https://www.dropbox.com/s/vs05mih8v6sku9t/Green%20Gem%20CTW.zip?dl=0 (still the same as above)

**Comment by master00ofdsiware** [comment]
This map has been added to the map pools.
