### ISSUE TITLE
[TDM w/ TNT 40v40] Explosive Vengeance

### ISSUE THREAD

**Issue by HardstyleRaver2** [OvercastCommunity/CommunityMaps#107]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Explosive Vengeance

## Gamemode & Map Description  
TDM map with scoreboxes

## Team Sizes
40v40

## Screenshots
https://imgur.com/a/kk4HMkC

# XML
The XML file is included in the download link

# Map Image
https://imgur.com/a/TJyU9kv

# Download Link
https://www.dropbox.com/s/4zwfab8d88he4tz/explosive_vengeance.zip?dl=0

**Comment by technodono** [comment]
this map kinda reminds me of retaliation 2... was that your inspiration?

**Comment by master00ofdsiware** [comment]
15 minutes seems like an excessively long time limit, should probably be 10 instead.

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/c80fe87cb5afe961036a85707754658bcc9f3ef9 (before but history is lost)

**Comment by Cazadorian** [comment]
We're unlikely to ever use this map for the main pool due to the map's size and a general phasing out of TDM heavy maps. The map will likely just remain only used for sponsoring and staff events. Thank you for the submission
