### ISSUE TITLE
[DTC/32v32] Drow's Crevice III

### ISSUE THREAD

**Issue by HardstyleRaver2** [OvercastCommunity/CommunityMaps#108]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Drow's Crevice III

## Gamemode & Map Description  
It is a DTC map with TNT. It takes place in the caverns and has measures to prevent OP tunneling from occurring. It has been tested a lot, and it has generally been liked from what I have remembered.

## Team Sizes
32v32

## Screenshots
https://imgur.com/a/hKMYYnl

# XML
XML is in the download

# Map Image
https://imgur.com/a/Z4eJBoT

# Download Link
https://www.dropbox.com/s/62u5pu0juevtbzk/Drow%20Crevice%20III.zip?dl=0

**Comment by HardstyleRaver2** [comment]
All right, here's a hot fix for my map. I added more TNT supplies to the map and added item remove to the players' tools, weapons, and torches. Here it is: https://www.dropbox.com/s/fsomctfyukxbgwb/Drow%20Crevice%20III.zip?dl=0

**Comment by master00ofdsiware** [comment]
Looks good to me. Added it to the map pools.
