### ISSUE TITLE
[3 TEAM CTW/20v20v20] TRIDENTE

### ISSUE THREAD

**Issue by chleongithub** [OvercastCommunity/CommunityMaps#109]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [yes ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [ yes] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [yes ] I have created an XML file
- [es ] I have created an map image
- [yes ] I have uploaded the map zip file to a file sharing service
- eys[ ] The map has been tested locally to make sure it works

# tridente
What is the map called?

## 3 team ctw  
each team has to teleport to the other bases to fight and teleport back to their own base to capture the wool.

## 20v20v20
How many teams and how large are they?

## Screenshots
 [Imgur](https://imgur.com/a/ZbQ9nfU) with screenshots of the map.

# XML
[make](https://gist.github.com/chleongithub/4852c386e2399ee9139b5164ac55d841)

# Map Image
Please attempt to [make](https://i.imgur.com/skgSSTQ.png) a nice `map.png` and upload it by dragging it into this text box.

# Download Link
[download](https://www.dropbox.com/s/tmw3q2yq6rwvypb/Tridente.zip?dl=0) a

**Comment by CoWinkKeyDinkInc** [comment]
Looks pretty good, could you share a screenshot of a full top down view of the map?

**Comment by chleongithub** [comment]
https://www.dropbox.com/s/iff1d1zsrh98247/tridente1.1.1.zip?dl=0

**Comment by master00ofdsiware** [comment]
This has been added to the map pools, thanks for posting.
