### ISSUE TITLE
[KotF/20v20] Zipline

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#11]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Zipline

## Gamemode & Map Description  
The map is in the KOTF game-mode with the team-flag no re-spawn variant where the team with the flag cannot respawn until it is dropped.

The flag can spawn in 4 different locations: The top platform an the bottom trench + the side cubes. This makes it hard to know which platform the flag will spawn on. Teams will have to split up to ensure they have better chances to get the flag
This map took inspiration from superprism and supercube (please add supercube to rots 🥇) and adds a new zip-line mechanic using specific velocities and a bit of hacky coding. It works however and the too much velocity log can be ignored when being ran on the server. 

The team colours which I wanted really bright unfortunately can't exactly match with the chat colours :( It would be nice if the team colours could be kept as it keeps with the vibrant colours theme. 

## Team Sizes
The team sizes are 20 with a max of 24 when overflow is on

## Screenshots
old:
https://imgur.com/a/Lk01s0F

# XML
https://gist.github.com/technodono/44fe13535f4b115c936f4f8bc2359964

it is also included with the world download

# Map Image
![map](https://user-images.githubusercontent.com/22761234/90976168-28b7de00-e57e-11ea-9834-570224790a64.png)

NEW!

![map](https://user-images.githubusercontent.com/22761234/91659374-769a8c00-eb12-11ea-820e-22ce0e4501ed.png)

# Download Link
[Zipline.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5113810/Zipline.zip)

old 1.0.1 download:

[ZiplineV2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5146775/ZiplineV2.zip)

Newer new download for 1.0.1 xml & map:

[Zipline 1.0.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5150233/Zipline.1.0.1.zip)

Release 1.0.2

[Zipline 1.0.2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5161565/Zipline.1.0.2.zip)

# Patch notes

**1.0.3**

- Fixed up all of the zip-line collision boxes so nobody should be getting stuck in the top tunnels :)
- Fixed up launch pads for all 4 top zip-lines as collision was incorrect there too
- Map back tubes are now sealed off
- Block on ziplines were changed to look more obvious

[Zipline 1.0.3map.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5217614/Zipline.1.0.3map.zip)

**Comment by fixitqixit** [comment]
I will load this up and test it. I'm not sure if theres much more feedback I can provide at this time without seeing it actually play.

**Comment by fixitqixit** [comment]
Heres some suggestions I have for your map:
- Based on the size of the map I think the team sizes are too big. Maybe create more ziplines or spaces to run around?
- Some of the jump pads regions are not aligned properly. Pease go over all the jumpads to ensure the regions are correct.
- The ziplines above the map do not work with players who have a connection to the server over 100ms (or around this). I have a 250ms connection to the server and when I use the ziplines above the map I get skyrocketed all over the place. There should be barriers on all open ziplines to ensure this doesnt happen.
- The jump pad region for the center ziplines is too close to the spawn area. As soon as you jump down you get flung down the middle of the map. In a real game scenario I suspect this will be quite annoying and wont give players much control over where they want to go. It also exacerbates the maps choke point in the middle of the map. 
- There needs to be more food in spawn kits. Or potentially hunger should be disabled. There is already a lot going on with this map, the last thing a player wants to worry about is their health bar.

Looking forward to testing this again soon!

**Comment by technodono** [comment]
Based on the size of the map I think the team sizes are too big. Maybe create more ziplines or spaces to run around?

- I am happy to reduce the player count down to 15 or so players...

- Jumpads in the xml always have been acting weird for me and when using the right co-ordinates will shrink is size to 2x2 pads... I'm not sure if this is a bug or something with my co-ords but all jump pads are supposed to be a 3x3 wide area covering the pad

-I will add barriers to the above zippiness... I didn't realise the issue was that bad for high latency players considering I probs had 0 latency when play testing

- I will fix these central zippiness to be more playable

- I thought about hunger and I think i'll disable it cause it's a bit of a nuisance

**Comment by technodono** [comment]
Map fixes:

- fixed all jump-pads having incorrect bounding boxes
- top zip-lines are now enclosed (you can get caught in them very rarely... this is something that is unavoidable as of now but I plan to fix in a future update)
- fixed up xml
-made map bigger & added 2 new flag posts
- hunger is disabled.. hooray
- updated map.png in world download
- Middle zip-lines are now a bit further out from spawn

**Comment by Pugzy** [comment]
Provided some feedback via Discord DM for the above update. Again let me know when fixed and I'll push.
Made a few changes to the XML (nothing game changing just formatting), you'll be able to see this once updated in the repo.

**Comment by CrazyisCreeps** [comment]
Not sure if it's been mentioned, but I was playing this earlier today and I notice some of the alignment for the top ziplines don't quick line up and you often get caught halfway through.

**Comment by technodono** [comment]
@CrazyisCreeps I've noticed that too and am currently working on a bug fix for this

**Comment by technodono** [comment]
Ver 1.0.3 has been released... the changed xml can be found by clicking on the xml link

**Comment by fixitqixit** [comment]
@technodono In future when you have an update for the map please make a pull request and update it through github. This is easier for mapdevs to use and it also serves to streamline the process.

**Comment by technodono** [comment]
> @technodono In future when you have an update for the map please make a pull request and update it through github. This is easier for mapdevs to use and it also serves to streamline the process. For the moment I have updated the XML for v1.0.3.

@fixitqixit how might I pull request... when I got to the page it was difficult to understand what to select

**Comment by fixitqixit** [comment]
@technodono I think it requires cloning the community maps repo onto your own computer and then using the GitHub application. If you’re not very familiar with GitHub I suggest you look at a tutorial. Once you get the hang of things it’s quite easy to utilise. 

Absolutely no worries if you struggle with using it, we can manually update the map for you. Keep in mind it may take longer for us to update your map this way if you decide to choose that option.

**Comment by Brottweiler** [comment]
Feedback from playing it just now, mostly about the arrow situation. IMO, arrows should be on `itemremove` and `killreward`. This will make the spawners not work, but unfortunately I don't think the spawners are useful. You don't have time or desire to use them like you do on Facility. You'll always have enough arrows, especially since stacks drop when you kill people, and there's no time either, you'll just get killed getting arrows most likely.

I know you said it was an attempt to break up those spots, but I think maybe something else should be done. What about _changing_ them to spawn **golden apples** instead? That will make them really useful.

**Comment by technodono** [comment]
@Brottweiler  That might actually be a smart idea...

**Comment by master00ofdsiware** [comment]
This was played tonight.

- Please fix the issue where players holding the flag can simply hide in their spawn and gain infinite points.

- I repeatedly got stuck in the purple zipline, please fix the regions.

**Comment by technodono** [comment]
Fixed... just gotta upload pull request soon

**Comment by technodono** [comment]
Than you for adding the map to the pulls, if this map has any further bugs, do me on discord
