### ISSUE TITLE
[KOTH/Scorebox/40v40] Ballot Box

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastCommunity/CommunityMaps#114]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Ballot Box

## Gamemode & Map Description  
A mixture of KotH and scorebox gamemodes. Uses the new reintroduced `owner-points` attribute that I have brought back to PGM.
In the first stage, it is an elimination game where players have to eliminate all of the enemies off of the state so they can capture it. Capturing the states gives you a set amount of points. Respawned players are teleported into a waiting lobby where they watch the map through a "TV" and get teleported to the next stage once the four states are captured. The surviving players are also teleported after touching the ground. It's a bit tricky since these things only work to players **entering** a region. In the second stage they get the regular TNT cannon sort of kit and everyone has to rush into the middle where they get three points after jumping into the ballot box. The first team to 270 points wins. It's like a meme map but I kinda put too much effort in the XML and PGM itself to do this xd

## Team Sizes
40v40

## Screenshots
![2021-01-14_00 42 42](https://user-images.githubusercontent.com/7586568/104566167-81117a00-560a-11eb-8f3a-6ea346373583.png)
![2021-01-14_00 44 03](https://user-images.githubusercontent.com/7586568/104566237-95557700-560a-11eb-97b7-da698a138340.png)

# XML
https://gist.github.com/CoWinkKeyDinkInc/e3150de0bc07c77d30a7b9d3e19d5f08

# Map Image
![map](https://user-images.githubusercontent.com/7586568/104566387-c46be880-560a-11eb-9b42-8b1d9f12fd45.png)

# Download Link
[Ballot Box.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5813310/Ballot.Box.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in #115

**Comment by master00ofdsiware** [comment]
This is a meme map. It will not be added to the map pools.
