### ISSUE TITLE
[CTW/16v16] SubZero

### ISSUE THREAD

**Issue by stuntguy3000** [OvercastCommunity/CommunityMaps#116]
### Checklist
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [x] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
SubZero

## Gamemode & Map Description  
This is a CTW map, both teams have two wool monuments to protect from the other side. The design is simple yet elegant, with a strong theme of frozen and cold colours and themes, combined with a logical and easy to learn layout. 

This map was designed to put a strong emphasis on strategy to defeat the opponents, as players must work together to capture the wool monuments. Being a smaller map, this is so important as it is incredibly easy for plans to go wrong or change at the last minute when going after monuments.

We believe this is a challenging, but fun and rewarding map to play on.

## Team Sizes
2 Teams, 16 Players Each

## Screenshots
[https://imgur.com/a/fiVsJEs](https://imgur.com/a/fiVsJEs)

# XML
[https://gist.github.com/stuntguy3000/5dd33162c29b41922e2e6dddb6eb770d](https://gist.github.com/stuntguy3000/5dd33162c29b41922e2e6dddb6eb770d)

# Map Image
![map](https://user-images.githubusercontent.com/1522389/105177672-eb7c6a00-5b76-11eb-9fd3-570cf6e3e7f4.png)

# Download Link
https://www.dropbox.com/s/p7m6ra5okp6jp2v/1.2.0.zip?dl=1

# Change Log
Version 1.2.0 (30/01/2021):
 - Rename map to SubZero from Sub-Zero
 - Ensure compliance with https://pgm.dev/docs/guides/xml-pointers/conventions
 - Remove first broadcast message regarding iron block regen
 - Reduce teams to 16 per side

Version 1.1.0 (20/01/2021):
 - Many issues in world fixed
	- Spawn updated
	- Added TNT
	- Added Bonus Chests
 - map.xml updated to latest PGM version featuring significant formatting changes
 - Map submitted to OvercastCommunity

Version 1.0.1 (10/12/2016):
 - Fix missing block at Purple wool room
 - map.xml cleanup

Version 1.0 (10/12/2016):
 - Initial Release

**Comment by rockymine** [comment]
yo, the map theme looks really nice as well as the layout. I think that the lanes will be way too narrow to hold 32 players per team however. You could change the team sizes to 16v16 or maybe enlargen the map. That's my first thoughts at least.

**Comment by stuntguy3000** [comment]
> yo, the map theme looks really nice as well as the layout. I think that the lanes will be way too narrow to hold 32 players per team however. You could change the team sizes to 16v16 or maybe enlargen the map. That's my first thoughts at least.

Thanks for your feedback!
We had a lot of debate internally regarding this very specific issue.

We decided to submit the map as 32v32 pending large scale playtesting which is out of our reach. We found in our tests when using 6 players. whilst the players were spread out, once everyone started building (especially over the 30 block void), the map felt empty. 

That being said, we can change to 16v16 with no issue if this is believed to be the best choice.

**Comment by stuntguy3000** [comment]
> You could change the team sizes to 16v16 or maybe enlargen the map.

Amending my previous comments, we have now taken this on board. @rockymine

**Comment by Pugzy** [comment]
The big "wow" of this map is the shape but as mentioned above it seems way too simplistic and small to work with even a small amount of players. In my opinion, the entire map should be scaled up by a factor of at least 2 and that you will have more room for detail in the terrain which is currently very basic in design and layout.

**Comment by CoWinkKeyDinkInc** [comment]
After playtesting the map, it got rushed quite quickly and it was hard to identify enemy players  I definitely would say that the lanes should be about 3 blocks wider. It is still a bit quite cramped even with 16v16 players. You should also consider extending the length it takes to get into the wool rooms.

**Comment by koodlelsoodley** [comment]
Sounds like you should make the map yourself then if you're going to be picky c:

**Comment by technodono** [comment]
> Sounds like you should make the map yourself then if you're going to be picky c

I don't think any of us are trying to be picky... were just identifying current issues with the maps so we can help you perfect your map and get it into pools. Don't except your maps to run smoothly... even my first maps took ~7 redesigns just it get it perfect.

I hope this help
~ Builder Technodono

**Comment by CoWinkKeyDinkInc** [comment]
> Sounds like you should make the map yourself then if you're going to be picky c:

We want to make all maps here viable to be in the pools or set frequently, and we believe that is also the goal of the mapmakers that post submissions. We only make critiques when we think it is necessary to improve the quality of the map. You don't have to take my word, @technodono has updated Space Base over a dozen times which you can see in the Pull Requests tab, which was a lot more tweaks than any of us asked for.

Please keep the comments here productive, creating a new (anonymous?) account for unproductive criticism is a waste of everyone's time.

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/c80fe87cb5afe961036a85707754658bcc9f3ef9 (before but history is lost)

**Comment by Cazadorian** [comment]
This map continues to have issues that were never addressed due to author inactivity and so will likely never be used for the pool. If another update is ever made for it we can reconsider this, but this seems very unlikely at this stage and therefore I'm just closing the issue. Thank you for the submission.
