### ISSUE TITLE
[CTW/12v12v12v12] Space Base

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#121]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Space Base

## Gamemode & Map Description  
This is the sequel to the popular map: zip-line... expect I've changed  a lot of things:

-  Replace zip-lines with massive spaceships with battle cannons that shoot players
- added a fast ring in the the map for fast paced wool capturing action
- The map is now a CTW map with a regenerating wool monument
- 4 teams better than 2 teams... proven [x]
- The theme is a space map

Space base... anew fast paced CTW map which has the definitive features of a CTW map while changing a few things:

- No bridging (finally a map without bridging)
- Wool monument (no more searching thru chests)
- Adds cool space team names based off the Greek alphabet

## Team Sizes
There a 4 teams and each team will have 12 players

## Screenshots
https://imgur.com/a/Ik2uv12

# XML
https://gist.github.com/technodono/49a7734d137738a5500c4023fef5744f

# Map Image
![map](https://user-images.githubusercontent.com/22761234/105621242-96cc3e00-5e59-11eb-8daa-63100b6b948e.png)

# Download Link (NEW!)
[Space Base.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5861649/Space.Base.zip)

# Changelog

- Fixed kill rewards and player safezones
- Tweaked some values

**Comment by technodono** [comment]
I'll eb updating the download very soon

**Comment by technodono** [comment]
I think space base is pretty close to being done... though I haven't received much updates on this soi IDK

**Comment by CoWinkKeyDinkInc** [comment]
Updated in #129 #141 #142 #152 #153 #155 #156 #164 #183 #186 #187 #212 #288 #289 #306 #311 and #312.

**Comment by technodono** [comment]
since this is going into pools very soon I'm gonna close this... also simply because alot of maps on the repo just need to be cleared so we can keep actuive submission neat & tidy
