### ISSUE TITLE
[TDM/8v8v8v8] Bomber Guys

### ISSUE THREAD

**Issue by Pe241** [OvercastCommunity/CommunityMaps#13]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Bomber Guys

## Gamemode & Map Description  
Theme: Bomberman

This is a 4 teams TDM which kills each other with explosion. No sword, no bow, but you have TNT and EGG grenade!
Match time is 8 minutes. After 4 minutes, Anvils fall down and block passages. Players must stay away from Black stained glass floor to avoid being crushed.
I hope everyone will enjoy this. :)

## Team Sizes
~~12vs12vs12vs12~~ →8v8v8v8

## Screenshots
[Imgur](https://imgur.com/a/PJp9gNp)

# XML
[Git Gist](https://gist.github.com/Pe241/16ea3211ebf105e1fc0ea0eb05be1a41)

# Map Image
![map](https://user-images.githubusercontent.com/18105767/91127438-38036c80-e6e1-11ea-92ff-459f540584bf.png)

# Download Link
[v1.0.0](https://drive.google.com/file/d/1EPigNqV7gQNq0TAMeff9rpLlbs77DdeJ/view?usp=sharing)
[v1.0.1](https://drive.google.com/file/d/1SDMOQCBogzL6vVxQxZ64vDgsYTZ891U_/view?usp=sharing)
[v1.0.2](https://drive.google.com/file/d/1ekeUwg-4rvCbAdV_kXE8B8N_PND7q67p/view?usp=sharing)

**Comment by master00ofdsiware** [comment]
Very creative idea!

**Comment by BGMP** [comment]
amazing

**Comment by Pe241** [comment]
### Updated to v1.0.1

### XML

- Added anvil in itemremove. (To prevent from dropping some anvils which was hit egg grenade while falling.)

- Fixed rules message & apply message.

- Expanded playable region. (y+2)

**Comment by fixitqixit** [comment]
Hey @Pe241! I just added this to the Community Maps repository. We just played our first game of it as well and here are a few of my suggestions:

- Significantly lower the time limit. The gameplay gets a bit stale after 5 minutes unfortunately. 
- More anvils and changing around of the map would be cool too within that time frame. Have you thought about making more monument modes and making more sandstone pillars appear/disappear throughout the game?
- Maybe less tnt and grenades in the spawn kit would mean there would be significantly less chaos across the map (which is incredibly loud and laggy), which would also allow for more strategic gameplay - which is something this map lacks opportunities for. 
- I'm not sure if its just me but some aspects of this map could do with more detail. Some parts of the built map look slightly bland and colour schemes dont match up very well. This is up to you but I would recommend capitalising on your block palette and extending its strengths to more parts of the map to make it more visually appealing.

I will hopefully provide additional feedback in the coming days/weeks. Good job though this is a very awesome concept and I can tell you've thought about this idea very hard. I'm looking forward to seeing more updates for this map and other new maps that I'm sure youre already working on!

**Comment by Pe241** [comment]
Thank you for testing my maps.
Updated to v1.0.2. Please check [pull request](https://github.com/OvercastCommunity/CommunityMaps/pull/18).

> Have you thought about making more monument modes and making more sandstone pillars appear/disappear throughout the game?
That's interesting, but can I change only the material of particular monument? In pgm.dev, It looks that all monuments except mode-change disabled  monument change at once...

**Comment by fixitqixit** [comment]
Alrighty just did another test of this map heres some feedback from both myself and other players:

- Less TNT in spawn kit, I recommend changing it to 16
- In my other feedback post I reccomended the following: "More anvils and changing around of the map would be cool too within that time frame. Have you thought about making more monument modes and making more sandstone pillars appear/disappear throughout the game?" I feel like this still needs to be done more regularly. 
- Also the message about being able to destroy melons with tnt should not be announced every few minutes, it only needs to be announced once
- People dont like (me included) the jump boost. I feel like players should be able to jump and block spam tnt if they want. This could make for more fun gameplay dynamics.

**Comment by Pe241** [comment]
@fixitqixit 

> More anvils and changing around of the map would be cool too within that time frame. 

I think it will be difficult to add anvils any more because it will affect the performance.
In fact, in my environment the screen freezes momentarily when the anvil begins to fall.

> Have you thought about making more monument modes and making more sandstone pillars appear/disappear throughout the game?

What's means? Erase the pillars around the base?
Already using mode-changes (barrier→air), the only operations that can be performed are to erase the barrier block.

The only things I can do is adding a falling sand or gravel floor, but this also affect performance, I think it's difficult.

**Comment by Pe241** [comment]
And, flowing water from walls to Interfere with player movement?

**Comment by fixitqixit** [comment]
> The only things I can do is adding a falling sand or gravel floor, but this also affect performance, I think it's difficult.

To prevent lag you could just have a layer of barrier blocks be removed and have pre-placed blocks fall onto the map? That would mean you wouldnt have to spawn the blocks in. We just played a round of this map and everyone enjoyed it but I'm still a major advocate for more falling anvils/blocks to make the map change more.

**Comment by Pe241** [comment]
@fixitqixit I saw test match few minutes ago, terrain data was not updated. I sent pull request again.

**Comment by Pe241** [comment]
Uh...What should I change in the next update?

**Comment by KingOfSquares** [comment]
Tried this today with the smaller teams, works great. I was thinking maybe one could make more "hot" areas. Right now its only in the middle, what do you think about having two areas similar to that instead? (Remember someone asking for more space, im guessing this will spread the chaos more?)

Just a thought, the map works good enough to put it into pools imo 👍

**Comment by Pe241** [comment]
@KingOfSquares Where are "two areas" you say?

**Comment by CrazyisCreeps** [comment]
Honestly it's a really unique idea, but the entire map seems to rely on TNT being fun and TNT running to spam it to also be fun. It's a little dry. I'm not sure what exactly could be done to improve it, if at all possible. 

To flip it around, I wonder what you think of the map and how it plays, and if you think anything could be improved?

**Comment by Pe241** [comment]
One of the ideas I have is to disable jumping to prevent people from spamming. I had once disabled, but [Qixit instructed me to enable it](https://github.com/OvercastCommunity/CommunityMaps/issues/13#issuecomment-691582432). What do you think about it? That's all I have ideas.

**Comment by master00ofdsiware** [comment]
> One of the ideas I have is to disable jumping to prevent people from spamming. I had once disabled, but [Qixit instructed me to enable it](https://github.com/OvercastCommunity/CommunityMaps/issues/13#issuecomment-691582432). What do you think about it? That's all idea I have.

My idea (after playing the map last night) was that maybe it would be more fun to have a ranged weapon (like a hoe) where you right click it and the primed TNT flies out? That way you could set a cooldown in XML, and you also wouldn't need to disable jumping as the cooldown would prevent TNT being spammed.

This could be accomplished using custom projectiles: https://pgm.dev/docs/modules/gear/projectiles

**Comment by Pe241** [comment]
> My idea (after playing the map last night) was that maybe it would be more fun to have a ranged weapon (like a hoe) where you right click it and the primed TNT flies out? That way you could set a cooldown in XML, and you also wouldn't need to disable jumping as the cooldown would prevent TNT being spammed.
> 
> This could be accomplished using custom projectiles: https://pgm.dev/docs/modules/gear/projectiles

Good idea!

**Comment by Pe241** [comment]
🏳
