### ISSUE TITLE
[FFA:Rage/40] Wanna Fly

### ISSUE THREAD

**Issue by Pe241** [OvercastCommunity/CommunityMaps#14]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Wanna Fly

## Gamemode & Map Description  
Theme: Flying PvP & Inside of the x16 blocks

This is a FFA:Rage map that players can fly like a creative mode.
Players must fly around the inside of blocks and be the top kill players in 8 minutes.
I wanna play flying PvP, so I made this. :)

## Team Sizes
~~36 Players (Max-overfill 38)~~ →40 players (Max-overfill 43)

## Screenshots
[Imgur](https://imgur.com/a/YR4Js83)

# XML
[Gist](https://gist.github.com/Pe241/661b7620258cfca7fa8051f488de35c0)

# Map Image
![WRKQiSelcbCiP5f1598818730_1598818764](https://user-images.githubusercontent.com/18105767/91668985-335d0f00-eb4c-11ea-9d8b-eb798d396662.png) (v1.0.0)
![map](https://user-images.githubusercontent.com/18105767/91885091-23ffd200-ecc2-11ea-8a18-5e0f20660719.png) (v1.0.1)

# Download Link
[v1.0.0](https://drive.google.com/file/d/1ziqKebr4Lpmw2GkoPfbOVrVLOVrOyQ0G/view?usp=sharing)
[v1.0.1](https://drive.google.com/file/d/1NAzwXzKyrl3pr1JL-WslelKexeUl6l70/view?usp=sharing)

**Comment by fixitqixit** [comment]
This looks so cool! Can't wait to test it out!

**Comment by fixitqixit** [comment]
This map is awesome to play on in my opinion. Excellent job. A lot of the players had similar feedback as well. I do have some suggestions I'd like to run past you though:

- Have you considered using projectiles or 'gun like' weapons in replacement of bows? Bows take a while to charge up and I feel like have not much use on the map. Projectiles are used on a lot of maps and I've actually seen them being used on maps that have made use of flying before (though a very long time ago). If not I think more arrows in the spawnkit would allow for more use of the bow.
- I feel like having jump pads at the bottom of each drop-down hole thingy would make it easier to travel across the map. 
- I dont see much point in having automatic respawns. Sometimes its fun to have the observing feature and allow players to fly around and choose when they respawn.
- The player limit can probably be extended slightly i reckon
- Jump boost should be increased by 1 I think just so its easier to time the jump between the holes in each cube
- This may be more aesthetic, but feel free to use real end and nether portals in the maps. They wont actually teleport players as only the overworld dimension is enabled.

These suggestions are honestly very nit-picky, this map is great and is essentially ready for many more fun games.

**Comment by Pe241** [comment]
Thank You for your feedback @fixitqixit .
I'll update later, but I would like to ask some questions before starting the update work.

- "Gun like" means using egg or snowball, right? Can these one shot kill in rage? How can I enable it? Add enchant to egg and snowball?

- You told that player limit can extended slightly, but I set spawn point with a room interval. The maximum number of point meet it is 38. If limit has extend, I can't help setting point in the next rooms... I think it may happen respawn kill, What do you think about it?

I'll decide whether change these considering answers.

By the way, I'm sorry for being persistent, when can I get feedback and go testing about my other maps? (Zombie Def, 2/4 palace, End Kingdom, and bomber guys) They have been left for about 1.5~2 weeks. I don't know whether my map are rejected and I need fix something or not...
I would like any response. :)

**Comment by fixitqixit** [comment]
Yep, the "gun like" feature/projectiles module can be one shot. Heres a sample XML that I've taken from docs.oc.tc:
`
<projectiles>
    <projectile id="lazer" name="lazer" projectile="Snowball" velocity="3.5" damage="50" throwable="false"  cooldown="5s"/>
</projectiles>


<kits>
    <kit name="lazer-kit">
        <item projectile="lazer" name="`alazer gun" material="stick"/>
    </kit>
</kits>`
I'm pretty certain the `damage="50"` is equivalent to 50 hearts damage, so in other words, instant kill.

Sorry I dont understand what youre saying in the second point, can you please rephrase?

Sorry about the wait for those maps. Theres a variety of reasons as to why no ones gotten back to you. I think its a combination (at least for me) that those maps are more complicated than Wanna Fly and the mapdevs being preoccupied with other submissions/mapdev stuff and just their lives outside of minecraft. I will endeavour to provide some feedback for your maps later this week, though I cant give any promises as to when this will be exactly.

**Comment by master00ofdsiware** [comment]
I believe he means that the map has 38 spawnpoints, so he's concerned that 2 players could spawn at the same point if the team sizes are raised.

Personally I would solve the spawnkilling issue by giving players resistance for several seconds when they respawn.

**Comment by Pe241** [comment]
> I believe he means that the map has 38 spawnpoints, so he's concerned that 2 players could spawn at the same point if the team sizes are raised.

Yes, that's exactly right.
I'll add more spawn points and change limits to 40 (max-overfill 43) in next update.

**Comment by Pe241** [comment]
### Updated to v1.0.1

### World

- Changed end portal blocks to end_portal from wool.
![2020-09-02_02 13 48](https://user-images.githubusercontent.com/18105767/91885417-b30cea00-ecc2-11ea-8ed5-5a3898e4ac71.png)
It's portal tp on obsidians in The End room.

- Changed world time to night from day. My client FPS has been improved.

### XML Changed

- TNT power. (2→4)

- Add more spawnpoint and changed max limit. (36→40, overfill 38→43)

- Regeneration effect duration. (3s→Infinity) Disabled being killed by non-instant death damage.

- Amount of Arrow (2→8)

- Disabled auto respawn and enabled spectate.

- Sword and Bow renamed. I heard that someone don't like magic fonts. :(

Details are in Git gist.

### Others

- Changed map.png

Please check v1.0.1, Thank you.

@fixitqixit 
>Sorry about the wait for those maps. Theres a variety of reasons as to why no ones gotten back to you. I think its a combination (at least for me) that those maps are more complicated than Wanna Fly and the mapdevs being preoccupied with other submissions/mapdev stuff and just their lives outside of minecraft. I will endeavour to provide some feedback for your maps later this week, though I cant give any promises as to when this will be exactly.

Sure. I'm looking forward it. Thank you for answer. :)

**Comment by Pe241** [comment]
Updated to v1.0.2
[Pull request](https://github.com/OvercastCommunity/CommunityMaps/pull/19)

**Comment by fixitqixit** [comment]
@Pe241 I'm going to give this map a few more tests but I'm pretty sure its near completion. Good work with the design and concept behind this map. I will likely close this Issue soon, but feel free to reopen it if you have any additional updates. 

If this map receives good feedback from tests I will consider adding it to the map pools!

**Comment by Pe241** [comment]
Closed this submission because of be adopted. Subsequent updates will be made in pull requests.
Thank you for adopting my map!
