### ISSUE TITLE
[DTM/14v14] Natsukashii

### ISSUE THREAD

**Issue by Antnecb** [OvercastCommunity/CommunityMaps#143]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Natsukashii

## Gamemode & Map Description  
This is a 14v14 DTM map I made a couple years ago. It's designed similar to old-style obsidian monument maps, particularly taking inspiration from Balloons DTM. There is also a gimmick where you have to get a diamond pickaxe from the spawners in mid in order to break the monument, except after 20 minutes, when the monument turns into emerald. You spawn with 7 gold nuggets which can be used to upgrade armor after collecting enough, and there is an enchantment table on each side to upgrade weapons, tools, and armor.

## Team Sizes
2 teams, 14v14

## Screenshots
[Album](https://imgur.com/a/BjgQl8x)

# XML
[Link](https://gist.github.com/Antnecb/c1d40308e6ae78006b04afd2071c1ff5)

# Map Image
![map](https://user-images.githubusercontent.com/26776253/108007039-f6d28200-6fca-11eb-9785-4fe848ff05ca.png)

# Download Link
[Download](https://drive.google.com/file/d/1_Fp0j5spU5pJS-Al8HsivII1eg3EJojJ/view?usp=sharing)

**Comment by rockymine** [comment]
Brottweiler will like this c:
looks very nostalgic

**Comment by calcastor** [comment]
Okay, I tested this locally, albeit briefly, and found no issues that would prevent it from being play tested. I've added it to the Community Maps repo in order for it to be play tested.

**Comment by master00ofdsiware** [comment]
Overall it's a nice little map, I like it. The main issue is that it's too easy for attackers to swarm the enemy monument and take over the building; I would suggest increasing the space between the islands, and considering other ways to make it take longer for attackers to get to the enemy's monument.

**Comment by calcastor** [comment]
In hopes of garnering a wider range of player feedback on several pending yet 100% functional community maps, I've gone ahead and added many of them to the pools. This map has been included in that, and I hope to be able to collect at least the most prevalent feedback on the each map to post in their respective issues pages.
