### ISSUE TITLE
[CTW/32v32] Columbia CTW

### ISSUE THREAD

**Issue by rockymine** [OvercastCommunity/CommunityMaps#144]
### Columbia CTW - a BioShock Infinite inspired map

This map was started (and finished) in early 2017. Theoretically this map is the second map of a series. A bit before I built this CTW version I built Columbia, a DTM map. Both maps are heavily inspired by the videogame BioShock Infinite. There's two teams battling in the sky. Here are some [images](https://imgur.com/a/oWgEJHo):

While we're at it... I proudly present you the first map that looks good from within the void as well 😄 

View from the top             |  View from the bottom
:-------------------------:|:-------------------------:
![](https://i.imgur.com/rK56Wob.png)  |  ![](https://i.imgur.com/fLnneyG.png)

# Map Image
![map](https://user-images.githubusercontent.com/8013626/108196585-8e45eb00-7119-11eb-8cd3-106300e0fe2b.png)

# [Download Link](https://www.dropbox.com/sh/9wm8228onu4bbj9/AACKOH2DAPEC9bEUACZXfDQCa?dl=0)
includes XML as well.

- [ x ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [ x ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [ x ] I have created an XML file
- [ x ] I have created an map image
- [ x ] I have uploaded the map zip file to a file sharing service
- [ x ] The map has been tested locally to make sure it works

**Comment by profbananaslug** [comment]
this is it right here, the best map. it's time to close map submissions because it can only be downhill from here.

**Comment by mxxtthias** [comment]
default kit can be dropped

**Comment by calcastor** [comment]
In hopes of garnering a wider range of player feedback on several pending yet 100% functional community maps, I've gone ahead and added many of them to the pools. This map has been included in that, and I hope to be able to collect at least the most prevalent feedback on the each map to post in their respective issues pages.

First one for this one though is that the wool room bows should probably be changed to Power I/Infinity in place of Power 2/Punch.

**Comment by calcastor** [comment]
issue was closed preemptively however I don't see any breaking issues with this map that would prevent it from staying in rotation. I've updated the map today to fix iron leggings not being craftable and the overpowered wool room gear, with the latter being the only notable issue prior to now, so should be good to stay in hecto. thanks for submitting!
