### ISSUE TITLE
[KOTF/20v20] Zipline: Moar Gunz Edition (april fools update)

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#159]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Zipline: Moar Gunz Edition

## Gamemode & Map Description  

This is basically zipline but I added gunz to it as an april fools reskin/update... I'm not palnning on updating this map as it is just an april fools thingo

## Team Sizes
20v20

## Screenshots
The map has not changed in looks at all!

# XML
https://gist.github.com/technodono/1025a8ea80e43e4fe64934188fafc934

# Map Image
![map](https://user-images.githubusercontent.com/22761234/111570780-a16fd780-87f9-11eb-9a79-674a75f54fe0.png)

# Download Link
[Zipline - Moar Gunz Edition.zip](https://github.com/OvercastCommunity/CommunityMaps/files/6161179/Zipline.-.Moar.Gunz.Edition.zip)

**Comment by CrazyisCreeps** [comment]
It looks cool, it reminds me of the Directrix with Gunz version. Have you thought about removing the bows completely to force people to use the fireball wand instead? I'm not sure how it would play in comparison, but it might make things more interesting and/or chaotic 😆

**Comment by technodono** [comment]
I did but I'll test with it and then remove if needed

**Comment by CrazyisCreeps** [comment]
That's fair enough, let me load this up

**Comment by technodono** [comment]
This map is in SNS and since April fools is over... I'm closing this off
