### ISSUE TITLE
[rage/9v9] DodgeBall

### ISSUE THREAD

**Issue by each1234** [OvercastCommunity/CommunityMaps#167]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [ ] The map has been tested locally to make sure it works

# Map Name
Dodge Ball

## Gamemode & Map Description  
Rage map with no swords, only bows. Arrows spawn @ middle, and teams can't cross onto the other side.

## Team Sizes
9 v 9 by default.

## Screenshots
![2021-03-27_10 52 16](https://user-images.githubusercontent.com/81478272/112725333-10ca8300-8eee-11eb-9095-88d99958e761.png)

# Download Link (w/ xml & image)
**Dropbox**.
https://www.dropbox.com/s/41usyodhqkh1p2r/dodge_ball.zip?dl=0

**Comment by CoWinkKeyDinkInc** [comment]
The map has not been tested locally, the XML does not load.

`- line 52, column 29: Error on line 52: Attribute name "item" associated with an element type "item" must be followed by the ' = ' ch`

**Comment by each1234** [comment]
https://www.dropbox.com/s/41usyodhqkh1p2r/dodge_ball.zip?dl=0

Updated download with a fixed xml

**Comment by calcastor** [comment]
I have loaded this with some XML edits. The only-blue and only-red filters were missing, so I created those, and also fixed some referencing of blue-team and red-team as blue and red instead of how they're ID'd as teams, since that would have referenced the kit IDs.

**Comment by calcastor** [comment]
closing issue as this is used in fun or set-next pools and plays fine within them
