### ISSUE TITLE
[DTC/16v16] Opposing Fortresses

### ISSUE THREAD

**Issue by RealEMK** [OvercastCommunity/CommunityMaps#168]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [✔] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [✔] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [✔] I have created an XML file
- [✔] I have created an map image
- [✔] I have uploaded the map zip file to a file sharing service
- [✔] The map has been tested locally to make sure it works

# Map Name
What is the map called?
Opposing Fortresses

## Gamemode & Map Description  
The gamemode used is DTC. It's a symmetrical map with two opposing fortresses. You may use TNT, free building, or any other means in order to overcoming your opponent.

## Team Sizes
2 teams. 16 players each.

## Screenshots
https://imgur.com/a/HEuTqwO

# XML
https://gist.github.com/RealEMK/4785a45c71869894b47a7fee6243832a

# Map Image
![map](https://user-images.githubusercontent.com/69766204/112896389-55038200-90ac-11eb-9208-fb968c2ce855.png)

# Download Link
https://drive.google.com/file/d/1XYjP85kVhdtmGVYP9Ikfg1rV5Wwh1d6j/view?usp=sharing

**Comment by rockymine** [comment]
simple and basic, I like it. Definitely falls under the nostalgic category.

**Comment by RealEMK** [comment]
> simple and basic, I like it. Definitely falls under the nostalgic category.

Thank you very much!
I've been an OC.TC player since 2012 and from my experience basic is best. I've enjoyed the more basic concept maps like CTF/DTM/DTC more than a lot of the more modern objective maps.

**Comment by Pugzy** [comment]
For me it would be nice to see some outpost structures towards the middle of the map. Maybe the one or both of objective(s) could be moved on top of them buildings so that both cores (or just one) are not directly in spawn (one forwards operating base and one further back) a bit like Total War. Spicing up the middle with some sort of path from spawn would make it a bit more defined than the vanilla terrain style and direct players towards mid. As for mid I would remove some of the sugarcane.

![image](https://user-images.githubusercontent.com/8608892/112966508-35b73400-9142-11eb-8943-de54b222f65e.png)

**Comment by technodono** [comment]
may I suggest if using world edit that you try custom trees too

once you make one tree you can copy/paste to add that depth & detail

**Comment by RealEMK** [comment]
> For me it would be nice to see some outpost structures towards the middle of the map. Maybe the one or both of objective(s) could be moved on top of them buildings so that both cores (or just one) are not directly in spawn (one forwards operating base and one further back) a bit like Total War. Spicing up the middle with some sort of path from spawn would make it a bit more defined than the vanilla terrain style and direct players towards mid. As for mid I would remove some of the sugarcane.
> 
> ![image](https://user-images.githubusercontent.com/8608892/112966508-35b73400-9142-11eb-8943-de54b222f65e.png)

The main reason I chose to put the cores at spawn, was to make it feel very close quartered. I want it to be really difficult to break the core, and I felt there was no better way to do it than put it near the respawn point.

Maybe I could use the red structures you drew to add monuments to the map as well?

**Comment by rockymine** [comment]
> > For me it would be nice to see some outpost structures towards the middle of the map. Maybe the one or both of objective(s) could be moved on top of them buildings so that both cores (or just one) are not directly in spawn (one forwards operating base and one further back) a bit like Total War. Spicing up the middle with some sort of path from spawn would make it a bit more defined than the vanilla terrain style and direct players towards mid. As for mid I would remove some of the sugarcane.
> > ![image](https://user-images.githubusercontent.com/8608892/112966508-35b73400-9142-11eb-8943-de54b222f65e.png)
> 
> The main reason I chose to put the cores at spawn, was to make it feel very close quartered. I want it to be really difficult to break the core, and I felt there was no better way to do it than put it near the respawn point.
> 
> Maybe I could use the red structures you drew to add monuments to the map as well?

I think it could be easier to defend the cores if they were not adjacent to the spawn building in such close proximity. You can probably sneak into the side towers quite easily. When you spawn you don't see the cores (unless you have a spawndrop). They are not in your field of view. Maybe have one core stay at the side and move one more to the middle. You could have resources in the other tower. Or have those in a mine.

Personally, I would not add more objectives to the map. You really don't know what you have to defend in such case. Maybe two monuments and one core is fine, but not two of both. After all it is a bit of personal taste as well.

**Comment by technodono** [comment]
I think I can echo most sentiments from prev maps to this one: this map has been in here forever and should probably be closed untill the author becomes active again.

If mapdev see this... maybe a map cleaning is in order

**Comment by CoWinkKeyDinkInc** [comment]
From what I can tell, RealEMK has abandoned this project and is no longer interested in being a part of this server anymore. Closed for inactivity/abandonment.
