### ISSUE TITLE
[CTW/18v18] Arabia

### ISSUE THREAD

**Issue by Blazy-36** [OvercastCommunity/CommunityMaps#171]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [ X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [ X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [ X] I have created an XML file
- [ X] I have created an map image
- [ X] I have uploaded the map zip file to a file sharing service
- [X ] The map has been tested locally to make sure it works

# Map Name
What is the map called?
Arabia
## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.
CTW - 2 wools plays similar to empired. It was on stratus for a few months and was very popular. When had ratings it was best over a multi month span
## Team Sizes
How many teams and how large are they?
2 - 18
## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible.
https://imgur.com/EDmrDil = this isn't the latest version. There was one minor update that fixed some things but its mostly the same as this album
# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.
I'm not sure what to do here. The XML is perfect. It has been on stratus for months. If I need to do this just leave a comment. 
# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` and upload it by dragging it into this text box.
![map](https://user-images.githubusercontent.com/56277290/113469003-fb86b480-9417-11eb-9b24-5a76d0eb03cf.png)

# Download Link
[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive** or **Dropbox**.
https://drive.google.com/drive/folders/15n9iRCeoQwoRMb84AIZH3nPsW_Fmj1XR?usp=sharing

**Comment by Blazy-36** [comment]
Sup. This was my most popular map so I'd like to have it be played again.

**Comment by calcastor** [comment]
> 
> 
> Sup. This was my most popular map so I'd like to have it be played again.

This is one of a few maps Cinco mentioned to me to see about loading. I'm excited to take a look!

**Comment by calcastor** [comment]
This has been loaded to the CommunityMaps repo and added to the centi rotation as of now given the fact that it's already had play testing etc.! Thanks for submitting!
