### ISSUE TITLE
[KotH/5v5/TE] Exit

### ISSUE THREAD

**Issue by each1234** [OvercastCommunity/CommunityMaps#173]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Exit

## Gamemode & Map Description  
KotH made for ranked and the next tm. There's a top level that can be used for rotating between sides and mid. They're ladders to get up to the top on the sidepoints and outside of spawn.

## Team Sizes
2 teams, 5v5.

## Screenshots
![2021-04-02_12 56 44](https://user-images.githubusercontent.com/81478272/113495371-44457880-94bf-11eb-95b6-a744a22ffbae.png)
![2021-04-02_12 57 01](https://user-images.githubusercontent.com/81478272/113495374-460f3c00-94bf-11eb-9ec9-bce90b757f39.png)
Side points:
![2021-04-02_12 57 14](https://user-images.githubusercontent.com/81478272/113495379-490a2c80-94bf-11eb-9882-a24ff8ed2c9c.png)
Spawns:
![2021-04-02_12 57 34](https://user-images.githubusercontent.com/81478272/113495387-53c4c180-94bf-11eb-87e1-898f336383c5.png)

# Download Link
Dropbox:
https://www.dropbox.com/s/owfniwv40rn6ijb/exit_te.zip?dl=0

**Comment by Pugzy** [comment]
This looks good, loaded it up and everything works.

Small thing but noticed your head in spawn is a skeleton skull is this correct? 🤔

**Comment by each1234** [comment]
Yeah, I did that cuz it fits the theme of the map better than my Steve skin

**Comment by calcastor** [comment]
Loaded this to competitive map repos as well as to public with minor kit changes to better match the current meta for both. Thanks for submitting!
