### ISSUE TITLE
[DTC/25v25] Pompeii DTC

### ISSUE THREAD

**Issue by each1234** [OvercastCommunity/CommunityMaps#182]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Pompeii DTC

## Gamemode & Map Description  
A 25v25 dtc made by a while ago by me, Jexel, and GoldenOre, but I reworked it with help from rockymine. This version has a void gap and fewer structures around the core. Bottles of enchanting are given after every three kills (each team has an enchant table on their side). The height limit over void is lower to make sky bridging more difficult.

## Screenshots
![2021-04-10_18 38 20](https://user-images.githubusercontent.com/81478272/114288075-487f1200-9a3a-11eb-90a6-b5fbbc31ddb7.png)
![2021-04-10_18 36 43](https://user-images.githubusercontent.com/81478272/114288059-26858f80-9a3a-11eb-8a8b-49d2a3249db3.png)
frontlines:
![2021-04-10_18 37 23](https://user-images.githubusercontent.com/81478272/114288062-28e7e980-9a3a-11eb-903b-1992733a43f9.png)
core:
![2021-04-10_18 37 35](https://user-images.githubusercontent.com/81478272/114288068-34d3ab80-9a3a-11eb-9bb8-d92701070c46.png)
spawn:
![2021-04-10_18 37 52](https://user-images.githubusercontent.com/81478272/114288073-3bfab980-9a3a-11eb-8340-deb7d50443d5.png)

# Download Link
https://www.dropbox.com/s/yqf03q10s4j2fa9/pompeii_dtc.zip?dl=0

**Comment by technodono** [comment]
a map is already called pompeii?

**Comment by calcastor** [comment]
> 
> 
> a map is already called pompeii?

well, it's a TDM with a Rage version and a 5x5 version. there shouldn't be an issue.

**Comment by each1234** [comment]
> a map is already called pompeii?

this is sort of a sequel

**Comment by calcastor** [comment]
was able to test locally and after a small fix it loaded fine, now loaded in repo for testing.

**Comment by master00ofdsiware** [comment]
Awesome map, I love the theme and aesthetics. However, the void gap needs to be smaller; you could move the sides closer together, or if you prefer, you could also consider filling in some of the space with smaller islands that players can bridge to.

**Comment by CoWinkKeyDinkInc** [comment]
The map needs more materials in spawn, a shorter void gap and maybe a few chests with extra building materials laying around. I would also make the iron supplies larger so it is more easier for players to spot out. Otherwise this is a solid map that is pretty good. 

I made some changes and formatting to the XML in 1cbc7d0 in the meanwhile.

**Comment by calcastor** [comment]
We've made changes to this to reduce the void gap and cleanup the XML, and have added it to the pools. Thanks for the submission!
