### ISSUE TITLE
[DTM/45vs45] Alpine Mining II

### ISSUE THREAD

**Issue by rockymine** [OvercastCommunity/CommunityMaps#190]
### Alpine Mining II

![](https://i.imgur.com/si4UCVb.png)

It's been a long wait - 7 years to be exact. Alpine Mining is one of the most iconic maps I've ever made. For that reason I spent a lot of time (and used new tools!) working on the sequel. 

Alpine Mining II is ready for you to play! Similar to it's original it features 2 monuments, each made of 3 blocks of obsidian. What probably no one remembers is that Alpine Mining originally had 3 monuments. This map starts with just two. The footprint of both maps is identical but it should be way easier to traverse the terrain using the paths that connect all important areas of the maps. 

Hopefully attackers will make use of the mineshafts and caves as [a lot of work](https://i.imgur.com/k4JuhXj.png) went into making these as well.

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file (Thanks to @calcastor )
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Summary
![](https://i.imgur.com/u6ocYm9.png)
Yellow (circle) = tunnel
Light Blue (star) = power bow
Pink (rectangle) = cave entrance
Red (triangle) = shaft
Purple (check) = monument

## Screenshots
[Finished Map](https://i.imgur.com/u6ocYm9.png)        |  [Making of](https://imgur.com/a/wI9lKZ0)
:-------------------------:|:-------------------------:
![](https://i.imgur.com/QUDW3I8.png)  |  ![](https://i.imgur.com/a8hUZPG.png)

# Download Link
[Dropbox](https://www.dropbox.com/s/ihwe3fb6yxvkxoo/Alpine%20Mining%20II.zip?dl=0) (fixed wrong xml)

_Thanks to DoomyBoy and Rasta_Jol for making the first map with me. Without them this sequel would have never happened!_
_Also thanks to [Arcaniax for making Arceon](https://github.com/Brennian/Arceon/wiki)_

**Comment by calcastor** [comment]
linking this here for visibility

https://github.com/OvercastCommunity/CommunityMaps/commit/bc9323a54b4fc9ba67f61ce768b2cc22505b81f6#commitcomment-50279796

update with kits added will be pushed tonight

**Comment by CoWinkKeyDinkInc** [comment]
Fixed a minor typo in 6cd36433f85765a7fb218a680055c5bfbdfc50ba that let players break blocks in spawn.

**Comment by calcastor** [comment]
With the latest update sent to me by @rockymine this map has been added to the mega pool.
