### ISSUE TITLE
[Blitz/64v1] Juggernaut's Hall: Sacrifice

### ISSUE THREAD

**Issue by CredensJustitiam** [OvercastCommunity/CommunityMaps#193]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Juggernaut's Hall: Sacrifice

## Gamemode & Map Description
This blitz map plays like the original Juggernaut's Hall, except in a new map. The map is divided into five different "stages", in which players must decide whether they want to sacrifice themselves so that everyone else can continue. This map will test people's cooperation and selflessness.

## Team Sizes
Just like in the original, 1 person is a juggernaut and everyone else is a runner.

## Screenshots
https://imgur.com/gallery/0iglUaK

# XML
https://gist.github.com/CredensJustitiam/4cda5d8a16b629a6e3c38a6eeec9c3d5

# Map Image
![map](https://user-images.githubusercontent.com/80809061/116323026-124bcd00-a772-11eb-9d49-f22b68210f31.png)

# Download Link
https://www.mediafire.com/file/7az41p477kc6q7p/Juggernaut%2527s_Hall_-_Sacrifice_%25281.8.9%2529.zip/file

**Comment by CrazyisCreeps** [comment]
Finally getting to this, sorry about that. So it looks like an interesting map, but it looks like there's a couple of issues. First off, the xml had a bunch of errors that preventing it from loading (that fixed xml can be found here; https://gist.github.com/CrazyisCreeps/fb72bb9b191034906c9a8d97f6a82d52). Your xml also had a bunch of indentation and general formatting issues, I'd just make sure to work on that to help improve the overall readability of it for us mapdevs.

Onto map related issues:

- Pistons don't work. You've disabled block interactions without allowing pistons to be able to move the blocks. One easy fix would be to disable block interactions specific to players, which would allow all other interactions as a result.
- Mob eggs found in the dispensers won't spawn. You'd need to include a rule for it (look at https://pgm.dev/docs/modules/environment/mobs for more info).
- The map has 7 runners, but requires more than 7 to alive to complete it, if all sacrifice options are used. There's potential for 8 sacrificed players throughout the whole course, which would require 9 runners as a bare minimum for the runners to win through that route.
- To add to that, stage 5 (the last one) really requires a decent amount of players alive to be able to complete it. You need either 4 players alive to be able to hold the pressure plates for the sand to fall, or 2 sacrifices and 1 sole player to capture the end point. I worry that with such a small player count, this stage might be too difficult.
- In general I'm also concerned about the difficulty of it all. A playtest would be the only way to really see how tough it is, but the course is quite long and tough, and you've only got a 15 second head start on the Juggernauts. On the other Juggernauts Hall map loaded on the server, the Juggernaut team usually catches up to the runners in a much shorter distance traveled (as the map is shorter)

I'd like to see the issues with team size, piston block interactions, and the mob egg spawning to be fixed as a first step. After that, we can try out some map testing, but I really think the map needs some major work to ensure its fun and enjoyable. Hopefully map testing would point out what can be improved and tweaked.

**Comment by CredensJustitiam** [comment]
I fixed most of the issues. I believe I fixed mob eggs, and I changed the minimum and maximum number of players. The reason that was incorrect (as well the of the formatting issues) is because I used the original Juggernaut's Hall xml as a base for this xml, and that was an older map on this server.

I'm just not sure how to disable block interactions specific to players to make the pistons work like you said. I'm assuming I have to do something in my <filters> section, but it's worth noting that I can't remove all block interactions for players, because runners need to be able to break endstone and juggernauts need to break spider webs. Can you help me with that? I did look through the PGM docs but couldn't figure out how to do this.

**Comment by CrazyisCreeps** [comment]
Yea bet, so here would be the expanded filter, which basically just allows interactions with the blocks the pistons push (but denies interactions from the players) https://gist.github.com/CrazyisCreeps/2871273ced131a32f188a5b0b3209c04

While I was testing the filter out I also couldn't help to notice that there's a piston missing from stage 4 (I think? The one with the parkour + pistons combo). Without the piston/block combo, the jump is impossible right now. 
![image](https://user-images.githubusercontent.com/7937351/124510444-cd5f9a80-dda1-11eb-9b7e-3cda0f009bcd.png)

**Comment by CredensJustitiam** [comment]
I updated the xml with your fixes. I redownloaded the map from the link I have here and checked out the part with the redstone lamp jumps, and everything seems to be working normally. Are you sure you didn't destroy a piston by accident?

**Comment by CrazyisCreeps** [comment]
Huh I didn't think I did, but if it works fine from your end maybe you can resend over the world file?

**Comment by CredensJustitiam** [comment]
[Juggernauts Hall - Sacrifice (1.8.9) (2).zip](https://github.com/OvercastCommunity/CommunityMaps/files/6766766/Juggernauts.Hall.-.Sacrifice.1.8.9.2.zip)

This should work

**Comment by CrazyisCreeps** [comment]
Not sure how I didn't notice this earlier, but since juggernaut's can't jump (and can only actually go up a block with double jump), you may want to add staircases to all areas where they are expected to be able to climb. Otherwise it's too painful to have to use a double jump for each step/level.

Other than that, looks good!

**Comment by CredensJustitiam** [comment]
Ok, I updated it again

**Comment by CrazyisCreeps** [comment]
Awesome. I've loaded it up to the server for some gameplay testing

**Comment by CredensJustitiam** [comment]
Cool, let me know if there's anything I should change about the map (because I'm taking a break from the server for a while)
