### ISSUE TITLE
[CTW/8x8] Summertime at Brown's Farms

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastCommunity/CommunityMaps#2]
### Checklist
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Summertime at Brown's Farms

## Gamemode
CTW

## Team Sizes
8 teams, 8 players each.

## Screenshots
https://imgur.com/a/zGfSih4

# XML
Included in the zip.

# Map Image
Included in the zip.

# Download Link
[Summertime at Brown's Farms.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5032685/Summertime.at.Brown.s.Farms.zip)

**Comment by alexsosnovsky** [comment]
`Also provide a small description of the map and how you envision it playing.`

This is an 8 team CTW with one wool per team. Each spawnpoint is shared by two teams, who then have separate portals to their own defense areas. Similarly, each wool lane is shared by two wool rooms. This is visible in the overhead screenshot.

Each team has to capture seven wools, and defend one. I have tried to balance attacking and defending so that the map doesn't always take forever to finish; the most notable inclusion would be horse spawners at each team's spawn. There are four types of horses that players can use to traverse the map more easily when going for enemy team wools. Horses can be parked behind the wool rooms while the player is inside the wool room. Additionally, the wool rooms are a no-PVP zone if both players are not on the defending team. The map has a minimal amount of iron blocks that can be used to make iron armor, these regenerate so the iron supply is unlimited. 

Since this is a fairly unique map, adjustments may be necessary based on the gameplay tests. The XML should work perfectly; I have tested it locally.

**Comment by master00ofdsiware** [comment]
`Also provide a small description of the map and how you envision it playing.`

This is an 8 team CTW with one wool per team. Each spawnpoint is shared by two teams, who then have separate portals to their own defense areas. Similarly, each wool lane is shared by two wool rooms. This is visible in the overhead screenshot.

Each team has to capture seven wools, and defend one. I have tried to balance attacking and defending so that the map doesn't always take forever to finish; the most notable inclusion would be horse spawners at each team's spawn. There are four types of horses that players can use to traverse the map more easily when going for enemy team wools. Horses can be parked behind the wool rooms while the player is inside the wool room. Additionally, the wool rooms are a no-PVP zone if both players are not on the defending team. The map has a minimal amount of iron blocks that can be used to make iron armor, these regenerate so the iron supply is unlimited. 

Since this is a fairly unique map, adjustments may be necessary based on the gameplay tests. The XML should work perfectly; I have tested it locally.

**Comment by Pugzy** [comment]
Played this yesterday, you already know about the donkey issue but not sure how that can be fixed.

- The wool monuments are in a weird place, nobody thinks to look there and people had to ask in chat.
- Once up at the wool monument there's a wool monument above the rest in the roof, also confusing.
- The horses being inside spawn is confusing and a little tricky to get out, maybe these could be put in a different building.
- I believe Brott said arrows were dropping on death which may need fixing with item remove/kill rewards.

**Comment by master00ofdsiware** [comment]
> Played this yesterday, you already know about the donkey issue but not sure how that can be fixed.

The guaranteed fix would be to remove all the horse spawners, but for now I will try and get this fixed on the plugin level, so that the map can still have the custom horses.
> * The wool monuments are in a weird place, nobody thinks to look there and people had to ask in chat.
> * Once up at the wool monument there's a wool monument above the rest in the roof, also confusing.

I'll add signs or invisible armor stands that say where the wool monuments are, and to look for one above.
> * The horses being inside spawn is confusing and a little tricky to get out, maybe these could be put in a different building.

I will see what I can do about this.
> * I believe Brott said arrows were dropping on death which may need fixing with item remove/kill rewards.

I'll check the XML, thanks for letting me know.

**Comment by master00ofdsiware** [comment]
OCC is now using a custom fork of ViaRewind that solves the issue of 1.7 players crashing on this map. With that done, I have made a PR with the necessary map changes. More details are in the PR description: https://github.com/OvercastCommunity/CommunityMaps/pull/15

**Comment by master00ofdsiware** [comment]
After spectating a match of the map's latest update, I couldn't really see anything that obviously needs changing. Feel free to let me know if something else comes up, but otherwise I think the map's all set.

**Comment by Pugzy** [comment]
I'd like to see the wool area fixed up but I'd be curious as to what others thought.

**Comment by fixitqixit** [comment]
I cant provide any feedback in relation to the wool monuments, as I never saw any of them. I did however love every other aspect of the map. The horses are really cool and the many ways this map can be played gave me great enjoyment. I look forward to playing this in the coming weeks when I have more time! I will likely also provide more feedback in detail (maybe).

Also dont forget to disable tnt damage for teammates i kept killing some of my own by mistake.

**Comment by master00ofdsiware** [comment]
https://gist.github.com/master00ofdsiware/851a04b30329f2e1ea8095734ac6b33f
Here's the updated XML. TNT no longer damages the player who set it down, or their teammates.

**Comment by fixitqixit** [comment]
@master00ofdsiware if possible can you make a pull request for this change?

**Comment by master00ofdsiware** [comment]
> @master00ofdsiware if possible can you make a pull request for this change?

Sure.
https://github.com/OvercastCommunity/CommunityMaps/pull/22

**Comment by master00ofdsiware** [comment]
This map has been added to the map pools.
