### ISSUE TITLE
[Dropper/64] The Dropper: Community Edition

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#202]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
The Dropper: Community Edition

## Gamemode & Map Description  
This is a new dropper game-mode created by many players who participated in the event and each contributed 1-2 droppers... a 15 dropper dropping experience with many custom modes such as falling, ladder climbs, bounce droppers and damage droppers! can you beat all 15 and get to the winner's balcony?

## Team Sizes
it's 64 max player-count isn't really a big factor in droppe rmaps

## Screenshots

Since I can't take a top view and most of the map has already been seen & checked by map-devs and other prominent figures i think it's safe to say it's looks are of upmost quality... also I'm not going to change peoples designs if it's lacking detail or smth... they made it... so they get to do what they want with it & also if needed I will ask them to edit it a bit or edit with their permission.... overall means no screenshots

# XML
https://gist.github.com/technodono/c5f55856f78b6f2bcee75f00a39072b0

# Map Image
![map](https://user-images.githubusercontent.com/22761234/119993451-e50f6a80-c00e-11eb-96bd-946505c635a6.png)

# Download Link
[The Dropper-Community Edition (NEW).zip](https://github.com/OvercastCommunity/CommunityMaps/files/6561217/The.Dropper-Community.Edition.NEW.zip)

**Comment by rockymine** [comment]
Hypers. But why not a collage of all stages as the map image 👎

**Comment by technodono** [comment]
> Hypers. But why not a collage of all stages as the map image 👎

sure can do

**Comment by technodono** [comment]
collage of all map stages is now the image... I tried to squeeze it all in so some maps are a little cut off but all of them are there

**Comment by CoWinkKeyDinkInc** [comment]
It's now loaded!

**Comment by CoWinkKeyDinkInc** [comment]
The difficulty is legendary. A lot of the maps have an issue where there is a giant obstacle almost immediately when you jump and sometimes (6, 11) is almost impossible to dodge them. Levels 5 and 6 have way too much of a difficulty spike compared to the previous levels and are really frustrating to play. Drop 12 doesn't have a lot of space to make a jump. The height on a few of these maps need to be made taller if that is possible.

**Comment by CoWinkKeyDinkInc** [comment]
![2021-05-28_19 32 52](https://user-images.githubusercontent.com/7586568/120055441-58a37e80-bff3-11eb-9216-8bed927ad7d2.png)
![2021-05-28_19 56 49](https://user-images.githubusercontent.com/7586568/120055458-77097a00-bff3-11eb-882d-3b4419df361d.png)
I got 261 deaths on my first playthrough on the map.

**Comment by CrazyisCreeps** [comment]
![2021-05-30_15 22 08](https://user-images.githubusercontent.com/7937351/120118578-4b0c0700-c161-11eb-9fc3-84460b3fae82.png)
I posted this in the discord for the guys making the community dropper but I also wanted to share here. I had not tested anyone else's dropper (other than my own) prior to this test. As you can see, much better time than CoWink's attempt

**Comment by KingOfSquares** [comment]
https://gist.github.com/technodono/c5f55856f78b6f2bcee75f00a39072b0#file-map-xml-L206-L207

The second of these alert should be delayed by 1 second or else it might show up in the wrong order like in crazys screenshot

**Comment by technodono** [comment]
> https://gist.github.com/technodono/c5f55856f78b6f2bcee75f00a39072b0#file-map-xml-L206-L207
> 
> The second of these alerts should be delayed by 1 second or else it might show up in the wrong order like in crazys screenshot

Will do ;)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in #205

**Comment by calcastor** [comment]
This was just play tested; when you reach the end and are TP'd, you get stuck and do not gain the 16th point after 30 seconds.

**Comment by technodono** [comment]
huh... I am on to that and will be finding a way to fix this

**Comment by CoWinkKeyDinkInc** [comment]
@technodono You need to make two regions for the ending balcony, one for the portal and one for the control point. The control point has to be one block beneath the platform so that the player can have it start ticking, and the portal one Y above so that the player doesn't get stuck.

**Comment by CoWinkKeyDinkInc** [comment]
Updated in #205, #208, and #209
