### ISSUE TITLE
[CTP, DTM, DTC, DTE/32 vs 32] Temple Complex (Failed to rehabilitation)

### ISSUE THREAD

**Issue by Omote23** [OvercastCommunity/CommunityMaps#213]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

**Current status : Failed to rehabilitation, because of serious lack of intuition.
Thanks for contributing and helping though...** 

# Map Name
Temple Complex

## Gamemode & Map Description  
Capture the Point (Mutation of KOTH), Destroy the Core, Destroy the Monument, Destroy the Everything

Features of This map
1. 2-Stage Objectives - Attackers Should complete all objectives(Gateway, Tower monument/core, Obelisks) from the mainland to reach Skybridge and destroy the sky monolith. 

2. Buff/Debuff Battle : There is a potion that buffs you and your allies greatly, or debuffs your enemies greatly, Use that potion to get an advantage!

3. Enchanting Gear : You can Enchant your gear by enchantment table which is located on the edge of the map. You can get exp points by mining coal blocks, cooking pork chops, and using Exp bottle spawners

4. Self Repairing Monument : The final Monument which is called "Sky monolith" will be self repaired. So attackers should damage the monolith A LOT at one shot.

5. Capture The Point, (The Mutation of KOTH) : Main Gate and Obelisk will be similar to normal KOTH, but it takes a long time to capture, and if attackers capture the points there is no return.

6. Skybridge Making/Reinforcing/Nullifying Is really REALLY IMPORTANT. because there is a LOT of space between mainland and sky monolith and Attacker's spawn.

## Team Sizes
32 vs 32

## Screenshots
https://imgur.com/a/ah600y8

# XML
https://gist.github.com/Omote23/e6d017d6a3318461cf66acefdd99b7b2
Testing is completed. It works. 

# Map Image
![map](https://user-images.githubusercontent.com/13076502/124549313-f64b6280-de69-11eb-91b2-3f103571d378.png)

# Download Link
https://www.dropbox.com/s/7u84macs9ut18hz/Temple%20Complex.zip?dl=0

1.0.1 addition. : Add stairs, add another entrance to obelisks control-point. add signs that indicate the location of objectives. changes location of defenders' iron.  
XML modification : indentation space : 3 -> 4, Expanded right-obelisk area. expanded core area.

**Comment by CoWinkKeyDinkInc** [comment]
The textures on some parts of the map could be a little more fleshed out. Just breaking up some repetitive textures with some new blocks will make a huge difference.

The sequential objectives is possible to accomplish with the `block` type filter. Although, why do you want it to be done sequentially? Is it clear on the map that players would do this in your order naturally to begin with? Is there any portals or "checkpoints" to make getting to the action quicker, like in BoomBox?

> Self Repairing Monument : The final Monument which is called "Sky monolith" will be self repaired. So attackers should damage the monolith A LOT at one shot.

This might work, players can repair monuments but I am not sure if this can be done automatically. This can be tested when you finish all the XML.

> Capture The Point, (The Mutation of KOTH) : Main Gate and Obelisk will be similar to normal KOTH, but it takes a long time to capture, and if attackers capture the points there is no return. However, If it's confirmed to impossible by current XML system. It will be changed to DTC, DTM

Control points can be captured permanently, so this works.

> Variable Time limit, If Attackers won't capture the first point within 15 minutes, Defenders instantly win, However when attackers complete each objective, the remaining time is extended by 10 minutes per each objective.

I am not sure if this is possible in PGM, it may already be implemented but not documented but I can't find the PR that would have this.

**Comment by Omote23** [comment]
> The textures on some parts of the map could be a little more fleshed out. Just breaking up some repetitive textures with some new blocks will make a huge difference.
> 
> The sequential objectives is possible to accomplish with the `block` type filter. Although, why do you want it to be done sequentially? Is it clear on the map that players would do this in your order naturally to begin with? Is there any portals or "checkpoints" to make getting to the action quicker, like in BoomBox?
> 
> > Self Repairing Monument : The final Monument which is called "Sky monolith" will be self repaired. So attackers should damage the monolith A LOT at one shot.
> 
> This might work, players can repair monuments but I am not sure if this can be done automatically. This can be tested when you finish all the XML.
> 
> > Capture The Point, (The Mutation of KOTH) : Main Gate and Obelisk will be similar to normal KOTH, but it takes a long time to capture, and if attackers capture the points there is no return. However, If it's confirmed to impossible by current XML system. It will be changed to DTC, DTM
> 
> Control points can be captured permanently, so this works.
> 
> > Variable Time limit, If Attackers won't capture the first point within 15 minutes, Defenders instantly win, However when attackers complete each objective, the remaining time is extended by 10 minutes per each objective.
> 
> I am not sure if this is possible in PGM, it may already be implemented but not documented but I can't find the PR that would have this.

Actually, I need some help with fleshing textures... although I think the fleshing texture will be the last stage of mapmaking. 

I completed to make XML. I think I have to test whether it works.

**Comment by CoWinkKeyDinkInc** [comment]
Yeah you have to test it. Some of the spacing and formatting needs to be fixed as well.

**Comment by Omote23** [comment]
> Yeah you have to test it. Some of the spacing and formatting needs to be fixed as well.

I edited an XML and XML testing is completed, all I have to do is public testing and seeing if it works correctly as I intended.

**Comment by CrazyisCreeps** [comment]
I'm so confused. It took me like 10 minutes to figure out what tower had the tower monument. And then another 10 minutes to find the left and right control points, and how to get into them. Why is there so many hurdles to jump through in order to complete all objectives?

But yea the xml is alright. Looks like your core region is off by a block on two of the sides, meaning there's bit of obsidian you can break that don't count as the core (defenders can break this and leak the core, or attackers before they capture the main gate). You also want to use block-break="only-iron" in your spawn regions, as this will only allow iron to be broken, not also placed.

A couple of other very minor things. Make sure to clean up unneeded files when packing the map for a download in the future (https://pgm.dev/docs/guides/packaging/cleaning-files). Also unsure that you use 4 spaces as indentation, it looks like you used 3.

Maybe a beacon at the tower would help to located it? The only other concern is that the map isn't super intuitive and I feel like you try to make that up by sending this huge wall of tips in the first minute of the match. Anyone who doesn't join right away misses all that info, and even for the players that do join at the beginning of the match, you're overloading them with too much information. I felt overwhelmed.

**Comment by Omote23** [comment]
> I'm so confused. It took me like 10 minutes to figure out what tower had the tower monument. And then another 10 minutes to find the left and right control points, and how to get into them. Why is there so many hurdles to jump through in order to complete all objectives?

Because I want to reiterate siege war of lineage 2 or Black desert online. Actually, this siege war has a "Gateway > Inner Gateway > Thorns" sequence. I tried to mutate that siege stage for minecraft style. So, I placed "Gateway > Tower monument/core > obelisks left and right > sky monolith"

However, taking 20 minutes to just finding objectives is a very serious problem. I agree. Originally, I want to provide information about the location of objectives via armor stand. however, I already moved this map from anax server to my personal singleplayer savefile, So It's hard to change it.

But instead, I follow 3 steps to find objectives easily.
1. I'll change the stone block which covers the tower monument to stained glass and normal glass to be visible for attackers and defenders. 
2. I'll add a left/right side entrance towards to obelisks control point for easier access. originally, I have an intention about making frontline on the tunnel. however. it won't happen if the majority of people doesn't know where the tunnel is
3. I'll add a sign that indicates x,y,z location of the objectives

> But yea the xml is alright. Looks like your core region is off by a block on two of the sides, meaning there's bit of obsidian you can break that don't count as the core (defenders can break this and leak the core, or attackers before they capture the main gate). You also want to use block-break="only-iron" in your spawn regions, as this will only allow iron to be broken, not also placed.

Ok, I'll edit that asap. 

> A couple of other very minor things. Make sure to clean up unneeded files when packing the map for a download in the future (https://pgm.dev/docs/guides/packaging/cleaning-files). Also ensure that you use 4 spaces as indentation, it looks like you used 3.

ah...... I found it. I'll change it

> Maybe a beacon at the tower would help to located it? The only other concern is that the map isn't super intuitive and I feel like you try to make that up by sending this huge wall of tips in the first minute of the match. Anyone who doesn't join right away misses all that info, and even for the players that do join at the beginning of the match, you're overloading them with too much information. I felt overwhelmed.

Maybe I have to extend the length between tips and remove some unnecessary tips.

**Comment by CrazyisCreeps** [comment]
Honestly I still find it really confusing but I get that your map idea relies on this/that was the inspiration behind the map. Usually any map that forces people to "do something before something else" leaves players feeling lost or frustrated. There's a lot that this map has to offer, I just don't feel like it was designed with it's gameplay in mind.

**Comment by Omote23** [comment]
> Honestly I still find it really confusing but I get that your map idea relies on this/that was the inspiration behind the map. Usually any map that forces people to "do something before something else" leaves players feeling lost or frustrated. There's a lot that this map has to offer, I just don't feel like it was designed with its gameplay in mind.

Uhh..... I'm so sad that you said that my map is not considered gameplay.......
My intention was...
1. Frontline power battle and TNT cannon tower for variations. : Gateway
2. Typical OCC's DTC/DTM attack-defend : Tower
3. Typical OCC's Control points but just attack/defend mode. + Strategic decision about players' separation/regrouping by restricting entrances: Obelisks.
4  Wailing void - testing skybridge tactics focused on reinforcing  : Air area
5. Typical OCC's DTE. but self-repair for variations. : Final big monument.
6. Enchanting gear/limited iron : a more strategic decision that requires resource management.

That was what I intended.... 
But whatever I intended, if OCC players can't accept and don't follows my intention, yeah, that's my fault (T^T) 
maybe I put so many gimmicks on one map?. maybe the vector distance (distance between spawn and objectives) was in error? maybe Sequential objectives have too many sequences that players will be confused about?
I want to know why you think that It's not designed for gameplay specifically, and do you think this map can do rehabilitation - being a good OCC map by editing a lot (including aesthetic, map size. etc...) on the current situation?

Even if this map doesn't have the potential to be a good map. please give me an honest expression about this map. because I have to accept that criticism and apply it to make a new map. 

here is the rehabilitation plan for this map
1. reducing map size and player size. removing some objective.
2. Removing Skybridge area or obelisk.
3. removing sequence about objectives except for the skybridge area

**Comment by technodono** [comment]
>  But whatever I intended, if OCC players can't accept and don't follows my intention, yeah, that's my fault (T^T)

it's not about that... It's about doing the objectives in order...

that's what makes the map the issue

**Comment by technodono** [comment]
If you have one objective unlocks a wool to win or smth that fine  like enderblast... if you ask players to destroy stuff in a specific order that when things start to not work and people get furstrated as crazy said

**Comment by Omote23** [comment]
> > But whatever I intended, if OCC players can't accept and don't follows my intention, yeah, that's my fault (T^T)
> 
> it's not about that... It's about doing the objectives in order...
> 
> that's what makes the map the issue

Maybe I should remove the specific order except for sky monolith.

**Comment by technodono** [comment]
> 
> 
> > > But whatever I intended, if OCC players can't accept and don't follows my intention, yeah, that's my fault (T^T)
> > 
> > 
> > it's not about that... It's about doing the objectives in order...
> > that's what makes the map the issue
> 
> Maybe I should remove the specific order except for sky monolith.

that sounds like a good idea... as long all the objectives before the monolith are linked in some way that makes it easy for players to determine that the monolinth is the final objective you complete like how it's done on ender blast TNT map

**Comment by CrazyisCreeps** [comment]
When you're making a map you want to try to do it up in an intuitive way. What I'm not a huge fan of, for example, is that you've got this massive open terrain, but require attackers to enter this gate building in order to progress. Sure, it's kinda in the general path they'd take to go to the defenders side, but it's not clear that that building is the gate. Everything else (the rest of the objectives) just feel scattered between the gate and the monolith with again no real sense of where they are. And then you have this boundary that just appears out in front of you, blocking your access to the back portion of the map.

If somehow you were to make the general flow of the map feel more natural and it sends players to each objective, it might make it easier for players to understand. You don't want to have a map where you need to play it some half dozen times to understand how it works and what exactly your strategy should be.

**Comment by Omote23** [comment]
> When you're making a map you want to try to do it up in an intuitive way. What I'm not a huge fan of, for example, is that you've got this massive open terrain, but require attackers to enter this gate building in order to progress. Sure, it's kinda in the general path they'd take to go to the defenders side, but it's not clear that that building is the gate. Everything else (the rest of the objectives) just feel scattered between the gate and the monolith with again no real sense of where they are. And then you have this boundary that just appears out in front of you, blocking your access to the back portion of the map.
> 
> If somehow you were to make the general flow of the map feel more natural as it sends players to each objective, it might make it easier for players to understand. You don't want to have a map where you need to play it some half dozen times to understand how it works and what exactly your strategy should be.

ok.... I understand.... So. the main target is "being intuitive" right?.... I accept it....
I have a last question, Do you suggest that I should give up this map and make a new map? or lots of edits can make this map intutitive?
