### ISSUE TITLE
[DTC&DTM/50v50] Jotunheim

### ISSUE THREAD

**Issue by Acernite** [OvercastCommunity/CommunityMaps#214]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Jotunheim

## Gamemode & Map Description  
DTM, DTC - Each team has to destroy the monument and leak the core on the enemy's side.

## Team Sizes
2 teams, 50v50

## Screenshots
https://postimg.cc/gallery/QsDp8BX

# XML
https://gist.github.com/Acernite/7b035b9bc9d8a1964214fe70e49e8045

# Map Image
![2021-06-25_16 20 01 (1)](https://user-images.githubusercontent.com/85270072/123481783-32f99d00-d5d2-11eb-9362-b8b118bb3634.png)

# Download Link
https://www.mediafire.com/file/bughmrfrja73nhv/Jotunheim.zip/file

**Comment by CoWinkKeyDinkInc** [comment]
The water melts on that ice pillar because you did not set it to the winter biome on this map. You need to set it to ice plains or some other winter biome.

**Comment by Acernite** [comment]
Do you mean the water on the cliff? I had meant to put water flowing down

**Comment by CoWinkKeyDinkInc** [comment]
yeah on that icesicle thing on the map.png image. So the water is supposed to flow?

**Comment by Acernite** [comment]
Yeah I thought it'd look better as water, plus it would also be easier for the players to pick it up

**Comment by CoWinkKeyDinkInc** [comment]
Added in f1a3925

**Comment by Cazadorian** [comment]
Unfortunately this map has been unable to receive much testing at the ideal player count size as a result of it being much higher than the usual player count. I'm going to close this issue for now but will potentially look at adapting the map in the future for a smaller player count. You're welcome to also attempt to make this update yourself if you ever have the desire to do so. Thank you for the submission.
