### ISSUE TITLE
[CTW/32v32] Stark Contrast

### ISSUE THREAD

**Issue by Acernite** [OvercastCommunity/CommunityMaps#215]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Stark Contrast

## Gamemode & Map Description  
Classic CTW. Partially inspired by Diversity, an older map that is not continued on OCC.

## Team Sizes
32v32

## Screenshots
https://postimg.cc/gallery/9z1ZnWr

# XML
https://gist.github.com/Acernite/4c3a59a7b1166833115e131f783b4606

# Map Image
![2021-07-04_11 25 28](https://user-images.githubusercontent.com/85270072/124396735-5e1e7380-dcd9-11eb-85b3-21b7ef8d6dd4.png)

# Download Link
https://www.mediafire.com/file/vvmsc34ed26n6p6/Stark_Contrast.zip/file

**Comment by Cazadorian** [comment]
This map still has issues such as the map being rather flat with little on each island and some issues with spawn camping. It seems unlikely at this point that the map will be used for the pool or updated further.  If another update is ever made for it we can reconsider this but until then I'm closing this issue. Thank you for the submission.
