### ISSUE TITLE
[CTW/50v50] Lost Haven

### ISSUE THREAD

**Issue by Acernite** [OvercastCommunity/CommunityMaps#217]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Lost Haven

## Gamemode & Map Description  
CTW, also includes a KoTH point that grants a speed and haste buff for the team that controls it.

## Team Sizes
2 teams, 50v50

## Screenshots
https://postimg.cc/gallery/Gp4zTLW

# XML
https://gist.github.com/Acernite/7f9b54b86fcd61417c5245af5a178f61

# Map Image
![2021-07-16_16 26 12](https://user-images.githubusercontent.com/85270072/126006367-6a6822be-212b-480a-a536-7456e09186e9.png)

# Download Link
https://www.mediafire.com/file/2m2riqv8uugxakm/Lost_Haven_-_2.zip/file

**Comment by CoWinkKeyDinkInc** [comment]
Works great :+1:

**Comment by Acernite** [comment]
Made changes to map layout and updated KoTH point so that the team that loses control of it also loses the buffs as well.

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!

**Comment by Acernite** [comment]
Redid wool lanes, terrain, centre woolroom, and other aesthetics.

Download link: https://www.mediafire.com/file/g6o25h2gt1pjicz/Lost_Haven_-_3.zip/file
Updated XML: https://gist.github.com/Acernite/7f9b54b86fcd61417c5245af5a178f61

**Comment by rockymine** [comment]
@Acernite could we have some updated images? 😃
