### ISSUE TITLE
[CTW/45v45] 3084

### ISSUE THREAD

**Issue by Acernite** [OvercastCommunity/CommunityMaps#218]
### Checklist
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
3084

## Gamemode & Map Description  
CTW with capture point that enables an upgraded kit for the team that controls it.

## Team Sizes
2 teams, 45v45

## Screenshots
https://imgur.com/a/wKl2T6F

# XML
https://gist.github.com/Acernite/ffd9704b20fea13f29d3a17921126e0d

# Map Image
![2021-07-26_16 28 43](https://user-images.githubusercontent.com/85270072/127054878-f54d4475-17c7-452f-890f-e4667adab121.png)

# Download Link
https://www.mediafire.com/file/2e0sdv06qrgp8ue/3084_-_2.zip/file

**Comment by rockymine** [comment]
could you please upload the images to imgur for better viewing pleasure, thanks!

**Comment by CoWinkKeyDinkInc** [comment]
What are the buffs that the team gets? You might not need to set the entire kit again to have it applied.

**Comment by Acernite** [comment]
Upgrades:
Slight increase in projectile protection and added feather falling I
Leather helm/chest -> chain helm/chest 
Iron pick -> Iron pick efficiency I
Stone axe -> Iron axe
1 gapple -> 2 gapples

When I upload images onto Imgur it kinda bugs out and most of the images don't load. That's why after Niflheim I've switched over to another site to post screenshots. But after several attempts, I managed to get all the pictures up. Link is updated

**Comment by CoWinkKeyDinkInc** [comment]
The upgraded kit does not get applied.

**Comment by Acernite** [comment]
The control point allows entry to the portal at spawn, which gives the upgraded kit. Just tested it again and it works on both teams. Made some changes in the XML as some block colours were wrong, though.

**Comment by Acernite** [comment]
Changed purple team to red — new download link and updated xml
