### ISSUE TITLE
[CTW/12v12v12v12] NewGen

### ISSUE THREAD

**Issue by dentmaged** [OvercastCommunity/CommunityMaps#221]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
NewGen

## Gamemode & Map Description  
A 4-team CTW. Inspired by NextGen.

## Team Sizes
4 teams of 16 players

## Screenshots
[Album](https://imgur.com/a/q10Qh3s)

# XML
[`map.xml`](https://gist.github.com/dentmaged/919b789d226fc3e5c09aeca14eb542b2)

# Map Image
![map.png](https://user-images.githubusercontent.com/9807038/127651273-9e00bc0e-9cb7-4728-940f-52907413fa4b.png)

# Download Link
[NewGen.zip](https://github.com/OvercastCommunity/CommunityMaps/files/6907440/NewGen.zip)

**Comment by CrazyisCreeps** [comment]
Hey, make sure your map.png is the right sized image please! Refer to https://pgm.dev/docs/guides/packaging/compiling-and-releasing about it.

Also, while you're at it, do you mind taking a picture with a vanilla or close to vanilla texture pack? The image right now looks a little bland and boring with what you're using.

**Comment by CoWinkKeyDinkInc** [comment]
Regions need to be made to stop people from building outside the lanes/map.

**Comment by calcastor** [comment]
Just a few initial XML things

1. Authors and contributors should be in different modules, there should be examples in other `CommunityMaps` XMLs
2. Double check your filter apply order, but also the usage of `<not>` as opposed to `<deny>` for denying placement of wool safeties is likely what is interfering with the void filter because it seems like it should work otherwise to me.
3. I get the humour behind the joke rule and having your name in authorship more than once lol, but probably best not to have either for production.

**Comment by dentmaged** [comment]
> Hey, make sure your map.png is the right sized image please! Refer to https://pgm.dev/docs/guides/packaging/compiling-and-releasing about it.
> 
> Also, while you're at it, do you mind taking a picture with a vanilla or close to vanilla texture pack? The image right now looks a little bland and boring with what you're using.

Done.

> Just a few initial XML things
> 
> 1. Authors and contributors should be in different modules, there should be examples in other `CommunityMaps` XMLs
> 2. Double check your filter apply order, but also the usage of `<not>` as opposed to `<deny>` for denying placement of wool safeties is likely what is interfering with the void filter because it seems like it should work otherwise to me.
> 3. I get the humour behind the joke rule and having your name in authorship more than once lol, but probably best not to have either for production.

Thank you. `deny` fixed the error with build regions that @CoWinkKeyDinkInc was talking about. I have removed the duplicate names & split authors and contributors up.

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!
