### ISSUE TITLE
[CTW/24v24] Wholething

### ISSUE THREAD

**Issue by C2Furious** [OvercastCommunity/CommunityMaps#222]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [ x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [ x] I have created an XML file
- [ x] I have created an map image
- [Y ] I have uploaded the map zip file to a file sharing service
- [ x] The map has been tested locally to make sure it works

I don't know how these work Need help tho

# Map Name

I don't have ideas name I called them Wholething but Suggest could be changed

## Gamemode & Map Description 

Capture The Wool

## Team Sizes

16v16

## Screenshots

https://imgur.com/a/kMHyO4L

# XML

N/A

# Map Image

N/A

# Download Link

https://drive.google.com/file/d/1oRKS5f1Q4hUGnm8EHuBwqYHptuypQTmo/view?usp=sharing

**Comment by C2Furious** [comment]
Somehow this world only work 1.16.5 
hope can fix somehow
You Probably Heard minehut popular server but other server make like minehut and create map there. It probably why there 1.16.5 server but i run older verison

**Comment by CoWinkKeyDinkInc** [comment]
The link is locked, you need to make the share link public

**Comment by C2Furious** [comment]
Link Updated

**Comment by CoWinkKeyDinkInc** [comment]
Where is the XML file?

**Comment by C2Furious** [comment]
> Where is the XML file?

I dont how theese work

**Comment by technodono** [comment]
you need an xml file for the map to work... you can learn more at the website pgm.dev or by looking at example xml's form the community maps repo

**Comment by C2Furious** [comment]
Mame_Bt help me for it All good!

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!

**Comment by CoWinkKeyDinkInc** [comment]
Please submit a properly formatted (290 x 246 resolution) image.
