### ISSUE TITLE
[CTW/35v35]Keipha CTW

### ISSUE THREAD

**Issue by simongrumer** [OvercastCommunity/CommunityMaps#223]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, (as mentioned in the README)
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Keipha CTW

## Gamemode & Map Description  
Captures the enemy´s wool

## Team Sizes
32 vs 32

## Screenshots
https://imgur.com/a/xjC67Ic

# XML
https://gist.github.com/simongrumer/78537bac0754fdc00bab9457b63c910b

# Map Image
![2021-07-30_10 44 18](https://user-images.githubusercontent.com/82534697/127629374-7f73c9ac-97dc-4fff-8cdf-021ec4429c55.png)
![2021-07-30_10 49 47](https://user-images.githubusercontent.com/82534697/127629352-86bf3fae-4593-418e-be2c-e5e0d61380c2.png)

# Download Link
https://app.mediafire.com/myfiles
https://www.mediafire.com/file/2varp0wd413d4e8/KeiphaCTW-by-zZkiIng-Polizei5_%25282%2529.zip/file

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!

**Comment by CoWinkKeyDinkInc** [comment]
Please submit a properly formatted (290 x 246 resolution) image.
