### ISSUE TITLE
[CTW/25v25v25v25] New Life CTW

### ISSUE THREAD

**Issue by RuedigerLP** [OvercastCommunity/CommunityMaps#224]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
New Life CTW

## Gamemode & Map Description  
It's a 4 team CTW, every team has to capture 2 wools from their left and right hand teams sides and place them in the victory monument room at the diagonally opposite teams side.

## Team Sizes
25v25v25v25

## Screenshots
![](https://imgur.com/f5iuGky.png)
[Imgur](https://imgur.com/a/u5Y5gcd)

**Comment by chleongithub** [comment]
where is the dwonload

**Comment by RuedigerLP** [comment]
> where is the dwonload

in the pull request below
