### ISSUE TITLE
[CTW/25v25v25v25] Corrupted Paradise CTW

### ISSUE THREAD

**Issue by RuedigerLP** [OvercastCommunity/CommunityMaps#225]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Corrupted Paradise CTW

## Gamemode & Map Description  
It's a 4 team CTW, each team is guarding 2 wools and captures 6. It was created as a summer school project with kids building their first map and getting a smalll insight into xml.

## Team Sizes
25v25v25v25

## Screenshots
![](https://imgur.com/P7yiKjx.png)
[Imgur](https://imgur.com/a/NjAfrPC)

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting, and congrats on first place!
