### ISSUE TITLE
[CTW/50v50] Dragon's Hearth

### ISSUE THREAD

**Issue by Artdamension** [OvercastCommunity/CommunityMaps#227]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Dragon's Hearth

## Gamemode & Map Description  
CTW, Capture the wools from the enemy dragon's wings!

## Team Sizes
2 Teams 50v50

## Screenshots
https://imgur.com/a/tei7cSD

# XML
[map-2.xml.zip](https://github.com/OvercastCommunity/CommunityMaps/files/6912623/map-2.xml.zip)

# Map Image
![map](https://user-images.githubusercontent.com/88203009/127689282-40a9fc40-00b3-4eee-be3f-56929483cadb.png)

# Download Link
https://drive.google.com/file/d/1TbqF4-tJyo9anlkIVMZZH2wTtOL9hETx/view?usp=sharing

**Comment by chleongithub** [comment]
this is art

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!

**Comment by CoWinkKeyDinkInc** [comment]
Please submit a properly formatted (290 x 246 resolution) image.
