### ISSUE TITLE
[CTW/32v32] Lupa

### ISSUE THREAD

**Issue by IcedCode** [OvercastCommunity/CommunityMaps#228]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Lupa

## Gamemode & Map Description  
CTW, Capture the Wools to win! You can also break the monument to access a supply room on the opposing teams side.

## Team Sizes
2 team, 32 v 32

## Screenshots
https://imgur.com/a/3TgYnAk

# XML
https://gist.github.com/IcedCode/0a75019783bf6c82a7d25f4d9184c5d8

# Map Image
![image](https://user-images.githubusercontent.com/7426927/127700626-d53b2003-b8ef-4eed-b8f4-32955698c250.png)

# Download Link
https://www.dropbox.com/s/uwzeyc9yb746tdf/Lupa.zip?dl=0

**Comment by calcastor** [comment]
being tested as 40v40 initially

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!

**Comment by CoWinkKeyDinkInc** [comment]
Please submit a properly formatted (290 x 246 resolution) image.
