### ISSUE TITLE
[CTW/50v50] Harbor CTW

### ISSUE THREAD

**Issue by RuedigerLP** [OvercastCommunity/CommunityMaps#229]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Harbor CTW

## Gamemode & Map Description  
From the makers of New Life CTW. Harbor CTW is a classic two-team map where two wools each must be defended and conquered. The classic design is mixed with a layout that combines geometric and organic shapes. Prominent features of the map are a port located on the mountain with a small but nice industrial metropolis containing several local companies. The interior design of the buildings is as if made by master craftsmen, the ship and train were created by the best engineers in the area and the green areas are innovative projects for nature conservation. Those who do not play this map are missing a true masterpiece.

## Team Sizes
50v50

## Screenshots
![](https://i.imgur.com/pSvDUqn.png)
[imgur](https://imgur.com/a/iRy7IhY)

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!
