### ISSUE TITLE
[CTW/50v50] Frost

### ISSUE THREAD

**Issue by Veilaa** [OvercastCommunity/CommunityMaps#230]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Frost

## Gamemode & Map Description
2 team CTW; Navigate your way through the frozen terrain and bring the enemy wools back to the victory monument at your Ice Palace.

## Team Sizes
2 teams; 50v50

## Screenshots
![image](https://user-images.githubusercontent.com/88005956/127724167-ae9fef5f-6906-42c3-b20d-2aa68df3e31e.png)
![image](https://user-images.githubusercontent.com/88005956/127724193-0630a343-1acf-40f5-8261-d9f477758dce.png)
More images: https://imgur.com/a/3Fp9aDW

# XML
https://gist.github.com/Veilaa/2e333416bfcf2d453a25c1c7af6a77e0

# Map Image
![mapimage](https://user-images.githubusercontent.com/88005956/127724977-6581ea2f-eb30-40c2-a2ac-dce93c9729c7.png)

# Download Link
(https://www.mediafire.com/file/bkqstl5agf5m1hj/Frost.zip/file)

**Comment by technodono** [comment]
there are gonna be alot of maps to vote on....

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!
