### ISSUE TITLE
[CTW/40v40] Tumbleweed

### ISSUE THREAD

**Issue by Xerocoles** [OvercastCommunity/CommunityMaps#232]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- (i'm including my own license, its not as restrictive as my competitive ones, hmu on discord if there's issues for some reason)
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Tumbleweed

## Gamemode & Map Description  
Big CTW, playercounts can be edited as needed, it should be nothing incredibly revolutionary but also not a super basic layout, it was well thought out and should give balanced gameplay and be fun to navigate. Some pretty epic aesthetics from us, and a cool layout which is slightly swervy, allows for mid-control, while still allowing heavy side-plays and skybridging, which is incentivized to start off one of the canyon cliffs at spawn. Lots of depth to the respawning route tree, lots of medium-sized void gaps, and lots of rotational areas. Also two very different wool room designs from each other

## Team Sizes
40v40 but can be changed idc

## Screenshots
[Imgur](https://imgur.com/a/aFiGEd1)

# Download Link
[tumbleweed.zip](https://github.com/OvercastCommunity/CommunityMaps/files/6910830/tumbleweed.zip)

**Comment by Brottweiler** [comment]
You have to agree to our license, no exceptions.

**Comment by calcastor** [comment]
it is the same license as this repo.

**Comment by Xerocoles** [comment]
> You have to agree to our license, no exceptions.

oh looks like the one i submitted is the same as was in the repo, so i don't really care either way tbh since im not very protective of my public maps

**Comment by Brottweiler** [comment]
> > You have to agree to our license, no exceptions.
> 
> oh looks like the one i submitted is the same as was in the repo, so i don't really care either way tbh since im not very protective of my public maps

Then please check the box and remove any license files in the zip if applicable.

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!
