### ISSUE TITLE
[DTM/C/20v20] Pyxa

### ISSUE THREAD

**Issue by RuedigerLP** [OvercastCommunity/CommunityMaps#253]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Pyxa

## Gamemode & Map Description  
It's DTM/C 2 Monuments and one Core, the entire map is parted into 18x18 cambers which are connected by litte 4x4 windows, this combined with infinite Golden Apples and Diamond Armor creates an experience never felt before. :)

## Team Sizes
20v20

**Comment by technodono** [comment]
It seems like half the submissions missing lol... where the screenshots & XML linkers

**Comment by CoWinkKeyDinkInc** [comment]
map image 
![image](https://user-images.githubusercontent.com/7586568/129115524-4ef834f3-f158-48e3-a2a3-5cda0dbb09bb.png)

**Comment by technodono** [comment]
> 
> 
> map image
> ![image](https://user-images.githubusercontent.com/7586568/129115524-4ef834f3-f158-48e3-a2a3-5cda0dbb09bb.png)

U sure? this does not fit the description

**Comment by CoWinkKeyDinkInc** [comment]
i only realized this is a map png of a different map smh

**Comment by CoWinkKeyDinkInc** [comment]
Please submit a properly formatted (290 x 246 resolution) image.

**Comment by CoWinkKeyDinkInc** [comment]
This map is really confusing for players to understand, why are there all these tight rooms? I think something where each room has a primary resource would be more easier to understand and make the gameplay more interesting.

Also in the two times I set this map it seems to be very easily rushed. Players don't know where their own objectives are and probably have a hard time finding where the diamonds are located on the map.
