### ISSUE TITLE
[DTM and CTW/32v32] Mythical Marsh

### ISSUE THREAD

**Issue by rockymine** [OvercastCommunity/CommunityMaps#263]
# Mythical Marsh

![](https://i.imgur.com/sivUF71.png)

A 32 v 32 DTM and CTW map. Breaking the monument unlocks both wool rooms. The wools spawn on top of bats. This map is a rework of a map that was built 2014 - but never played.

[Screenshots](https://imgur.com/a/oKQttIm)

See Pull Request for Download

- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

**Comment by rockymine** [comment]
https://github.com/OvercastCommunity/CommunityMaps/pull/264

**Comment by calcastor** [comment]
Adding to pools with March pool update
