### ISSUE TITLE
[CTW/32vs32] Factorio Mainbus 

### ISSUE THREAD

**Issue by Omote23** [OvercastCommunity/CommunityMaps#265]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Factorio Mainbus
(The redux version of Factorio gridbase = the contest ctw)

## Gamemode & Map Description  
Pure CTW. The amended version of the Factorio Gridbase, which has improved aesthetics (Thanks to Technodono and Polizei5), 
Most of the gimmicks are similar to Factorio Gridbase, but It has additional gimmicks. the time-based potion upgrading.

At the start of the match, you will get Seal potion (instant damage and slowness 1 15s) however when the match passes 20 minutes, to reduce the stalemate situation, a new Drive(Speed 1 but weakness 1) potion will be given to all players when they spawn. this will make easy to build skybridge and rushing and hard to defend. 
However, even the match passes 40 minutes. another potion upgrade is progressed. at this time, you will get speed 1 pots without penalties, and a new debuff potion (Plague - Mining fatigue 1 and Hunger 1 (90s)) is replaced instead of seal.) replaces the Seal. 
After 60 minutes passed, you'll get a Speed 2 Potion which is quite OP when you spawn, but It has really harsh penalty, it instantly drains 6 hearts. So use it carefully. and debuff potion's strength is increased but duration is reduced. 

In addition, I added the center spot called "The Pylon" which has really strong potions inside. However, It has only one potion per type and never respawned)

Of course, Balancing between potions is not perfect because It hasn't been tested in public. I'll keep mediating this balancing issue. 

## Team Sizes
32 vs 32 (Hecto or Centi even works I think)

## Screenshots
https://imgur.com/a/QphpuwR

# XML
https://gist.github.com/Omote23/79c29dce069b623266d331b9c8a43157

# Map Image
![2021-08-23_15 02 38](https://user-images.githubusercontent.com/13076502/130398843-0284fd76-d4dc-42c0-a8cd-060058436f07.png)

# Download Link
https://www.dropbox.com/s/eemt89d7or06lob/Factorio%20Mainbus.zip?dl=0

**Comment by CoWinkKeyDinkInc** [comment]
The `Rocket Fuel` and `Calipers` potion needs to be updated to show what the effects the potion gives off. The portal for the purple wool room is broken and portal exit for cyan seems to be 5 blocks off. The aesthetics of the map are great!

**Comment by Omote23** [comment]
> The `Rocket Fuel` and `Calipers` potion needs to be updated to show what the effects the potion gives off. The portal for the purple wool room is broken and portal exit for cyan seems to be 5 blocks off. The aesthetics of the map are great!

I edited it. xD

2.0.1 patch
1. Calipers and Rocket fuel potions are now shown effects before using
2. Fixed the wool room portal bug.
3. Revised some potion's strength on the pylon (Center building).

**Comment by calcastor** [comment]
In hopes of garnering a wider range of player feedback on several pending yet 100% functional community maps, I've gone ahead and added many of them to the pools. This map has been included in that, and I hope to be able to collect at least the most prevalent feedback on the each map to post in their respective issues pages.
