### ISSUE TITLE
[Arcade/50v8] Hide n' Seek: Shaheedieni Zombie Edition

### ISSUE THREAD

**Issue by lunaceeee** [OvercastCommunity/CommunityMaps#267]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Hide n' Seek: Shaheedieni Zombie Edition

## Gamemode & Map Description  
Arcade
## Team Sizes
50v8

# Map Image
https://i.imgur.com/NjKn40p.png

# Download Link and XML

https://www.dropbox.com/s/c0vgg0zo1k03bms/HNS%20Zombies.rar?dl=0

**Comment by CoWinkKeyDinkInc** [comment]
Loaded

**Comment by CoWinkKeyDinkInc** [comment]
Added to the fun pool, thanks for contributing!

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 0c332e83e36e2888c2097d5ba83ae19d70b1cc09
