### ISSUE TITLE
[CTW/DTM/15v15] Piorun

### ISSUE THREAD

**Issue by lunaceeee** [OvercastCommunity/CommunityMaps#269]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Piorun
## Gamemode & Map Description  
CTW/DTM 
you may bridge via mid after 5 mins 
## Team Sizes
15v15

#screenshots
https://i.imgur.com/pwSpi5c.png

# Map Image
https://i.imgur.com/jtIhO9H.png

# Download Link
https://www.dropbox.com/s/wad056yk7xw62ws/Piorun.zip?dl=0

**Comment by calcastor** [comment]
adding to pools with november pool update
