### ISSUE TITLE
[CTW/20v20] Vesuvius

### ISSUE THREAD

**Issue by lunaceeee** [OvercastCommunity/CommunityMaps#270]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Vesuvius
## Gamemode & Map Description  
CTW - you can build anywhere on the map except the areas near spawn
## Team Sizes

20v20
## Screenshots
https://i.imgur.com/z1Ranaa.png

# Map Image
https://i.imgur.com/8nQn47s.png

# Download Link and XML
https://www.dropbox.com/s/vn64n9min6eq1yc/Vesuvius.zip?dl=0

**Comment by CoWinkKeyDinkInc** [comment]
Added in b84edb9

**Comment by CoWinkKeyDinkInc** [comment]
![image](https://user-images.githubusercontent.com/7586568/133911454-472e77a8-1045-4e23-a9b5-0b4de84c823e.png)
A lot of the map feels a bit disconnected, im not sure if it was clear to players where they were supposed to go

**Comment by lunaceeee** [comment]
Ello, I got to see the map get played like 3 more times and everyone knew where to go and stuff so yea. I've updated the team sizes to 25v25 (could maybe even bump it up to 30v30), and added water lanes at 20 minutes (https://i.imgur.com/SV3kUqt.png) 

Map played fine, lasted like 15 minutes, and once it gets played more ppl will naturally find out how to defend properly and it will prob last a good while, but not 10 hours or anything

[Vesuvius.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7192829/Vesuvius.zip)

^updated XML and few changes to chests

**Comment by CoWinkKeyDinkInc** [comment]
Updated in b549ada. Mame has told me he did not help you with the XML so I have removed him as a contributor. I have also cleaned up styling and alignment a bit.

**Comment by calcastor** [comment]
adding to pools with november pool update
