### ISSUE TITLE
[Arcade/8 teams (80 Players)] Art Contest

### ISSUE THREAD

**Issue by CredensJustitiam** [OvercastCommunity/CommunityMaps#271]
### Checklist
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [ ] The map has been tested locally to make sure it works

# Map Name
Art Contest

## Gamemode & Map Description  
This is an arcade map in which teams work together to create a drawing out of blocks in 3 minutes, and then vote on whose team's artwork is the best.

## Team Sizes
There are 8 teams with a maximum of 10 players on each.

## Screenshots
https://imgur.com/gallery/eahj3Z6

# XML
https://gist.github.com/CredensJustitiam/5b0e6b89ffdfae60c4b3cfc55c156686

# Map Image
![map](https://user-images.githubusercontent.com/80809061/133168062-95af5816-9c63-49a3-a1df-caa7cb0aa571.png)

# Download Link
https://www.mediafire.com/file/g27j7k9635fokii/Art_Contest_%25281.8.9%2529.zip/file

----------

My XML isn't completely finished because there were a few things
I didn't know how to do. If I can't do them, I will have to rework
certain parts of this map. Here's what I need to do:

1. I want a randomized message from a list to appear in chat at the start of the
round, but I don't know how randomization works in XML.
2. Everyone gets the ability to fly at the beginning of the round,
but I want flying to become disabled after 3 minutes.
3. When a "scorebox" is entered, I want a different team to get
points from it than the team that's entering the scorebox.

I also might ask someone for help with decorating the map later since it's
somewhat bland right now. I want to solve the XML stuff first if possible.

**Comment by CoWinkKeyDinkInc** [comment]
A lot of the XML uses outdated conventions that are incompatible with proto 1.4.0. These are things such as `name=` as region references, which should be replaced with `'id=`.

**Comment by CredensJustitiam** [comment]
I fixed that part of the xml, let me know what else I need to fix

**Comment by CredensJustitiam** [comment]
I might reupload this map sometime but im kinda done with this server rn
