### ISSUE TITLE
[CTW/12v12v12v12v12v12] Thunderbolt

### ISSUE THREAD

**Issue by rockymine** [OvercastCommunity/CommunityMaps#273]
### Thunderbolt

> The first-ever six-team map.

Thunderbolt is the fourth installation of the Thunder series. The map is the very first to host SIX teams. Using Arceon's Revolve tool, one side was rotated six times. Some buildings had to be manually edited to look good - even at odd angles. The shape of the islands has remained mostly the same and shouldn't affect gameplay too much. It will be interesting to see how the sky bridges will play out. The maximum build height is 23 blocks to incentivize ground rushing.

![](https://i.imgur.com/qiwIUnE.png)

I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map [ x ] and agreed with assigning the CC BY-SA license to this map, as mentioned in the README [ x ]. @RuedigerLP has created an XML file [ x ]. @Just_ created the map image [ x ]. The map has been tested locally to make sure it works [ x ].

The map download is included in the [corresponding pull request](https://github.com/OvercastCommunity/CommunityMaps/pull/272). Map images are available [here](https://imgur.com/a/u2TQghp).

**Comment by calcastor** [comment]
finally got to see this tested today and I don't really think it has any issues to address before entering pools. thus I have added it to hecto, thank you for submitting!
