### ISSUE TITLE
[TDM/15v15] Die Noon (Miner Sixty Niner Halloween)

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#274]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Die Noon

## Gamemode & Map Description  
The map is just a halloweenified version of the already loaded Miner Sixty Niner and thus should play identically.

## Team Sizes
15v15.

## Screenshots
[Imgur](https://imgur.com/a/fdYcuGG)

# XML
[XML](https://gist.github.com/Cazadorian/85bc0edd1911193cd012016cdde81d5e) 

# Map Image
![map](https://user-images.githubusercontent.com/73002842/134600261-132c9f44-4a2b-4b05-88e7-413bb703d2ff.png)

# Download Link
[Die Noon.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7221385/Die.Noon.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in edd270b
