### ISSUE TITLE
[16*4/CTW] Nether War CTW

### ISSUE THREAD

**Issue by simongrumer** [OvercastCommunity/CommunityMaps#275]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Nether War CTW

## Gamemode & Map Description  
Capture the Wool from the other teams!

## Team Sizes
24 x 4

## Screenshots
https://imgur.com/a/l7YGxyx

# XML
https://gist.github.com/simongrumer/e9cac6ae23849ac96a8a6b3a39b5b6f4

# Map Image
![image](https://user-images.githubusercontent.com/82534697/134977517-161c233c-4726-477b-a286-ed5d571132df.png)

# Download Link
https://drive.google.com/file/d/13-KqIab9msiPpk0ccHzcLJL4PjrFUICH/view?usp=sharing

**Comment by simongrumer** [comment]
Not pruned!!!!

**Comment by simongrumer** [comment]
Updated the Xml (wrong one; I got so many Xml files and Im kinda messy, sorry for that). Ruediger helped me out there.

**Comment by CoWinkKeyDinkInc** [comment]
The regions are fixed, so now the map is added in b5142f2. Thanks for the fixes!
