### ISSUE TITLE
Missing Wool Regions on 3078 CTW

### ISSUE THREAD

**Issue by huuian** [OvercastCommunity/CommunityMaps#282]
**Intended Behavior**: There isn't a gaping hole where the chunk for the wool room is supposed to be.
**Current Behavior**:
![image](https://user-images.githubusercontent.com/91851089/135949291-d1960962-bcfb-45e2-a400-037676cbe7a5.png)
![image](https://user-images.githubusercontent.com/91851089/135949308-75648ccf-77cc-4323-bf87-42ad93eada80.png)
![image](https://user-images.githubusercontent.com/91851089/135949326-06643450-807e-43fb-8ee9-5a38196e7bdd.png)
![image](https://user-images.githubusercontent.com/91851089/135949356-b122c589-83b0-40f6-957f-2adb21caedc8.png)
![image](https://user-images.githubusercontent.com/91851089/135949371-17119b5f-f9ac-4f02-9c27-0157505161bf.png)
![image](https://user-images.githubusercontent.com/91851089/135949395-eab2c975-3920-4c12-bb1f-849c14429182.png)

These images were gathered while using the map files from https://github.com/OvercastCommunity/CommunityMaps/tree/master/3084/region.

**Comment by technodono** [comment]
that's funny... images took ages to load for some reason... I'm not a developer but maybe this is pgm issue???

**Comment by technodono** [comment]
> 
> 
> **Intended Behavior**: There isn't a gaping hole where the chunk for the wool room is supposed to be. **Current Behavior**: ![image](https://user-images.githubusercontent.com/91851089/135949291-d1960962-bcfb-45e2-a400-037676cbe7a5.png) ![image](https://user-images.githubusercontent.com/91851089/135949308-75648ccf-77cc-4323-bf87-42ad93eada80.png) ![image](https://user-images.githubusercontent.com/91851089/135949326-06643450-807e-43fb-8ee9-5a38196e7bdd.png) ![image](https://user-images.githubusercontent.com/91851089/135949356-b122c589-83b0-40f6-957f-2adb21caedc8.png) ![image](https://user-images.githubusercontent.com/91851089/135949371-17119b5f-f9ac-4f02-9c27-0157505161bf.png) ![image](https://user-images.githubusercontent.com/91851089/135949395-eab2c975-3920-4c12-bb1f-849c14429182.png)
> 
> These images were gathered while using the map files from https://github.com/OvercastCommunity/CommunityMaps/tree/master/3084/region.

also second thing to note is that this map isn't in the pools so I doubt there's much of a worry... as for the gaping holes... maybe @Acernite knows?

**Comment by mybeary-afk** [comment]
> that's funny... images took ages to load for some reason... I'm not a developer but maybe this is pgm issue??? neither am I the map creator funny enough

One thing to also note was that I was loading these maps on a TGM server; sure, a fallacy can be made that I'm using an unsupported plugin, but again I don't think that would cause a targeted chunk corruption to all wool rooms.

**Comment by calcastor** [comment]
> > that's funny... images took ages to load for some reason... I'm not a developer but maybe this is pgm issue??? neither am I the map creator funny enough
> 
> One thing to also note was that I was loading these maps on a TGM server; sure, a fallacy can be made that I'm using an unsupported plugin, but again I don't think that would cause a targeted chunk corruption to all wool rooms.
> 
> I'll reload on PGM; I'll come back on this lol.

What version are you using for this? this world is a 1.8 world and from what I understand, TGM is 1.16 based (though I've heard it can run on 1.8?). Converting worlds between versions can result in chunk errors such as this even if done properly.

Either way, I'm going to close this issue as the copy that is in our repo loads properly in 1.8 + upstream PGM. However, feel free to reply back if you are having issues with converting it between versions as I might be able to help if you'd like.

**Comment by master00ofdsiware** [comment]
Don't come to us if you are having issues when trying to load our maps on an unsupported server version with an unsupported plugin. This repository's purpose is to provide maps that work with PGM on Spigot 1.8.

Any other version or plugin is not our concern. @huuian @mybeary-afk
