### ISSUE TITLE
[Rage CTF/30v30] Stairs to Nowhere

### ISSUE THREAD

**Issue by EpicPuppy613** [OvercastCommunity/CommunityMaps#286]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Stairs to Nowhere

## Gamemode & Map Description  
King of the Flag / Rage
1. Rage - All bow hits or sword hits are 1 hit kill, a knockback stick that doesn't 1 hit kill is also included
2. CTF - Collect the flags and bring them back to your side to put them on your posts, you will earn points based on how many flags you control
3. Steal flags from the enemy team to prevent them from getting more points

## Team Sizes
24v24 (32v32 including overflow)

## Screenshots
![image](https://raw.githubusercontent.com/EpicPuppy613/stairs-to-nowhere/main/images/close%20up.png) ![image](https://raw.githubusercontent.com/EpicPuppy613/stairs-to-nowhere/main/images/map%20side.png) ![image](https://raw.githubusercontent.com/EpicPuppy613/stairs-to-nowhere/main/images/whole%20map.png)

# XML
[https://github.com/EpicPuppy613/stairs-to-nowhere/blob/main/map.xml](https://github.com/EpicPuppy613/stairs-to-nowhere/blob/main/map.xml)

# Map Image
![image](https://raw.githubusercontent.com/EpicPuppy613/stairs-to-nowhere/main/map.png)

# Download Link
[https://github.com/EpicPuppy613/stairs-to-nowhere/releases](https://github.com/EpicPuppy613/stairs-to-nowhere/releases)

**Comment by CoWinkKeyDinkInc** [comment]
I am confused on what is the objective of this map, King of the Flag maps do not have a net to score from, but this map describes nets. Could you share what type of CTF type this is? You can make a custom game title using `<game>`. Also don't forget to use comments in the XML to describe what you're doing with the filters.

Since this is a rage map I would strongly suggest removing the bread and disabling hunger. I would add a few more colours to help players find their way around the map easier, and feather falling II. From how the map is designed you may need to add more stairs, but we can check that out after testing.

I fixed the formatting and some mistakes on your XML (you misspelled contributors), use this to start off with some new adjustments
[map_xml.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7361705/map_xml.zip)
.

**Comment by EpicPuppy613** [comment]
> I am confused on what is the objective of this map, King of the Flag maps do not have a net to score from, but this map describes nets. Could you share what type of CTF type this is? You can make a custom game title using `<game>`. Also don't forget to use comments in the XML to describe what you're doing with the filters.
> 
> Since this is a rage map I would strongly suggest removing the bread and disabling hunger. I would add a few more colours to help players find their way around the map easier, and feather falling II. From how the map is designed you may need to add more stairs, but we can check that out after testing.
> 
> I fixed the formatting and some mistakes on your XML (you misspelled contributors), use this to start off with some new adjustments [map_xml.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7361705/map_xml.zip) .

According to the king of the flag defined in the documentation, the common king of the flag often referred to is actually flag blitz. The documentation says that KotF is 
> Capture a shared flag in your own net to bring it to your side, then keep it there as long as possible.

**Comment by EpicPuppy613** [comment]
## 1.0.3
[https://github.com/EpicPuppy613/stairs-to-nowhere/releases](https://github.com/EpicPuppy613/stairs-to-nowhere/releases)

- Turned hunger off
- Removed bread from kits
- Feather falling I -> II
- Added more color indicators
- Added in-game tip

**Comment by EpicPuppy613** [comment]
## 1.0.4
[https://github.com/EpicPuppy613/stairs-to-nowhere/releases](https://github.com/EpicPuppy613/stairs-to-nowhere/releases)
- Actually turned hunger off

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 9c7f7ed

**Comment by EpicPuppy613** [comment]
> Remember that we don't use tabs we use 4 spaces when indenting XML.
That's probably because of my code IDE, sorry

**Comment by EpicPuppy613** [comment]
## 1.2.0
- Added more walls to some of the platforms
- Added author and contributor player heads to the spawn information board
- Fixed some issues with formatting in the xml document

[https://github.com/EpicPuppy613/stairs-to-nowhere/releases](https://github.com/EpicPuppy613/stairs-to-nowhere/releases)

**Comment by EpicPuppy613** [comment]
## 1.2.1
- Updated the map.png image to be more recent to the current version of the map

[https://github.com/EpicPuppy613/stairs-to-nowhere/releases](https://github.com/EpicPuppy613/stairs-to-nowhere/releases)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 40ea46b. Sorry for the wait!

**Comment by CoWinkKeyDinkInc** [comment]
A player has told me that some players spawn inside of the blocks, double check that the spawn coordinates are correct.

**Comment by Cazadorian** [comment]
I've added the map to the Rage and Fun pools for use in staff events. The map is also currently sponsorable and has been for a long time. I do not believe this map can be improved any further, but the overall concept makes it unsuitable for the everyday map pool and so won't be added to it. As a result I'm closing this issue as complete.
