### ISSUE TITLE
[CTW/16v16] Fairy Tales: Metamorphose

### ISSUE THREAD

**Issue by Palmidence** [OvercastCommunity/CommunityMaps#29]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Fairy Tales: Metamorphose

## Gamemode & Map Description  
A CTW map that I built on Anax when D347HxD briefly returned to mapmaking. After talking with him, there were evidently various other Fairy Tales renditions that never came to fruition, most of them pretty much lost to time as well as other (much older) maps. 

## Team Sizes
2 teams - 16v16

## Screenshots
![image](https://user-images.githubusercontent.com/17485345/93165463-2151a380-f6ea-11ea-852a-643bd805d1ec.png)

**Album** - https://imgur.com/a/7tURqNx

# XML
https://gist.github.com/Palmidence/31370245625776a394b3ec9eb1bc4699 (Thanks to @CrazyisCreeps)

# Map Image
![](https://raw.githubusercontent.com/MCResourcePile/stratus-maps/master/maps/fairy_tales_metamorphose/map.png)

# Download Link
https://www.dropbox.com/s/9ibnlvcvy4mcf5i/fairy_tales_metamorphose%20%282%29.zip?dl=0

**Comment by CrazyisCreeps** [comment]
Is this the same version as the one previously loaded on Stratus? I remember there were a couple of things I had wanted to change and can't remember if I ever got around to doing it back there.

For example, the portals to the side lanes weren't very clear, and people often had no idea of their existence. If I remember right, you had to go up a ladder to get to them?

The other thing I had wanted to do something about was the build height limit. I found as you got closer to the other team's spawn, to get to the wools, the limit was too low and it was challenging to do a sky push into the wool. On the flip side, it was a little too close to spawn to really succeed with a ground push. I think I wanted to stagger the height limit to try and see what would happen and how that would affect the gameplay.

**Comment by Palmidence** [comment]
@CrazyisCreeps Yes, it's the same version - I never really got to see people use the portals much either, but it was nice they were there for people who started to get more familiar with the map. My line of thinking was that as people observe the match, having a faster way to get to front lines would be beneficial later in the match if the middle lane gets clogged up. Not sure where I could move the portals - maybe to the sides of spawn? (I just don't want to have _everyone_ use the portals, otherwise, a good portion of the team's side becomes effectively underused. My best guess was to put them in spawn, just not in front of everyone's face.) 

Maybe portals open up on the sides after a certain amount of time in the match has passed? But as far as I know PGM doesn't support a feature that you can't enter a portal until a certain point in the match, and I'd have to make side islands inaccessible for a while.

As for the height limit, I'm okay with increasing it.

**Comment by CrazyisCreeps** [comment]
Yea, okay that's a fair point in terms of not wanting it to become the main route for players. Let's keep the idea of doing something with filters handy, I want to see how it gets played a few times more before trying to see how that could affect it (it's been a while since I last played it). Are you able to fix the download link? It doesn't work for me and I'd like to take a look at the map to try and suggest what a good tweak to the height limit could be.

**Comment by Palmidence** [comment]
The download link has been fixed.

**Comment by CrazyisCreeps** [comment]
Alright so it after a few tests, I can say people really have no idea about the portals. Most people access the lanes via pillaring up to them, and don't quite understand why they can't bridge to them directly. The increased build limit (8 blocks) seems to have made sky bridging near their spawn a lot more feasible, I'm glad that worked out nicely. But yea, maybe we can give the portals some more visibility, they're an awesome addition to the map but I fear that people just won't know of their potential as it stands now. Maybe we can delay the usage of them by something like 10-15 mins, to prevent people from using them as an easy point to rush?

**Comment by CrazyisCreeps** [comment]
Bit of a delay here but I took it upon myself to fix up the side portal situation. I moved the portals to the lower floor of spawn, and made it pretty clear they don't open up for access until x time. Right now I have it set to 5 minutes, I'll see how that goes and I might increase it up to 10 minutes depending (it seems like it might be kinda short). If you didn't want to pull from the repo itself and you wanted a copy of the new changes, you can find that from here https://www.dropbox.com/s/fdjz74nrfnq0nym/Fairy%20Tales%20Metamorphose.zip?dl=0

Oh and I'll be adding this to the pools. Thanks for submitting the map!
