### ISSUE TITLE
[Rage TDM+KoTH/20v20] Stratosphere Rage

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#291]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Stratosphere Rage

## Gamemode & Map Description  
This is one of three versions of Stratosphere, with this one being the main Rage version. This version of the map is both a TDM and a KoTH, with kills awarding 1 point and the hill awarding 0.3 points per second held. The kits on this map are in line with the standard kits for Rage, and the map uses speed boosts and jump pads for increased mobility

## Team Sizes
Two teams 20v20

## Screenshots
[Imgur album](https://imgur.com/a/ys5dW8G)
# XML
[XML](https://gist.github.com/Cazadorian/56c6680b7e3efb624958d372a9748193)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/139563181-51d3dc00-1138-41dd-a8bd-a190b8fb08ee.png)

# Download Link
[Stratosphere Rage.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7447914/Stratosphere.Rage.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in dd1c446.

**Comment by Cazadorian** [comment]
Map has been updated based on feedback from it being played earlier today

- Jump pad velocities have been increased to prevent people slowing down too much when drawing a bow in mid air
- Hill has been renamed to Pit to make it a bit clearer where it is
- Hill has been increased from 0.3 points per second to 0.5 points per second
- Tip has been added to make the points per second more obvious
- Speed potion spawners have been removed and the default kit now has the equivalent to speed 2 in attributes. (Experimental change, may be reverted)
- Arrow kill reward upped from 1 to 2

[Stratosphere Rage V1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7509860/Stratosphere.Rage.V1.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in ea30974.

**Comment by Cazadorian** [comment]
Updated based on further feedback

- A second hill has been added to the top of the map as at the moment players tend to just all pile into Pit and go nowhere else.
- A short speed buff that was accidentally included in the spawn kit has been removed.
- Hill capture time reduced to 0.5 seconds to allow trades back and forth to happen much faster
- Gamemode renamed from CP to KoTH as it is more accurate.
 
[Stratosphere Rage V1.2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7585434/Stratosphere.Rage.V1.2.zip)

**Comment by calcastor** [comment]
closing issue as it is currently in pools
