### ISSUE TITLE
[CTW/20v20] Stratosphere CTW

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#292]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Stratosphere Rage

## Gamemode & Map Description  
This is one of three versions of Stratosphere, with this one being the CTW version. This version of the map is a CTW in the style of Ender Hill or Cloud Nine where there are four dye spawners across the map, and players are awarded string upon kill. String must be crafted together to create wool, and then dyed to get wool for the victory monuments.

## Team Sizes
Two teams 20v20

## Screenshots
[Imgur album](https://imgur.com/a/nrITuXW)

# XML
[XML](https://gist.github.com/Cazadorian/7f75d26f1bd6905aca9ffdc448a77c78)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/139563287-2cdfc304-c9ec-4a21-9797-76f764c4e889.png)

# Download Link
[Stratosphere CTW.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7447918/Stratosphere.CTW.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in ac1f366.

**Comment by Cazadorian** [comment]
Map has been updated based on feedback from it being played yesterday

- A few void holes have been added to the map to hopefully result in higher death rates
- All spawn kit gear reduced to leather and projectile protection removed to make it much faster to kill players, based on feedback of it being too easy to survive to 4 kill streaks
- White wool removed from item remove to potentially allow people to steal wools from the other team and to allow players to drop the white wools to team mates with dyes. 

[Stratosphere CTW V1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7526758/Stratosphere.CTW.V1.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 07aa666.

**Comment by Cazadorian** [comment]
Map has been updated based on further feedback

- Fixed some minor XML mistakes from the last update.
- Added speed 1 to the spawn kits.
- Added a jump boost 255 kit to the jump pads, removed with the grounded filter. This completely removes all fall damage from using the jump pads while keeping all forms of damage enabled elsewhere in the map.

[Stratosphere CTW V1.2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7561906/Stratosphere.CTW.V1.2.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 85557a9

**Comment by Cazadorian** [comment]
This map is likely never going to receive any future updates or be added to pools as the rage version of Stratosphere is very much the main one at this point, so closing this issue as a result.
