### ISSUE TITLE
[FFA/32] La Piazza

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#293]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
La Piazza

## Gamemode & Map Description  

This a classic v32 FFA designed for the centi-pool... this map makes use of projectiles too to create a mock "crossbow" that sacrifices firing rate for range & damage... If it's too boring I may make it explosive at some point.

## Team Sizes
32 players max (Centi)

## Screenshots
https://imgur.com/a/AIDCV7u

# XML
https://gist.github.com/technodono/e1cf1edbfbe449ffc3bee196a21c4523

# Map Image

![map](https://user-images.githubusercontent.com/22761234/139846537-e8723175-8a63-46da-b7e8-3bd2a02a1189.png)

# Download Link
[La Piazza.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7460618/La.Piazza.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Your XML has a spawners comment but there are no spawners defined. Is there meant to be spawners in the XML?

**Comment by CoWinkKeyDinkInc** [comment]
Added in b6fbf4c

**Comment by calcastor** [comment]
going to be added to pools next month, closing issue
