### ISSUE TITLE
[CTW/24v24] Renegade

### ISSUE THREAD

**Issue by rockymine** [OvercastCommunity/CommunityMaps#298]
### Renegade

![](https://i.imgur.com/AY1O4Jq.png)
Renegade is a CTW map created by byRobo, rockymine, and Just_.

- [ x ] I have pruned the map
- [ x ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [ x ] I have created an XML file
- [ x ] I have created an map image
- [ x ] I have uploaded the map zip file to a file sharing service
- [ x ] The map has been tested locally to make sure it works

More [images](https://imgur.com/a/HHVOLk9).
The map can be downloaded from the builders dropbox (if you happen to have access to that 😄 )

**Comment by rockymine** [comment]
https://github.com/OvercastCommunity/CommunityMaps/pull/299

**Comment by Cazadorian** [comment]
This map seems unlikely to get any further updates as the authors have indicated that they're disinterested in doing so so long after it was originally submitted. We're unlikely to use the map further but if there are ever any further updates to fix the issues it has we can reconsider this. Thank you for the submission.
