### ISSUE TITLE
[CTW/16x16x16x16] NeoTrad

### ISSUE THREAD

**Issue by Alternqtive** [OvercastCommunity/CommunityMaps#300]
### Checklist
[X] I have pruned the map
[X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
[X] I have created an XML file
[X] I have created an map image
[X] I have uploaded the map zip file to a file sharing service
[X] The map has been tested locally to make sure it works

# Map Name
NeoTrad

## Gamemode & Map Description  
NeoTrad is a 16x16x16x16 Capture The Wool map created by Alternqtive and Anarquista. It is inspired by, and supposed to be a futuristic revamp of Tetrad by Chicky. 

## Team Sizes
16x16x16x16

## Screenshots

https://imgur.com/gallery/8RfMGOG

# XML
https://gist.github.com/Alternqtive/21f2baea540ee983553e0f45c9cdbb75

# Map Image

![map](https://user-images.githubusercontent.com/94016692/141010222-52ac55f4-bc68-455a-8a4a-5ebc0e39ae17.png)

# Download Link

https://www.mediafire.com/file/ekgc7susgu1rm62/NeoTrad.rar/file

**Comment by Cazadorian** [comment]
The author has said that they most likely won't make any further updates to this map, and we seem unlikely to add this map to the pool for now. We may potentially consider using the map for a pool update at some stage, but as we currently have no plans to I'll close this issue for now. Thank you for the submission.
