### ISSUE TITLE
[TDM/20v20] Death DeNile

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#301]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Death DeNile

## Gamemode & Map Description  
This map is a TDM using the same subgamemode concept already used by Miner Sixty Niner/Die Noon. Like with that map instead of scoring upon kill players are given a score item(for this map emeralds) which is redeemed into points when scoring in the scorebox with them. The score items drop upon death allowing other players to "steal" the points for themselves instead. Platforms to the scorebox open up for 30 seconds, then close for 30 seconds, until the match is over. Winning team is the one with the most points by the end of the match.

## Team Sizes
2 Teams 20v20

## Screenshots
[Screenshots](https://imgur.com/a/6wAUgVt)

# XML
[XML](https://gist.github.com/Cazadorian/3e52ef59358aba1b59a72b0bb45dc1f2)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/141280116-7902cc51-182f-4810-9c36-a4dea079d7a6.png)

# Download Link
[Death DeNile.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7519565/Death.DeNile.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in ac9801d

**Comment by Cazadorian** [comment]
Map updated based on playtest
- Poison 2 region added to the scorebox entrance platform. This should ideally make it impossible for players to camp up on it the entire time as that currently makes attacking the scorebox too difficult. 
- Fixed regen upon scoring so it actually works

[Death DeNile 1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7585341/Death.DeNile.1.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in c96a00a.

**Comment by Cazadorian** [comment]
I'm unlikely to update this map further and I don't think I'd ever be adding it to the pool as it's the weakest map of the gamemode so just closing this issue and leaving the map as is.
