### ISSUE TITLE
[CTF-Rage/12v12] Focus

### ISSUE THREAD

**Issue by Alternqtive** [OvercastCommunity/CommunityMaps#302]
### Checklist
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [x] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Focus

## Gamemode & Map Description  
Focus is a CTF Rage map by Alternqtive. Inspired by Electroid's Directrix

## Team Sizes
12v12

## Screenshots
[Screenshots](https://imgur.com/a/pJCRgZW)

# XML
[XML](https://gist.github.com/Alternqtive/0298f4e971ccd3e28c60617fae2bf27a)

# Map Image

![map](https://user-images.githubusercontent.com/94016692/141423301-1f603f4b-8ee6-47a7-917b-29aa594fed9e.png)

# Download Link
[Map download](https://www.mediafire.com/file/ogolr0lrbjpg25r/Focus.rar/file)

**Comment by CoWinkKeyDinkInc** [comment]
Added in 75dfd49

**Comment by CoWinkKeyDinkInc** [comment]
Certain velocities are quite weak, but it should be pretty obvious which ones need to be fixed. Despite the large space the map takes up it is still confusing to navigate and it feels restricted in a lot of ways to travel to the flag, It's still pretty difficult to reach the flag, despite the extra space and only 12 enemies to deal with.

**Comment by calcastor** [comment]
From my understanding you don't intend to update this map any further which is fine. Thank you for submitting it! We won't add it to pools in its current state but we'll leave it to be sponsorable if that's alright!
