### ISSUE TITLE
[CTW/24v24] Oceano CTW

### ISSUE THREAD

**Issue by Jussssst** [OvercastCommunity/CommunityMaps#303]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Oceano CTW

## Gamemode & Map Description  
I build this 24v24 CTW map because i thought that the maps in the hecto rotation are very overplayed and could use some variety. The map has a unique, asymmetrical layout and has a clean and gameplay focused build style. The color sceme is also unique and having to capture only 1 wool inst too common either for a map of this size.

## Team Sizes
Its a 24v24 map!

## Screenshots
https://imgur.com/a/7A9G7Cp

# XML
https://gist.github.com/Jussssst/9ec3d440d80c1cdcffb18f7eebee3325

# Map Image
![OceanoCTW](https://user-images.githubusercontent.com/69433766/141515234-00d059b8-6431-43a3-85a1-cd43b6c69259.png)

# Download Link
https://drive.google.com/file/d/1gu5WiqXQBMM2hiEMyYG2Cd4VRcqni35D/view?usp=sharing

**Comment by calcastor** [comment]
Adding v2.0 to pools with March pool update
