### ISSUE TITLE
[CTW/8v8] EnderiumCTW

### ISSUE THREAD

**Issue by Quantum155** [OvercastCommunity/CommunityMaps#304]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
EnderiumCTW

## Gamemode & Map Description  
This 8v8 (nano) CTW map features a minimalistic single-lane design. The woolrooms are behind the enemy spawn, to compensate for that, players can bridge above enemy spawn.

## Team Sizes
8v8, overfill size 13.

## Screenshots
https://imgur.com/a/Xa8PpGN

# XML
https://gist.github.com/Quantum155/a5a45e9a24aef42f7704c80af5f26caa

# Map Image
![map](https://user-images.githubusercontent.com/61941975/141527714-c4ccd76d-f31f-4735-a383-50fc04a340f1.png)

# Download Link
https://drive.google.com/drive/folders/1rvC6YjNB61Vb-ao11jqUdkE48hwKvd4A?usp=sharing

**Comment by CoWinkKeyDinkInc** [comment]
One of the chests is empty with no birch logs, and spawns need to be protected. It needs more improvement on gameplay, as a team can get stuck behind on their spawn island and do little of anything since leaving becomes very difficult.

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/a6e4482e33142db0bd5a9e7cf0acae351389b680

**Comment by Quantum155** [comment]
Going to close this issue as the map plays very badly, and it's not really fixable without recreating the entire map. I think unloading the map would be the best here.
