### ISSUE TITLE
[RAGE-TDM] Focus - 1.0

### ISSUE THREAD

**Issue by Alternqtive** [OvercastCommunity/CommunityMaps#305]
### Checklist

- [ X ] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [ X ] I have uploaded the map zip file to a file sharing service
- [ X ] The update has been tested locally to make sure it works

# Changes

- Gamemode changed from CTF to TDM
- Changed max players from 12v12 to 20v20
- Fixed jump pads - Used double jumps
- Spawn spread increased to 2
- Added extra cover walls all across the map
- Added an extra path on the left of each base that leads to the side middle islands
- Decorative improvement

[Screenshots](https://imgur.com/gallery/HWZSy49)

**New Map Image**

![map](https://user-images.githubusercontent.com/94016692/141703474-582c661a-b979-4b95-b3e4-85c9ca2ea01b.png)

# XML

[XML](https://gist.github.com/Alternqtive/0298f4e971ccd3e28c60617fae2bf27a).

# Download Link
[Download](https://www.mediafire.com/file/xck57lfvuwe23oe/Focus.rar/file)

**Comment by CoWinkKeyDinkInc** [comment]
Should this replace the #302 that is already loaded?

**Comment by calcastor** [comment]
updated in a818b62193f399d84f4453d06e859911f4ec1413
