### ISSUE TITLE
[TDM/20v20] Bob-Omb Battlefield

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#307]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Bob-Omb Battlefield

## Gamemode & Map Description  
This map is a TDM using the same sub-gamemode concept already used by my other maps of Miner Sixty Niner/Die Noon and Death DeNile. Like with those maps instead of scoring upon kill players are given a score item(for this map nether stars) which is redeemed into points when scoring in the scorebox with them. The score items drop upon death allowing other players to "steal" the points for themselves instead. The entrances to jump pads to the scorebox open up for 30 seconds, then close for 30 seconds, until the match is over. Winning team is the one with the most points by the end of the match.

## Team Sizes
2 Teams 20v20

## Screenshots
[Screenshots](https://imgur.com/a/5fu4sdW)

# XML
[XML](https://gist.github.com/Cazadorian/07bd1b890aa1ad7b7a236e2590560a8d)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/141967115-7e3b6a6d-120a-47ff-9412-3fee95aaadeb.png)

# Download Link
[Bob-Omb Battlefield.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7545478/Bob-Omb.Battlefield.zip)

**Comment by Cazadorian** [comment]
Map updated with changes requested by Mame

-Edited way up to the scorebox cannons to be stairs, pushed the monument wall inwards to better fit this change.
-Adjusted jump pad velocity.

[Bob-Omb Battlefield v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8414248/Bob-Omb.Battlefield.v1.1.zip)

**Comment by Cazadorian** [comment]
Updated the map further with a bunch of minor tweaks.

-Added two Bob-Ombs to the map to please Crazy and Tommy.
-Changed some map aesthetics minorly.
-Edited spawners, tunnel jump pads, and a few other things minorly to improve gameplay.

[Bob-Omb Battlefield v1.1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8421806/Bob-Omb.Battlefield.v1.1.1.zip)

**Comment by Cazadorian** [comment]
Updated the map with some major changes

-Scorebox now opens and closes every 20 seconds instead of 30.
-After 7 minutes nether stars will award twice as many points when scored, to make it more likely teams that are behind can make comebacks and to make the last few minutes more interesting.
-Added spawn entry protection.

[Bob-Omb Battlefield v1.2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8523860/Bob-Omb.Battlefield.v1.2.zip)

**Comment by calcastor** [comment]
closing issue as it has been added to pools, will push missed update
