### ISSUE TITLE
The Grand Dueling Tournament II

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastCommunity/CommunityMaps#308]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

The map is found with a BY-SA license on [ResourcePile](https://mcresourcepile.github.io/maps/overcast?query=grand_tournament_ii&match=all&invert=false), so this is simply released under that same license. Not my map (duh), I just did the xml and got it to function with missing modules that would have been otherwise needed.

I've only been able to test the map with 2 players, not a full team test. The logic works for the small scale test, and I see no reason why it would fail with more players, I just can't ensure it'll work 100% without issues. If any are found, please comment it here and I can try to figure it out.

## Team Sizes
2v2 swiss styled map with 8 teams so 16 players, with support for 6 per team with scoring still working correctly, handy for when mods expand team sizes

# XML
[Now 1000 lines shorter](https://gist.github.com/CrazyisCreeps/19d51f6b3975fa24b221ef5be5e5fc34). I've redone the xml to function with dynamic portals, rather than structures. Took the time to clean up some useless lines as well

# Map Image
![map](https://user-images.githubusercontent.com/7937351/142162774-264d5c48-8074-492b-a1ed-3ba7239c9102.png)

# Download Link
[boop](https://www.dropbox.com/s/ean3jku2wfdcanw/grand_tournament_ii.zip?dl=0)

**Comment by calcastor** [comment]
going to load this in this repo for now, but I'll move it to the not-yet-completed-nor-work-started-for PublicMaps repo later on as I'd like to restrict this repo to original community maps while having previously made + publicly available maps in PublicMaps in the future.

**Comment by CrazyisCreeps** [comment]
Feel like this should be reopened so people are aware the map still has issues. At the moment there's issues with not all players scoring on match end, as well as not all players teleporting from spawn and back to spawn after round ends in spec areas.

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/467ce27b42fa7ef7e90847315a2ba648da1060ad
