### ISSUE TITLE
[CTW/8vs8vs8vs8] Emergency meeting

### ISSUE THREAD

**Issue by Trionaf** [OvercastCommunity/CommunityMaps#324]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X ] I have created an XML file
- [X ] I have created an map image
- [X ] I have uploaded the map zip file to a file sharing service
- [X ] The map has been tested locally to make sure it works

# Map Name
What is the map called?
Emergency meeting

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.
4 teams capture the wool
The spawn is behind the wool, you can enter the wools from the left or right side. If you break blocks they won't drop but there are some chests with defender materials. There are side islands and a middle. You can bridge to the enemy's side from the mid island or sides island.
## Team Sizes
How many teams and how large are they?
4 teams 8vs8vs8vs8

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible.
https://imgur.com/a/XNDwlLr
# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.
https://gist.github.com/Trionaf/67a86f966bdc2bd8478405eebca4a95d

# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` in `290x246` resolution and upload it by dragging it into this text box.

![emergency meeting screenshot 290 x 246](https://user-images.githubusercontent.com/96479475/146941693-a46bfaa7-668a-4a61-8126-2c8105c909cf.png)
it's the same one as in the screenshots

# Download Link
[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive** or **Dropbox**.

[fruitlogicFAN.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7755844/fruitlogicFAN.zip)

**Comment by Strangeys** [comment]
I would highly suggest changing up the mid islands a bit, they're very thin and easy to get knocked off and aren't unique as the map already looks a LOT like Battle Ecliptica II. You could probably make the mid islands asymmetric similar to how Thunder does it. Just anything to make the map look like it has something other than the giant wool room, spawn and emergency button in mid. The rest of the map is very plain and could use some things to spice it up. It also doesn't need to be that tall.

**Comment by CoWinkKeyDinkInc** [comment]
You didn't prune the map
