### ISSUE TITLE
[CTW/12v12] Huanxiang

### ISSUE THREAD

**Issue by DerStiv** [OvercastCommunity/CommunityMaps#325]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
What is the map called?
Huanxiang

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.
I choosed to build a CTW 12v12 Map. I tryed to build an asian style looking map which is fast to play but also friendly for defenders.

## Team Sizes
How many teams and how large are they?
2 Teams a 12v12

## Screenshots
https://imgur.com/a/SjPsg60

# XML
https://gist.github.com/DerStiv/f04a4fa4689c5ab92336f3935f04c3c2

# Map Image
![Overcast_HuanxiangV2](https://user-images.githubusercontent.com/96599295/147299445-b4e11c8f-c69b-45e9-95a0-4eab55213b0e.png)

# Download Link
[[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive** or **Dropbox**.](https://drive.google.com/file/d/1P7T3ZtP3sViY7M9kenQMapZQX80X4JG_/view?usp=sharing)

**Comment by CoWinkKeyDinkInc** [comment]
Added in c75ec33ca3c85b1b64bdeb1e705885e76d29c869.
