### ISSUE TITLE
[CTW/24v24] Kanto

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#331]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Kanto

## Gamemode & Map Description  
SUPER awesome CTW

## Team Sizes
24v24

## Screenshots
https://imgur.com/a/Lsry9eM

# XML
https://gist.github.com/0uzi/aa7fa1dcb169cfdefa26b953ba98ce28

# Map Image
![map](https://user-images.githubusercontent.com/96648252/147402332-49ee4767-41ea-4881-9d28-df027577d565.png)

# Download Link
https://www.mediafire.com/file/ryihr5i2u9uv48y/0uzi.zip/file

**Comment by Strangeys** [comment]
Is this map intended for the contest? Team sizes for the micro map making contest can range from 10v10-16v16. This could fit a 16v16 so let me know.

**Comment by 0uzi** [comment]
This wasn't intended for the contest but if you think it would be ok for the micro rot then ok lol
