### ISSUE TITLE
[DTC/M/16v16] Tulog 

### ISSUE THREAD

**Issue by lunaceeee** [OvercastCommunity/CommunityMaps#342]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [ x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [ x] I have created an XML file
- [x] I have created an map image
- [ x] I have uploaded the map zip file to a file sharing service
- [ x] The map has been tested locally to make sure it works

# Map Name
Tulog

## Gamemode & Map Description  
DTC/DTM Nice little simple map w/ 3 lanes, some pistons in some chests to make bridging easier, gapple spawner in middle. some quirky items in some chests too

## Team Sizes
16v16

## Screenshots
https://i.imgur.com/7xdutcl.png

# Map DL w/ XML
https://www.dropbox.com/s/0979vpe3j8sjzz3/Tulog.zip?dl=0

**Comment by CoWinkKeyDinkInc** [comment]
Looks pretty great, make sure to make a proper `map.png`, I gotten the XML formatted properly but so far well done! :)
