### ISSUE TITLE
[CTW/16v16] When Men Cried

### ISSUE THREAD

**Issue by lunaceeee** [OvercastCommunity/CommunityMaps#347]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [ x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [ x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x ] I have created an XML file
- [x ] I have created an map image
- [ x] I have uploaded the map zip file to a file sharing service
- [ x] The map has been tested locally to make sure it works

# Map Name
When Men Cried

## Gamemode & Map Description  
A tribute to Steve Irwin. Snake, crocodile, spider lanes. The atrocious stingray that took Steve away from us. Australian red sand, bushes, and above all, Steve.

## Team Sizes
16v16

## Screenshots
https://i.imgur.com/UJI1YwY.png

# Download Link
https://www.dropbox.com/s/1rtw1n8wng5flkt/When%20Men%20Cried.zip?dl=0

**Comment by CoWinkKeyDinkInc** [comment]
Blocks can be placed and broken inside of the wool room. The stained glass that covers the beacon in the wool room should also be prevented from breaking or having blocks placed on top of it so players can still see the beacon. Only one wool room has Power I bows so I'm not sure if this is intentional.

**Comment by CoWinkKeyDinkInc** [comment]
Also don't forget to make a proper `map.png` btw

**Comment by lunaceeee** [comment]
> Blocks can be placed and broken inside of the wool room. The stained glass that covers the beacon in the wool room should also be prevented from breaking or having blocks placed on top of it so players can still see the beacon. Only one wool room has Power I bows so I'm not sure if this is intentional.

yes ppl can place and break blocks in wool room thats what every1 wants. can just make the beacon area unbreakable w xml. and yes both wool rooms are uniqyue so 1 side has the bows the other doesnt
