### ISSUE TITLE
[CTW/16v16] Blossom

### ISSUE THREAD

**Issue by Dowly06** [OvercastCommunity/CommunityMaps#351]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Blossom

## Gamemode & Map Description  
CTW. It is a standard CTW map with a couple paths to one defendable wool room. 

## Team Sizes
Two teams, 16v16 max

## Screenshots
https://imgur.com/a/xBG5oms

# XML
https://gist.github.com/Dowly06/2f92506c14884be9ac97c9dbc042f2f1

# Map Image
![map png](https://user-images.githubusercontent.com/84115754/148592332-cafa4501-9db0-45dc-814a-d133702fa2de.png)

# Download Link
https://www.dropbox.com/s/6r4ig2m9e36dk0j/Blossom.zip?dl=0

**Comment by KingOfSquares** [comment]
Is the linked XML an old version? 
Line 101 in current file: `<!-- need golden apple updated with itemkeep, clear inventory on death and kill reward-->`
