### ISSUE TITLE
[CTF/FFB/16v16] Keeper 

### ISSUE THREAD

**Issue by TommyHillfigger** [OvercastCommunity/CommunityMaps#352]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [ x] I have created an XML file
- [ x] I have created an map image
- [ x] I have uploaded the map zip file to a file sharing service
- [ x] The map has been tested locally to make sure it works

# Map Name
Keeper FFB

## Gamemode & Map Description  
The gamemode of the map is Flag Football CTF. The flag spawns in the middle and the two teams need to capture (score) the flag in the goal which is on the enemies side. Most goals wins, with a time limit of 8 minutes. In the middle there are portals to switch sides and there are punch 1 bows in the spawn castle. You can leave the spawn castle but you can't get back in it.

## Team Sizes
2 teams, 16v16, can be made smaller if needed too.

## Screenshots
https://imgur.com/a/oNyP5Tf

# XML
https://gist.github.com/TommyHillfigger/dcc9c34fa387d0e3be844c0573fee4c2

# Map Image

![](https://i.imgur.com/KLbEs5H.png)

# Download Link
[Keeper FFB fixed colour coding.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7832387/Keeper.FFB.fixed.colour.coding.zip)

**Comment by KingOfSquares** [comment]
Small nitpick. As specified in https://pgm.dev/docs/reference/misc/formatting section color codes `§` should not be used in newer XML. This might break formatting (e.g on client linebreaks)

**Comment by TommyHillfigger** [comment]
> Small nitpick. As specified in https://pgm.dev/docs/reference/misc/formatting section color codes `§` should not be used in newer XML. This might break formatting (e.g on client linebreaks)

Okay thanks for the heads up. I have fixed it now.
