### ISSUE TITLE
[CTW/16v16] Edo

### ISSUE THREAD

**Issue by Blazy-36** [OvercastCommunity/CommunityMaps#354]
![2022-01-07_18 36 33](https://user-images.githubusercontent.com/56277290/148624603-99056027-e961-46b3-b21f-dbf0eddcfaa2.png)

### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X ] I have created an XML file
- [X ] I have created an map image
- [X ] I have uploaded the map zip file to a file sharing service
- [X ] The map has been tested locally to make sure it works

## Gamemode & Map Description  
CTW: two wool ctw with a large connected mid island and two smaller islands. I imagine it'll play somewhat like a ctw map

# XML
https://gist.github.com/Blazy-36/82619f63eada656a3838c677746a5711

# Map Image
![map](https://user-images.githubusercontent.com/56277290/148624583-39fb915e-0d49-4ef6-a1a5-7ebe0df4c1f0.png)

# Download Link
https://drive.google.com/drive/folders/1F5BYd4v1g1CLuolfY_ochiJ9Ve2_NS14?usp=sharing

**Comment by calcastor** [comment]
> CTW: two wool ctw with a large connected mid island and two smaller islands. I imagine it'll play somewhat like a ctw map

unprecedented.
