### ISSUE TITLE
[DTM/16v16] Dominion

### ISSUE THREAD

**Issue by lunaceeee** [OvercastCommunity/CommunityMaps#356]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x ] I have created an XML file
- [x ] I have created an map image
- [x ] I have uploaded the map zip file to a file sharing service
- [ x] The map has been tested locally to make sure it works

# Map Name
Dominion

## Gamemode & Map Description  
DTM, literally a logo of the civ 6 civ England, yes. Medieval style map. There are water lanes for the crescent void gaps to account for times if the map lasts too long, its at 10minutes. Emerald monuments, very few amount since it's decently close to spawn and far from the enemy side. 

JUST CHANGE THE WATER LANES TIMING CUZ I WAS TESTING IN LOCAL HAve FUn AHAH

## Team Sizes
16v16

## Screenshots
https://i.imgur.com/Fvx2e8w.png

# Download Link
https://www.dropbox.com/s/cv3aglxuzvqimnk/Dominion.zip?dl=0

**Comment by Blazy-36** [comment]
Submitted with the same time remaining as all of my college essays
