### ISSUE TITLE
[Blitz DTM/8v8v8v8] Gold in Them Thar Kills

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#358]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Gold In Them Thar Kills

## Gamemode & Map Description  
The map is a 4 team DTM, which as far as I'm aware is the only four team DTM currently for PGM. The maps gameplay is quite similar to bedwars style maps, but built very much like a PGM DTM. When a team's monument is broken respawns are disabled for them via a Blitz filter, and the winning team is the last team standing. As the map uses the Blitz filter I do not think this map will be playable in standard rots, but I see it being mainly for people to sponsor/SN.

## Team Sizes
4 Teams 8v8v8v8

## Screenshots
[Screenshots](https://imgur.com/a/fNC2T8h)

# XML
[XML](https://gist.github.com/Cazadorian/b94aa3e296e3437299ed581e7f6aa535)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/149640212-36d65a22-3e39-4821-a9d3-813da9c08a33.png)

# Download Link
[Gold In Them Thar Kills.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7876038/Gold.In.Them.Thar.Kills.zip)

**Comment by technodono** [comment]
I know that 101 rooms had a tdm version and a rage version so that’s not the first 4 team tdm

**Comment by Cazadorian** [comment]
> I know that 101 rooms had a tdm version and a rage version so that’s not the first 4 team tdm

![image](https://user-images.githubusercontent.com/73002842/149641081-067049cd-a9c8-4472-9a9e-cfb291b8f35a.png)

**Comment by technodono** [comment]
> > I know that 101 rooms had a tdm version and a rage version so that’s not the first 4 team tdm
> 
> ![image](https://user-images.githubusercontent.com/73002842/149641081-067049cd-a9c8-4472-9a9e-cfb291b8f35a.png)

Oh interesting, my bad

**Comment by CoWinkKeyDinkInc** [comment]
Added in 60b188f.

**Comment by Cazadorian** [comment]
This is what should be the final map update to just fix up a few last issues, any further gameplay changes will instead be saved for a future map with the same concept. The map's been played a bunch already from setnexts and sponsors, and the map in its current state plays very well from feedback given on it. Since blitz makes this incompatible with rots in its current form this issue can likely just be closed once this update is loaded as it doesn't need anything further for setnexts/sponsors. 

Changes in this version
-Adjusted all the region Y levels for the spawners so they work properly with the new side island heights
-Added a small layer of bedrock to the edges of the water lanes so you can actually pillar up out of them if you boat as the water itself is considered void and I'm too lazy to attempt to make 24 new diagonal regions to fix this via XML.
-Added night vision to the observer kit as well as not everyone knows of the observer tool setting for night vision.

[Gold in Them Thar Kills v1.2.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8369168/Gold.in.Them.Thar.Kills.v1.2.1.zip)

**Comment by Cazadorian** [comment]
> Since blitz makes this incompatible with rots in its current form this issue can likely just be closed once this update is loaded as it doesn't need anything further for setnexts/sponsors.

^
