### ISSUE TITLE
[CTW/24v24] Oasis CTW

### ISSUE THREAD

**Issue by DerStiv** [OvercastCommunity/CommunityMaps#362]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Oasis CTW

## Gamemode & Map Description  
Capture the Wool | two teams try to steal a wool from each other. Every team has two spawns.

## Team Sizes
24vs24

## Screenshots
https://imgur.com/a/3l4Hoj0

# XML
https://gist.github.com/DerStiv/cb91f597590fd5aace71d923b47e24b8

# Map Image
![map](https://user-images.githubusercontent.com/96599295/150859616-1d527c97-5286-4382-b709-a8b757ed288e.png)

# Download Link
https://drive.google.com/file/d/1d6g1VUGGoa6gaFibUZ4D_DPxqEFQieHt/view?usp=sharing

**Comment by Cazadorian** [comment]
Closing this issue as the map has been added to the map pool. Thank you for submitting it.
