### ISSUE TITLE
[Rage TDM+KoTH/8v8v8v8] Quadrosphere Rage

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#363]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Quadrosphere Rage

## Gamemode & Map Description  
Quadrosphere Rage is a modified version of my other Quadrosphere map following requests for a rage version. Like the previous map in the series Quadrosphere Rage is a Rage TDM+KoTH, with this one having four hills compared to Stratosphere's two. The map's core layout is still similar to Quadrosphere CTW, but large parts of it have been overhauled to better fit Rage.

## Team Sizes
4 teams 8v8v8v8

## Screenshots
[Screenshots](https://imgur.com/a/TiRWeUH)

# XML
[XML](https://gist.github.com/Cazadorian/000c6b345768645fc13ec29f5b4b2228)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/151015420-d631fd36-7f26-4f7c-9f3d-9fff815ac41e.png)

# Download Link
[Quadrosphere Rage.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7936071/Quadrosphere.Rage.zip)

**Comment by calcastor** [comment]
adding with march pool update
