### ISSUE TITLE
[Ctw/24V24] Sakura Garden

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#370]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Sakura Garden

## Gamemode & Map Description  
Capture the Wool | Sakura Garden, a place where you can relax looking at the flowers and trees with while your teammates try to steal the enemy's wool

## Team Sizes
24v24

## Screenshots
https://imgur.com/a/iOaXS2o

# XML

# Map Image
![2022-02-09_21 40 56](https://user-images.githubusercontent.com/99238656/153287940-b57a1c55-df00-4a4f-a0b7-782d6ea823e5.png)

# Download Link

**Comment by rockymine** [comment]
To clarify, the map is inside the builder's dropbox.

**Comment by RuedigerLP** [comment]
https://github.com/OvercastCommunity/CommunityMaps/commit/492a7d1731d35d21e29fe36fa38840545059e060

**Comment by calcastor** [comment]
Adding to pools in March pool update
