### ISSUE TITLE
[CTW+DTM/28v28] Mo'ai

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#378]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Mo'ai

## Gamemode & Map Description  
This map is a CTW+DTM with one emerald monument and two wools per team. Like Enderblast and other similar maps this map uses sequential objectives, requiring players to destroy the monument before they are able to access the wool room. This is achieved using the relatively new monument mode filtering feature, which allows the map to generate full lanes to the wool room once a team destroys the enemy's monument.

[Demonstration of the lane spawning](https://imgur.com/sAG9DkT)

## Team Sizes
28v28

## Screenshots
[Screenshots](https://imgur.com/a/wrARc1G)

# XML
[XML](https://gist.github.com/Cazadorian/fe2ebf040c8796449e1cfff75573fffc)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/155562164-96be3a70-95c2-417f-839c-89a49128b2bc.png)

# Download Link
[Mo'ai.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8133988/Mo.ai.zip)

**Comment by Cazadorian** [comment]
Small map update

-Added a beacon marker above both monuments to make their location clearer
-Reduced blocks from kill reward

[Mo'ai v1.0.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8141098/Mo.ai.v1.0.1.zip)

**Comment by calcastor** [comment]
adding in march pool update
