### ISSUE TITLE
[DTM/20v20] Blast Mining

### ISSUE THREAD

**Issue by EpicPuppy613** [OvercastCommunity/CommunityMaps#379]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Blast Mining

## Gamemode & Map Description  
Blast your way through the map to destroy the enemy monument. Teams should be using TNT to create a tunnel through the map to get to the enemy monument.

## Team Sizes
2 teams, 20 players each, 40 players total

## Screenshots
[screenshots](https://imgur.com/a/xJBjU0l)

# XML
[xml](https://gist.github.com/EpicPuppy613/e517ee1f26c33d2ae310d1d115ec484c)

# Map Image
![map](https://user-images.githubusercontent.com/61771471/155900434-10edc573-ac86-4ce3-9184-7a5930b736b9.png)

# Download Link
[map package](https://github.com/EpicPuppy613/maps/blob/main/Blast%20Mining.zip)

**Comment by technodono** [comment]
Overflow is no longer a necessary team size component your xml component you need since pgm will automatically handle that. I'd suggest removing it and also I'd recommend trying it on a lower size first, you can always adjust it up if 10v10 is too small :)

**Comment by EpicPuppy613** [comment]
## V1.0.1
- Removed overflow
- Lowered team size

**Comment by EpicPuppy613** [comment]
## V1.1.0
- Spawn is now further back from the center
- Added iron mines
- Lowered player count
All of the original links to files have already been updated

[map download](https://github.com/EpicPuppy613/maps/blob/main/Blast%20Mining.zip)

**Comment by EpicPuppy613** [comment]
## V1.1.1
- Monuments are now a bit smaller
- The last few blocks of a monument are now easier to destroy
- Gold blocks have been added to the itemremove

All original links have been updated

[Blast Mining.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8193847/Blast.Mining.zip)

**Comment by EpicPuppy613** [comment]
## V1.1.2
- Yes I skipped a version I know (but I'm too lazy to fix it)
- Added some tunnels to the map to show that you're meant to blow it up

All of the original links have been updated

[Blast Mining.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8201801/Blast.Mining.zip)

**Comment by EpicPuppy613** [comment]
## V1.1.3
- Added some secret diamonds to the mines
- Increased player count from 20 -> 24 (10 -> 12 per team)

All original links have already been updated

[Blast Mining.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8228095/Blast.Mining.zip)

_totally not updating this map as an excuse to get it noticed_

**Comment by CoWinkKeyDinkInc** [comment]
Added in d23f6bc.

**Comment by EpicPuppy613** [comment]
after a *few* funky friday tests... (and a couple of months)

## V1.2.0
- Removed the mines entirely
- Disabled friendly mines damage
- Raised the bedrock floor of the map

All original links have already been updated

[Blast Mining.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8228095/Blast.Mining.zip)

**Comment by RuedigerLP** [comment]
updated in https://github.com/OvercastCommunity/CommunityMaps/commit/270d9c2becc5faec6f995301833e8fe18b6d2059

**Comment by EpicPuppy613** [comment]
# V1.2.2
- Included formatting changes made in 973054b
- More changes related to removing the iron mines:
  - TNT yield is now 0
  - Removed all regions and filters relating to the iron mines
- Cleaned up the XML some more

(this is purely a XML update)

[map.xml](https://gist.github.com/EpicPuppy613/e517ee1f26c33d2ae310d1d115ec484c)

**Comment by EpicPuppy613** [comment]
# V1.2.3

- Fixed removing the iron mines for both teams

- Changed some information signs
All original links have already been updated

[Blast Mining.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8228095/Blast.Mining.zip)

**Comment by Cazadorian** [comment]
This map likely won't be ever added to the main server pool due to how different it is compared to most of the other maps in the standard pool. I have however added the map to the newly created Funky Friday event pool, as it seems much more suited for the regular staff map events we have and I've received multiple requests to add this map into said pool. As it is now in a map pool and will likely be played regularly, I'm closing this issue as complete for now. Thank you for the submision.
