### ISSUE TITLE
[Koth/16v16v16v16] Supheriox

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#381]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Supheriox

## Gamemode & Map Description  
King Of The Hill (KOTH) Inspired by Equinox, this new royal place with bridges, trees, jumpads and teleports, will bring you a lot of fun

## Team Sizes
4 Teams (16v16v16v16)

## Screenshots
https://imgur.com/a/345hLRL

# XML
[map.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8191520/map.zip)

# Map Image
![WhatsApp Image 2022-03-05 at 1 53 58 PM](https://user-images.githubusercontent.com/99238656/156900628-75e9678e-9d1e-46b5-895a-63255af49be1.jpeg)

# Download Link
https://www.mediafire.com/file/ua9luse773p7a5t/Supheriox.zip/file

**Comment by RuedigerLP** [comment]
https://github.com/OvercastCommunity/CommunityMaps/commit/03df83fa342838b47f88b9e5b845643033d81552

**Comment by calcastor** [comment]
closing issue as it has been added to pools
