### ISSUE TITLE
[CTW/24v24] Belvedere

### ISSUE THREAD

**Issue by Xaeros** [OvercastCommunity/CommunityMaps#382]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Belvedere

## Gamemode & Map Description  
Capture the Wool. The map has lots of Gazebo's and good landscape. Players will have cover and the match shouldn't last too long considering the bridging lanes aren't too big.

## Team Sizes
24v24

## Screenshots
https://imgur.com/a/dUHra3U

# XML
In comment below.

# Map Image
![map image](https://user-images.githubusercontent.com/29107127/156940799-fe08c29c-73c1-465d-b422-f1f2522cdb54.png)

# Download Link
In comment below.

**Comment by RuedigerLP** [comment]
https://github.com/OvercastCommunity/CommunityMaps/commit/35d167ee6fde2572ba2174e1f1beea9237b17e6e

**Comment by calcastor** [comment]
closing issue as it has been added to pools
