### ISSUE TITLE
Hide n Seek Cinema Jungle Scenario

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#383]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Hide n Seek Cinema Jungle Scenario

## Gamemode & Map Description  
Gamemode : hide and seek
A jungle inspired by rambo movies, we built a jungle with tunnels, traps, platforms and many places to hide and run, I hope the hiders team will move around the map by activating traps to survive against seekers. 

## Team Sizes
2 teams and hiders : 50 max seekers: 5

## Screenshots
Imgur album : https://imgur.com/gallery/OzUo2P1

# XML
Git link : https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/fc3da84f26a85bc58d66d40cb730286773f368cb/Hide%20n%20Seek%20Cinema%20Jungle%20Scenario.txt

# Map Image
![mapImage](https://user-images.githubusercontent.com/82010545/157316777-59ff472f-dfe7-46f6-b473-fc845880418e.png)

 map.png in 290x246 

# Download Link
 Dropbox : https://www.dropbox.com/s/bv669ra0m5nppxs/Hide%20n%20Seek%20Cinema%20Jungle%20Scenario.zip?dl=0

**Comment by JosueSaenzLacayo-UCR** [comment]
I forgot to put the xml file in the zip file in DropBox now it is update https://www.dropbox.com/s/bv669ra0m5nppxs/Hide%20n%20Seek%20Cinema%20Jungle%20Scenario.zip?dl=0

**Comment by calcastor** [comment]
loaded in 90e5a83cdf2399ccf985d87c7ba89dc5bd795224

**Comment by Cazadorian** [comment]
This map has played quite a few times already and in its current state seems finished. Like with the other Hide n Seek maps this map will likely stay restricted to staff events due to using blitz, and as there seems to be no current issues with it I'm marking it as completed.

**Comment by JosueSaenzLacayo-UCR** [comment]
Ok. my mistake, I was a bit busy, now I have time to fix it, I will place some invisible blocks and reduce the time to 6 minutes. Also, I'll be working on an infection version because a friend mentioned that the map will work better in that game mode.
