### ISSUE TITLE
[CTW/8v8] Ringpull

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#384]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Ringpull

## Gamemode & Map Description  
This map is a pretty standard CTW that's intended to help fill the current demand for new Nano maps. No special gimmicks, just a regular 8v8 CTW map.

## Team Sizes
Two teams, 8v8.

## Screenshots
[Screenshots](https://imgur.com/a/eufN3JW)

# XML
[XML](https://gist.github.com/Cazadorian/b096c11e49fd9be243360cf0cfb8ae23)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/157352974-6120ace5-cfca-46f4-94c8-109d7666494e.png)

# Download Link
[Ringpull.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8210812/Ringpull.zip)

**Comment by Cazadorian** [comment]
Map updated

-Made bedrock wall larger because circle jumping was too easy before.
-Modified a lot of the map's aesthetics.

[Ringpull v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8369155/Ringpull.v1.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 93cceb9.

**Comment by Cazadorian** [comment]
Closing as the map's done and I likely won't add it to the pool as I think Deciduous Nights is just an improved version of this map's layout. May cycle them out with each other at some point for variety but not for a while.
