### ISSUE TITLE
[TDM/Scorebox/8v8] Aurosphere

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#385]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Aurosphere

## Gamemode & Map Description  
The map's an 8v8 Scorebox/Death Deposit style TDM very similar to my other similar TDMs such as Miner Sixty Niner or Bob-Omb Battlefield. Gold nuggets are awarded upon kill, and depositing them into a scorebox that periodically opens and closes is the only way to score. The main difference with this map is that there are two gold nugget spawners located on each side of middle, which should help make the map fit a smaller size than normal for this gamemode.

## Team Sizes
Two teams 8v8

## Screenshots
[Screenshots](https://imgur.com/a/dIbjlUs)

# XML
[XML](https://gist.github.com/Cazadorian/4daef1f14e902f6081bc1279fb241dd9)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/157537457-e99f19d6-e2ef-42ee-ac8d-cd6087a63a0c.png)

# Download Link
[Aurosphere.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8219963/Aurosphere.zip)

**Comment by Cazadorian** [comment]
Map update
- Replaced the side islands with curving bridges as inherent jump pad inconsistency made them not work too well
- Adjusted the rest of the map to fit this change
- Reduced the scorebox open/close time to 15 seconds instead of 30
- Updated map.png cause of major layout changes

[Aurosphere v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8731730/Aurosphere.v1.1.zip)

**Comment by calcastor** [comment]
Added to pools in https://github.com/OvercastCommunity/MapPools/commit/9487cd11744343642885811e0ac117854a570091
