### ISSUE TITLE
[CTW/14v14v14v14] Mahatma

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#386]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Mahatma

## Gamemode & Map Description  
This map is a large 4 team CTW, with the main unique part of this map being it's layout of long voidless lanes with large amounts of verticality which should provide a different experience from most 4 team maps, and provide significant space for team fights.

## Team Sizes
4 teams 14v14v14v14

## Screenshots
[Screenshots](https://imgur.com/a/Yof8UZm)

# XML
[XML](https://gist.github.com/Cazadorian/4e1d314d43339a7409155a7af17e0d60)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/157715901-9f31f098-df1c-4260-9022-6d4d1544bb43.png)

# Download Link
[Mahatma.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8225471/Mahatma.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in 8b41305.

**Comment by Cazadorian** [comment]
Map updated

-Prebuilt wall around the wool rooms made larger to slow down rushes.
-Added another row of cobwebs to the wool room entrance.

[Mahatma v1.0.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8240540/Mahatma.v1.0.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 714f020.

**Comment by calcastor** [comment]
closing issue as it has been added to pools
