### ISSUE TITLE
[Update] Mushroom Monuments v1.1

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#387]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
-Broken bridge added between spawn to encourage players to actually try to bridge to their monument and defend it.
-Buffed the axe from efficiency 1 to efficiency 2 as destroying skybridges is currently too difficult.
-Doubled the arrows received in the kill reward due to complaints of too few arrows.

# XML
[XML](https://gist.github.com/Cazadorian/fabcc1c4f753b71a7aece2d489583fc9)

# Download Link
[Mushroom Monuments v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8226769/Mushroom.Monuments.v1.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
#348 updated in 23383d2.
