### ISSUE TITLE
[Update] Quadrosphere Rage v1.1

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#388]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
-Point gain from hills halved to 0.25 a second, 0.5 points a second was too fast and made kills completely irrelevant to scoring. 
-Added Sharpness X to the bow due to Siceth requesting it

# XML
[XML](https://gist.github.com/Cazadorian/000c6b345768645fc13ec29f5b4b2228)

# Download Link
[Quadrosphere Rage v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8226820/Quadrosphere.Rage.v1.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
#363 Updated in 8e566f5.
