### ISSUE TITLE
[Update] Riot in Prison RAGE, Version 2

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#389]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Resize the size of the map, I made it smaller.
Add tunnels, decoration and improve design.
I changed the number of players to 40.
Also I pruned the map and change the XML.

# XML
[Git](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/7d4ae95ac7905c7e98b9c3f773f630ec2f2c9869/Riot%20in%20Prision%20RAGE.xml) 

# Download Link
[Map](https://www.dropbox.com/s/0krhj1kle7iwbjr/Riot%20in%20Prison%20RAGE.zip?dl=0)

**Comment by JosueSaenzLacayo-UCR** [comment]
Map images https://imgur.com/gallery/Mm9l32z

**Comment by CoWinkKeyDinkInc** [comment]
#332

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 23aea5e7c7d12a247ffe6b2f45bc4be107113d8f.
