### ISSUE TITLE
[Update] Gold in Them Thar Kills v1.1

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#390]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
-Fixed up a filter that was accidentally denying use actions on the entire map
-Added a packed ice monument mode after 15m to avoid matches lasting too long.

# XML
[XML](https://gist.github.com/Cazadorian/b94aa3e296e3437299ed581e7f6aa535)

# Download Link
[Gold in Them Thar Kills v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8236725/Gold.in.Them.Thar.Kills.v1.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
#358

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 60b188f.
