### ISSUE TITLE
[Infection/40vs6] Infection: Riot in Prison

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#391]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Infection: Riot in Prison

## Gamemode & Map Description  
Gamemode: Infection
Normal infection map but here police vs prisoners.

## Team Sizes
40- zombies = "prisoners" vs 6-humans= "prison police"

## Screenshots
Album [Imgur](https://imgur.com/gallery/kPt4KMP) 

# XML
XML [Git](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/370b78d55f7ac38ea9a49510e817a188fea290e2/Infection_Riot%20in%20Prison.xml) 

# Map Image
![map png](https://user-images.githubusercontent.com/82010545/158002996-e44f4e95-c21e-4e26-8ef6-940fdf33bde4.png)

# Download Link
[Package the map](https://www.dropbox.com/s/a3vmt48p7x6jgjd/Infection_Riot%20in%20Prison.zip?dl=0)

**Comment by Cazadorian** [comment]
This map seems complete at this stage and likely doesn't need any further updates. The map is already used for sponsoring and staff events, and I'll potentially consider adding it to an upcoming pool dedicated to staff events. Thank you for the submission.
