### ISSUE TITLE
[DTM/12v12] Iti Mo'ai

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#393]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Iti Mo'ai

## Gamemode & Map Description  
The map's a mini version of Mo'ai, with the wools having been removed and parts of the map adjusted to fit the smaller size.

## Team Sizes
Two teams 12v12

## Screenshots
[Screenshots](https://imgur.com/a/yiADpiI)

# XML
[XML](https://gist.github.com/Cazadorian/278bb4923122e9e6264c55da38d0e014)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/158493323-e908aa0b-45fd-454e-8e36-5d4c8802e306.png)

# Download Link
[Iti Mo'ai.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8258029/Iti.Mo.ai.zip)

**Comment by calcastor** [comment]
this got missed by accident but I've since loaded it and added to pools. seems to play alright but could maybe do with a team size increase in the future, but for now we'll leave it as it is.
