### ISSUE TITLE
[CTW/8v8] Honeycombed

### ISSUE THREAD

**Issue by killtrixy** [OvercastCommunity/CommunityMaps#394]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X ] I have created an XML file
- [X ] I have created an map image
- [X ] I have uploaded the map zip file to a file sharing service
- [X ] The map has been tested locally to make sure it works

# Map Name
Honeycombed

## Gamemode & Map Description  
Gamemode: CTW
Description: Capture the enemy teams wool to win.

## Team Sizes
8v8

## Screenshots
[https://imgur.com/a/8njVVBF](url)

# XML
https://github.com/OvercastCommunity/CommunityMaps/commit/b9e6d6a65c21fbba3b085deb3897ff9458661e1c

# Map Image
![1mapimage](https://user-images.githubusercontent.com/101747964/158710987-a678d508-cdbe-4b32-bcd4-f96fe3d24a7c.png)

# Download Link
https://github.com/OvercastCommunity/CommunityMaps/commit/b9e6d6a65c21fbba3b085deb3897ff9458661e1c

**Comment by RuedigerLP** [comment]
https://github.com/OvercastCommunity/CommunityMaps/commit/b9e6d6a65c21fbba3b085deb3897ff9458661e1c

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/b9e6d6a65c21fbba3b085deb3897ff9458661e1c

**Comment by Cazadorian** [comment]
Closing this issue as the map has been added to the map pool. Thank you for submitting it.
