### ISSUE TITLE
[CTW 5v5] Ingwaz

### ISSUE THREAD

**Issue by Tywnis** [OvercastCommunity/CommunityMaps#395]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created a map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Ingwaz 

## CTW 
Small teams vying for a foothold on either of the 2 side islands before to launch runs for the wools across the waters. 
Minimal defenses are already set up, to hopefully slow down the first rush. 

## Size 
5v5 and overfill at 6 

## Screenshots
https://imgur.com/a/yGqMLAH

# XML
https://gist.github.com/Tywnis/a94fcc2caddcc31df362a64ffc710400

# Map Image
![map](https://user-images.githubusercontent.com/4369123/159712084-1466ee6b-7378-48fa-aceb-b48554952770.png)

# Download Link
https://www.dropbox.com/t/24w2sc6MKBmr0vpP  
Expires 30th March, pls request for another if delayed. 

Thanks,
Tyw

**Comment by calcastor** [comment]
3a73a3dd699f8f6a9494df1b30b8682d09822ba0

**Comment by CoWinkKeyDinkInc** [comment]
A few chunks are missing.

**Comment by Tywnis** [comment]
[Ingwaz.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8360994/Ingwaz.zip)

New data/region files for the missing chunks

**Comment by CoWinkKeyDinkInc** [comment]
Chunks fixed in 1b635e6.

**Comment by calcastor** [comment]
closing issue as it has been added to pools
