### ISSUE TITLE
[Arcade/60] Water Drop: Directrix

### ISSUE THREAD

**Issue by mitchts** [OvercastCommunity/CommunityMaps#397]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Water Drop: Directrix

## Gamemode & Map Description  
Arcade, Water Drop, themed around Directrix (shudder)

This is a direct replacement to [version 1.0 of Water Drop: Directrix](https://mcresourcepile.github.io/stratus-maps/water_drop_directrix/#/26/64/-32/-2/world/world-smooth_lighting) from Stratus which was pretty bad. I don't believe this version is loaded on OCC, but if it is, it should be burned.

Jump pads work perfectly for me on localhost, but as with Water Drop: Ender Blast, I doubt that this will directly translate into a playable experience without some adjustments.

Thank

## Team Sizes
FFA, 60 players

## Screenshots
[Overview](https://mcresourcepile.github.io/pgm-maps/water_drop_directrix/#/-166/64/167/-2/world/world-smooth_lighting)

# XML
[XML](https://raw.githubusercontent.com/MCResourcePile/pgm-maps/master/maps/water_drop_directrix/map.xml)

# Map Image

![map](https://user-images.githubusercontent.com/6386297/160224053-e5fdab12-22db-405c-b147-df3721baa884.png)

# Download Link
[ResourcePile](https://mcresourcepile.github.io/maps/pgm?dl=water_drop_directrix)

**Comment by technodono** [comment]
now this is the map overcast desperately needed

**Comment by CoWinkKeyDinkInc** [comment]
Added in 8638da2.

**Comment by CoWinkKeyDinkInc** [comment]
Jump pads on the left side of the map probably have to be tweaked, also a deny water placement region on top of the jump pads would be good.

**Comment by mitchts** [comment]
[Updated download via ResourcePile](https://mcresourcepile.github.io/maps/pgm?dl=water_drop_directrix).

Will have to test the jump pads on the actual server as I said before making adjustments as I don't know which way they need to be tweaked. Having water not be on the direct jump pad will likely help any short falls previously experencied.

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 79bb2bf.

**Comment by Cazadorian** [comment]
The map in its current state has no issues, and is regularly played both from sponsors and staff events. If you have any further updates you wish to make for the map you're free to submit them, and for now I'll close the issue.
