### ISSUE TITLE
[DTM/7v7] Aquatica

### ISSUE THREAD

**Issue by Mewzzy** [OvercastCommunity/CommunityMaps#399]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Aquatica
## Gamemode & Map Description  
Aquatica is a 7v7 DTM map. The objective being each team going to the opposing side to break the enemies team's 12 emerald block Monument, inside the Clam.
## Team Sizes
7v7
## Screenshots
https://imgur.com/a/fYa8erZ
# XML
https://gist.github.com/Mewzzy/0d651823f57310b1fa919b83ddc041a8
# Map Image
![2022-04-05_12 26 41_290x246](https://user-images.githubusercontent.com/102499103/161808483-8980c4af-19e7-42dd-897f-cbde225fe737.png)
# Download Link
[Aquatica.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8420344/Aquatica.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Great work! I've fixed the date on your `<created>` tag for you, which uses the ISO YYYY-MM-DD date format. This looks like it will play great.
Added in d9756e4.

**Comment by Mewzzy** [comment]
> Great work! I've fixed the date on your `<created>` tag for you, which uses the ISO YYYY-MM-DD date format. This looks like it will play great. Added in [d9756e4](https://github.com/OvercastCommunity/CommunityMaps/commit/d9756e44838a79479a1b0c5c92f577c0f329f6b4).

Oh I didn't even see the date format, thank you so much for fixing it!

**Comment by CoWinkKeyDinkInc** [comment]
I just set the map, with a full 7v7 it was quickly rushed. I would suggest making the void gap longer the gold blocks with stone pickaxes are still fine if you want to keep them, but they might need to be harder to mine.

**Comment by Mewzzy** [comment]
> I just set the map, with a full 7v7 it was quickly rushed. I would suggest making the void gap longer the gold blocks with stone pickaxes are still fine if you want to keep them, but they might need to be harder to mine.

I will work on making those updates to the map

**Comment by Mewzzy** [comment]
Map has been updated

**Comment by calcastor** [comment]
closing issue as it has been added to pools
