### ISSUE TITLE
[KotH/16v16] Q*Boid

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastCommunity/CommunityMaps#4]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Q*Boid or simply Q_Boid if the asterisk doesn't work

## Gamemode
King of the Hill

## Team Sizes
16v16

## Screenshots
https://imgur.com/a/euzgUSL

# XML
https://gist.github.com/CoWinkKeyDinkInc/3c171850b5a85ffa3e698168fc6a4864

# Map Image
![map](https://user-images.githubusercontent.com/7586568/89595028-b4a4d880-d810-11ea-9e7b-d04f37780b0f.png)

# Download Link
[qboid.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5038647/qboid.zip)

**Comment by CoWinkKeyDinkInc** [comment]
This was a really old map that I recently cleaned about last year that I once submitted on OCN but it never got to being tested. I think back then PGM used to crash with the amount of hills that this map uses, but since Stratus PGM and 1.8 PGM all the hills work great and behave normally. 

Some ideas I have on tweaking this map might be extending the captured region to include the red and blue coloured sides, jump boost II and reducing the TNT kill reward to 2 kills for one/two TNT.

**Comment by CoWinkKeyDinkInc** [comment]
Oh yes, regions for the bottom cubes have to be figured out, currently you can build as far out as you can diagonally on the bottom cubes. I need a region added so you can build only an extra "square" outwards from the bottom cubes.

**Comment by fixitqixit** [comment]
> Oh yes, regions for the bottom cubes have to be figured out, currently you can build as far out as you can diagonally on the bottom cubes. I need a region added so you can build only an extra "square" outwards from the bottom cubes.

Do you need help with adding this, or is this a feature you look to implement soon?

**Comment by CoWinkKeyDinkInc** [comment]
@fixitqixit This is something that has to be added, I want something like this, where you can build within the yellow area. This could probably be best done with a `</void>` tag I guess.

![2020-08-07_12 00 45](https://user-images.githubusercontent.com/7586568/89674577-a2c14500-d8a5-11ea-82a6-38d3aef062f1.png)

**Comment by fixitqixit** [comment]
> @fixitqixit This is something that has to be added, I want something like this, where you can build within the yellow area. This could probably be best done with a `</void>` tag I guess.
> 
> ![2020-08-07_12 00 45](https://user-images.githubusercontent.com/7586568/89674577-a2c14500-d8a5-11ea-82a6-38d3aef062f1.png)

Yeah, that sounds like an easy fix. Let us know when its updated or if you need any help at all.

**Comment by CoWinkKeyDinkInc** [comment]
I noticed the tags were moved for this submission, does that mean the map is accepted?

**Comment by fixitqixit** [comment]
I think it is meant to be more of a recognition of your submission on the map development side. Your map, like others that have been given this new tag, are still being finalised on the mapmakers side. Hopefully this part of the submission process will see the feedback from mapdevs as well as members of the community. Once the XML is finished with the void filters for this map I will, or someone else will, play around with the map on our mapdev server and potentially provide feedback like I've done [here](https://github.com/OvercastCommunity/CommunityMaps/issues/5#issuecomment-671014334).

**Comment by CoWinkKeyDinkInc** [comment]
@fixitqixit I've added the regions for the whole playable area/heightlimit in the updated gist. I just need help on denying block placements on the inverse of these regions, and a basic filter that only lets a team build in their respective 2 block spawn gap.

**Comment by CoWinkKeyDinkInc** [comment]
I have added the inverse regions and the filters, so the map is now playable! :tada:

**Comment by fixitqixit** [comment]
> I have added the inverse regions and the filters, so the map is now playable! 🎉

@CoWinkKeyDinkInc Is the map link in the main forum post updated with these changes? I will load the map this weekend if so.

**Comment by CoWinkKeyDinkInc** [comment]
@fixitqixit the map files are already complete so nothing had to be changed there, you might have to prune two chunks which I could do tomorrow.

**Comment by fixitqixit** [comment]
![Screen Shot 2020-08-29 at 3 54 34 pm (2)](https://user-images.githubusercontent.com/64303629/91629876-17545300-ea10-11ea-8ed7-16a1ebc23c96.png)

There appears to have been a pruning issue. Would you please update the map? Then we can get to testing 😎

**Comment by fixitqixit** [comment]
Just played this with a bunch of players, heres my feedback:

- Sounds and fireworks need to be disabled for hills. When several are being captured simultaneously it is sheer mayhem. If the message in chat can also be disabled that would be good. (Im unsure if any of these can be done but hopefully they can)
- A time limit for the map, instead of a set amount of points to be scored could be better. Maybe around 10-15 minutes? 
- I feel like theres more potential for this map to be even bigger? Its great as it is, but perhaps bigger cubes as well as more cubes could allow for bigger team sizes which would allow this map to be played in other pools - Maybe this will be a future version of the map, or potentially a later map in this series (if this map design will be a series) - something I could potentially help with making. 
- Once some of these things are updated I will be able to give more feedback.

**Comment by CoWinkKeyDinkInc** [comment]
Here is the updated map file with the pruned chunks.
[qboid_updated.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5145882/qboid_updated.zip)

There is a way to disable the fireworks and soundeffects with the `show` attribute which I can still do, but the downside is that it would not show up on the scoreboard at all. Considering this I think I will also expand the `captured` region to include the red and blue sides. Back on OCN this also meant that these objectives were never tracked on the website, so I did not realize that this feature was ported over.

I will agree about the timelimit, it makes more sense and I can't remember if that was possible back when I made it before. I can make a second map that is bigger and has more cubes, we can do that together if you want!

**Comment by CoWinkKeyDinkInc** [comment]
The map is now added with expanded captured region, `show="false"`, timelimit and I fixed some dumb mistakes with the itemremove.

**Comment by fixitqixit** [comment]
Awesome thanks @CoWinkKeyDinkInc . Will load it up shortly and I’ll give it another test

**Comment by fixitqixit** [comment]
Also for future updates, feel free to use the pull request feature of github. That way it streamlines the process and makes everything happen more quickly.

**Comment by fixitqixit** [comment]
Okay heres some feedback after just playing:

- Players desperately need to have spawn protection/resistance. In the game we just played the enemy team was able to take control over pretty much the whole map and just went about spawn killing for the rest of the match.
- Decrease the amount of points you get from hills, getting 6000 points on the scoreboard is a bit strange
- The back of the map needs to be filled in completely with solid blocks, players were going behind hit.
- There are certain benefits to the layout of the map. However there appears to be a lot of choke points and once certain parts of the map are captured, they seem to never be captured again. 
- I personally think jump boost should be removed. It makes it difficult to pvp with. 

While the layout of this map is what sets it apart and makes certain parts of it enjoyable, I worry gameplay gets stale quite quickly and theres not much variability to how the map can be played. I still believe there is a lot of potential here, it just may need more testing. Feel free to test it yourself when you're online (within reason, we don't want to overload players with map testing as it sometimes bores them), it may help with developing this map further.

**Comment by CoWinkKeyDinkInc** [comment]
Yeah I have worried a lot about the spawn protection being a huge weakness, I'll try and figure out something that will stop players from cornering everything. How does glass panes as fences in the spawn sound? I will fill in the map since it looks kind of dumb. I'm not sure if it's clear but you can build outward and make towers and ladders outside of the cubes so you can climb up without them. Perhaps there should be more building materials to start out with and kill rewards. What do you think of the TNT? I'll make PRs next time

**Comment by fixitqixit** [comment]
In regards to the ability to build outward, I was not aware and neither were any other players AFAIK. However, there appears to be little need to do so anyway. You could make players more aware of this by changing the structure of the map, though I am unsure how you would do this currently (need to think about it), or potentially even change the location of the spawns so it makes the map seem less linear. I think you need both glass fences and potion effects to prevent players from taking damage. Tnt seems like a cool addition but I would just double check how much the TNT does, when I briefly looked at the XML the value you had seemed too high but I'm not sure if this was actually a problem or not..

One idea that just came to me was having two pyramid like structures facing eachother across a void space. Essentially your own team would be unable to capture hills on their own side, but the opposing team would be able to. Once hills are captured they cant be taken back - so in a way like DTM... once captured you cant (at least in most maps) repair the objective. So basically a team would win by capturing most, if not all the hills on the other teams side. Anyway thats just an idea that came to me quite spontaneously, not sure if it has any merit (though, in other words, another way to hint at the potential of similar game mechanics).

**Comment by fixitqixit** [comment]
I'm not sure if you've ever seen Cubist's map Checkmate but it has a very similar design to your map, excluding the fact that his map has two sides and yours has only one. I just saw this map today and I feel like it coincidentally reflects the suggestions I made in my above comment. Just thought I'd put it out there that having two sides could improve gameplay on this map significantly.

**Comment by CoWinkKeyDinkInc** [comment]
I've addressed some complaints with #52 after seeing the map preform. It worked out a lot better than I thought.

**Comment by technodono** [comment]
Here are some ideas and suggestions I got while playing the map which might help you:

- especially on the higher checkpoints above spawns... it's really hard to attack it cause people keep making block defences that can't be destroyed... It should be easier to either: destroy their defences or have an easier way to get up onto the upper platforms cause having those is the real difference between winning & losing 
- Hills need less points awarded as we still have matches go up-to 6000pts which is odd... be a cool idea where higher hills award more points... explore this
- Gapples really need to be a killreward and put in itemremove... sometimes you pick up 40gaps in one which is too much
- Maybe a possiblity is to have spawns moved up a pit to make the map feel less linear... my idea would be to spread them out like have a top, mid & bottom spawn and then do what cos(TNT) does and allow players to choose where they spawn... you have a lot of space under the back of the map to maybe put it there
- fun map... would play again needs fixing

**Comment by CoWinkKeyDinkInc** [comment]
The golden apples were added to the kill reward sometime ago (don't remember) and I have made another update in fcc2fd232d335955c17e309a13262a72f45839f3. I have made it match more with Grand Q*Boid, with points and TNT kill rewards.

**Comment by technodono** [comment]
> The golden apples were added to the kill reward sometime ago (don't remember) and I have made another update in [fcc2fd2](https://github.com/OvercastCommunity/CommunityMaps/commit/fcc2fd232d335955c17e309a13262a72f45839f3). I have made it match more with Grand Q*Boid, with points and TNT kill rewards.

nice... another change you might wanna consider is to make all the block insta-mineable
so it's not so easy to defend especially when climbing the vines up to the upper floors.
