### ISSUE TITLE
TDM/KOTH/Score - 12v12 - Ziggurat

### ISSUE THREAD

**Issue by Tywnis** [OvercastCommunity/CommunityMaps#400]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Ziggurat

## 12v12 
OvF 15v15

![image](https://user-images.githubusercontent.com/4369123/160074123-0ae4e2ad-6c37-4826-9d22-e1c14a931a81.png)

# XML
https://gist.github.com/Tywnis/202be66633d27b941e8ccc2f5e5b8422

# Map PNG
![map](https://user-images.githubusercontent.com/4369123/160074515-c3ad959e-f3e8-4d28-a7ff-4922c8c62daa.png)

# Download Link

[Ziggurat.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8360524/Ziggurat.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in d831445.

**Comment by Tywnis** [comment]
XML update 1.2.0 
https://gist.github.com/Tywnis/f67a42cf68ba07ef2b9aa20af14a492d

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 3727095.

# Ziggurat 1.2.0

- Increased score from 600 to 750
- 24 to 20 arrows 
- emeralds give out 2 points instead of 1
- fixed portals
- Tips explaining where scorebox is

**Comment by Strangeys** [comment]
Closing since you're a MapDev now and can add these if you'd like.
