### ISSUE TITLE
[CTW/28v28] Xunkohtli

### ISSUE THREAD

**Issue by each1234** [OvercastCommunity/CommunityMaps#401]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Xunkohtli
A 2 team 28v28 (max overfill 30) CTW by 3Each and Tywnis.

## Screenshots

![2022-03-30_16 12 07](https://user-images.githubusercontent.com/81478272/160926257-24c79116-cec2-4cd8-b5f9-7174dc511fcb.png)
![2022-03-30_16 12 45](https://user-images.githubusercontent.com/81478272/160926285-c7ab5d4e-7552-4fcd-ac58-1eae09050463.png)
![2022-03-30_16 12 52](https://user-images.githubusercontent.com/81478272/160926299-3f6aa360-2106-426c-8306-c3fedf4a4183.png)
![2022-03-30_16 13 33](https://user-images.githubusercontent.com/81478272/160926327-6d4d1dc4-3d65-48cf-8226-b988323b2a9d.png)
![2022-03-30_16 13 00](https://user-images.githubusercontent.com/81478272/160926311-766d86d2-bead-4e32-acf3-6771c4300b3a.png)

# Download Link
https://github.com/OvercastCommunity/CommunityMaps/tree/master/ctw/standard/xunkohtli

**Comment by calcastor** [comment]
closing issue as it has been added to pools
