### ISSUE TITLE
Rage TDM+Score - Wrath Tor - 10v10

### ISSUE THREAD

**Issue by Tywnis** [OvercastCommunity/CommunityMaps#402]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works (basically same map as what used to be in PA/OCN)

# XML
https://gist.github.com/Tywnis/ee4bf235c4cab2dee78b093c573409aa

# Map Image
![map](https://user-images.githubusercontent.com/4369123/161008202-918f30b9-0645-4287-ae8d-6dcec4de8c99.png)

# Download Link
[WrathTor Rage.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8387324/WrathTor.Rage.zip)

**Comment by CoWinkKeyDinkInc** [comment]
The `<tutorial>` tags have been deprecated and will not work, so have commented out the tutorial and removed `<include>`. Added in 7247cc7.

**Comment by Tywnis** [comment]
https://gist.github.com/Tywnis/737c9322559b57cf2310831dea21b00e

added spawners & some details

**Comment by Tywnis** [comment]
xml update - https://gist.github.com/Tywnis/737c9322559b57cf2310831dea21b00e

3 second resistance on spawn
added spawners
details

**Comment by Strangeys** [comment]
Closing since you're a MapDev now and can add these if you'd like.
