### ISSUE TITLE
Deepest Dungeon; 60+ Blitz 7 lives FFA

### ISSUE THREAD

**Issue by Tywnis** [OvercastCommunity/CommunityMaps#403]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [?] The map has been tested locally to make sure it works

# Deepest Dungeon
## FFA
A sprawling underground and brigde labyrinth with 4 flags and one central hill, and shrinking world borders, and Blitz of 7 lives because why not. 

## 60 players

# XML
https://gist.github.com/Tywnis/b7b929281d4e512308d08236b25014c8

# Map Image
![map](https://user-images.githubusercontent.com/4369123/161213754-f6e1b2e2-6083-445a-8c9f-c77db5de1449.png)

# Download Link
[Deepest Dungeons.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8395461/Deepest.Dungeons.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in d6551fc. `map.png` has been resized but not cropped, so I didn't add the image for now.

**Comment by Tywnis** [comment]
![map](https://user-images.githubusercontent.com/4369123/161215240-97f0f6ee-a86f-4450-a998-f569d28a53b8.png)

**Comment by CoWinkKeyDinkInc** [comment]
Seems spawns might need fixing, and the shrinking border has to be readjusted, too far inwards.

**Comment by Tywnis** [comment]
[Deepest Dungeons.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8396585/Deepest.Dungeons.zip)

Fixed a hiding place, fixed XML for world border movement and hopefully spawn too

**Comment by Strangeys** [comment]
Closing since you're a MapDev now and can add these if you'd like.
