### ISSUE TITLE
[HNS/50v4] Amusement Park Hide n' Seek

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#404]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*

- [x] I have [pruned] the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
What is the map called? **Ameusement Park Hide n' Seek**

## Gamemode & Map Description  
What gamemode(s) It's an arcade map, approaching a Hide n' Seek in an amusement park.

## Team Sizes
How many teams and how large are they? 2 Teams Hiders & Seekers. 50v4

## Screenshots
![image](https://user-images.githubusercontent.com/97280598/162844757-24dfa4b9-a8d9-47bb-a36c-8e4632d1c085.png)

## Map Download
[download](https://github.com/OvercastCommunity/CommunityMaps/tree/master/arcade/hns/amusement_park_hide_n_seek)

**Comment by CrazyisCreeps** [comment]
Rather than this being a single elimination hide n seek map, have you considered going with an infection styled take of the map? Allows for people to join mid game and gives other opportunities of fun for hiders that are found.

**Comment by calcastor** [comment]
closing issue as it's been loaded in both HnS and Infection format, with the second one sponsorable
