### ISSUE TITLE
Koth 12v12 Pyramid Scheme

### ISSUE THREAD

**Issue by Tywnis** [OvercastCommunity/CommunityMaps#405]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X]  I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X]  I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [N] The map has been tested locally to make sure it works

# Pyramid Scheme

## 3 hill koth
first thought for the competition but went overboard and it's too big :) 

## 12v12

# XML
https://gist.github.com/Tywnis/0210766a14f20275ec2e5f86e1820269

![map](https://user-images.githubusercontent.com/4369123/163584685-a789d9c8-d2b4-40d6-a3ae-c53b4c1d8877.png)

# Download Link

[Pyramid Scheme.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8496533/Pyramid.Scheme.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in 743d314.

**Comment by calcastor** [comment]
closing issue as it has been added to pools
