### ISSUE TITLE
CTF 8v8 Tsuba 

### ISSUE THREAD

**Issue by Tywnis** [OvercastCommunity/CommunityMaps#406]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [N] The map has been tested locally to make sure it works

# Tsuba CTF
## 8v8

This is a Public version of the map submitted to Bolt contest.  

# XML
https://gist.github.com/Tywnis/12a0c67dbefa8879ad3f241d88effc6f

![map](https://user-images.githubusercontent.com/4369123/164163626-1875bc83-c512-47d6-ac1d-938121202011.png)

[Tsuba CTF.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8518772/Tsuba.CTF.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in 601c881.

**Comment by Tywnis** [comment]
Looks like the version that was added was the 5v5 (comp) instead of 8v8 (pub)

**Comment by calcastor** [comment]
closing issue as it has been added to pools
