### ISSUE TITLE
[Rage TDM] Moor Rage 10v10 

### ISSUE THREAD

**Issue by Tywnis** [OvercastCommunity/CommunityMaps#407]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works (It did work with that same xml a few years ago so..) 

# Moor Rage

Rage TDM with scoreboxes & emerald top ups

## 10v10

# XML
https://gist.github.com/Tywnis/7f511aa9cd55a9486cb43e5241e4869d

[Moor Rage.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8537380/Moor.Rage.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Added in 6b6a618.

**Comment by Strangeys** [comment]
Closing since you're a MapDev now and can add these if you'd like.
