### ISSUE TITLE
FFA KOTF - Paladins Kotf (25 players)

### ISSUE THREAD

**Issue by Tywnis** [OvercastCommunity/CommunityMaps#409]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Paladins Kotf

## 25 players

# XML
https://gist.github.com/Tywnis/ff6d20f8a40af8b0dcceedb7c0b67123

![map](https://user-images.githubusercontent.com/4369123/165552272-fbb613c9-87ff-4efc-93c2-a4672e36ca5e.png)

[Paladins FFA King of the Flag.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8573330/Paladins.FFA.King.of.the.Flag.zip)

**Comment by CoWinkKeyDinkInc** [comment]
I made this small addition to your XML, shouldn't change much:
```xml
<kill-rewards>
    <!-- Normal rewards, every kill -->
    <kill-reward>
        <item amount="2">arrow</item>
        <item>golden apple</item>
    </kill-reward>
    ...
</kill-rewards>
```

Added in 0f5ea6c.

**Comment by Strangeys** [comment]
Closing since you're a MapDev now and can add these if you'd like.
