### ISSUE TITLE
[CTW/12v12v12v12] Ruffland

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#410]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Ruffland

## Gamemode & Map Description  
CTW | 4 teams on a medieval map

## Team Sizes
12v12v12v12 | 48 Players

## Screenshots
https://imgur.com/a/QrqXKLT

# XML
[map.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8628276/map.zip)

# Map Image
![2022-05-05_02 57 10](https://user-images.githubusercontent.com/99238656/166850193-7f553e7c-db64-444e-bc07-c955823b1e1f.png)

# Download Link
https://www.mediafire.com/file/07zfogkm6pkeqmj/Ruffland.zip/file

**Comment by CoWinkKeyDinkInc** [comment]
Loaded in ffe24b0b2ef1a0f332de9b75e7281c6d2dd8d62a. The layout of this looks exciting and promising!

**Comment by calcastor** [comment]
closing issue as it has been added to pools
