### ISSUE TITLE
[Rage TDM/28v28] Disc Wars

### ISSUE THREAD

**Issue by MishM0sh1** [OvercastCommunity/CommunityMaps#415]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
What is the map called?
Disc Wars

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.
Centi rotation-sized rage TDM lasting 8 minutes, players are able to use jump pads and other features to quickly move around the map and interact with the layout. Teams consist of 28 players maximum per team.

## Team Sizes
How many teams and how large are they?
2 teams, 28 vs 28

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible.
https://imgur.com/a/XEQimKv

# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.
[Disc_Wars (1).zip](https://github.com/OvercastCommunity/CommunityMaps/files/8747010/Disc_Wars.1.zip)

# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` in `290x246` resolution and upload it by dragging it into this text box.
![map](https://user-images.githubusercontent.com/105904508/169636802-76822ad1-bcc8-4186-b70f-f16ef7322f8c.png)

# Download Link
[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive** or **Dropbox**.
[Disc_Wars (1).zip](https://github.com/OvercastCommunity/CommunityMaps/files/8747011/Disc_Wars.1.zip)
![map](https://user-images.githubusercontent.com/105904508/169636804-b15ccd43-d4dd-464c-9be0-05a58a06e8a6.png)

**Comment by CoWinkKeyDinkInc** [comment]
Loaded in ccb8a4e.

**Comment by calcastor** [comment]
Thanks for submitting this map! We've added it to the pool in https://github.com/OvercastCommunity/MapPools/commit/95069092df966dee91daff1e33b244b7251e0bb8.
