### ISSUE TITLE
[KOTH/24] Limbo IV

### ISSUE THREAD

**Issue by supremeZone** [OvercastCommunity/CommunityMaps#416]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X ] I have created an XML file
- [X ] I have created an map image
- [X ] I have uploaded the map zip file to a file sharing service
- [X ] The map has been tested locally to make sure it works

# Map Name
Limbo IV

## Gamemode & Map Description  
There are not enough Limbos. This is control point/koth

## Team Sizes
2 teams of size 12

## Screenshots
https://imgur.com/a/D08r9Np

# Download Link
https://mega.nz/folder/P3J0wCYJ#P1PpXKDVWz109G4pj8XRRg

**Comment by CoWinkKeyDinkInc** [comment]
Since you aren't the authors of the original versions of Limbo, please give this a new unique map name.

**Comment by CoWinkKeyDinkInc** [comment]
Closed for inactivity.
