### ISSUE TITLE
[Mob Arena/150 playes vs mobs] MobArena: Silent City

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#417]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
MobArena: Silent City

## Gamemode & Map Description  
Inspired by the simple city layout of Resident Evil and Silent Hill for PS1, this map is a mob arena where you have to survive against hordes of zombies, blazes, spiders, witches, etc....

## Team Sizes
150 players

## Screenshots
[Imgur](https://imgur.com/gallery/2HI70wU) 

# XML
[Git](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/44f54eddb741d9ab825bef9aec12e64401bdcbb4/Silent%20City%20(MobArena).xml)  it compiles

# Map Image
![2022-05-19_17 36 40](https://user-images.githubusercontent.com/82010545/169925369-6266e5d8-2037-4730-a789-648a2d3c0b85.png)
  `map.png` in `290x246` .

# Download Link
[Package the map](https://www.dropbox.com/s/nu2w03ghhqgxa6t/Mob%20Arena%20Silent%20City.zip?dl=0)  **Dropbox**.

**Comment by calcastor** [comment]
loaded in 90e5a83cdf2399ccf985d87c7ba89dc5bd795224

**Comment by Cazadorian** [comment]
This map has been in the Funky Friday events pool for some time now and seems overall fine at this point. If you have any further updates for this map feel free to submit them as a new issue but for now I'm closing this submission as complete.
