### ISSUE TITLE
[CTW/16v16] Veld

### ISSUE THREAD

**Issue by Alternqtive** [OvercastCommunity/CommunityMaps#418]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Veld

## Gamemode & Map Description  
A 2 team 16x16 CTW by Alternqtive, Cazadorian and Tundren

## Screenshots
[Screenshots](https://imgur.com/gallery/DqeCNS4)

# XML
[XML](https://gist.github.com/Alternqtive/c38ac541d3f7e30847a8a1c35b3a1079)

# Map Image
![map](https://user-images.githubusercontent.com/94016692/170137956-9886f90e-a56e-4ecd-bda5-c5fd6b6b4e03.png)

# Download Link
[Map](https://www.mediafire.com/file/emsuyslnzzznid4/Veld.rar/file)

**Comment by calcastor** [comment]
4326719d628dfaf98f76ee3c4a04c77bf745a933

**Comment by Cazadorian** [comment]
The spawners for blue and light blue wool were the wrong way around, fixed xml below

https://gist.github.com/Cazadorian/484c54a4567528a14e6d15aeb51824bc

**Comment by Cazadorian** [comment]
Updated to v1.1

- Team sizes lowered to 12v12
- Changed the kill rewards to match the spawn kits
- Fixed some anti-tunnelling bedrock walls being hollow
- Regions added to water lanes to allow players to build directly in the water

[Veld v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8884562/Veld.v1.1.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in 5fd0262.

**Comment by Cazadorian** [comment]
Closing this issue as the map has been added to the map pool. Thank you for submitting it.
