### ISSUE TITLE
[KOTH/12] Limbo 1/2

### ISSUE THREAD

**Issue by supremeZone** [OvercastCommunity/CommunityMaps#419]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X ] I have created an XML file
- [X ] I have created an map image
- [X ] I have uploaded the map zip file to a file sharing service
- [X ] The map has been tested locally to make sure it works

# Map Name
Limbo 1/2

## Gamemode & Map Description  
Control point, nano or micro pool

## Team Sizes
2 teams of size 6

## Screenshots
https://imgur.com/a/giv6U15

# Download Link
https://mega.nz/folder/6nYxEbTY#Tx09jzvLN1_pVUzJytuqnA

**Comment by CrazyisCreeps** [comment]
What's the special twist on this from Limbo?

**Comment by EpicPuppy613** [comment]
> What's the special twist on this from Limbo?

its tiny apparently

**Comment by CoWinkKeyDinkInc** [comment]
Since you aren't the authors of the original versions of Limbo, please give this a new unique map name.

**Comment by CoWinkKeyDinkInc** [comment]
Closed for inactivity.
