### ISSUE TITLE
[Update] Riot in Prison RAGE 

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#421]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Map decoration. [PicsOfDeco](https://imgur.com/gallery/BkenPjh)
Players from 40 to 45.
Add spawns  
Time from 12 m to 8m

# XML
P[GIT](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/b4eb34c04a3a98986aab7c7c1e7aeb3c9c26849a/Riot%20in%20Prison%20RAGE.xml) 

# Download Link
[Package the map](https://www.dropbox.com/s/4a9nzum0r0u69em/Riot%20in%20Prison%20RAGE%20%28Final%20Mod%29.zip?dl=0)  **Dropbox** Map pics, XML and map files.

**Comment by CoWinkKeyDinkInc** [comment]
#332

**Comment by CoWinkKeyDinkInc** [comment]
2fb9bbb
