### ISSUE TITLE
[CTW/16v16] Fiesta Mexicana

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#423]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Fiesta Mexicana

## Gamemode & Map Description  
Capture the Flag on this Mexican Party, enjoy of the enviroment

## Team Sizes
16v16

## Screenshots
https://imgur.com/a/nHhRIo5

# XML
https://www.dropbox.com/sh/m29f1mlx1e9dysv/AAAhfLEU8TittQFJMChYCkbca?dl=0

# Map Image
![2022-06-04_00 46 13](https://user-images.githubusercontent.com/99238656/171963960-33e443d8-36be-4614-bb83-ceb70b4eb286.png)

# Download Link
The map is already in the dropbox Builders1 (kazoha) https://www.dropbox.com/sh/m29f1mlx1e9dysv/AAAhfLEU8TittQFJMChYCkbca?dl=0

**Comment by CoWinkKeyDinkInc** [comment]
Playtesting this map I think it would do much better if the teamsizes were increased to 25v25. It plays well so at the moment it needs more aesthetic changes and attention in the spawn areas (the middle island is great). It's surprising that mossy stone bricks aren't used in this map at all.

**Comment by Cazadorian** [comment]
This map has been in the pool for a few months now and it seems unlikely that it'll receive any further changes so I'm closing this issue for now, thanks for the submission.
