### ISSUE TITLE
[TDM/10v10v10v10] Spheres

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#425]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Spheres

## Gamemode & Map Description  
TDM Fight against the other teams but be careful to not fall into the lava pool

## Team Sizes
10v10v10v10

## Screenshots
https://imgur.com/a/hj5kNAZ

# XML
https://www.dropbox.com/s/rw12b6i2jwc8dup/map.xml?dl=0

# Map Image
![2022-06-04_00 29 22](https://user-images.githubusercontent.com/99238656/171967864-ff192a66-58fe-485e-9e55-a6781d34a3ed.png)

# Download Link
The map is already in the dropbox builders1 (kazoha)
https://www.dropbox.com/sh/n6qrxymk95jlrn3/AACGWwXOyh-ske4BaYOu6MLAa?dl=0

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/d1015c5f5bfdc686ba77860e64e07093fadfe806

**Comment by Cazadorian** [comment]
This map hasn't been updated for almost half a year now despite significant feedback being given. and the map is very unlikely to be used for the map pool in its current state. I'm therefore closing this issue for now due to inactivity, however if any further updates are made feel free to reopen this issue and post them.
