### ISSUE TITLE
[BLITZ/12v12v12v12] 9 Layers of Random Blocks

### ISSUE THREAD

**Issue by StanleyThat** [OvercastCommunity/CommunityMaps#429]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file-sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
 9 Layers of Random Blocks

## Gamemode & Map Description  
Blitz. Intended for arcade purposes. The last team standing wins, players mine the random blocks on their island to get to other teams. The islands are made from wood, stone, pistons, iron ore and other random blocks. Border shrinks at the 5-minute mark.

## Team Sizes
4 Teams, 12 per team
## Screenshots
https://imgur.com/a/xQFeeAw
# XML
https://gist.github.com/StanleyThat/b1d8d38381d2f8565660ccdd26624d2f
# Map Image
https://imgur.com/a/0eYQunI
# Download Link
[9 Layers of Random Blocks]https://www.dropbox.com/s/jskpiaxropvx6xi/9%20Layers%20of%20Random%20Blocks.zip?dl=0

**Comment by rockymine** [comment]
just why

**Comment by StanleyThat** [comment]
> just why

I thought it would be fun for sns

**Comment by StanleyThat** [comment]
Edit: Updated and tested with the help of CoWinkKeyDinkInc.
- Fixed pickaxe breaking after mining one block - Made it unbreakable
- Added obs spawn location

**Comment by CoWinkKeyDinkInc** [comment]
Added in 65c6abb.

**Comment by CoWinkKeyDinkInc** [comment]
There needs to be more incentive to get players bridging. I think putting visible diamond blocks in the center would be a good idea. So other than fixing armor I don't know what else could be added in.

**Comment by StanleyThat** [comment]
Edit published:
Reduced border shrink time
Added secret obs spawn maze
Added more diamonds to incentivise players to go to mid
Fixed armour bug
Fixed world border bug

**Comment by StanleyThat** [comment]
Edit: 1.0.3
Fixed syntax error

**Comment by calcastor** [comment]
Thanks for submitting, since this is an arcade map and won't be added to the standard pool I'll close the issue for now. When I get the chance I'll add this and others to the fun or sns pool.
