### ISSUE TITLE
[Blitz FFA/64] Knockout Stick Fight

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#430]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Knockout Stick Fight

## Gamemode & Map Description  
Submitting on behalf of Mariogoat.

Map is a blitz FFA where players spawn on a collection of discs with knockback 3 sticks and have to knock the enemy players off into the void, and be the last person standing.

## Team Sizes
FFA max 64 players

## Screenshots
![2022-06-15_16 39 29](https://user-images.githubusercontent.com/73002842/173871903-aa9a85e2-22e2-4181-91e6-bf10ca2bb511.png)

# XML
[XML](https://gist.github.com/Cazadorian/42dd1f304d6c373569f5e46472a60831)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/173872145-e679b311-b529-475f-b4b0-53141ca2d077.png)

# Download Link
[Knockout Stick Fight.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8911113/Knockout.Stick.Fight.zip)

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/9c5b4678d989ab33d5f3d2b0d5dde6023768e6eb

**Comment by Cazadorian** [comment]
Update to v1.1
-Redid spawns to stop some players spawning on the outer edges of platforms as some of them would immediately just run off the map.

[Knockout Stick Fight v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/8920696/Knockout.Stick.Fight.v1.1.zip)

**Comment by Cazadorian** [comment]
Updated to v1.2
-Added 3 seconds of spawn knockback resistance to go along with the 3 seconds of damage resistance
-Added a second of slowness 255 at the start to stop people blindly running off the map at the start. If you still manage to do so it's just natural selection at this stage.
-Added scaling levels of knockback on the stick that increase as the match progresses
-Upped time limit to 6m to fit the scaling change
Updated XML: https://gist.github.com/Cazadorian/42dd1f304d6c373569f5e46472a60831

**Comment by Pugzy** [comment]
Updated
