### ISSUE TITLE
[Koth/16v16] Sky Shot

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#431]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Sky Shot

## Gamemode & Map Description  
Inspired in long shot, now you will have to capture the hills to win instead of flags, bridge to the other island and practice your water drops 

## Team Sizes
16v16

## Screenshots
https://imgur.com/a/BPzsiTq

# XML
https://www.dropbox.com/s/jjznwor5bq08yej/map.xml?dl=0

# Map Image

![2022-06-11_00 36 30](https://user-images.githubusercontent.com/99238656/174643928-b83d229b-e627-487d-813d-bdbf81f0339a.png)

# Download Link
The map is already in the dropbox builders(1) Kazoha
https://www.dropbox.com/sh/vi11n4dd8bi393e/AAB5Dd2a7ooUCYp2yZJQB7SJa?dl=0

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/b4a9fa5569bcce38d64d625adbcb95bdb974a632

**Comment by Cazadorian** [comment]
This map hasn't been updated for almost half a year now despite significant feedback being given. and the map is very unlikely to be used for the map pool in its current state. I'm therefore closing this issue for now due to inactivity, however if any further updates are made feel free to reopen this issue and post them.
