### ISSUE TITLE
[Update] Iti Mo'ai, v1.1

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#432]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
-Upped team sizes to 16v16
-Swapped monument from gold block+iron pickaxe to emerald+stone efficiency 2 pickaxe
-Changed defender chest pickaxe from efficiency 1 diamond to efficiency 5 gold

# XML
[XML](https://gist.github.com/Cazadorian/278bb4923122e9e6264c55da38d0e014)

# Download Link
[Iti Mo'ai v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9016308/Iti.Mo.ai.v1.1.zip)

**Comment by RuedigerLP** [comment]
https://github.com/OvercastCommunity/CommunityMaps/commit/e51637f607e99ce7f9311144c2f37e50263d358e
