### ISSUE TITLE
[Update] Stratosphere Rage, v1.3

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#433]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
-Removed jump pad directly out of spawn, resulted in players being too funnelled into middle which was detrimental to gameplay(sorry to those who told me they really like having it).
-Readded two of the splash speed potion spawners on the dropdown path to compensate for the jump pad removal.
-Added two jump pads on the platforms outside the spawn exits to make the upper and side levels a lot more viable by being faster to reach mid.
-Added two jump pad platforms to lower which fire up onto temple, should massively encourage players to contest temple as well instead of just focusing on pit like before.
-Adjusted cover to fit the new map changes
-Fixed an XML error that meant dying to the void gave your team a point
-Fixed obs spawn being off by a block
-Unified speed boost with Quadrosphere.

# XML
[XML](https://gist.github.com/Cazadorian/56c6680b7e3efb624958d372a9748193)

# Download Link
[Stratosphere Rage v1.3.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9016343/Stratosphere.Rage.v1.3.zip)

**Comment by CoWinkKeyDinkInc** [comment]
#291
