### ISSUE TITLE
[Update] Stratosphere Rage, v1.4

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#434]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
-Readded spawn jump pads with velocity reduced compared to v1.2, the reduced velocity should hopefully still result in it not funnelling players directly to pit as much.
-Gave the bow sharpness 10 to unify with Quadrosphere
-Added adventure mode to spawn kit
-Adjusted the velocities of a lot of the jump pads
-Removed the jump pad from lower to Temple as it funnelled players too much towards Temple and heavily interfered with fights on lower.
-Readded two speed splash potion spawners from earlier versions.
-Restored speed boost from 0.3 to 0.4.
-Updated map.png

# XML
[XML](https://gist.github.com/Cazadorian/56c6680b7e3efb624958d372a9748193)

# Download Link
[Stratosphere Rage v1.4.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9032249/Stratosphere.Rage.v1.4.zip)

**Comment by CoWinkKeyDinkInc** [comment]
84c72a6 #291 Done!
