### ISSUE TITLE
[Rage CTF/12v12] Disc Wars II

### ISSUE THREAD

**Issue by MishM0sh1** [OvercastCommunity/CommunityMaps#437]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Disc Wars II

## Gamemode & Map Description  
Rage ctf, players try to capture their teams flag from the opposite teams side and bring it back to their own sides flag spawn area. First team to have a 3 flag advantage wins, with a 12 minute time-limit. If teams are tied after 12 minutes, the match will go into overtime for a maximum time of 2 minutes.

## Team Sizes
2 teams of 12.

## Screenshots
[](https://imgur.com/a/sdgpMDF)

# XML
https://gist.github.com/Cazadorian/73da3f721c678fb3d870b3fc702055d0

# Map Image
![map](https://user-images.githubusercontent.com/105904508/177224237-08ce5b41-5a6c-4f34-b1d5-739cb3c6e199.png)

# Download Link
[Disc_Wars_II.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9042327/Disc_Wars_II.zip)

**Comment by Cazadorian** [comment]
Updated to v1.1.1

-Added spawn changes Mame missed.
-Slightly adjusted some cover to better fit jump pad landing spots.
-Reduced flag respawn time from 10 to 5.
-Added creation date.


[Disc Wars II v1.1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9060458/Disc.Wars.II.v1.1.1.zip)

**Comment by Cazadorian** [comment]
Updated to v1.2

-Adjusted cover around the map
-Added additional walls and cover to the flag platform.
-Added stairs up to the jump pads as jumping onto them instead of walking results in too much inconsistency.
-Added team locked jump pads on each's team's side of mid up to the upper island.

[Disc Wars II v1.2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9113072/Disc.Wars.II.v1.2.zip)

**Comment by Cazadorian** [comment]
Closing this issue as the map has been added to the map pool. Thank you for submitting it.
