### ISSUE TITLE
[DTC/9X9] Medieval Village DTC

### ISSUE THREAD

**Issue by vitor-barros** [OvercastCommunity/CommunityMaps#438]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
What is the map called?
Medieval Village DTC

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.
DTC
Awesome gameplay, encourages more pvp and less bow spamming.

## Team Sizes
How many teams: 2 
how large are they? [9x9]

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible.
https://prnt.sc/MK2Ng6pL85El

# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.
ruediger did the xml, he's the goat

# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` in `290x246` resolution and upload it by dragging it into this text box.
![MapSC](https://user-images.githubusercontent.com/84398653/177431569-93034a23-cf2b-4102-b7a2-96463a5553fb.png)

# Download Link
[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive** or **Dropbox**.
[medieval_village_dtc.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9050164/medieval_village_dtc.zip)

**Comment by vitor-barros** [comment]
![map](https://user-images.githubusercontent.com/84398653/177431909-ecaf9ea3-7aeb-481f-b20b-926e56c22bab.png)

I just noticed I added the wrong sc in this post, but the right one is in the zip file, but im sending here again anyways

**Comment by CoWinkKeyDinkInc** [comment]
Comments from @Cazadorian :

- Change the bell from Gold Blocks to yellow wool so players don't get confused thinking it's a monument 
- Fix observer spawn
- Leak distance needs to be 1 block higher

**Comment by vitor-barros** [comment]
- [x] Change the bell from Gold Blocks to yellow wool so players don't get confused thinking it's a monument
- [x] Fix observer spawn
- [x] Leak distance needs to be 1 block higher 
- [x] And some minor features xd

[Medieval_Village_pruned_files.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9051397/Medieval_Village_pruned_files.zip)

**Comment by RuedigerLP** [comment]
updated to 1.0.1 in https://github.com/OvercastCommunity/CommunityMaps/commit/919dd1b6b51470c76e4897b2b0116dd299f82d01

**Comment by vitor-barros** [comment]
[x] Fixed minor issues
[x] Max buid height 26 (instead of 27)
[x] 48x wood and 32x glass (instead of 64x wood and 64x glass)
[x] added new chests on the map
[x] XML improvements 

[Medieval Village DTC.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9125720/Medieval.Village.DTC.zip)

**Comment by calcastor** [comment]
Added this to pools in [https://github.com/OvercastCommunity/MapPools/commit/075e5a6cdcc497200cbaa22202cca4a11e11a8f9](this commit), so I'm going to close this issue for now. Thanks for submitting! We have an update template for any potential future updates to the map.
