### ISSUE TITLE
[DTC/8v8] Hearts of Atlantis

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#440]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
What is the map called?

## Gamemode & Map Description  
This map is an 8v8 DTC designed with a unique layout and shape to make it play better at lower player counts than are standard for DTC maps. The map otherwise is a rather standard TNTless DTC map.

## Team Sizes
2 teams 8v8

## Screenshots
[Screenshots](https://imgur.com/a/Kj2Wqua)

# XML
[XML](https://gist.github.com/Cazadorian/8bd6bf8abe671b9307c09718fd13ca41)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/177895892-40f9f517-d06f-481f-b067-a134fbdb1bbc.png)

# Download Link
[Hearts of Atlantis.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9068124/Hearts.of.Atlantis.zip)

**Comment by calcastor** [comment]
Closing as this has been added to pools. Thanks for the submission!
