### ISSUE TITLE
[CTW/8v8] Deciduous Nights

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#441]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Deciduous Nights

## Gamemode & Map Description  
This map is a simple 1 wool per team CTW intended for smaller player counts such as 8v8. The key unique thing about this map is that every single full block within the playable area is a type of clay. The map should hopefully play like a standard CTW.

## Team Sizes
2 teams 8v8

## Screenshots
[Screenshots](https://imgur.com/a/ILed12W)

# XML
[XML](https://gist.github.com/Cazadorian/97c94b8a62f83d3e1a3e76133225e3be)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/177896409-f034e00a-1b1a-4743-86f3-24de74b202e8.png)

# Download Link
[Deciduous Nights.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9068151/Deciduous.Nights.zip)

**Comment by calcastor** [comment]
Closing as this has been added to pools. Thanks for the submission!
