### ISSUE TITLE
[Update] Infection: Riot in Prison

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#444]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Same cosmetic changes as in Riot in Prison RAGE, and improved XML, also forgot to add a glass wall the first time I made the map, then the problem is now solved.
More players 60 vs 6 (8 overfill)
Kits mod

# XML
[GIT](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/2768786764b59cdc47502683fad9cfc31f1bc878/Infection_Riot%20in%20Prison.xml) 

# Download Link
[Package the map](https://www.dropbox.com/s/c57qs9ni5i1m6fv/Infectio%20Riot%20in%20Prison.zip?dl=0)  **Dropbox**.

**Comment by JosueSaenzLacayo-UCR** [comment]
Today I had some problems with my dropbox so here is the link again in the update request

**Comment by Cazadorian** [comment]
Updated in cac9bcc
