### ISSUE TITLE
[Update] MobArena _ Silent City

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#445]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks)
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
place invisible blocks where players cheated and remove some blocks to improve mob mobility, also add weapons to improve map exploration

# XML
N/A, in the future I hope to implement the selection of classes in the map

# Download Link
[Package the map](https://www.dropbox.com/s/jxvmho20gk9p539/MobArena%20_%20Silent%20City.zip?dl=0)  **Dropbox**.

**Comment by Cazadorian** [comment]
Updated in 670244d
