### ISSUE TITLE
[Rage/Scorebox/AD/Mixed/8v8] Transit

### ISSUE THREAD

**Issue by Alexander2972** [OvercastCommunity/CommunityMaps#446]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Transit 

## Gamemode & Map Description  
Players are separated into two teams with different toolkit. Terrorists can use their TNT to break their way into the scorebox and Guards are given cobweb to block their way.

## Team Sizes
Two teams of 8

## Screenshots
https://imgur.com/a/n1zLB7k

# XML
https://gist.github.com/Alexander2972/fa8e776354dd7981e86390230a4ab34e

# Map Image
![map](https://user-images.githubusercontent.com/43311897/181487281-c9ef3b30-f252-4275-a74d-5ff772ef1546.png)

# Download Link
[Transit.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9213821/Transit.zip)

**Comment by Cazadorian** [comment]
Closing this issue as the map has been added to the map pool. Thank you for submitting it.
