### ISSUE TITLE
[CTW/24V24] Villa 2

### ISSUE THREAD

**Issue by eliminate123** [OvercastCommunity/CommunityMaps#455]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Villa 2

## Gamemode & Map Description  
CTW 1 wool for each team

## Team Sizes
24v24

## Screenshots
https://imgur.com/a/znKqYNI

# XML
https://gist.github.com/eliminate123/b55bf63de740e96ec9351a6a170bf871

# Map Image
![map](https://user-images.githubusercontent.com/96848330/183314926-b4ec8e73-d1d0-4714-97e6-ae5a0d405da0.png)

# Download Link
[Villa 2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9277754/Villa.2.zip)

**Comment by eliminate123** [comment]
Fixed:
-Spawn chests
-Defenders chest (added dispensers and redstone blocks)
-Weird parts of bedrock wall under dirt at wool room
-Added buttons to side of wall outside of wool room to help deter block glitching
-Fixed rocks filled with gold blocks at mid
-Removed random orange wool in flags at mid

[Villa II.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9579485/Villa.II.zip)

**Comment by Cazadorian** [comment]
> Fixed: -Spawn chests -Defenders chest (added dispensers and redstone blocks) -Weird parts of bedrock wall under dirt at wool room -Added buttons to side of wall outside of wool room to help deter block glitching -Fixed rocks filled with gold blocks at mid -Removed random orange wool in flags at mid
> 
> [Villa II.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9579485/Villa.II.zip)

Loaded in 2d30b92

**Comment by Cazadorian** [comment]
Closing this issue as the map has been added to the map pool. Thank you for submitting it.

**Comment by eliminate123** [comment]
Fixed: 
-Bedrock wall (for some reason some blocks were missing)

[Villa.II.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9641254/Villa.II.zip)

**Comment by eliminate123** [comment]
Made some QOL changes:
- Added 2 floating gravel jumps to wool room to help defenders get to bedrock wall faster at start of the game
- Fixed the section of terrain behind the bedrock wall
- Changed defender materials (was just copied from Kanto, now it is different. Blame Tundren)
- Made minor changes to observer spawn
- Made minor changes to front of wool room

[Villa 2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10609475/Villa.2.zip)

**Comment by zzuf-fer** [comment]
Updated in db5046d
