### ISSUE TITLE
[Update] Infection Riot in Prison 

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#457]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Just deco, add Mishm0sh and Fb changes  in their cells

# XML
N/A

# Download Link
[Package the map](https://www.dropbox.com/s/m2frwrpqyifbmx5/Infection%20Riot%20in%20Prison.zip?dl=0)  **Dropbox**.

**Comment by Cazadorian** [comment]
Updated in 9741866
