### ISSUE TITLE
[CTW/16v16] Dead Noon

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#458]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x ] I have created an XML file
- [x ] I have created an map image
- [x ] I have uploaded the map zip file to a file sharing service
- [x ] The map has been tested locally to make sure it works

# Map Name
Dead Noon

## Gamemode & Map Description  
CTW. One word to describe the map? Moist.

## Team Sizes
2 teams, 16v16

## Screenshots
https://imgur.com/gallery/g6r7clD

# XML
https://gist.github.com/0uzi/dafe67fffdea3c702d068795bb86a95b

# Map Image
![map png pngh](https://user-images.githubusercontent.com/96648252/183359165-af4435b6-c4ba-4191-8ea4-09a5f8fe0fd9.png)

# Download Link
[0uzi (2).zip](https://github.com/OvercastCommunity/CommunityMaps/files/9279506/0uzi.2.zip)

**Comment by calcastor** [comment]
loaded in 66df9c25ff0009392fbff5ef380e978d4b67be8f

**Comment by 0uzi** [comment]
TO DO LIST:
Iron blocks respawn too fast
Remove water buckets from dropping on death

**Comment by calcastor** [comment]
> TO DO LIST: Iron blocks respawn too fast Remove water buckets from dropping on death

resolved

**Comment by calcastor** [comment]
Thank you for submitting! We've added this map to the pools here: https://github.com/OvercastCommunity/MapPools/commit/9487cd11744343642885811e0ac117854a570091.
