### ISSUE TITLE
[FFA/Arcade/50p] Fall Guys

### ISSUE THREAD

**Issue by samschaap** [OvercastCommunity/CommunityMaps#459]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Fall Guys

## Gamemode & Map Description  
The map is a free-for-all runner map, the first player to reach the finish wins. PVP is disabled and there are multiple checkpoints around the map where players will respawn if they die.

## Team Sizes
Free-for-all, 50 players

## Screenshots
https://imgur.com/a/TzVA0oY

# XML
https://gist.github.com/samschaap/db19b32769c1b454297d1610b338f368

# Map Image
![map](https://user-images.githubusercontent.com/1810738/183387273-db20b0ad-951e-4beb-9383-6e09052b945b.png)

# Download Link
[fall_guys.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9280695/fall_guys.zip)

**Comment by samschaap** [comment]
Based on the map test yesterday we made some small changes. The arrow dispenser at the wither area has been removed and the wither region has been expanded to prevent players from sneaking around it on the edge.
[fall_guys.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9291733/fall_guys.zip)

**Comment by Cazadorian** [comment]
> Based on the map test yesterday we made some small changes. The arrow dispenser at the wither area has been removed and the wither region has been expanded to prevent players from sneaking around it on the edge. [fall_guys.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9291733/fall_guys.zip)

Loaded in 3fc8590

**Comment by samschaap** [comment]
We have made some more small changes: an extra checkpoint has been added and a extra jump boost effect and small parkour so 1.7 players do not get stuck at the part with the slime blocks.
[fall_guys.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9329664/fall_guys.zip)

**Comment by Cazadorian** [comment]
This map seems complete at this stage and likely doesn't need any further updates. The map is already used for sponsoring and staff events, and I'll potentially consider adding it to an upcoming pool dedicated to staff events. Thank you for the submission.
