### ISSUE TITLE
[Update] Hide n Seek :Cinema Jungle Scenario

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#460]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Invisible blocks were placed to prevent cheaters and some additions were made. The time was reduced to 6 minutes. Change in spawn points. Infection ver cooming soon!!!

# XML
[GIT](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/107b224329a14978bf4fdf5ed8ca667d72b98287/Hide%20n%20Seek%20Cinema%20Jungle%20Scenario.txt) 

# Download Link
[Package the map](https://www.dropbox.com/s/cv1qd14eupj9ocr/Hide%20%26%20Seek_%20Cinema%20Jungle%20Scenario.zip?dl=0)  **Dropbox**.

**Comment by Cazadorian** [comment]
Updated in bd82a32
