### ISSUE TITLE
[Update] MobArena: Silent City

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#461]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Implementation of class selection, replacement of weapons around the map for ammo, and addition of spawner within the library.
And time reduction to 10 mins

# XML
[GIT](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/2c03df3839501d7550fd8155242b08881b666842/Silent%20City%20(MobArena).xml)

# Download Link
[Package the map](https://www.dropbox.com/s/jxvmho20gk9p539/MobArena%20_%20Silent%20City.zip?dl=0)  **Dropbox**.

**Comment by Cazadorian** [comment]
Updated in 9d95eeb
