### ISSUE TITLE
[CTF/3v3v3v3] Happy Rainbow

### ISSUE THREAD

**Issue by lkfjimmy** [OvercastCommunity/CommunityMaps#462]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Happy Rainbow

## Gamemode & Map Description  
CTF mixes block falling feature from puddin' pops. Players need to keep running to avoid fall to the void.
Capture the enemy flag with the mercy limit of 3

## Team Sizes
4 teams. 3v3v3v3

## Screenshots
[imgur](https://imgur.com/a/DeErHDw)

# XML
[map.xml](https://gist.github.com/lkfjimmy/b52ecf81ea00f52d7b5902d9acf77916)

# Map Image
![map](https://user-images.githubusercontent.com/110178996/185590031-d88e6a3a-4fa4-4bf8-a3c1-4f42de315d67.png)

# Download Link
[[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive** or **Dropbox**.](https://drive.google.com/file/d/1VNfYeWzvek4L1PVe01Th3u3X-0Sz7pnK/view?usp=sharing)
[Happy Rainbow.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9461121/Happy.Rainbow.zip)

**Comment by CoWinkKeyDinkInc** [comment]
This map is really fantastic! It plays great as a 5v5v5v5 and was pretty fun.

**Comment by calcastor** [comment]
This has been added to pools within the last few months and seems to play decently at the player count CoWink mentioned above. Closing this issue as I don't think there's any other concerns at the moment.
