### ISSUE TITLE
[KotF/24v24] Zipline II - the next test

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#465]
# Map Image
![map](https://user-images.githubusercontent.com/22761234/185557311-6fe07406-52a9-4eeb-810d-3a5640d4e0fb.png)

### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Zipline - the next test

## Gamemode & Map Description  
The classic zipline KotF experience but in a new sequel map with an upgraded look & feel to the map

## Team Sizes
24 v 24 (aka around hecto sized)

## Screenshots
https://imgur.com/a/pTQVVxH

# XML
https://gist.github.com/technodono/17429e0ba9aba04fe5ef4d3070c47a8e

# Download Link
uploading direct to git-hub gave me issues so here it is:
https://www.dropbox.com/s/n1m9n4ipfygu0v5/zipline_II_the_next_test.zip?dl=0
(NEW NAME VER)

**Comment by Cazadorian** [comment]
I'd consider renaming the map to "Zipline II: The Next Test" just so it's more clear that it's a sequel rather than something like a redux.

**Comment by technodono** [comment]
> I'd consider renaming the map to "Zipline II: The Next Test" just so it's more clear that it's a sequel rather than something like a redux.

wise idea

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
