### ISSUE TITLE
[Update] Dead Noon, 1.1.0

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#469]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x ] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x ] I have uploaded the map zip file to a file sharing service
- [x ] The update has been tested locally to make sure it works

# Changes
Moved spawn back so there is not a straight shot to wool lane

# XML
https://gist.github.com/0uzi/8aaaad48f8ce04766b17b08913fd8540

# Download Link
[Uploading 0uzi.zip…]()

**Comment by 0uzi** [comment]
[0uzi.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9388589/0uzi.zip)

oops here is the download link

**Comment by CoWinkKeyDinkInc** [comment]
#458
