### ISSUE TITLE
[CTW/24v24] Firestone Lake Research Facility

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastCommunity/CommunityMaps#47]
### Checklist
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Firestone Lake Research Facility

## Gamemode & Map Description  
This is a CTW map with a relatively standard layout; the main concept is that instead of a void gap, the map has a lava gap. Players receive a limited amount of non-flammable blocks, so the goal is to try and avoid your bridges burning too much, or get more non-flammable blocks through the kill reward.

## Team Sizes
Since we are short on centi-sized CTWs, I intentionally made this as a 24v24 CTW. If it's too crowded, it can get bumped down to 20v20.

## Screenshots
https://imgur.com/a/xxmMreY

# XML
Included in the zip.

# Map Image
Included in the zip.

# Download Link
[Firestone Lake Research Facility.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5310774/Firestone.Lake.Research.Facility.zip)

**Comment by fixitqixit** [comment]
Looks very interesting! Looking forward to seeing and playing this soon :)

**Comment by CrazyisCreeps** [comment]
Loaded up for testing

**Comment by master00ofdsiware** [comment]
This map is in the map pools.
