### ISSUE TITLE
[Update] Rangi-nui v1.0.2

### ISSUE THREAD

**Issue by jacketjack** [OvercastCommunity/CommunityMaps#473]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [X] I have uploaded the map zip file to a file sharing service
- [X] The update has been tested locally to make sure it works

# Changes
- Fixed spawner locations
- Updated timer to 7.5m
- Added contributor
- Updated alerts
- Other minor bug fixes

# XML
[map.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9396360/map.zip)

# Download Link

**Comment by CoWinkKeyDinkInc** [comment]
#471
