### ISSUE TITLE
[Update] Rangi-nui v1.0.3

### ISSUE THREAD

**Issue by jacketjack** [OvercastCommunity/CommunityMaps#475]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [X] I have uploaded the map zip file to a file sharing service
- [X] The update has been tested locally to make sure it works

# Changes
- Add beacons on pads
- Reworked spawn launch pads
- Edited tips and alerts
- Edited mid hologram
- Other minor tweaks

# XML

# Download Link
[Rangi-nui.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9414954/Rangi-nui.zip)

**Comment by Cazadorian** [comment]
Loaded in 87f0f79
