### ISSUE TITLE
[CTW/18v18] Röntgen 

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#479]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Röntgen

## Gamemode & Map Description  
CTW map, I imagine it will play similar to Deepwind Jungle, so 15 min games max

## Team Sizes
18v18 

## Screenshots
https://imgur.com/a/V0xmkIw

# XML
https://gist.github.com/oafMH/9e646b28eb6eccc7eddd28cf55dc85e7

# Map Image
![image](https://user-images.githubusercontent.com/7586568/187537107-f3b360e3-2882-4ba5-8c12-d62562b32c5f.png)

# Download Link
https://www.dropbox.com/s/gb8n255njilu3m3/roentgen.zip?dl=0

**Comment by Cazadorian** [comment]
Feedback on the map after seeing it play:
- The lane layout is rather confusing at the moment as to where and where you cannot build. I'd suggest either swapping over to water lanes to make it clearer, or just making most of the middle area buildable and just allow natural lanes to form through gameplay.
- The right upper islands on each team's side are currently pretty useless and should likely have a use added or be removed.
- A lot of the islands are currently completely flat with no structures at all on them, there are some islands with structures on them though and similar ones should be added to the other islands.
- I'd advise adding a roof or a building around spawn so it doesn't just become people firing into and out of spawn the second a skybridge is built.

**Comment by Cazadorian** [comment]
Closing this issue as the map has been added to the map pool. Thank you for submitting it.
