### ISSUE TITLE
[Update] Dead Noon, 1.1.1

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#480]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x ] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x ] I have uploaded the map zip file to a file sharing service
- [x ] The update has been tested locally to make sure it works

# Changes
Removed floating bench at mid
Removed pig spawners in wool rooms
Changed the wool room indicator above wool rooms to match the theme of the map
Retook map.png/imgur screenshots
Add crafting tables to itemkeep
Up spawnkit stone bricks from 32 -> 64

# XML
https://gist.github.com/0uzi/7774d0d236e30d7d95bd42c246c4427f

# Map Image
![map](https://user-images.githubusercontent.com/96648252/187021028-464e95e0-d18f-40db-b335-42d13c0ae86f.png)

# Download Link
[0uzi (1).zip](https://github.com/OvercastCommunity/CommunityMaps/files/9437513/0uzi.1.zip)

**Comment by 0uzi** [comment]
imgur https://imgur.com/gallery/dWALTZO

**Comment by Cazadorian** [comment]
Loaded in 64344df
