### ISSUE TITLE
[Update] RÖNTGEN, 1.0.1

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#481]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [X] I have uploaded the map zip file to a file sharing service
- [X] The update has been tested locally to make sure it works

# Changes
-Added more structures to make islands less flat
-Added 2 extra islands on either side to encourage use of the island to the right of spawn
-Changed teams back to Red / Blue, subsequently changing wool colors to red / blue
-Added more cover in spawn
-Added water lanes rather than cobwebs so it is easier to see buildable regions

' ' '
XML CHANGES 
' ' '
-Change void filter so it is possible to build at Y=0
-Added Golden Apple to spawn kit
-Moved spawn forward by one block 

# XML
https://gist.github.com/oafMH/78f26d0be8238ba4023aebf464a9f050

# Download Link
https://www.dropbox.com/s/8kb9pqgs3ysddvi/roentgen%20%281%29.zip?dl=0

**Comment by Cazadorian** [comment]
Loaded in af2c0a9
