### ISSUE TITLE
[Update] RÖNTGEN, 1.0.2

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#484]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [X] I have uploaded the map zip file to a file sharing service
- [X] The update has been tested locally to make sure it works

# Changes
-Moved iron platform one block forward
-Removed cobwebs around the map since water was already marking the regions
-Removed one stack of quartz (1 stack quartz, 1 stack stone bricks in current kit)

# XML
https://gist.github.com/oafMH/346df0fe10c2586654adbd3bf920c399

# Download Link
https://www.dropbox.com/s/gb8n255njilu3m3/roentgen.zip?dl=0

**Comment by Cazadorian** [comment]
Loaded in 2a40589

**Comment by oafMH** [comment]
https://gist.github.com/oafMH/346df0fe10c2586654adbd3bf920c399 new xml lowered the height limit a bit
