### ISSUE TITLE
[Update] Happy Rainbow, v2.0

### ISSUE THREAD

**Issue by lkfjimmy** [OvercastCommunity/CommunityMaps#485]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [X] I have uploaded the map zip file to a file sharing service
- [X] The update has been tested locally to make sure it works

# Changes
Please provide a short summary of changes to the map.
Changing gamemode from CTW to CTF.
No more slow-paced crafting and other complicated things. Simply capture the enemy flags.
(similar to Thunderrush, score from capture and a mercy limit)
Tuned down the player size to 3v3v3v3 to make the match less crowded and less chaos.
Replaced glass to wool solving the noise produced by the renewing glass. (PGM's sound="false" is not working)
(ps. Sorry for making such huge changes and updating maps that frequent)

# XML
[Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.](https://gist.github.com/lkfjimmy/b52ecf81ea00f52d7b5902d9acf77916)

# Download Link
[[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive** or **Dropbox**.](https://drive.google.com/file/d/1VNfYeWzvek4L1PVe01Th3u3X-0Sz7pnK/view?usp=sharing)
[Happy Rainbow.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9461121/Happy.Rainbow.zip)

**Comment by Cazadorian** [comment]
Loaded in 0ca3889
