### ISSUE TITLE
[CTW/6v6] PRISMA CTW

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#491]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Prisma CTW

## Gamemode & Map Description  
CTW//Micro map inspired by Oceano CTW

## Team Sizes
Two teams of six

## Screenshots
https://imgur.com/a/T5sa9k9

# XML
https://gist.github.com/oafMH/7974c70fcc7a68def05d0d6cc1bbef84

# Map Image
https://gyazo.com/90e2cf4031a521aadf612b76faeae0c8

# Download Link
https://www.dropbox.com/s/z2v92gg1erncwgz/prisma_ctw.zip?dl=0

**Comment by calcastor** [comment]
In pools for some months now with no issues, thanks for submitting.
