### ISSUE TITLE
[CTW/16v16] Undead Noon

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#492]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Undead Noon

## Gamemode & Map Description  
Spooky version of hit map "Dead Noon"

## Team Sizes
2 teams 16v16

## Screenshots
https://imgur.com/gallery/qVYG0ak

# XML
https://gist.github.com/0uzi/3e28ddda650b9f906b7ba6cf1c6bc308

# Map Image
![dead](https://user-images.githubusercontent.com/96648252/190323863-721eaebb-f729-4a37-843b-69bda38ece4a.png)

# Download Link
[0uzi.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9572186/0uzi.zip)

**Comment by 0uzi** [comment]
New download link:
[0uzi.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9581524/0uzi.zip)

XML with updated creation date:
https://gist.github.com/0uzi/8ffa5beed28714e6c7d1e305a685fd56

**Comment by Cazadorian** [comment]
Loaded in 78c8556
