### ISSUE TITLE
[CP-RAGE/8v8] Paintmans day off

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#496]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Paintmans day off

## Gamemode & Map Description  
Rage, splatoon style capture points

## Team Sizes
8v8

## Screenshots
[Image album](https://imgur.com/a/ie0vTJV)

# XML
[XML](https://gist.github.com/Samuel-Roach/6dd1b6dce8a76ede4a3c2c18fb26a58a). It's kinda big, sorry

# Map Image
![](https://imgur.com/0TwUTS0.jpg)

# Download Link
[Mediafire download](https://www.mediafire.com/file/89mcpq8naqsl0o2/Paintmans_day_off.zip/file)

**Comment by Samuel-Roach** [comment]
Update:

- Changed speed pot spawner region
- Changed speed pot spawner timer
- Reduced time for the match
- Added another ladder to access rafters

**Comment by Samuel-Roach** [comment]
Version 1.0.3:
- Added Speed Attribute to spawn boots to give all players a little speed boost
- Add a spawn protection to both spawns

**Comment by Cazadorian** [comment]
> Version 1.0.3:
> 
> * Added Speed Attribute to spawn boots to give all players a little speed boost
> * Add a spawn protection to both spawns

Updated in 2b566d6

**Comment by TheRealPear** [comment]
Seeing that the last response on this ticket is from October 2022 and the map has been in the pool since March with little to no issues, I will be closing this. Thank you for your submission!
