### ISSUE TITLE
[RAGE FFA/10] Deadwood

### ISSUE THREAD

**Issue by zzuf-fer** [OvercastCommunity/CommunityMaps#497]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Deadwood

## Gamemode & Map Description  
3 minute long non-standard RAGE and FFA deathmatch. Swords don't kill in one hit. Players are able to double jump.
Fast gameplay with short match times.

## Team Sizes
10 players (12 max), spawning on any of the 14 spawnpoints available.

## Screenshots
[Imgur album](https://imgur.com/a/wiH7JBV)

# XML
[map.xml](https://gist.github.com/zzuf-fer/cadcc12319de69cef693d24eaa6857ef)

# Map Image
![map](https://user-images.githubusercontent.com/11651753/192122114-5c5d6981-6369-4e79-992f-6a773ca72891.png)

# Download Link
[Mega.nz link](https://mega.nz/file/jjQGGBrL#hitPx9rjw3hgHxSb5P1Q-Qq8HdcAeIo8hzbqj4-_F3A)

**Comment by zzuf-fer** [comment]
XML has received a very minor update, as I realized I had a region as a rectangle instead of a cuboid, making it possible to activate a message in unintended places.

**Comment by zzuf-fer** [comment]
XML has received another update (removed a duplicate module) + bumped base player count from 8 to 10

**Comment by Cazadorian** [comment]
> XML has received another update (removed a duplicate module) + bumped base player count from 8 to 10

Update loaded in 6381ccd

**Comment by zzuf-fer** [comment]
**Deadwood 1.0.2**
 - Added arrows to itemremove.
 - Fixed miscellaneous design inconsistencies across the map.
