### ISSUE TITLE
[Race/50] Rainbow Race

### ISSUE THREAD

**Issue by alejo112** [OvercastCommunity/CommunityMaps#498]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Rainbow Race

## Gamemode & Map Description  
Race, the one to finish the map faster wins

## Team Sizes
FFA, 50 but up to whatever

## Screenshots
https://imgur.com/a/CcQFH2z

# XML
https://gist.github.com/alejo112/9f9fc86a0d2df19c93083430657fd769

# Map Image
![map](https://user-images.githubusercontent.com/79621801/192125296-1aa760ac-4849-4d2b-8bbd-995f04676f34.png)

# Download Link
https://www.mediafire.com/file/r6bugrnqyt9bjdr/rainbow+road.zip/file

**Comment by calcastor** [comment]
Closing as this is fine in its current state and is played for/during Friday events and other events
