### ISSUE TITLE
[FFA/8] Paint Can't Wait 2

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#499]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Paint Can't Wait 2

## Gamemode & Map Description  
FFA fast paced 1m

## Team Sizes
8 players

## Screenshots
[Album](https://imgur.com/a/CnQkCrS)

# XML
[XML](https://gist.github.com/Samuel-Roach/bad0cddf7f7831fd52bc25d1bdd61557)

# Map Image
![](https://imgur.com/UVbuzz9.jpg)

# Download Link
[Map download](https://www.mediafire.com/file/qcbip3lmmy1jbs6/Paint_Can%2527t_Wait_2.zip/file)

**Comment by Cazadorian** [comment]
I've added this map to the Funky Friday events pool and it doesn't seem to have any major issues with it, so I'm closing this issue as complete. Thank you for the submission.
