### ISSUE TITLE
[RAGE Blitz/8v8v8v8] Sagujo

### ISSUE THREAD

**Issue by zzuf-fer** [OvercastCommunity/CommunityMaps#500]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created a map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Sagujo

## Gamemode & Map Description  
3 minute long non-standard RAGE and Blitz match. Swords don't kill in one hit. Players are able to double jump.
Fast gameplay with short match times.

Other gamemodes such as FFA and even ones like Infection have also been considered for this map. Could be interesting for a different version.

## Team Sizes
4 teams of 8 players each (with a maximum overfill of 12)

## Screenshots
[Imgur album](https://imgur.com/a/aDqCgTF)

# XML
[map.xml](https://gist.github.com/zzuf-fer/883b0b5f598bb145dacbcd9040b5bd08)

# Map Image
![map](https://user-images.githubusercontent.com/11651753/192611109-a46276be-8079-4c7d-b9eb-f21001d26d9c.png)

# Download Link
[Mega.nz link](https://mega.nz/file/v7QyzA7S#gIXri6iljHpek1h4ZJXIT6y_9jZb9W2eBBFkPVACDB8)

**Comment by zzuf-fer** [comment]
Map has received some very minor aesthethic changes and additions (fixed a couple of pillars).
Bumped version to 1.0.1

**Comment by Cazadorian** [comment]
> Map has received some very minor aesthethic changes and additions (fixed a couple of pillars). Bumped version to 1.0.1

Loaded in 3e54c4b

**Comment by zzuf-fer** [comment]
Very minor XML update: added arrows and leather helmets to itemremove. Bumped to 1.0.2

**Comment by Cazadorian** [comment]
> Very minor XML update: added arrows and leather helmets to itemremove. Bumped to 1.0.2

Updated in dde0f42
