### ISSUE TITLE
[Update]PURPLE HAZE,1.0.1

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#501]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [X] I have uploaded the map zip file to a file sharing service
- [X] The update has been tested locally to make sure it works

# Changes
-Added two alternative routes out of spawn (get it cos alternqtive xml'd it)
-Changed jump pad values 
-Moved wall in front of spawn

# XML
https://gist.github.com/oafMH/870ed9c4266c71e89c5c16465cd24892

# Download Link
https://www.dropbox.com/s/ya0vf3ewolldhrt/purple_haze.zip?dl=0

**Comment by oafMH** [comment]
https://gist.github.com/oafMH/0ff58ffb350da48d21c596a02d47f4b3 NEW XML THAT ONE IS WRONG

**Comment by Cazadorian** [comment]
Loaded in 07fc292
