### ISSUE TITLE
[CTW/28v28] Shroom Galaxy

### ISSUE THREAD

**Issue by samschaap** [OvercastCommunity/CommunityMaps#502]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Shroom Galaxy

## Gamemode & Map Description  
Capture the Wool map, in Mario 64/Mario Galaxy style

## Team Sizes
2 teams, 28 players per team

## Screenshots
https://imgur.com/a/RhiAtvj

# XML
https://gist.github.com/samschaap/467cbff0c2719e2836fd2b9fa45db8e6

# Map Image
![map](https://user-images.githubusercontent.com/1810738/193090682-dd3d16ac-bcfc-486d-a66f-886f3f1e79aa.png)

# Download Link
[shroom_galaxy.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9677130/shroom_galaxy.zip)

**Comment by Cazadorian** [comment]
This map has been in the pool for a few months now and while it does occasionally stalemate this doesn't seem to be the consistent norm so the map seems fine for now. If there's any future updates feel free to submit them as a new issue, and I'm closing this issue as complete for now.
