### ISSUE TITLE
[KotH/6v6] Byas

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#503]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Byas

## Gamemode & Map Description  
KotH - Be the first to 750 points

## Team Sizes
6v6

## Screenshots
[Images](https://imgur.com/a/8K33REK)

# XML
 [XML](https://gist.github.com/Samuel-Roach/165fc0f9ac1ed5e6464345dd9ae0d9e1) 

# Map Image
![map](https://imgur.com/VKXeLhA.png)

# Download Link
[Download](https://www.mediafire.com/file/0r2jzgpxgufb4oz/Byas.zip/file)

**Comment by Samuel-Roach** [comment]
Version 1.0.1:

- Added Spawn Protection
- Added Ladder to side hills
- Updated download and XML

**Comment by Cazadorian** [comment]
> Version 1.0.1:
> 
> * Added Spawn Protection
> * Added Ladder to side hills
> * Updated download and XML

Updated in 0d6692f

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
