### ISSUE TITLE
[BLITZ RAGE/5348] Charge 2.0

### ISSUE THREAD

**Issue by alejo112** [OvercastCommunity/CommunityMaps#504]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
What is the map called?

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.

## Team Sizes
4 teams, 1337 players per team

## Screenshots
https://imgur.com/a/LJAmHwZ

# XML
https://gist.github.com/alejo112/f33411ce7a571d8583a319853540d083

# Map Image
![map](https://user-images.githubusercontent.com/79621801/193400421-8ad1983e-6c6f-40c6-9dbf-1304aec65056.png)

# Download Link
https://www.mediafire.com/file/jwoq2nsxbuif6en/charge_2.0.zip/file

**Comment by calcastor** [comment]
I'm just going to assume this works
