### ISSUE TITLE
[CTW/5v5] Solaris

### ISSUE THREAD

**Issue by killtrixy** [OvercastCommunity/CommunityMaps#506]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
What is the map called?

Solaris

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.

CTW, Capture the wool to win.

## Team Sizes
How many teams and how large are they?

2 teams (red and blue) 5v5

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible.
[https://imgur.com/a/O4xxIEU](url)

# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.

# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` in `290x246` resolution and upload it by dragging it into this text box.

![map](https://user-images.githubusercontent.com/101747964/193439333-c10fea02-7e11-45a2-8344-1fb5503a9781.png)

# Download Link
https://www.dropbox.com/sh/16pul0i55uu5pet/AAATkDBUCg12FUKW44u7QaTSa?dl=0

**Comment by Cazadorian** [comment]
This map quality is significantly below the minimum of what we'd accept for use on OCC. The locations of the spawns and woolrooms would make the map incredibly painful to actually play, and the map in general would likely need to be just completely redone in order to work. If you wish to actually update the map to try to fix these issues please let me know, otherwise I'll close the issue if not.

**Comment by killtrixy** [comment]
> 

How would you know it wouldn't play well unless you tested it? Your opinion on whether this map is playable or not is subjective and have no concrete evidence to support your claims. You also don't have to talk down my map as "low quality" when it's literally a 5v5. Based on my timezone I find myself often playing a lot of micro maps which most of the "quality" ones tend to get rushed since they offer multiple lanes. This map was created with 1 lane so that

**Comment by CoWinkKeyDinkInc** [comment]
Why isn't it taken place at night time?
