### ISSUE TITLE
[Blitz/20v20] Dodge Ball Stadium

### ISSUE THREAD

**Issue by xvicho** [OvercastCommunity/CommunityMaps#507]
### Checklist
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Dodge Ball Stadium

## Gamemode & Map Description  
The map is a blitz/rage map where you have to one-shot kill your enemies using arrows that spawn at the center of the field.

## Team Sizes
It is a 20vs20 map but it can be expanded

## Screenshots
https://imgur.com/a/BQwkG7v

# XML
https://gist.github.com/xvicho/8b9a9157a6cfd522084522f4f03d9c65

# Map Image
![map](https://user-images.githubusercontent.com/26119702/193466455-f53a8f12-b791-469d-bbdd-563e2fb55a8a.png)

# Download Link
https://www.dropbox.com/s/x2xhlqxc3ro0911/Dodge%20Ball%20Stadium.zip?dl=0

**Comment by Cazadorian** [comment]
In its current state this map is still lacking something significant enough to make it stand out from the original map. Subtracting the small pieces of cover, this map is ultimately the original with a different set of aesthetics and a higher base player count. I'm not exactly sure what to suggest to change, potentially making large modifications to the playable arena would work but ultimately I'll leave these decisions to you.

**Comment by calcastor** [comment]
If you choose to address the above comment, please feel free to submit an issue updating the map. Otherwise, this has worked fine for arcade events so I will close this issue.
