### ISSUE TITLE
[Infection/61 players] Infection: Cinema Jungle Scenario

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#509]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Infection: Cinema Jungle Scenario

## Gamemode & Map Description  
Is the HNS Cinema Jungle Scenario but infection version

## Team Sizes
55 hiders
6 seekers

## Screenshots
[Imgur](https://imgur.com/gallery/chRQnQR) 

# XML
[GIT](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/1174840d44743e48510b751424f58ae6ea3abd19/Infection_CinemaJungleScenario.xml) 

# Map Image
 
![2022-10-02_21 58 08](https://user-images.githubusercontent.com/82010545/193507002-339b49bc-5eec-438b-b2e9-eb960da1476a.png)

# Download Link
[Package the map](https://www.dropbox.com/s/bkf7vz9t5e5sl67/InfectioCinemaJungleScenario.zip?dl=0)  **Dropbox**

**Comment by TheRealPear** [comment]
Seeing that this map has been in the Funky Friday pool since November 2022 with no issues, I will be closing this. Thank you for your submission!
