### ISSUE TITLE
[Update] Hide n Seek Cinema Jungle Scenario

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#510]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [X] I have uploaded the map zip file to a file sharing service
- [X] The update has been tested locally to make sure it works

# Changes
Decorative changes and correction of minor details on the map. Also some special additions.

# XML
N/A

# Download Link
[Package the map](https://www.dropbox.com/s/sw6azdjnnggqm0d/Hide%20n%20Seek%20Cinema%20Jungle%20Scenario.zip?dl=0)  **Dropbox**.

**Comment by JosueSaenzLacayo-UCR** [comment]
Please close this request the map was tested in its infection version and it has a detail where the players get on an area where they shouldn't, I'll fix it as soon as I can

**Comment by Cazadorian** [comment]
> Please close this request the map was tested in its infection version and it has a detail where the players get on an area where they shouldn't, I'll fix it as soon as I can

When you've made this fix you can update this post with the new files, just post a comment as well so we know that it has been updated.

**Comment by JosueSaenzLacayo-UCR** [comment]
Ty Caz. I decided to fix the problem using the XML delimiting a cuboid where the players will not be able to climb on the trees. I attached the modification of the map without barriers and the XML link.
[GIT] https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/7b465b18f6a56dbaa9d8ce608dfefedd26ca51c9/Hide%20n%20Seek%20Cinema%20Jungle%20Scenario.xml 
[DROPBOX] https://www.dropbox.com/s/yoo08lfs8np3zf9/Hide%20%26%20Seek_%20Cinema%20Jungle%20Scenario.zip?dl=0
Files are prune, XML validated and tested

**Comment by Cazadorian** [comment]
Loaded in 81dcbe9
