### ISSUE TITLE
[CTW/24v24] Noble's District

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#512]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Noble's District

## Gamemode & Map Description  
This is the most map ever (My father left me)

## Team Sizes
2 teams. 24v24

## Screenshots
https://imgur.com/gallery/GuViIyr

# XML
https://gist.github.com/zzuf-fer/519d4be7016cb6180dc2ba29c2b96838

# Map Image
![map](https://user-images.githubusercontent.com/96648252/193746844-54da0d96-a199-4644-afd3-7e928dabd45a.png)

# Download Link
[0uzi.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9703035/0uzi.zip)

**Comment by zzuf-fer** [comment]
Minor XML update: fixed being able to build over cobweb lines at mid. Bumped to 1.0.1

**Comment by Cazadorian** [comment]
> Minor XML update: fixed being able to build over cobweb lines at mid. Bumped to 1.0.1

Loaded in df73170

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
