### ISSUE TITLE
Amusement Park Halloween Edition

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#513]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
What is the map called? Amusement Park Halloween Edition

## Gamemode & Map Description  
The same as Amusement Park Infection but halloween edition

## Team Sizes
50 hiders and 3 seekers ( I think ) ^_^

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible. 
![2022-10-03_22 26 52](https://user-images.githubusercontent.com/97280598/193896426-acf99224-4ed2-435b-9d6a-36ea8a4aeea4.png)

# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here. 
[amusement_park_infection_halloween_edition.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9709626/amusement_park_infection_halloween_edition.zip)
( XML AND DOWNLOAD )

# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` in `290x246` resolution and upload it by dragging it into this text box. 🥇 

# Download Link
[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive**, **Dropbox**, or by dragging it into this text box. Make sure your file contains a region folder, a level.dat, a map.xml, and a map.png. 

#404

**Comment by Cazadorian** [comment]
Map has been loaded and the regular version has been swapped out for this edit for the rest of the month.
