### ISSUE TITLE
Fall Guys

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#514]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Please provide a short summary of changes to the map. - We decided to remove the wither effects because it was quite buggy and replaced it with lava. 

# XML
[fall_guys.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9709962/fall_guys.zip) ( XML AND DOWNLOAD )

# Download Link
[Package the map]and upload it somewhere where we can downpiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.

**Comment by Cazadorian** [comment]
Updated in 559d166
