### ISSUE TITLE
[Update] MobArena: Silent City

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#517]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Time reduction from 10 mins to 7 mins, (If I left for 5 minutes, the challenge of surviving would not be so difficult.).
New obs spawn and decoration.
Implementation of 2 new classes: the original game mode and the Space Marine (if it goes wrong I will remove it)
Zones like the library are now in balance (I think so)
Fixed medical class because potions were not working.

# XML
[GIT](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/618cba9bae96eea1e7a41ada36a4c9b40fdaa0c6/Silent%20City%20(MobArena).xml) 

# Download Link
[Package the map](https://www.dropbox.com/s/eeul9gh6iididw4/MobArena%20_%20Silent%20City.zip?dl=0)  **Dropbox**

**Comment by Cazadorian** [comment]
Updated in e20505c
