### ISSUE TITLE
[CP/6v6v6v6] Paint The Streets

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#518]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Paint The Streets

## Gamemode & Map Description  
Capture Point / Painters

## Team Sizes
6v6v6v6

## Screenshots
[Images](https://imgur.com/a/Mfr0Fpc)

# XML
[XML](https://gist.github.com/Samuel-Roach/0509063e99d04c5e4be61a32c592ed53)

# Map Image
![Image](https://imgur.com/jaAz0Bp.png)

# Download Link
[Download](https://www.mediafire.com/file/63mmrqchj52vv46/Paint_The_Streets.zip/file)

**Comment by Cazadorian** [comment]
This map has been in the pool for a few months now and it seems to fit in decently well despite being more arcadey than what is usual for the pools so going to close the issue as complete. Thanks for the submission.
