### ISSUE TITLE
[CTW/18v18] Colorado

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#520]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
What is the map called? Colorado

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.
CTW 18v18

## Team Sizes
How many teams and how large are they? 18v18

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible. 

# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.

# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` in `290x246` resolution and upload it by dragging it into this text box. 
![image](https://user-images.githubusercontent.com/97280598/194747155-912f2818-ec7f-4791-9256-308f8fbb0b28.png)

# Download Link
[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive**, **Dropbox**, or by dragging it into this text box. Make sure your file contains a region folder, a level.dat, a map.xml, and a map.png.

( XML AND DOWNLOAD LINK )

[colorado.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9741123/colorado.zip)

**Comment by calcastor** [comment]
This map was updated via a PR and then some XML side changes were made by mapdevs. It was added to pools and generally seems to play fine in its current state. The biggest concern is the bedrock placement/format in the wool lanes but this can be addressed later if needed. Thanks for submitting, closing this issue now.
