### ISSUE TITLE
[CTW/12v12] Jupiter

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#521]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created a map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Jupiter

## Gamemode & Map Description  
CTW, capture the enemy team's wools to win

## Team Sizes
12v12

## Screenshots
https://imgur.com/a/vT9mUf3

# XML
https://gist.github.com/oafMH/29d55c69a9b7e257b11158ca2b580c82

# Map Image
![](https://i.gyazo.com/7d05f74951e4d996d1a5183a621252d1.png)

# Download Link
https://www.dropbox.com/s/cb3pmrcac8yugiv/jupiter.zip?dl=0

**Comment by oafMH** [comment]
COMMON SAMSHEEP W

**Comment by Cazadorian** [comment]
> Version 1.0.1, small update to XML to disable hunger https://gist.github.com/samschaap/5b7d29592a6fbf68f254f410693f3e42

Updated in 60183e9

**Comment by TheRealPear** [comment]
Closing this as it has been almost a year since the last comment and the map is currently in the pool without major issues. Thank you for your submission!
