### ISSUE TITLE
[AD Rage/8v8] Transit: Halloween Edition

### ISSUE THREAD

**Issue by lkfjimmy** [OvercastCommunity/CommunityMaps#524]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created a map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Transit: Halloween Edition

## Gamemode & Map Description  
Players are separated into two teams with different toolkit. Terrorists can use their TNT to break their way into the scorebox and Guards are given cobweb to block their way.

## Team Sizes
Two teams of 8

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible.

# XML
https://gist.github.com/lkfjimmy/6994642e7c4495aa7484d64d98210649

# Map Image
![map](https://user-images.githubusercontent.com/110178996/195251030-200b5c99-341b-4fd3-9211-47807b23ae5d.png)

# Download Link
[Transit HE.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9761543/Transit.HE.zip)

**Comment by calcastor** [comment]
Loaded in ce034da795c05c87352ae0877e80100934785327, thank you!
