### ISSUE TITLE
[DTM/24v24] Mythica DTM (by DerStiv)

### ISSUE THREAD

**Issue by rockymine** [OvercastCommunity/CommunityMaps#527]
### Checklist
- [x] ~~I have~~ @Cazadorian has (hopefully) [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] ~~I have~~ **DerStiv** has agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] ~~I have~~ @Cazadorian has (hopefully) created an XML file
- [x] ~~I have~~ **DerStiv** created a map image
- [x] ~~I have uploaded the map zip file to a file sharing service~~ Builders don't do this.
- [x] The map ~~has been tested locally to make sure it works~~ will work (eventually)

# Map Name
Mythica DTM

## Gamemode & Map Description  
24v24 DTM map.

## Team Sizes
24v24

## Screenshots
![](https://i.imgur.com/rRJLvfl.png)

# XML
[XML](https://gist.github.com/Cazadorian/89a0c57c5e8de8da9ad0468fb440bd07)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/196053076-71e8b020-ed70-4b0f-8038-d7121860bfee.png)

# Download Link
[mythica dtm.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9795466/mythica.dtm.zip)

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
