### ISSUE TITLE
[CTW/10v10v10v10] Forgotten Kingdom 

### ISSUE THREAD

**Issue by vitor-barros** [OvercastCommunity/CommunityMaps#528]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created a map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Forgotten Kingdom

## Gamemode & Map Description  
CTW. Its 4 teams based map, 2 wools each team, 6 wools to capture (8 wools in total) its similar to Levels and BE3.

## Team Sizes
4 teams, 10v10v10v10

## Screenshots
![Screenshot_8](https://user-images.githubusercontent.com/84398653/196070060-66f504c8-6cda-4fb3-90dc-ef1691827946.png)

# XML
https://gist.github.com/zzuf-fer/880fe34d3fa768cf54e947f9e673d03a

# Map Image
![map](https://user-images.githubusercontent.com/84398653/196070173-aa915946-8e61-4bd1-9fa1-54e58dcaa3dc.png)

# Download Link
[forgotten_kingdom.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9796186/forgotten_kingdom.zip)

**Comment by zzuf-fer** [comment]
Minor XML update (1.0.1): Disabled hunger
