### ISSUE TITLE
[Update] Prisma CTW, 1.0.1

### ISSUE THREAD

**Issue by samschaap** [OvercastCommunity/CommunityMaps#531]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [X] I have uploaded the map zip file to a file sharing service
- [X] The update has been tested locally to make sure it works

# Changes
-Moved buildable regions one block out
-Moved spawns further back to make it easier to run out with wool
-Modified kill rewards, added blocks and more arrows
-Modified spawn kit, more blocks

# XML
https://gist.github.com/samschaap/b0d3149e13315886a91579896f4944aa

# Download Link
[prisma_ctw.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9814127/prisma_ctw.zip)

**Comment by oafMH** [comment]
Updated XML file https://gist.github.com/oafMH/f169878c61beb2b785b4c5747ab1ee71

**Comment by Cazadorian** [comment]
Updated in 4d71b8c
