### ISSUE TITLE
[CTW/8v8] Research Base

### ISSUE THREAD

**Issue by eliminate123** [OvercastCommunity/CommunityMaps#532]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created a map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Research Base

## Gamemode & Map Description  
8v8 CTW

## Team Sizes
8v8

## Screenshots
![image](https://user-images.githubusercontent.com/96848330/196581232-902524c7-fb67-45dd-8abc-1c3c7edd874e.png)

# XML
https://gist.github.com/zzuf-fer/a59c7b21e78d23c20fd0e603d030f2ea

# Map Image
![map](https://user-images.githubusercontent.com/96848330/196580852-ab290aa3-e171-407a-911e-c1197a5aed00.png)

# Download Link
[Research Base.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9816370/Research.Base.zip)

**Comment by calcastor** [comment]
Loaded in d6cd53a96ef66daceea99ddc918a3282ca95e9cf

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.

**Comment by eliminate123** [comment]
Fixed an insane game breaking issue where 1 block was missing

[Research Base.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10609446/Research.Base.zip)

**Comment by zzuf-fer** [comment]
Updated in 8a87b95
