### ISSUE TITLE
[WALLS/11v11v11v11] Citadel Walls

### ISSUE THREAD

**Issue by LoganVe** [OvercastCommunity/CommunityMaps#534]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have (_Pear) created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Citadel Walls

## Gamemode & Map Description  
Walls drop at 3 minutes! Try to prepare and kill everyone else on the other teams!

## Team Sizes
4 teams 11 per 

## Screenshots
https://imgur.com/a/deHHwWj

# XML

https://www.mediafire.com/file/lhzl15rmw890ppq/XML.zip/file

# Map Image

![](https://cdn.discordapp.com/attachments/1031647339443666976/1032307932462854144/Map_image.png)

# Download Link
https://www.mediafire.com/file/t3h8ki25sskgs5u/Citadel_Walls.zip/file

**Comment by Cazadorian** [comment]
This map appears to use an edited version of another server's lobby as a large part of the map. This lobby isn't publicly licensed and our server does not have permission to use it even if partially edited, therefore we are unable to use this map in its current form. Please completely remove all content from the map that you are not licensed to use, and then reopen this issue.

Content that should be removed with a comparison to the original can be seen below:

![2022-10-20_07 27 13](https://user-images.githubusercontent.com/73002842/196876208-aa19fe12-929b-44c2-bbef-c9f9bf3ee6c9.png)

![2022-10-20_07 24 08](https://user-images.githubusercontent.com/73002842/196876242-804110a7-ccb0-4644-9265-ddeda6287956.png)
