### ISSUE TITLE
[CTW/8v8] EnderiumCTW

### ISSUE THREAD

**Issue by Quantum155** [OvercastCommunity/CommunityMaps#538]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
EnderiumCTW

## Gamemode & Map Description  
Standard one wool CTW

## Note
I have submitted a map called "EnderiumCTW" in the past, this is the complete rework of that map. Only the name and theme stayed the same, so I've decided to submit this as a new map.

~~Also, I couldn't get MCedit or MCAselector to work on linux with minecraft 1.8.9, so I'm unable to prune the map myself. I'm sorry about this, I'll try to figure something out for this in the future.~~

## Sizes
Two 8 player teams

## Screenshots
https://imgur.com/a/70moWPT

# XML
https://gist.github.com/Quantum155/92a4c7580eeff3fcd9f17dd2bacfa7a7

# Map Image
![map](https://user-images.githubusercontent.com/61941975/197299107-c062c95e-5a4e-434f-b63d-bd59a1c9cca4.png)

# Download Link
https://drive.google.com/file/d/1zO7t2QCc2oui91G5qZgeIH_-lvZWVzY-/

**Comment by Quantum155** [comment]
I've pruned the map and updated the download link.

**Comment by calcastor** [comment]
Loaded in d33cd9046939cadf7f21a3996dd7d5f265a5c4b6

**Comment by Quantum155** [comment]
I've updated the map XML (both in the github gist and the zip downloadable from google drive).
Changes:
- Fixed build height limit not working
- Standardized hotbar layout by swapping the pickaxe and axe slots

**Comment by Cazadorian** [comment]
> I've updated the map XML (both in the github gist and the zip downloadable from google drive). Changes:
> 
> * Fixed build height limit not working
> * Standardized hotbar layout by swapping the pickaxe and axe slots

This update was originally loaded in 4e98dd4 and superseded by 5dfdf4e
