### ISSUE TITLE
[CTF:FF/15v15] Royal Rumble

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#54]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Royal Rumble

## Gamemode & Map Description  

This map is based off a game-mode I don't think has ever been used on pgm called flag-football. In the xml I've listed the game-mode as ctf until this category gets added. 

The way the game works is that 2 teams have goals on their side of their map which they need to defend from the flag holder. The person holding the flag gets a speed buff and must race to the opposing teams goal and score to win! If a player get's killed the ball is open to anyone for 10 seconds to scoop up and try score on the opposing team

For this map each team has a front and a back goal worth 1pt and 2pts respectively. The first team to score 5 goals will win!

This may need to be tweaked if matches end up in checkmates constantly but we'd need to test that

## Team Sizes
I have 15 ppl per team but can change this if it's to much/little

## Screenshots
https://imgur.com/a/V38hVXl

# XML
https://gist.github.com/technodono/8650f404795ecc78bd799213f9417540
XML is also included in world download

# Map Image
![map](https://user-images.githubusercontent.com/22761234/95668416-856b6880-0bbf-11eb-9466-7fdbdba3d1cf.png)

# Download Link
[Royal rumble.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5360480/Royal.rumble.zip)

# Newer Download Link
[Royal rumble (NEW!).zip](https://github.com/OvercastCommunity/CommunityMaps/files/5390670/Royal.rumble.NEW.zip)

**Comment by master00ofdsiware** [comment]
Added for testing.

**Comment by CrazyisCreeps** [comment]
Increase time limit and I wonder if there's a way to make it easier to understand how to cap?

**Comment by master00ofdsiware** [comment]
The map is way too crowded, should probably be a 12v12 or even less.

**Comment by technodono** [comment]
The way I made this map doesn't really work in a Flag football scenario... I'll look at making abetter version sometime in he future... but for now i'll close this and this cna go into the rejected map pools
