### ISSUE TITLE
[Update] Noble's District

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#541]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Noble's District

## Gamemode & Map Description  
Decreased middle void gap by 16 blocks
Decreased both wool lane lengths by 16-18 blocks
Moved left wool lane 20 blocks further from spawn
Added a third stack of blocks to spawn kit
Reduced crafting tables in spawn kit from 32 to 16
Moved tree out of spawn region as it was causing disruption
Added a horse
Made the map round instead of square

## Team Sizes
2 teams 24v24

## Screenshots
https://imgur.com/gallery/jf0kQAE

# XML
https://gist.github.com/zzuf-fer/519d4be7016cb6180dc2ba29c2b96838

# Map Image
![map](https://user-images.githubusercontent.com/96648252/197377032-1c4c8329-971d-4b0f-a529-5dcff7cf7f9d.png)

# Download Link
[Noble's District.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9845857/Noble.s.District.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Is this an update or otherwise related to #512 ?

**Comment by Cazadorian** [comment]
Updated in 5879bbd
