### ISSUE TITLE
[CTW/8v8] Outlyne

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#543]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Outlyne

## Gamemode & Map Description  
CTW

## Team Sizes
8v8

## Screenshots
[Images](https://imgur.com/a/uuits2e)

# XML
[XML](https://gist.github.com/Samuel-Roach/6e8dbc93b42a82cffb28f9fff42b5dc3)

# Map Image
![map.png](https://imgur.com/bIFXPEf.jpg)

# Download Link
[Download](https://www.mediafire.com/file/3l2oark4rga579a/Outlyne.zip/file)

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
