### ISSUE TITLE
[KOTF/14v14] Limit

### ISSUE THREAD

**Issue by eliminate123** [OvercastCommunity/CommunityMaps#545]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Limit

## Gamemode & Map Description  
KOTF

## Team Sizes
14v14

## Screenshots
https://i.imgur.com/iFw0NK7.jpeg

# XML
https://gist.github.com/eliminate123/868c4b5cc5e6c3a987dff262839a23ce

# Map Image
![map](https://user-images.githubusercontent.com/96848330/197859313-434a3398-91e4-4a9f-8a88-bdb816046af6.png)

# Download Link
[Limit.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9863223/Limit.zip)

**Comment by technodono** [comment]
One screenshot in the folio :(
Now I can't see the layout of the beautiful city map. (if you couldn't tell I like city/indoor maps)

Otherwise great (as all builder rank maps should be)

**Comment by eliminate123** [comment]
![image](https://user-images.githubusercontent.com/96848330/198888096-719a81d3-2bec-4b47-a774-94153bcfcbed.png)
![image](https://user-images.githubusercontent.com/96848330/198888169-539ff580-9298-4d3a-9cb6-b5e81aba2e5a.png)
![image](https://user-images.githubusercontent.com/96848330/198888116-fc1fda43-9133-4014-900b-836a47bb5f43.png)
![image](https://user-images.githubusercontent.com/96848330/198888178-3d9f88a5-58fe-4af2-bc90-ec97c527f335.png)

there

**Comment by calcastor** [comment]
This has been in pools for a bit and its only outstanding issue is certain blocks causing drops in FPS for some players. This isn't an urgent bug and it's otherwise fine for pools. Thank you for submitting!
