### ISSUE TITLE
[Update] Colorado

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#547]
### Checklist 
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only
- [x] I have uploaded the map zip file to a file sharing service
- [x] The update has been tested locally to make sure it works

# Changes
Please provide a short summary of changes to the map.
We have changed bridgeable ares, added smal islands, moved lft wr closer

# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here.

# Download Link
[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive**, **Dropbox**, or by dragging it into this text box. Make sure your file contains a region folder, a level.dat, a map.xml, and a map.png.
[colorado (3).zip](https://github.com/OvercastCommunity/CommunityMaps/files/9888732/colorado.3.zip)

**Comment by Cazadorian** [comment]
One of the regions in the submitted XML was incorrect, this has been fixed and the update has been loaded in 07d17b5
