### ISSUE TITLE
[FFB/8v8] Flag Football: Ice Rift

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#548]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Flag Football: Ice Rift

## Gamemode & Map Description  
Flag football

## Team Sizes
8v8

## Screenshots
[Screenshots](https://imgur.com/a/Mgxga6m)

# XML
[XML](https://gist.github.com/Samuel-Roach/9597e555e1c61d08df67f41ce6feb0a6)

# Map Image
![map.png](https://imgur.com/hpcSUv6.jpg)

# Download Link
[Map download](https://www.mediafire.com/file/lzjg9crjl81yvpz/Flag_Football_Ice_Rift.zip/file)

**Comment by technodono** [comment]
Map looks quite fun to play, But with the builds I just think the cliffs are a bit too white (and not steep enough) those on the sides on the field. 

I don't exactly know what good map examples I can provide, but I'd extend the grey up allot more and have the snow kind of drooping off the edges of the cliffs 

Apart from that great job, looks good!

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
