### ISSUE TITLE
[CTF (Flag Assault)/12v12] Kalahari Sanctuary

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#552]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Kalahari Sanctuary

### Gamemode & Map Description

I was inspired by the look of desert sanctuary and decided to make a savanna/desert style map with garden & foliage almost an Oasis some may say. Which has ended up with this brand new map: Kalahari Sanctuary.

This map uses the flag assault game-mode seen in other maps Like royal rumble II & the big dig, the goal being to escort the flag from your spawn to the enemies goals. This encourages an attack/defend play-style much more balanced and interesting compared to it's linear flag football countergamemode

Additionally with use of the crossbow mechanic featured in some of my other maps allows for close range weapon variety having the option to c-bow & sword strike rather than relying on no charge bows

### Team Sizes

12 v 12

### Screenshots

https://imgur.com/a/uHnojGJ

### XML

https://gist.github.com/technodono/8618bc47f5e2b392bb9bc169820c9305
(This XML is outdated, I forgot to update team sizes. Use the one in the map download provided)
Also dev-phased for caz's sake. he'll be a happy chappy after reading this
### Map Image

![map](https://user-images.githubusercontent.com/22761234/198948194-059d058f-f59b-4d5b-9d8c-0db8c47c9af5.png)

### Map Download

[kalahari_sanctuary.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9898706/kalahari_sanctuary.zip)

**Comment by calcastor** [comment]
added to pools in 405955dfe41819c29684c05aa80b885d6fcb47f9
