### ISSUE TITLE
[Update] Infection: Cinema Jungle Scenario

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#555]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

The same cosmetic changes were made to the hns version.
Various XML modifications, such as correctly deploying kits and renaming teams.
Invisible blocks have been removed and the problem of players climbing trees is solved via XML.

### XML

https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/b22a56320e9a55e2b530ce762738202c2de263c1/Infection_CinemaJungleScenario.xml

### Download Link

https://www.dropbox.com/s/6r5bw1nctis9uiq/Infection_%20Cinema%20Jungle%20Scenario.zip?dl=0

**Comment by Cazadorian** [comment]
Updated in d266ad5
