### ISSUE TITLE
[CTW/5v5] La Bataille de l'épée

### ISSUE THREAD

**Issue by Flamiix** [OvercastCommunity/CommunityMaps#559]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

La Bataille de l'épée

### Gamemode & Map Description

-CTW
-1 wool to cap for each team
-2 team
-5v5

### Team Sizes

5v5

### Screenshots

https://imgur.com/a/wjc2zlv

### XML

https://gist.github.com/zzuf-fer/9b689e069fc09f9baffc653dce25d840

### Map Image

![2022-11-08_22 28 04](https://user-images.githubusercontent.com/105971633/200679571-e761525f-3663-4d20-b350-b9e2af2d55e2.png)

### Map Download

https://mega.nz/file/S6JmgTDJ#rRWPQnWSGU_PXbE8H51gt79nG3PLd-ajuV01mr5VAIs

**Comment by Cazadorian** [comment]
Loaded in 3cfe2e0

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
