### ISSUE TITLE
[KotH/10v10] Rafiki

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#562]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Rafiki

### Gamemode & Map Description

KotH, 10v10

### Team Sizes

10v10

### Screenshots

https://imgur.com/a/g7QqM9o

### XML

https://gist.github.com/Samuel-Roach/ca7ce6d55f5fd8a93d947925cdcdf9b6

### Map Image

![](https://imgur.com/cFUY5Ps.png)

### Map Download

https://www.mediafire.com/file/0l9gv2bumi6lbar/Rafiki.zip/file

**Comment by eliminate123** [comment]
swag map

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
