### ISSUE TITLE
[Update] Blast Mining, V1.2.6

### ISSUE THREAD

**Issue by EpicPuppy613** [OvercastCommunity/CommunityMaps#563]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

- Actually updated the region files this time
- (it took 4 months for me to realize)

### XML

https://gist.github.com/EpicPuppy613/e517ee1f26c33d2ae310d1d115ec484c

### Download Link

https://github.com/EpicPuppy613/maps/raw/main/Blast%20Mining.zip

**Comment by Cazadorian** [comment]
Updated in 91751e0
