### ISSUE TITLE
[DTM/24v24] Mole Dream (by minuyo)

### ISSUE THREAD

**Issue by zzuf-fer** [OvercastCommunity/CommunityMaps#567]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Mole Dream

### Gamemode & Map Description

DTM map with 2 teams of 24 players each. Monument has a Beacon mode after 30 minutes.
The map also features a very detailed underground area, full of traps and items like potions hidden there.

This map was made by minuyo, just submitting it here for him.

### Team Sizes

2 teams of 24 players each

### Screenshots

https://imgur.com/a/pjeFEkE

### XML

https://github.com/zzuf-fer/zzuf/blob/main/mole_dream/map.xml

### Map Image

![map](https://user-images.githubusercontent.com/11651753/202010248-1a39713e-b58e-40b1-9c51-641958fd3910.png)

### Map Download

https://mega.nz/file/qq5T2Z7D#Cgbdvhd0aFjOF9QhkjsuGspXYpzPEdq3aPQeSiJe7Pw

Also available in zzuf's folder

**Comment by Cazadorian** [comment]
My main initial feedback on this map so far is that the amount of powerful loot scattered around the map needs to be heavily scaled back. Having the ability to craft full diamond and run around with a knockback 2 diamond axe, as well as strength 2 potions, when the initial spawn kit isn't even a full set of leather armour isn't going to end up playing too well. Having most of this hidden, especially in some cases literally buried in spots where you have to know it's there beforehand to find, is going to likely result in a lot of games having one person who knows the map in full diamond with strength pots kill farming while the rest of the players ultimately confused as to where they got those from.

I would also likely heavily increasing the amount of food in the spawn kit, or just completely disabling hunger all together as a mechanic on the map. Even with steak on a kill reward, you're potentially likely to run out of food if you're defending for long periods where you'll not be getting many kills and having to manage your food doesn't really add anything to the map.

**Comment by zzuf-fer** [comment]
Minuyo has updated the map with the changes you've previously discussed. Link has been updated.

**Comment by Cazadorian** [comment]
Map has been in the pool for a few months and seems fine, so closing this issue for now. Thanks for the submission.
