### ISSUE TITLE
[DTM/20v20] Total Beesness

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#570]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Total Beesness

### Gamemode & Map Description

Mid sized DTM map 

### Team Sizes

20v20

### Screenshots

https://imgur.com/a/E4N7A0W

### XML

https://gist.github.com/Samuel-Roach/0abe149df25d0dae020639c7725e0d37

### Map Image

![](https://imgur.com/iGEgcvk.png)

### Map Download

https://www.mediafire.com/file/39skqgdi7zg9edr/Total_Beesness.zip/file

**Comment by Samuel-Roach** [comment]
[UPDATE] https://gist.github.com/Samuel-Roach/0abe149df25d0dae020639c7725e0d37

- Increased height limit to 25
- Added feather falling 1 to boots
- Added efficiency 1 to stone pickaxe
- Added wood and leaves to item remove

**Comment by Cazadorian** [comment]
> [UPDATE] https://gist.github.com/Samuel-Roach/0abe149df25d0dae020639c7725e0d37
> 
> * Increased height limit to 25
> * Added feather falling 1 to boots
> * Added efficiency 1 to stone pickaxe
> * Added wood and leaves to item remove

Updated in 6da300c

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
