### ISSUE TITLE
[Update] Mega Cacti Terror, v1.2.0

### ISSUE THREAD

**Issue by mitchts** [OvercastCommunity/CommunityMaps#575]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

Replaces the dodgy filtered falling blocks mechanic with the newly merged [fill action](https://github.com/PGMDev/PGM/pull/1103) which makes removal of each layer controlled and not subject to blocks falling prematurely, which occurred occasionally when cacti was placed too close to the edge.

This update also takes advantage of variables and structures to randomly select between a square or circle arena format.

While the map isn't in this repo, I would like it moved from PrivateMaps to CommunityMaps please.

### XML

https://gist.github.com/mitchts/017f220a149c32e5f2e64a337134e8ca

### Download Link

https://drive.google.com/file/d/133tksz71FR8J96fIS6RuUnARdzQ7WoiG/view?usp=share_link

**Comment by mitchts** [comment]
Updated to version 1.2.1 per chats in Discord.

Download: https://drive.google.com/file/d/133tksz71FR8J96fIS6RuUnARdzQ7WoiG/view?usp=share_link
XML: https://gist.github.com/mitchts/017f220a149c32e5f2e64a337134e8ca

- Fixed (to the best of my knowledge) a layout sometimes not being placed before the match starts
- Readded the central snowball spawner
- Slowed the border removal increments
    - 5 second delay from 0:00 to 1:00
    - 4 second delay from 1:00 to 1:20 (previously 0:00 to 1:00)
    - 3 second delay from 1:20 to 1:40 
    - 2 second delay from 1:40 to 1:56 (previously 1:100 to 1:28)
    - 1 second delay from 1:56 to 2:00 (previously 1:28 to 1:35)
- Final border removal no longer makes the showdown island red sand

**Comment by Cazadorian** [comment]
Finally updated in [f4abf3a](https://github.com/OvercastCommunity/PublicMaps/commit/f4abf3af0e3b246069f61bd3a123ab5507cfd196) now that the server is compatible with the new changes. The map has also already been moved out of PrivateMaps and into PublicMaps, which seems more fitting due to this being a pre-existing map. If you specifically wish for it to instead be moved into CommunityMaps let me know.
