### ISSUE TITLE
[CTW/6v6v6v6] Daydream Mini

### ISSUE THREAD

**Issue by eliminate123** [OvercastCommunity/CommunityMaps#576]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Daydream Mini

### Gamemode & Map Description

4 team CTW. This map is a miniature version of Hillside Daydream. 

### Team Sizes

4 Teams 6v6v6v6

### Screenshots

https://imgur.com/a/KMeKYp2

### XML

https://gist.github.com/eliminate123/4359f5e46a361c9bafeaa555f98c124e

### Map Image

![map](https://user-images.githubusercontent.com/96848330/204153734-be4f57c5-c4f4-4db6-ac3c-279dbb0b153f.png)

### Map Download

[Daydream Mini.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10098950/Daydream.Mini.zip)

**Comment by Cazadorian** [comment]
Loaded in 752334c

**Comment by Cazadorian** [comment]
The Christmas version of this map was used in the recent tournament, and in pools afterwards for the past few weeks without issue, so I'm closing this issue as complete for now. Thank you for the submission.
