### ISSUE TITLE
[CTW/8v8v8v8] Timbered

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#583]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Timbered

### Gamemode & Map Description

CTW

### Team Sizes

8v8v8v8

### Screenshots

https://imgur.com/a/UHZYTv2

### XML

https://gist.github.com/Samuel-Roach/7c00736c65ee29fb9fb990071cbeddd9

### Map Image

![](https://imgur.com/3B4oc6s.png)

### Map Download

https://www.mediafire.com/file/jd5ac06w1i8asfq/Timbered.zip/file

**Comment by Samuel-Roach** [comment]
### Update 1.1.0

- Moved spawns further from wool rooms and removed one exit
- Modified spawn kit to include wood over glass
- Moved cobwebs up by 1 to prevent blocks being placed
- Updated comment in XML including wrong contributor name

XML : https://gist.github.com/Samuel-Roach/7c00736c65ee29fb9fb990071cbeddd9
Download : https://www.mediafire.com/file/r4ut58iiyrrcp08/Timbered.zip/file

**Comment by Cazadorian** [comment]
> ### Update 1.1.0
> * Moved spawns further from wool rooms and removed one exit
> * Modified spawn kit to include wood over glass
> * Moved cobwebs up by 1 to prevent blocks being placed
> * Updated comment in XML including wrong contributor name
> 
> XML : https://gist.github.com/Samuel-Roach/7c00736c65ee29fb9fb990071cbeddd9 Download : https://www.mediafire.com/file/r4ut58iiyrrcp08/Timbered.zip/file

Update loaded in 0a4a205

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month and seems fine, so closing this issue for now. Thanks for the submission.
