### ISSUE TITLE
[RAGE KOTH/24v24] Disc Wars III

### ISSUE THREAD

**Issue by MishM0sh1** [OvercastCommunity/CommunityMaps#584]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Disc Wars III

### Gamemode & Map Description

A 24v24 rage KOTH, utilizing jump-pads and speed boosters

### Team Sizes

2 teams of 24

### Screenshots

https://imgur.com/gallery/A2PJXzy

### XML

https://github.com/zzuf-fer/zzuf/blob/main/disc_wars_iii/map.xml

### Map Image

![Disc Wars III](https://user-images.githubusercontent.com/105904508/205536429-f560c1ca-e61b-4db2-8b1f-88a355bc6d82.png)

### Map Download

[disc_wars_iii.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10150260/disc_wars_iii.zip)

**Comment by MishM0sh1** [comment]
[disc_wars_iii (1).zip](https://github.com/OvercastCommunity/CommunityMaps/files/10150352/disc_wars_iii.1.zip)

^^^ updated zip file

**Comment by calcastor** [comment]
This has been cycled out of pools temporarily, but has worked fine in the time it is in. Some XML side changes have been internally suggested to make it play faster however. In particular we may decrease the points limit, as I set it somewhat higher than it maybe should be for a rage map when XML'ing the map. Let us know if this sounds like a good idea to you, but I will close this issue for now.
