### ISSUE TITLE
[CTW/12v12] Raceway

### ISSUE THREAD

**Issue by eliminate123** [OvercastCommunity/CommunityMaps#587]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Raceway

### Gamemode & Map Description

CTW 12v12 2 wools per team

### Team Sizes

2 Teams 12v12

### Screenshots

https://imgur.com/a/f8XHCb3

### XML

https://github.com/zzuf-fer/zzuf/blob/main/raceway/map.xml

### Map Image

![map](https://user-images.githubusercontent.com/96848330/206295556-c3b65f15-ec92-4782-b547-fa0ea8a96649.png)

### Map Download

[Raceway.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10179997/Raceway.zip)

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month and seems fine, so closing this issue for now. Thanks for the submission.
