### ISSUE TITLE
[Arcade/50] BlockGlitch 2: Electric Boogaloo

### ISSUE THREAD

**Issue by iam-pkb** [OvercastCommunity/CommunityMaps#589]
### Checklist

- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

BlockGlitch 2: Electric Boogaloo

### Gamemode & Map Description

A race game with blocks that disappear instantly. Players place blocks to get through obstacles.

### Team Sizes

50 players (FFA)

### Screenshots

https://imgur.com/a/8kJWtND

### XML

https://gist.github.com/XxPKBxX/d726f77e14003186908c19efa1b3b44e

### Map Image

![map](https://user-images.githubusercontent.com/29917385/206836302-487bf6b5-dbaf-4094-9a9a-ee648f961b98.png)

### Map Download

[blockglitch_2_electric_boogaloo.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10199366/blockglitch_2_electric_boogaloo.zip)

**Comment by calcastor** [comment]
ea2af1d41ebd30dd8e7fd433865619a5f8fcf47a
