### ISSUE TITLE
[DTM/16] Hobbit Hill

### ISSUE THREAD

**Issue by Kurbowurbo** [OvercastCommunity/CommunityMaps#599]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Hobbit hill

### Gamemode & Map Description

Hobbit hill is a normal Destroy the monument map themed around hobbits from the lord of the ring books. It's a red vs blue and 16 players per team. when players spawn, they spawn a a hobbit hole which leads out to the monument, mines and bridge. In the spawn area, there is a supply chest of building/defence materials. The mines is an area where players mine iron blocks for armour. The bridge is the defence archer place. the bridge servers a an area for players to fire arrows at incoming enemy players. Both of the teams have the same exact map replica so both teams are equal and one doesn't have an advantage. The  monument is guarded my rainbow sheep suggested by Ammzzy and PANxo. Both team will have to bridge over the void to the enemy's side and destroy the monument. the monument has stages. Games starts with obsidian, after 30 min, monument becomes beacon. After 45 min it becomes coal block and after 1hr 15min it changes to gold block.

### Team Sizes

16 players on both red and blue teams

### Screenshots

https://drive.google.com/drive/u/0/folders/1-lx0fSvrcdDXB1xDGDli_aSrGwOGl4ih

### XML

https://gist.github.com/Kurbowurbo/931e0086ed0a74b9236309b631ef1c93

### Map Image

![map](https://user-images.githubusercontent.com/121776347/210189354-8b5c079f-766d-481d-9a45-a9d6a335c746.png)

### Map Download

https://drive.google.com/open?id=1ftUTXr8AhtS-LeuLqIBdsrsLagSpbkRN&usp=drive_copy

**Comment by technodono** [comment]
**If you do update the map I have some building tips/suggestions that could elevate the map a bit:**

- The stone mountains need some sort of variation. Perhaps doing a #fractal pattern with equal parts stone, andesite, gravel & cobblestone will achieve some texture
- The boulders on the ground also need variation, I'd just use stone, cyan terracotta, cobble, mossy cobble to give the effect of weathered boulders (you can pick any combination)
- For next time more custom trees please :)
- Maybe add snow caps to the mountains? **(Big maybe)**

Anyways you may/may not find these useful. The map layout wise looks solid and is built actually pretty well for what I presume is your 1st submission. Enjoy the feedback!

**Comment by Cazadorian** [comment]
> **If you do update the map I have some building tips/suggestions that could elevate the map a bit:**
> 
> * The stone mountains need some sort of variation. Perhaps doing a #fractal pattern with equal parts stone, andesite, gravel & cobblestone will achieve some texture
> * The boulders on the ground also need variation, I'd just use stone, cyan terracotta, cobble, mossy cobble to give the effect of weathered boulders (you can pick any combination)
> * For next time more custom trees please :)
> * Maybe add snow caps to the mountains? **(Big maybe)**
> 
> Anyways you may/may not find these useful. The map layout wise looks solid and is built actually pretty well for what I presume is your 1st submission. Enjoy the feedback!

I think most of these changes aesthetically would benefit the map. I believe the map also likely needs to have the sides and frontlines smoothed out a lot more. At the moment they look very rough due to essentially just being WE boulder brush placements without further editing, and the roughness of the frontlines is likely going to have a negative impact on gameplay with all the random bits jutting in and out. I'd also smooth the back sides of the map out as well so people can't just run around behind the map on the bits that jut out still.

**Comment by TheRealPear** [comment]
Seeing that quite some time has passed since the last response and the fact this map has been in the pool since March 2023, I will go ahead and close this ticket. Thank you for your submission!
