### ISSUE TITLE
[CTF/16v16] Battlefloat

### ISSUE THREAD

**Issue by Pe241** [OvercastCommunity/CommunityMaps#60]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Battlefloat

## Gamemode & Map Description  
Theme: Prepare blocks yourself and build skybridge to cross the islands.
This is a 3 flags CTF. Players get cobblestone from generator to build skybridge, and capture 3 teamcolor flags.
They can use an ender pearl and TNT(to break enemy's bridge/get every 3 kill-streak).
Make strong teamwork and reach to the goal!

## Team Sizes
~~10v10 (for nano)~~ →16v16(for micro)

## Screenshots
[Imgur](https://imgur.com/a/Mub7LFm)

# XML
[Gist](https://gist.github.com/Pe241/b9312d697dcc67d13e7da2eebce51356)

# Map Image
![map](https://user-images.githubusercontent.com/18105767/96248686-e55e7680-0fe6-11eb-8e3a-5339c0b6b1b1.png)

# Download Link
[v2.0](https://drive.google.com/file/d/1kOgCrrYmRpMvghnwqH7-5G-LA-AJGJdp/view?usp=sharing)
v1.x is tourney edition that I gave up updating.

**Comment by master00ofdsiware** [comment]
Added for testing.

**Comment by Pe241** [comment]
What should I change in the next update?

**Comment by master00ofdsiware** [comment]
This map still needs a lot of testing; feel free to ask a moderator to set it when you are online and the player count is appropriate.

For now, please disable the usage of ender pearls by flag carriers. You may find the carrying-flag filter helpful:
`<carrying-flag>flag_id</carrying-flag>`

**Comment by Pe241** [comment]
@master00ofdsiware 

> please disable the usage of ender pearls by flag carriers

How to do it? I tried filter & apply use, but not work...

**Comment by CrazyisCreeps** [comment]
Mining for cobblestone is a little tedious, and I really like what you did at the flag spawns with the cobblestone spawners! Maybe the cobblestone generators can be replaced with spawners, to allow for people to get blocks without the need to mine it out?

As mentioned before, ender pearls need to be disabled for flag carriers. 

The other minor thing too, it appears that when you pick up a flag you're given a bow? Add a filter that checks to see if the person already has a bow before giving one, as capping multiple flags stacks up the bows.

**Comment by Pe241** [comment]
> Mining for cobblestone is a little tedious, and I really like what you did at the flag spawns with the cobblestone spawners! Maybe the cobblestone generators can be replaced with spawners, to allow for people to get blocks without the need to mine it out?

Ok, I'm going to add cobblestones (about 32?) to spawn kit. However, the cobblestone generator is a feature of this map, so I don't wanna remove even if it's a tedious. Besides, changing to a spawner would make the landscape lonely, and staying would give us a monopoly.

> As mentioned before, ender pearls need to be disabled for flag carriers.

How to do it? Need I remove ender pearls from spawn kit?

> The other minor thing too, it appears that when you pick up a flag you're given a bow? Add a filter that checks to see if the person already has a bow before giving one, as capping multiple flags stacks up the bows.

Ok, I'm going to add to toolrepair.

**Comment by master00ofdsiware** [comment]
Fun map, I've added it to the map pools.

**Comment by CrazyisCreeps** [comment]
Going to keep the map around in the repo, so it can be set, but after some time in the rots, we've found the map to be stale and not as much fun as we would have hoped. A lot of the gameplay comes down to mining cobblestone to be able to bridge, and there's little engagement with enemy players. It's a unique map, so we definitely want to keep it around for the occasional set next.
