### ISSUE TITLE
[Rage FFA/38] Andy's Room

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#602]
### Checklist

- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [x] I have created an XML file.
- [x] I have created a map image.
- [x] I have uploaded the map zip file to a file sharing service.
- [x] The map has been tested locally to make sure it works.

### Map Name

Andy's Room

### Gamemode & Map Description

Rage FFA

### Team Sizes

38

### XML

XML down in Map Download

### Map Image

![2023-01-05_21 30 39](https://user-images.githubusercontent.com/97280598/210879391-31086f61-f827-4456-ba70-5be74a0be905.png)

### Map Download

[andys_room.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10355657/andys_room.zip)
Download and XML

**Comment by mariogoaty** [comment]
first play it when I'm online tomorrow 🍡

**Comment by Strangeys** [comment]
If you continue to message every staff member possible to load this map, we will just not load it. A bunch of other players submit map issues on here and wait patiently, even our Builders. If you can't wait and keep harassing our staff team, we will not load your map and potentially any future maps.

**Comment by mariogoaty** [comment]
wtf chill on baby i just want to be on when it gets played 🥇

**Comment by EpicPuppy613** [comment]
> wtf chill on baby i just want to be on when it gets played 🥇

Even after it’s loaded it won’t be in any pools, so you won’t be able to play it on OCC

**Comment by oafMH** [comment]
epic puppy 613 GOAT!!!! 🔥 🔥 🔥

**Comment by mariogoaty** [comment]
> 

hello mr epicpoop 
you can set the map :D

**Comment by calcastor** [comment]
This is loaded and I don't see any reason to keep the issue open, closing
