### ISSUE TITLE
[CTW/15v15] Simplicity CTW

### ISSUE THREAD

**Issue by Jussssst** [OvercastCommunity/CommunityMaps#607]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Symplicity CTW

### Gamemode & Map Description

Small and simple CTW map for a playercount of 30. 

### Team Sizes

15 players per team 

### Screenshots

https://imgur.com/a/xsLM4Ys

### XML

https://gist.github.com/Cazadorian/8a59b359a8339656442c5edbb7575d97

### Map Image

![Simplicity CTW](https://user-images.githubusercontent.com/69433766/211639857-d53a45fa-e5e1-437f-8a5f-7e9ffda3140a.png)

### Map Download

https://www.dropbox.com/s/5epdiug0p8o1gco/Simplicity%20CTW.zip?dl=0

**Comment by TheRealPear** [comment]
Seeing that this map has been in the pool since March 2023 with without any issue, I will go ahead and close this ticket. Thank you for your submission!
