### ISSUE TITLE
[Update] Andy's Room

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#608]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

added blocks reduced double jump a bit and timer 8 minutes instead of 10

### XML

download link

### Download Link

[andys_room (3).zip](https://github.com/OvercastCommunity/CommunityMaps/files/10405004/andys_room.3.zip)

**Comment by zzuf-fer** [comment]
Updated in [85de520](https://github.com/OvercastCommunity/CommunityMaps/commit/85de52099e25f723ce07b997f4ccd5b08052912a)
