### ISSUE TITLE
[CTW/16v16] Greenhill

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastCommunity/CommunityMaps#609]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Greenhill

### Gamemode & Map Description

Capture both of the enemy team's wools to win.

Not sure exactly about the team sizes so feel free to adjust. Kinda second guessing myself on everything as I make my first real map here. So much easier to just prune a survival map and make it a rage ffa :wink:

### Team Sizes

16v16

### Screenshots

https://imgur.com/a/WG6ZirC

### XML

https://gist.github.com/CrazyisCreeps/8cf9fac6b3e2b926c453e38e29991fef

### Map Image

![2023-01-13_04 52 09](https://user-images.githubusercontent.com/7937351/212293233-f9a82a1e-e08d-4af2-bca7-dcc3614c9690.png)

### Map Download
[greenhill.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10416707/greenhill.zip)

**Comment by CrazyisCreeps** [comment]
Actually updated it to a 16v16, felt it was a little too big for a 12v12

**Comment by CrazyisCreeps** [comment]
[greenhill but bedrock is lower.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10608350/greenhill.but.bedrock.is.lower.zip)
No more underbridging

**Comment by Cazadorian** [comment]
> [greenhill but bedrock is lower.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10608350/greenhill.but.bedrock.is.lower.zip) No more underbridging

Updated in d8145ff

**Comment by CrazyisCreeps** [comment]
> > [greenhill but bedrock is lower.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10608350/greenhill.but.bedrock.is.lower.zip) No more underbridging
> 
> Updated in [d8145ff](https://github.com/OvercastCommunity/CommunityMaps/commit/d8145ff5943b3dfedc7f4d3e1811667e32d8b770)

Uh, isn't that just a version bump?

**Comment by Cazadorian** [comment]
> > > [greenhill but bedrock is lower.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10608350/greenhill.but.bedrock.is.lower.zip) No more underbridging
> > 
> > 
> > Updated in [d8145ff](https://github.com/OvercastCommunity/CommunityMaps/commit/d8145ff5943b3dfedc7f4d3e1811667e32d8b770)
> 
> Uh, isn't that just a version bump?

Wasn't sure at the time if this update was loaded in the initial commit or not, so just committed it anyway to make sure.
