### ISSUE TITLE
[TDM/15v15] Miner Sixty Niner

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#61]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Miner Sixty Niner

## Gamemode & Map Description  
The map's gamemode is TDM, but a very modified form based around the redeemables module. 

Unlike regular TDM where points are scored upon kill, on this map a golden nugget is awarded for every kill. There is then a scorebox in middle which opens every minute and stays open for 30 seconds before reclosing again for another minute. Points are gained on this map by jumping into the scorebox while carrying golden nuggets. Players who die with golden nuggets in their inventory drop all of them on death allowing others to "steal" the points they would have got for them if they then score. The match lasts 12 minutes with the scorebox opening and closing 8 times during this. The team with the highest score when time is up wins.

## Team Sizes
2 teams, 15v15

## Screenshots
[Screenshots](https://imgur.com/a/wPphEJu)

# XML
[XML](https://pastebin.com/hSTuH9vs)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/96321157-4fd5dd80-100c-11eb-9f6d-a054a87d64a0.png)

# Download Link
[Miner Sixty Niner V1.02](https://github.com/OvercastCommunity/CommunityMaps/files/5449367/Miner.Sixty.Niner.V1.02.zip)

**Comment by CoWinkKeyDinkInc** [comment]
You posted the old XML, this is the latest one that had updates on golden apples

https://pastebin.com/8umAUfb6

**Comment by Cazadorian** [comment]
> You posted the old XML, this is the latest one that had updates on golden apples
> 
> https://pastebin.com/8umAUfb6

Both download and XML link should be fixed to include the updated XML.

**Comment by master00ofdsiware** [comment]
Added for testing.

**Comment by CoWinkKeyDinkInc** [comment]
https://pastebin.com/hSTuH9vs

New XML that simply disables hunger, I forgot to add that in at the end.

**Comment by master00ofdsiware** [comment]
Interesting concept, but still needs some work.

- Players can't find the scorebox. Add a beacon through it (maybe make it yellow), and place signs at ground level saying that the scorebox is above.

- The area before the scorebox platform is too much of a chokepoint. Make the dynamic platforms appear on the other side of the scorebox as well.

- In the XML, remove the word "Team" from the team names.

**Comment by CrazyisCreeps** [comment]
Overall it's a very impressive map. You've managed to create this entirely new take on TDM and scorebox gamemode, and it's very fun to play. I hope it inspires more people to make maps like this.

My plan is to add it into the pools and really be able to see how it responds to constant community interaction with it. Great job with the map, thanks for submitting it!
