### ISSUE TITLE
[CTW/16v16] Paddo's

### ISSUE THREAD

**Issue by samschaap** [OvercastCommunity/CommunityMaps#610]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Paddo's

### Gamemode & Map Description

CTW map with a futuristic/mushroom theme. There are 3 lanes to bridge to the other team's side, two outside and two in the middle which are connected. The playercount is 16v16 but it might be changed depending on how it plays.

### Team Sizes

2 teams, 16v16

### Screenshots

https://imgur.com/a/2VuHYip

### XML

https://gist.github.com/samschaap/fdea8a91eb4bec63d582490c37d89598

### Map Image

![map](https://user-images.githubusercontent.com/1810738/212409757-849a9047-7294-4907-b125-8a9123aad9ea.png)

### Map Download

[paddos.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10415014/paddos.zip)

**Comment by TheRealPear** [comment]
Seeing that this map has been in the pool for a month without any issue, I will go ahead and close this ticket. Thank you for your submission!
