### ISSUE TITLE
[CTW/14v14] Kerskyn

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#611]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Kerskyn

### Gamemode & Map Description

CTW 14v14 small map with 2 wools

### Team Sizes

14v14

### Screenshots

https://imgur.com/a/CcfFmie

### XML

https://gist.github.com/Samuel-Roach/4d86b51f3b307511e748539fc7f9b77d

### Map Image

![map](https://user-images.githubusercontent.com/44307075/212542240-d2e76978-1e90-41cc-82bd-9058298200bb.png)

### Map Download

https://www.mediafire.com/file/1bhxf5au44e9fn3/Kerskyn.zip/file

**Comment by oafMH** [comment]
i like it

**Comment by Cazadorian** [comment]
> i like it

![cover1](https://user-images.githubusercontent.com/73002842/212542377-c59e9303-a1c9-4094-ae16-154c401dd60d.jpg)

**Comment by oafMH** [comment]
thats a funny one
