### ISSUE TITLE
[DTM/24v24] Deepwood

### ISSUE THREAD

**Issue by Wyviryn** [OvercastCommunity/CommunityMaps#620]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Deepwood

### Gamemode & Map Description

Deepwood is a DTM map set among reasonably dense tree cover. Each team has to defend two monuments in an uneven and nature-inspired setting, with unusual buildings and trees nestled amongst each other. The aim of Deepwood is to provide a somewhat nostalgic map structure in a new and unusual setting, as well as a different and more strategic round of gameplay. Players have the usual defense-or-offense choice, but will have to deal with an irregular setting.

### Team Sizes

2 Teams, 24 Each

### Screenshots

https://imgur.com/a/hHO9o9m

### XML

https://github.com/zzuf-fer/zzuf/blob/main/deepwood/map.xml

### Map Image

![Deepwood Image](https://user-images.githubusercontent.com/95257658/214687520-246a0c75-aaed-4778-bdf6-d18a6ff2a2f7.png)

### Map Download

[deepwood.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10503739/deepwood.zip)

**Comment by zzuf-fer** [comment]
Loaded in 50c7a4658375ca96fe553fbab322d1a7769d7d4c

**Comment by TheRealPear** [comment]
Seeing that this map has been in the pool for a month and played a handful times without any issue, I will go ahead and close this ticket. Feel free to open a pull request if you would like to make an update. Thank you for your submission!
