### ISSUE TITLE
[Blitz/TDM/15v15] Red Core Blue Core

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastCommunity/CommunityMaps#63]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Red Core Blue Core

## Gamemode & Map Description  
A Blitz DTC map that has both cores merged as "one", in the center of the map. I originally got this idea from PepsiDog, who made a map similar to this on the forums, but it was never loaded on and I don't think I could find a copy of it anywhere. If anyone wants to help greatly improve the aesthetics that would be really nice. It does run into issues where it thinks that the other core leaks from unknown forces at the same time as the real core leakage happens, but from the match conditions it doesn't seem to falsely declare a winner so that's alright in the end. Ten minutes into the match, a "leaf core" mode starts.

## Team Sizes
The team sizes are 15v15, though it might have to be smaller later on.

## Screenshots
![2020-10-19_22 38 05](https://user-images.githubusercontent.com/7586568/96541166-a76a8800-125c-11eb-8879-b97fa6489b5a.png)
![2020-10-19_22 38 18](https://user-images.githubusercontent.com/7586568/96541169-a89bb500-125c-11eb-9a4c-0d2e0264d4a3.png)
![2020-10-19_22 38 38](https://user-images.githubusercontent.com/7586568/96541171-a9cce200-125c-11eb-8f9d-3ca1100e6afe.png)

# XML
https://gist.github.com/CoWinkKeyDinkInc/a01f00c47696de02759ff4a5fc8bc329

# Map Image
![map](https://user-images.githubusercontent.com/7586568/96646899-0de9b780-12ea-11eb-8fe9-948819ed1cd2.png)

# Download Link
[redcorebluecore.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5406328/redcorebluecore.zip)

**Comment by master00ofdsiware** [comment]
I recommend either trying a bit harder with the aesthetics, or getting someone to help you with them. In its current state, the map is quite bland and uninteresting to look at.

**Comment by technodono** [comment]
@CoWinkKeyDinkInc even just adding things like gravel/stone paths or bushes will help improve the look... It just lacks depth and doesn't quite fit the forest village theme you are going for. I you added some cabins maybe or trees that might help fix what @master00ofdsiware... Look at the Fenland map cause that might be a good place to start decorating based on

**Comment by CoWinkKeyDinkInc** [comment]
Yeah pretty much the only sense I know of aesthetics is breaking up the repeating textures lol. I'll try and fix it around a bit more, and update the core

**Comment by CoWinkKeyDinkInc** [comment]
If anyone wants to do a real collaboration with me with this idea (or just take it) that would be great, my sense of aesthetics sucks and I don't see how I can improve this map. Also PGM is kinda buggy with tracking leaking lava leaks of cores this close to each other, so yeah.

**Comment by technodono** [comment]
@CoWinkKeyDinkInc I maight be up for the collab.. i'd be happy to beautify it for you and then you do the rest... you can claim it as your work or credit me

**Comment by CoWinkKeyDinkInc** [comment]
@technodono sounds good, I was thinking of redoing it entirely and making it bigger

**Comment by technodono** [comment]
> 
> 
> @technodono sounds good, I was thinking of redoing it entirely and making it bigger

Yea be warned tho... I only do futuristic stuff :)
