### ISSUE TITLE
[DTM/8v8] Little Roses

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#636]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Little Roses

### Gamemode & Map Description

Destroy the monument of the enemy while you explore the garden around you.

### Team Sizes

8v8

### Screenshots

https://imgur.com/a/6rarX0Q

### XML

XML on Builders' Dropbox https://www.dropbox.com/s/r1rr68bg2xptual/map.xml?dl=0

### Map Image

![2023-01-30_03 49 52](https://user-images.githubusercontent.com/99238656/215624936-f8b1acbd-28c6-4eaa-883b-05802388e868.png)
![2023-01-30_01 29 42](https://user-images.githubusercontent.com/99238656/215624966-2e1b8712-5f87-4736-a056-6a5f2678f84c.png)

### Map Download

Map on Builders' Dropbox https://www.dropbox.com/scl/fo/wxz15ujn10jxgs8vu8oja/h?dl=0&rlkey=f5p6goec5t8eghedy0pjinvxa

**Comment by TheRealPear** [comment]
Seeing that this map has been in the pool for a month and played without any issue, I will go ahead and close this ticket. Feel free to open a pull request if you would like to make an update. Thank you for your submission!
