### ISSUE TITLE
[Update] Ulcinj v1.1.1

### ISSUE THREAD

**Issue by jacketjack** [OvercastCommunity/CommunityMaps#646]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Ulcinj v1.1.1
- Mid water is no longer glass
- Birds are no longer broken
- Added ink sack ("mussel") spawners to replace buggy armorstands
- 4 mussels can be crafted into a golden apple

### XML

https://gist.github.com/jacketjack/d6a27872a1a5fb1e7c946e3b6bb72d1c

### Download Link

[Ulcinj.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10688509/Ulcinj.zip)

**Comment by RuedigerLP** [comment]
https://github.com/OvercastCommunity/CommunityMaps/commit/4a04279ae53ed3dd439848e85aaabbe9698106eb
