### ISSUE TITLE
[DTM/28v28] Parabola II

### ISSUE THREAD

**Issue by Wyviryn** [OvercastCommunity/CommunityMaps#649]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Parabola II

### Gamemode & Map Description

Parabola II, much like its predecessor, is a DTM based around two spherical monuments constructed out of end stone. These monuments contain one obsidian block at their centers. While not majorly different in terms of structure from the first Parabola, Parabola II aims to be an improvement across the board over its predecessor. There are multiple ways of reaching the monuments, but as with the first map, they must ultimately be attacked from the platform they're above or higher. A lot of options exist for players who want to play in different ways, be it direct attacks, sneaking around, or doing nothing related to the objective.

### Team Sizes

2 Teams, 28 Each

### Screenshots

https://imgur.com/a/jOWkLzw

### XML

https://github.com/zzuf-fer/zzuf/blob/main/parabola_ii/map.xml

### Map Image

![map](https://user-images.githubusercontent.com/95257658/218239514-90b05ced-62ec-4604-9617-c089eae48a43.png)

### Map Download

[Parabola II.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10712602/Parabola.II.zip)

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since July 2023 without any major issues. Thank you for your submission!
