### ISSUE TITLE
[CTW/24v24] Ad Astra

### ISSUE THREAD

**Issue by Dawthon** [OvercastCommunity/CommunityMaps#651]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Ad Astra

### Gamemode & Map Description

Gamemode: CTW

Description: A heavily guarded fortress contains prized wool. Defy all odds, break through the defenses, and capture the wool!

### Team Sizes

2 teams, 24 players each

### Screenshots

https://imgur.com/gallery/LFYNl9o

### XML

https://github.com/zzuf-fer/zzuf/blob/main/ad_astra/map.xml

### Map Image

![image](https://user-images.githubusercontent.com/125154667/218284186-29d9fcfc-cdb8-4f59-9123-7fa8873f85a6.png)

### Map Download

[Ad Astra.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10854636/Ad.Astra.zip)

**Comment by Dawthon** [comment]
moved cobwebs in 4 places

**Comment by TheRealPear** [comment]
Been re-added to rotation and I don't think there's any further feedback for now. Thanks for your submission
