### ISSUE TITLE
[Blitz/2 Teams] Charge: Lightning Cable Edition

### ISSUE THREAD

**Issue by iam-pkb** [OvercastCommunity/CommunityMaps#655]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Charge: Lightning Cable Edition

### Gamemode & Map Description

Variation version of existing map "Charge." It uses Blitz and Rage. Players spawn on an iPhone and fight 'til all their enemies get eliminated.

### Team Sizes

1976vs1976 (2 Teams)

### Screenshots

https://imgur.com/a/XqqBLw0

### XML

https://gist.github.com/iam-pkb/6eea54fe89a491c13a9e6e41519a693a

### Map Image

![map](https://user-images.githubusercontent.com/29917385/219595935-2059c10c-5f5b-4da6-aed8-ec62c4cd61d8.png)

### Map Download

[Charge_ Lightning Cable Edition.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10766733/Charge_.Lightning.Cable.Edition.zip)

**Comment by technodono** [comment]
That's an iphone alright...

**Comment by iam-pkb** [comment]
Updated XML. Includes some clean-ups.

**Comment by TheRealPear** [comment]
Hello, thank you for your submission! My apologies for the five-month wait (as this ticket was submitted a few days before I joined the mapdev team). After a brief review with other map developers, unfortunately, we've concluded that this map does not meet OCC's quality standards. Once again, I apologize if this was not the news you were expecting.

However, I've gone ahead and fixed the map XML file for you. I liked the map's theme, but it is very small when compared to other Charge maps. I would like to encourage you to try and improve the map so we can reconsider it for submission. Don't hesitate to reach out in #mapmaking channel if you would like help.
<details><summary>Fixed XML</summary>

```xml
<map proto="1.4.2" game="Charging...">
<name>Charge: Lightning Cable Edition</name>
<version>1.0.0</version>
<objective>Eliminate the enemy team as quick as possible.</objective>
<created>2023-02-16</created>
<phase>development</phase>
<gamemode>arcade</gamemode>
<gamemode>blitz</gamemode>
<gamemode>rage</gamemode>
<authors>
  <author uuid="ca25df12-cc0b-4812-a85b-7aa134561f88" contribution="Map idea, XML, Building" /> <!-- _pkb -->
  <author>Tim Cook</author>
  <author>Steve Jobs</author>
</authors>
<contributors>
  <contributor uuid="f2efb814-9e02-4d17-bdf5-8ed449f9df77" contribution="Making Apple logo" /> <!-- Alexander_ -->
  <contributor uuid="59655bfd-1fda-4e15-b6f7-eb6b6f84b406" contribution="Help with idea" /> <!-- Digitalight -->
</contributors>
<world>
  <timeset>13000</timeset>
  <timelock>on</timelock>
</world>
<rules>
  <rule>Kill the enemies.</rule>
</rules>
<broadcasts>
  <alert after="2s">This is a rage map. You kill the enemy instantly once you hit them.</alert>
</broadcasts>
<teams>
  <team id="rose-gold" color="light purple" max="1976">Rose Gold</team>
  <team id="sierra-blue" color="blue" max="1976">Sierra Blue</team>
</teams>
<blitz>
  <lives>1</lives>
</blitz>
<time>9m</time>
<hunger>
  <depletion>off</depletion>
</hunger>
<kits>
  <kit id="spawn">
    <effect duration="oo" amplifier="1">night_vision</effect>
  </kit>
  <kit id="players" parents="spawn">
    <game-mode>adventure</game-mode>
    <effect duration="oo" amplifier="255">strength</effect>
  </kit>
</kits>
<spawns>
  <default kit="spawn">
    <regions yaw="-90">
      <block>1.5,32,5.5</block>
    </regions>
  </default>
  <spawn team="rose-gold" spread="true" kit="players">
    <regions yaw="90">
      <cuboid min="30,30,12" max="25,30,1" />
    </regions>
  </spawn>
  <spawn team="sierra-blue" spread="true" kit="players">
    <regions yaw="-90">
      <cuboid min="13,30,1" max="8,30,12" />
    </regions>
  </spawn>
</spawns>
<regions>
  <apply block="never" use="never" />
</regions>
</map>
```

</details>
