### ISSUE TITLE
[Update] Transit v1.2.1 + Transit: Halloween Edition v1.1.1

### ISSUE THREAD

**Issue by lkfjimmy** [OvercastCommunity/CommunityMaps#657]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

Transit v1.2.1 + Transit: Halloween Edition v1.1.1
(XML update only)

- Upgraded grenade to smoke bomb (2s blindness II) and slightly buffed its power (1.5 to 1.6)
- Adjusted the chance of getting jump boost potion (10% to 20%)
- Reduce Cobwebs in Guards kit
- Shorter spawn protection time

### XML

https://gist.github.com/lkfjimmy/ae5aeadea9fd70bcac742dc9cda4aa8f
https://gist.github.com/lkfjimmy/6994642e7c4495aa7484d64d98210649

### Download Link

Transit v1.2.1
[Transit.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10781467/Transit.zip)

Transit: Halloween Edition v1.1.1
[Transit.HE.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10781468/Transit.HE.zip)

**Comment by Cazadorian** [comment]
Updated in abc9228
