### ISSUE TITLE
[KotH/16vs16] War for Iacon

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#661]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

War for Iacon

### Gamemode & Map Description

A simple koth map inspire in transformers animated serie 1984

### Team Sizes

16vs16

### Screenshots

https://imgur.com/gallery/KYimmAs

### XML

https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/0e444ed94ee748a4a54cb5203dccc745a5696889/War%20for%20Iacon.xml

### Map Image

![2023-02-19_14 27 46](https://user-images.githubusercontent.com/82010545/220246185-13fc2a8c-8b9d-44d5-9a52-54e8db3feb0b.png)

### Map Download

https://www.dropbox.com/s/yfc8ztv9zxgput4/War%20for%20Iacon.zip?dl=0

**Comment by JosueSaenzLacayo-UCR** [comment]
Hello. After testing this map, I noticed that the progress display region changes every terracotta block. I thought I would just change the white terracotta, but I was wrong, so I decide to change those regions in the XML to make them smaller, sorry for the inconvenience, here is the link. 
https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/99ddc4038edba8b0922bbed8441d76500b8c7ad1/War%20for%20Iacon.xml

**Comment by Cazadorian** [comment]
> Hello. After testing this map, I noticed that the progress display region changes every terracotta block. I thought I would just change the white terracotta, but I was wrong, so I decide to change those regions in the XML to make them smaller, sorry for the inconvenience, here is the link. https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/99ddc4038edba8b0922bbed8441d76500b8c7ad1/War%20for%20Iacon.xml

It's possible to filter which blocks the progress display and capture region changes using visual-materials. It might make more sense to filter it so only white terracotta is changed instead of shrinking the region.
