### ISSUE TITLE
[Arcade/64] Mega Cacti Terror (Redux)

### ISSUE THREAD

**Issue by mitchts** [OvercastCommunity/CommunityMaps#664]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Mega Cacti Terror

### Gamemode & Map Description

This is intended as a direct replacement to the Mega Cacti Terror version under PublicMaps.

This improves on both v1.1.0 and the reverted v1.2.0 versions in how it removes each layer to shrink the arena. This version takes advantage of fill triggers to cause each row of blocks to fall. This has the benefit of blocks not falling prematurely sometimes seen in v1.1.0 while also retaining the falling block effect, something that v1.2.0 did not do.

Besides that, the map functions identical to the older versions with a facelift to appear more aligned with the theming of Cacti Terror and Water Drop: Cacti Terror.

This version only uses a sqaure arena. The circle isn't coming back as it was too difficult to implement while retaining the falling block effect.

### Team Sizes

64, FFA

### Screenshots

https://imgur.com/a/YVyozXR

### XML

https://gist.github.com/mitchts/dbba31710c6a848e6af8750a40a0e9a4

### Map Image

![map](https://user-images.githubusercontent.com/6386297/221397140-dfedb6ed-b545-439a-8599-6cfeca21ab5e.png)

### Map Download

[mega_cacti_terror.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10833197/mega_cacti_terror.zip)

**Comment by mitchts** [comment]
[mega_cacti_terror_v2.0.2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10952390/mega_cacti_terror_v2.0.2.zip)

**Comment by mitchts** [comment]
[mega_cacti_terror_v2.0.3.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10952738/mega_cacti_terror_v2.0.3.zip)
Removes dead weight and halves the size of the XML for the same thing. Thanks Pablete.

**Comment by Cazadorian** [comment]
Loaded in [5420862](https://github.com/OvercastCommunity/PublicMaps/commit/54208620838a054d2789363d37171e4855a21463). I'll keep this issue open for now just in case there's any further issues with the map.

**Comment by mitchts** [comment]
I'd say this is okay to close now.
