### ISSUE TITLE
[DTM/6v6] Home by the Sea

### ISSUE THREAD

**Issue by samschaap** [OvercastCommunity/CommunityMaps#669]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Home by the Sea

### Gamemode & Map Description

A DTM map for the smaller player counts during the day, the map has a coast/beach town theme and the players spawn in the hotel.

### Team Sizes

2 teams, 6v6

### Screenshots

https://imgur.com/a/bUhPL3Y

### XML

https://gist.github.com/samschaap/d10278f5eac76d112dd3f3a61de7a086

### Map Image

![map](https://user-images.githubusercontent.com/1810738/222153755-bc1ee708-c206-4f5d-89e4-6b56a1290992.png)

### Map Download

[home_by_the_sea.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10934275/home_by_the_sea.zip)

**Update 2023-03-09:** Added more items to itemremove and change to 6v6

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since July 2023 without any major issues. Thank you for your submission!
