### ISSUE TITLE
[Arcade/100v3] Do Not Press The Button For Two Minutes

### ISSUE THREAD

**Issue by Dawthon** [OvercastCommunity/CommunityMaps#680]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Do Not Press The Button For Two Minutes

### Gamemode & Map Description

Arcade

Do Not Press The Button For Two Minutes

100 Subjects spawn into an island where to win, they cannot push a button (break an endstone monument) for two minutes. If they do, they lose and the 3 Researchers who are watching from above win. If the Subjects can keep themselves from pressing the button after the 2 minute time limit, they win.

### Team Sizes

2 teams, 100 Subjects, 3 Researchers

### Screenshots

https://imgur.com/gallery/5jCAMVH

### XML

https://gist.github.com/Dawthon/d2ee05ad88fe17c06171156c9af63225

### Map Image

![do not press button image](https://user-images.githubusercontent.com/125154667/224570222-8497fa7c-a517-4fb4-9d33-59197961493a.png)

### Map Download

[Do Not Press The Button For Two Minutes.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10951905/Do.Not.Press.The.Button.For.Two.Minutes.zip)

**Comment by calcastor** [comment]
Thank you for submitting, interesting concept for an arcade map. Loaded and works, so I'm closing this issue.
