### ISSUE TITLE
[Rage CTF/16v16] Courtyard Classic

### ISSUE THREAD

**Issue by Dawthon** [OvercastCommunity/CommunityMaps#682]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Courtyard Classic

### Gamemode & Map Description

Rage CTF 

Capture the flags

In the Courtyard Classic

With your friends

Rage Mode

### Team Sizes

2 teams, 16 players each

### Screenshots

https://imgur.com/gallery/UuuvAmV

### XML

https://gist.github.com/Dawthon/559f12ff753f37da564cef98dbfb8640

### Map Image

![courtyardclassic img](https://user-images.githubusercontent.com/125154667/225724809-91dc8d90-60bf-4f25-a1f0-ab27736c86df.png)

### Map Download

[courtyard_classic.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11042972/courtyard_classic.zip)

**Comment by Dawthon** [comment]
[Courtyard Classic (2).zip](https://github.com/OvercastCommunity/CommunityMaps/files/11142595/Courtyard.Classic.2.zip)

**Comment by Dawthon** [comment]
[Courtyard Classic (2).zip](https://github.com/OvercastCommunity/CommunityMaps/files/11142599/Courtyard.Classic.2.zip)

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since July 2023 without any major issues. Thank you for your submission!
