### ISSUE TITLE
[Bridge Scorebox/5v5] Chernot

### ISSUE THREAD

**Issue by vanderm135** [OvercastCommunity/CommunityMaps#684]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [ ] The map has been tested locally to make sure it works.

### Map Name

Chernot

### Gamemode & Map Description

Bridge 5v5

Cross a 1 wide bridge and score 5 goals in order to win

### Team Sizes

5v5

### Screenshots

https://imgur.com/a/SKpOW9V

### XML

https://gist.github.com/vanderm135/d03e55fe852a6795b446e8e1ec30e647

### Map Image

![map](https://user-images.githubusercontent.com/30009475/226706169-e2ca89d9-dda4-4100-b353-44414a3c0e13.png)

### Map Download

[Chernot.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11032366/Chernot.zip)

**Comment by calcastor** [comment]
Thank you for submitting! This is loaded on private servers as well as the public server, and has fit well in with maps for lower player counts.
