### ISSUE TITLE
[Update] Bridge: Castle, 1.1.0

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#685]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [ ] The update has been tested locally to make sure it works.

### Changes

-The spawn room was cramped so I made it one block taller. Adjusted the XML accordingly.
-Added an obs island
-Changed the map name from "Castle" to "Bridge: Castle" I am open to changing this though

### XML

https://gist.github.com/0uzi/54a0ed52361fd5115e0549d91584833f

### Download Link

[Bridge Castle.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11035196/Bridge.Castle.zip)

**Comment by TheRealPear** [comment]
The new map name should be good for now as it distinguishes it from other maps with similar names. I've also went ahead and renamed its folder name as well. Thanks for your submission!
