### ISSUE TITLE
[KotF/8v8] Crater Resort

### ISSUE THREAD

**Issue by EsotericSorcery** [OvercastCommunity/CommunityMaps#687]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Crater Resort

### Gamemode & Map Description

A KotF map set inside a crater formerly known as part of a luxurious lunar resort. Suitable for smaller player counts.

Update: downsized the teams to 5v5 since it would likely suit the map size better.

### Team Sizes

8v8

### Screenshots

https://imgur.com/a/vzls6DZ

### XML

https://gist.github.com/EsotericSorcery/3ee49301968b6f9f0c16963b1dd71280

### Map Image

![Crater Resort](https://user-images.githubusercontent.com/107477007/230456544-61ff2d41-c933-4fd8-820b-330e37efcdbf.png)

### Map Download

[Crater Resort.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11445849/Crater.Resort.zip)

**Comment by Cazadorian** [comment]
Initial feedback on the map:
- I'd potentially low the max score limit to 120 or 150, generally for smaller KotF maps we have lower max scores than larger KotFs as they work better with faster games at that size and drag on less at low counts or if people leave mid game.
- The death glass area around the arrow spawner should maybe be lowered down a block so it doesn't look like you can jump in and out of it, as I can see people jumping down to it and getting surprised when they suddenly die.
![2023-04-06_13 15 39](https://user-images.githubusercontent.com/73002842/230395718-2c8b0502-665c-4262-8328-34b5198a6ea3.png)
- I'd make it more obvious where the cave flag posts are, the main two indicators at the moment are the tower above it and the beam that comes off the flag through it, both of which are very hard to spot against the dark black background at the moment.
- I would personally avoid using snowball projectiles for bows as they're unable to hit enemies through the hitboxes of your team mates like regular arrows in PGM, and they cannot be picked back up afterwards which matters on a map with limited arrows like this one. 
- I'd push the spawns back slightly so they're further into the cave, to avoid the issue of people easily just being able to shoot in on people right as they respawn.

**Comment by EsotericSorcery** [comment]
Updated the map.

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since June 2023 without any major issues. Thank you for your submission!
