### ISSUE TITLE
[CTW/8v8v8v8] Enchanted

### ISSUE THREAD

**Issue by Jussssst** [OvercastCommunity/CommunityMaps#7]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Enchanted

## Gamemode & Map Description  
This is a 4-team CTW map wich has a unique and asymmetrical map layout. Because of the maplayout the way to the woolrooms is different everytime (depending on the team you choose to attack). Wich also means that defenders have it easier to defend certain teams. The theme of the map is supposed to be magical thats why we used vibrant colors and the map is played during nighttime but of course there are enough lightsources. The map has been in the rotation on the stratus network for quite some time now and has gotten pretty good feedback.

## Team Sizes
There are 4 teams with 8 players each! (32 players total)

## Screenshots
Screenshots: https://imgur.com/a/WMimXkz

# XML
XML: https://gist.github.com/Jussssst/83aa24d399b2cfe02723719499d6711c

# Map Image
![map](https://user-images.githubusercontent.com/69433766/89740560-05733600-da8a-11ea-8e92-fc2cb510ccda.png)

# Download Link
Download: https://drive.google.com/file/d/1XXaK3YsRh6IXJYtTAEhxzR-I55L6CiDg/view?usp=sharing

**Comment by Pugzy** [comment]
Just checked out this map and it seems like a solid submission.

### Packaging
- The map was not pruned (see [packaging guide here](http://docs.oc.tc/guides/packaging/pruning_chunks)).
- The `map.png` does not match the correct dimensions (290x246). 

### XML
- Kits reference a `maybe` element which doesn't exist within the official docs? Was this a fork feature? This will not work.

### Map
- Team kit shown in observer spawn doesn't match up with actual inventory content (avoid putting kits in chests for this reason).

**Comment by fixitqixit** [comment]
@Jussssst I've played this a few times and enjoyed it immensely. Looks like this has also dropped off our testing radar for a few weeks. Soon I'll try and do a test if I have no feedback to give I reckon this map could be considered for the map pools.

**Comment by Jussssst** [comment]
@fixitqixit Im glad to here that and I would love to see the map in the rotation!

**Comment by master00ofdsiware** [comment]
This map has been in the map pools for a few weeks now.
