### ISSUE TITLE
[CTW/12V12] JUPITER

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#704]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

JUPITER

### Gamemode & Map Description

CTW map Jupiter, capture the enemy's wools to win

### Team Sizes

12v12

### Screenshots

https://imgur.com/a/vT9mUf3

### XML

https://gist.github.com/oafMH/0831e5ecb928d07b9cd19d87b42020bb

### Map Image

![image](https://user-images.githubusercontent.com/75836128/234086951-8deed963-cc0a-47cb-9981-50b3841a4607.png)

### Map Download

https://www.dropbox.com/s/cb3pmrcac8yugiv/jupiter.zip?dl=0

**Comment by TheRealPear** [comment]
Is this a map update? It already has its own ticket at #521

**Comment by oafMH** [comment]
Yes, it is an update to a map, but I felt the changes made were big enough to warrant another submission as there are few similarities between this version and the original.

**Comment by EpicPuppy613** [comment]
> Yes, it is an update to a map, but I felt the changes made were big enough to warrant another submission as there are few similarities between this version and the original.

You might want to change the map name or differentiate in some way as it will have name conflicts with the original version.

**Comment by oafMH** [comment]
No

**Comment by EpicPuppy613** [comment]
> No

What do you mean by "no", what I'm trying to say is that the map cannot be loaded because it's name conflicts with the original, either the original needs to be replaced/updated or this map submission needs a name change.

**Comment by EpicPuppy613** [comment]
> i aint readin allat xD

???? is this a map update or not?

**Comment by Cazadorian** [comment]
This is very clearly an update to the original map and so should be resubmitted as an update, rather than a new submission.

**Comment by oafMH** [comment]
zzz
