### ISSUE TITLE
[Update] Jupiter, 1.1.0

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#705]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

moved spawns back

added height variation to islands

added side islands

added more cover to spawn

changed wool lanes to make it more balanced

some aesthetic changes to spawn islands

### XML

https://gist.github.com/oafMH/0831e5ecb928d07b9cd19d87b42020bb

### Download Link

https://www.dropbox.com/s/cb3pmrcac8yugiv/jupiter.zip?dl=0

**Comment by TheRealPear** [comment]
Thanks for refiling this as a map update. In the future, please refrain from making comments that may be considered rude, as seen in #704. As such, I've hidden inflammatory comments between you and an another user.

**Comment by oafMH** [comment]
I see you have closed the issue but the map isn't in pools. Will it get added or not? The new version has only been tested once, so I would appreciate if we could test it a bit more.

**Comment by TheRealPear** [comment]
It is still open in #521. This is an map update form that we don’t generally keep open for feedback if the original ticket is still open.
