### ISSUE TITLE
[CTW/15v15] Black Betty

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/CommunityMaps#706]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Black Betty

### Gamemode & Map Description

CTW - 2 Wools per team

The **Black Betty** map is combination of some visions I had for a "dream" map including:
- Obsidian design
- Spacious layout
- Full diamond kit and 
- Enchanting (instead of mining iron)

The map name is from a classic rock song of the same name, and relevant due to the black obsidian design.   Elements from the song are integrated into the map, for example:
-  "Alabam'" Island
- Sharpness II swords in the wool rooms called "Bam-ba-lam"
- Blindness potions in wool rooms called "The damn thing gone blind"
- "Birmingham" Battle Axes in team supply chests

**Black Betty** is dual CTW with optional diamond armor enchanting *no mining required), a large playing field and a few twists.  Map is intended to be easy to just run and go (diamond armor plus speed splash spawners), with layout to prevent sky bridge being over-powered, and provided resources that will inspire creative offending/defending.   Besides the 3 storerooms (Blue, Red and Island) there are 22 chests "hidden" around the map with useful supplies, weapons and armor.   There are a variety of spawners for resources and speed buffs.  Renewable anvil in team supply rooms.  Special kill streak rewards of very powerful TNT and XP.   The middle island has farming and build supplies with special grief protections.

Lots of tips/alerts included in XML.  Also, special handling of lava with filters/applicators to prevent typical cobble/stone/obsidan generation.

The team size is currently set at 50 per team, but I think this map will also play well with smaller teams like 15 each.

Extensive play testing on a server with PGM (although limited team size of 1 per team). 

### Team Sizes

Two Teams, 15 to 50 players per team

### Screenshots

https://imgur.com/a/EBqMN7t

### XML

https://gist.github.com/marksteadham/fd7b177f10344e38523d8434734c0d55

### Map Image

![map](https://user-images.githubusercontent.com/3164203/234408788-d28bb3a4-a502-4c32-b31e-f5be5faae920.png)

### Map Download

https://www.mediafire.com/file/g7vpradcn68c5h9/black-betty-1-0-0.zip/file

**Comment by oafMH** [comment]
black betty bamalam
