### ISSUE TITLE
[CTF/16v16] Friday Night Lights

### ISSUE THREAD

**Issue by Dawthon** [OvercastCommunity/CommunityMaps#707]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Friday Night Lights

### Gamemode & Map Description

Flag Football

Capture the flag

Under the Friday Night Lights

### Team Sizes

2 teams, 16 players each

### XML

https://gist.github.com/Dawthon/9c2a0580e032ac1d85ac24d140c9b4df

### Map Image

![fnl image](https://user-images.githubusercontent.com/125154667/234451444-c635a789-ba38-4347-bce8-4b0c8552e045.png)

### Map Download

[Friday Night Lights.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11328397/Friday.Night.Lights.zip)

**Comment by technodono** [comment]
I like the map but it seems bit too heavily inspired by the map "Keeper"

**Comment by Dawthon** [comment]
no shit

**Comment by technodono** [comment]
> no shit

Well as long as it plays better I think we'll all be happy to see a new FFB map.
OD you recon it might be better bumped up to 20v20 so it's more distinguished and plays in a "different pool?"
