### ISSUE TITLE
[32v32] Arrowless CTW

### ISSUE THREAD

**Issue by CredensJustitiam** [OvercastCommunity/CommunityMaps#710]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [x] I have uploaded the map zip file to a file sharing service.
- [ ] The map has been tested locally to make sure it works.

### Map Name

Arrowless CTW

### Gamemode & Map Description

This is (probably) the only CTW map that contains no arrows! Well, except for a single one at the center of the map. I made this map because I thought it would be cool to see more maps on this server that play significantly differently from one another.

Obviously this map has a big emphasis on melee combat. Bridging across the middle of the map shouldn't be too annoying since people won't constantly be shooting at each other like usual. To accommodate the lack of arrows, the max build height is significantly lower than that of a normal map. The map also contains custom items, potions, and shops to make combat and defending more interesting.

I'm open to making changes to the map if it ends up being too easy (or hard) for players to get into the wool rooms. Suggestions for better balancing shops and items are also appreciated.

### Team Sizes

32v32

### Screenshots

https://imgur.com/a/JxXa64r

### XML

https://gist.github.com/CredensJustitiam/d59a72ec750b2490d93e4e23078e3f54

### Map Image

![map](https://user-images.githubusercontent.com/80809061/234758355-e6311fae-03b2-41ab-ba57-29343cecdedf.png)

### Map Download

[Arrowless CTW (1.8.9).zip](https://github.com/OvercastCommunity/CommunityMaps/files/11350312/Arrowless.CTW.1.8.9.zip)

**Comment by TheRealPear** [comment]
Hello, thank you for your submission and apologies in advance for the slow response. I've just got to reviewing your map and noticed that the xml could be further simplified by removing redundant things and correcting certain things for the map to load properly. Here's what I've done so far:
<details><summary>XML Details</summary>

* Some lines were mis-indented, make sure you are pressing the spacebar 4 times (not tab). This has been fixed for you.
* You can combine two kits into one to save on the number of lines in the xml. You can also use the [`team-color` attribute](https://pgm.dev/docs/modules/gear/items/#team-color-attribute) to automatically color *most* items into the player's corresponding team color. However, some people may choose to use specific colors for their armors–so I kept it separate from the kit so you can decide how you want it set up.
* When making `id`s to assign names to things, avoid ambiguous names like `id="red"` for the tea, kit id, etc... because it can cause confusion and errors when loading the map. Instead, use something like `id="red-team"` and `id="red-kit"`.
* You can use the [Material Finder](https://pgm.dev/docs/reference/items/inventory/#material-finder) to find the matching internal name for an item because it is not always the same as it appears in Minecraft. (example: `material="wood"` is Oak Wood Planks, not `material="planks"`. Iron shovel is `material="iron spade"`, not `material="iron shovel"`)

```xml
<map proto="1.4.2">
<name>Arrowless CTW</name>
<created>2023-04-28</created>
<version>1.0.0</version>
<phase>development</phase>
<objective>Capture both wools from the enemy's wool rooms and return them to your victory monument!</objective>
<authors>
    <author uuid="ffd655e7-9c56-46fb-9551-be3069839381"/> <!-- CredensJustitiam -->
</authors>
<teams>
    <team id="red-team" color="dark red" max="32">Red</team>
    <team id="blue-team" color="blue" max="32">Blue</team>
</teams>
<kits>
    <kit id="teams">
        <item slot="0" material="iron sword"/>
        <item slot="1" name="`5Super Ultra God Bow Deluxe" enchantment="arrow damage:10;arrow knockback:10;arrow fire:3;damage all:1;durability:5" material="bow"/>
        <item slot="2" material="iron pickaxe"/>
        <item slot="3" material="iron axe"/>
        <item slot="29" material="iron spade"/>
        <item slot="4" amount="64" material="wood"/>
        <item slot="30" amount="64" material="wood"/>
        <item slot="8" material="golden apple"/>
        <leggings material="chainmail leggings"/>
        <boots material="iron boots"/>
        <potion amplifier="3" duration="5">damage resistance</potion>
        <item slot="5" amount="64" team-color="true" material="stained clay"/>
    </kit>
    <kit id="red-kit" parents="teams">
        <helmet color="993333" material="leather helmet"/>
        <chestplate color="993333" material="leather chestplate"/>
    </kit>
    <kit id="blue-kit" parents="teams">
        <helmet color="334CB2" material="leather helmet"/>
        <chestplate color="334CB2" material="leather chestplate"/>
    </kit>
</kits>
<spawns>
    <spawn team="red-team" kit="red-kit">
        <region yaw="-90">
            <cuboid id="red-spawn-point" min="-126.5,10,0.5" max="-126.5,10,0.5"/>
        </region>
    </spawn>
    <spawn team="blue-team" kit="blue-kit">
        <region yaw="90">
            <cuboid min="127.5,10,0.5" max="127.5,10,0.5"/>
        </region>
    </spawn>
    <default>
        <region yaw="180">            
            <cuboid id="observer-spawn" min="0.5,42,0.5" max="0.5,42,0.5"/>
        </region>
    </default>
</spawns>
<maxbuildheight>20</maxbuildheight>
<toolrepair>
    <tool>iron sword</tool>
    <tool>bow</tool>
    <tool>iron pickaxe</tool>
    <tool>iron axe</tool>
    <tool>iron spade</tool>
</toolrepair>
<itemremove>
    <item>wood</item>
    <item>stained clay</item>
    <item>leather helmet</item>
    <item>leather chestplate</item>
    <item>chainmail leggings</item>
    <item>iron boots</item>
    <item>string</item>
    <item>flint</item>
</itemremove>
<filters>
    <team id="only-red">red-team</team>
    <team id="only-blue">blue-team</team>
    <all id="woolroom-red">
        <not>
            <material>chest</material>
        </not>
        <team>red-team</team>
    </all>
    <all id="woolroom-blue">
        <not>
            <material>chest</material>
        </not>
        <team>blue-team</team>
    </all>
    <not id="no-void">
        <void/>
    </not>
    <not id="only-red-usage">
        <all>
            <any>
                <material>chest</material>
                <material>workbench</material>
            </any>
            <team>blue-team</team>
        </all>
    </not>
    <not id="only-blue-usage">
        <all>
            <any>
                <material>chest</material>
                <material>workbench</material>
            </any>
            <team>red-team</team>
        </all>
    </not>
    <all id="cobwebs-red">
        <material>web</material>
        <team>red-team</team>
    </all>
    <all id="cobwebs-blue">
        <material>web</material>
        <team>blue-team</team>
    </all>
</filters>
<regions>
    <negative id="outside-map">
        <rectangle id="map" min="-150,-99" max="150,99"/>
    </negative>
    <negative id="outside-center">
        <rectangle id="center" min="-37,-44" max="37,44"/>
    </negative>
    <union id="red-spawn">
        <rectangle min="-106.5,-2.5" max="-106.5,3.5"/>
        <rectangle min="-107.5,-8.5" max="-107.5,9.5"/>
        <rectangle min="-108.5,-9.5" max="-108.5,10.5"/>
        <rectangle min="-109.5,-18.5" max="-109.5,19.5"/>
        <rectangle min="-110.5,-19.5" max="-148.5,20.5"/>
    </union>
    <union id="blue-spawn">
        <rectangle min="107.5,3.5" max="107.5,-2.5"/>
        <rectangle min="108.5,9.5" max="108.5,-8.5"/>
        <rectangle min="109.5,10.5" max="109.5,-9.5"/>
        <rectangle min="110.5,19.5" max="110.5,-18.5"/>
        <rectangle min="111.5,20.5" max="149.5,-19.5"/>
    </union>
    <union id="red-wool-rooms">
        <!-- Pink Room -->
        <rectangle min="-126.5,82.5" max="-142.5,98.5"/>
        <!-- Yellow Room -->
        <rectangle min="-142.5,81.5" max="-126.5,-97.5"/>
    </union>
    <union id="blue-wool-rooms">
        <!-- Light Blue Room -->
        <rectangle min="127.5,-81.5" max="143.5,-97.5"/>
        <!-- Lime Room -->
        <rectangle min="143.5,82.5" max="127.5,98.5"/>
    </union>
    <apply region="outside-center" block="no-void"/>
    <apply region="blue-wool-rooms" enter="only-red" message="You may not enter your own wool rooms!"/>
    <apply region="red-wool-rooms" enter="only-blue" message="You may not enter your own wool rooms!"/>
    <apply region="blue-wool-rooms" block="woolroom-red" use="only-red-usage" message="You may not edit chests in this region."/>
    <apply region="red-wool-rooms" block="woolroom-blue" use="only-blue-usage" message="You may not edit chests in this region."/>
    <apply region="red-spawn" enter="only-red" message="You may not enter enemy spawn room!"/>
    <apply region="blue-spawn" enter="only-blue" message="You may not enter enemy spawn room!"/>
    <apply region="outside-map" block="never" message="Don't modify outside the map!"/>
    <apply block="never" message="Don't modify the spawns!">
        <region>
            <region id="blue-spawn"/>
            <region id="red-spawn"/>
        </region>
    </apply>
</regions>
<wools>
    <wool team="red-team" color="light blue" location="131,13,-87">
        <monument>
            <block location="-130,11,-1"/>
        </monument>
    </wool>
    <wool team="red-team" color="lime" location="131,13,87">
        <monument>
            <block location="-130,11,1"/>
        </monument>
    </wool>
    <wool team="blue-team" color="pink" location="-131,13,87">
        <monument>
            <block location="130,11,1"/>
        </monument>
    </wool>
    <wool team="blue-team" color="yellow" location="-131,13,-87">
        <monument>
            <block location="130,11,-1"/>
        </monument>
    </wool>
</wools>
</map>
```

</details> 

As for the map itself, I have no strong opinion on the design as it is not really my field of expertise yet, but it could use more block variation so it does not look plain. For the custom shops, you could replace the NBT villagers with the [Shops module](https://pgm.dev/docs/modules/gear/shops/) offered by PGM so you can easily edit it from the xml in the future. Whether you want to implement this is completely up to you.

**Comment by CredensJustitiam** [comment]
Thanks so much for improving the xml. I was using another map’s xml as a template so that I wouldn’t have to make the whole file from scratch, so that’s why some of the code was a bit dated probably.

I spawned the villagers using a command that I have saved on my pc, so I can easily edit the command and spawn in new villagers whenever I want. I’ll just keep using that if I need to edit the trades instead of adding more to the xml.

As for the block variation, I will probably ask some people on the discord server soon for their advice on how to make the map look better. I’m not an expert at design either (this is my first non-arcade map for the server), so I was wanting to ask for people’s suggestions anyway.

**Comment by CredensJustitiam** [comment]
Maybe I'm crazy, but I actually kind of like the simplicity of how it looks currently. People on the discord gave some good suggestions based on how the map looks from the images, so I was going to make some changes, but I realized that the map looks fine in-game when you're actually running around in it instead of looking at it from afar.

Plus, people are gonna end up spamming blocks all over it anyway, so I'm hoping it's okay the way it is now?
