### ISSUE TITLE
[KotH/25v25] Skynet

### ISSUE THREAD

**Issue by EpicPuppy613** [OvercastCommunity/CommunityMaps#711]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Skynet

### Gamemode & Map Description

- 25v25 KotH with 2 hills
- 2 points per second per hill
- 2000 points to win (~15 min game time)
- Large skynet/grid above the entire map
- Players on the skynet get TNT minecarts to drop on people below

I might make a few minor improvements with the xml later on.
The map decoration is also a bit bland at the moment, a future update might solve this.

### Team Sizes

25v25

### Screenshots

https://github.com/EpicPuppy613/maps/blob/main/Skynet.md

### XML

https://gist.github.com/EpicPuppy613/e66016893af6336e58d5a07126642452

### Map Image

![map](https://user-images.githubusercontent.com/61771471/236113558-46926b7e-957f-4b9a-b5a1-71f5d5b7abac.png)

### Map Download

[download](https://github.com/EpicPuppy613/maps/blob/main/Skynet.zip)

**Comment by marksteadham** [comment]
Congrats on releasing.  Interesting concept, looking forward to seeing it in action.

**Comment by EpicPuppy613** [comment]
i’m hoping that it will get loaded by tomorrow’s funky friday so i can test it out
