### ISSUE TITLE
[CTW/20v20] Nyxis

### ISSUE THREAD

**Issue by EsotericSorcery** [OvercastCommunity/CommunityMaps#716]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Nyxis

### Gamemode & Map Description

Nyxis is dark-fantasy-themed 20v20 CTW map, containing various gameplay mechanics such as shops and portals that players can use to their advantage. 

### Team Sizes

20v20

### Screenshots

https://imgur.com/a/w1N876p

### XML

https://gist.github.com/EsotericSorcery/ab130aed73c5bb3f0960346df1a26764

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/107477007/5d37035f-bd74-456a-94f2-84823df15e6e)

### Map Download

[Nyxis.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11468569/Nyxis.zip)

**Comment by zzuf-fer** [comment]
Took a look at the map and I found it very interesting, really liked the usage of structures at the wool rooms. I understand that you wanted to write items differently, but it'd be very nice if you could edit some sections to follow our XML conventions, especially around items and regions. Makes big sections in the XML way more complicated to follow, especially for kits and shops.

**Comment by EsotericSorcery** [comment]
Thanks for the comment! Yeah, I wrote it in that way so debugging would be a lot easier, but I get your point about the XML conventions. I edited the XML, so now it follows the conventions a bit more, and for any future maps I'll try to stick to them.

**Comment by zzuf-fer** [comment]
Awesome! Loaded in https://github.com/OvercastCommunity/CommunityMaps/commit/b737485b641223529ddb9a056420e0f41f050f19
