### ISSUE TITLE
[Control Point/4v4] Tug of War

### ISSUE THREAD

**Issue by eliminate123** [OvercastCommunity/CommunityMaps#717]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Tug of War

### Gamemode & Map Description

5 Control points in a row. The goal is to control all points, points can only be capped sequentially. 

I am requesting for this map to be on public server and private server. 

### Team Sizes

~~4v4~~ 5v5

### Screenshots

https://i.imgur.com/e72BISa.png

### XML

https://gist.github.com/eliminate123/8256efe86e36cfbb0eb06cb211b39ef2

### Map Image

![map](https://user-images.githubusercontent.com/96848330/236704511-ac15cf8d-95bf-498e-bd6a-229a58132e51.png)

### Map Download

[Tug Of War.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11416070/Tug.Of.War.zip)

**Comment by TheRealPear** [comment]
I do not approve of myself being author, given that you listed me twice as a contributor.

**Comment by eliminate123** [comment]
dont listen to him he did around 90% of the xml I dont approve of him not being author

**Comment by Guini2** [comment]
I think I should get credit because I was a big helper.

**Comment by eliminate123** [comment]
> 

err.... with what exactly?? I dont remember you helping with anything? 😎

**Comment by eliminate123** [comment]
> I do not approve of myself being author, given that you listed me twice as a contributor.

fixed 🤓

**Comment by eliminate123** [comment]
XML fixed https://gist.github.com/eliminate123/1b45297618e481d4693599aafec64327
- Removed fall dmg
- Fixed build regions
- Made team size 5v5
