### ISSUE TITLE
[DTM/6v6] Neptune

### ISSUE THREAD

**Issue by samschaap** [OvercastCommunity/CommunityMaps#719]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Neptune

### Gamemode & Map Description

Small Destroy the Monument map in "OAF6 style", one 4x3 emerald monument per team with 2 access routes to monument island. Gold mode after 20 minutes

### Team Sizes

2 teams, 6v6

### Screenshots

https://imgur.com/a/yECKLyx

### XML

https://gist.github.com/samschaap/56c71bde889fd743362d5d0795f03ba5

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/1810738/1154d018-71a4-4a72-abae-0fac62c067f7)

### Map Download

[neptune.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11433626/neptune.zip)

**Comment by oafMH** [comment]
https://gist.github.com/oafMH/4e9e1bad9b54f21042d2e121f01fa4b5 removed devphase since it got added and is somehow in votes

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since June 2023 without any major issues. Thank you for your submission!
