### ISSUE TITLE
[CTF/8v8] Lush Oasis

### ISSUE THREAD

**Issue by Zynnphony** [OvercastCommunity/CommunityMaps#721]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Lush Oasis

### Gamemode & Map Description

Capture the Flag 

TL:DR
Focus on recovery. Flag holders lose their projectile protection helmet making it easier to recover the flag with bow. Flags dont drop on the ground. Flag holders must use the map to their advantage using the parkour integrated within the map

**Armour:** (in either red or blue)
Leather helmet with `projectile protection 1`
Leather chestplate
Chain leggings with `projectile protection 1`
Leather boots

**Gear:**
Stone sword
Bow with `power 1` and `infinity`
Arrow

**Killing:**
Players receive a golden apple upon a kill

**Flag holders:**
Keep the same speed
Lose their weapons
Lose their helmet (place banner on their head)
Keep their current golden apples

**Spawn points:**
Red spawn: `29.5 62 41.5 90 0`
Blue spawn: `29.5 62 -40.5 90 0`

Red flag: `1.5 63 73.5 0 0`
Blue flag: `1.5 63 -72.5 0 0`

OBS spawn: `-69.5 84 0.5 -90 0` (can be spread out around the platform in a 3x3 manner)

**Team sizes:**
minimum of 4v4
maximum of 8v8

**No time limit:**

### Team Sizes

2 teams 8v8 max

### Screenshots

https://imgur.com/a/o44SaB8

### XML

https://gist.github.com/zzuf-fer/94fe6df6ea53d6e610731bbf6edd3dce

### Map Image

![LushOasis](https://github.com/OvercastCommunity/CommunityMaps/assets/85294819/517a47a0-8a65-4e81-9d76-465f3f43674d)

### Map Download

https://www.mediafire.com/file/nz0r2vjjpals23u/world.zip/file

**Comment by eliminate123** [comment]
Wow what a high quality map, you could totally get builder with maps like these 👍

**Comment by technodono** [comment]
> Wow what a high quality map, you could totally get builder with maps like these 👍

I agree, keep making maps like this and you'll have bright future

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since July 2023 without any major issues. Thank you for your submission!
