### ISSUE TITLE
[DTM/16v16] Rock the Casbah

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/CommunityMaps#723]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Rock the Casbah

### Gamemode & Map Description

A TNT-based DTM game that plays more like Directrix than classic DTMs.

**Map**

- **Rock the Casbah** features a unique three-dimensional course with 3 vertical levels and over a hundred jump pads!
- Classy obsidian and glass platforms provide broad space for PVP
- **130 Jump Pads**
  - Including 6 with dual velocity zones for a total of **136 velocity zones**.  
  - Jump Pads are intuitive, indicated with pressure plates, and color-coded for up, down or across.  
  - Up and down jump pads additionally indicated with player head arrows.
 
- "Gauntlet" routes are a series of 5 super-fast sequential hops that could be a risky path, but put attackers 1 jump pad away from the Pyramid.  Total of 4 Gauntlet routes.
- The Pyramids are constructed of end stone and quartz blocks creating distinctive focal points, as the DTM targets.
- The iron bars leading to the Pyramid serve multiple functions.  Besides being an assist to the Pyramid center, they can be used to drop TNT down on the Pyramid, as well as providing a critical route to Pyramid for attackers in the case the last few percent are not at ground level.
- Similarly, the 1 block of bedrock integrated into the top area of the Pyramid has two roles: Keeping players from falling into and becoming stuck in the beacon tunnel, and also guaranteeing access to those last "in-air" Pyramid blocks.
- Map includes team-color accented diorama based on the Algerian Casbah, with palm trees and minarets providing contrast with the dark map and tying together with the Pyramid designs, creating cohesive map of disparate elements.
- Sniper Island, provides a small burst of green in the lower center of map, as well as a landmark to keep players oriented in the map during fast action.  Players may fall accidentally on the island (possibly intentionally), and although the player can snipe from behind the palms, there is no way alive off the island.
- Players spawn is in the air above the rear/center/upper platform, falling through the 3 rings towards back of each teams side.  The rings have barrier blocks to prevent laggy players from being able to land on rings.

**Gameplay**

- Players spawn right into the battle with mixed-armor with Blast Protection and 5 TNT, along **constant Speed** 1 and **no fall damage**, for high-velocity action.

- Players also have 1 minute of Absorption, 5 seconds of damage resistance and 10 seconds of regeneration since players spawn in an action zone.
- TNT is powerful (level 6) with auto-ignite and short 1 second fuse.
- Players will lose at least half a heart, possibly several from each TNT they deploy.  This limits TNT spamming.
- TNT also useful for PVP and defense.  No damage to team-mates.
- The Pyramids will drop Endstone potentially from TNT explosions which can be used by teams to repair their Pyramid.
Much of the Endstone will be destroyed by subsequent TNT, but otherwise, defense can quickly repair, or attackers can take it home to repair their Pyramid.
- Endstone can't be placed anywhere else on the map besides the Pyramid area.
- It takes approximately 40 TNT "hits" to completely destroy a Pyramid (assuming no repairs).
- Precision hits work slightly better than spammed, as sometimes TNT are deflected away from Pyramid, doing less damage.
- If teams don't defend, they can be quickly beat, but this map is more like Boombox than The Nile, in that teams have some time to get-it-together if they start losing because of the larger target.
- Players earn 1 gapple and 2 TNT for each kill, and 1 Strength Pot for each 3-streak
- 4 TNT spawners are positioned in the 4 opposing front/center/lower platforms  
- 2 Regeneration spawners are located on the rear/center/lower platforms (below the spawn landing platform) giving the home team an easy buff option, but attackers coming from via the 2 Gauntlet routes do, as well.

### Team Sizes

16v16

### Screenshots

https://imgur.com/a/FQ480Eq

### XML

https://gist.github.com/arcadeboss/51fecb21138f222a11a7cbfaec8dab3e

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/34e95ff4-736a-4e96-87b5-62517c4d6b62)

### Map Download

https://www.mediafire.com/file/wwq6sb0io6tkr0g/rock-the-casbah-zip.zip/file

**Comment by Guini2** [comment]
Hey nice map name

**Comment by technodono** [comment]
The sharif won't like this :)
