### ISSUE TITLE
[Update] Chilla, v1.0.2

### ISSUE THREAD

**Issue by eliminate123** [OvercastCommunity/CommunityMaps#727]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

- Updated defense materials to the current version of Villa
- Updated bedrock wall to current version of Villa

### XML

Not needed

### Download Link

[Chilla.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11492775/Chilla.zip)

**Comment by Guini2** [comment]
Villa 3
