### ISSUE TITLE
[CTW/12v12] Wintertime

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#729]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Wintertime

### Gamemode & Map Description

CTW 12v12

### Team Sizes

12v12

### XML

https://gist.github.com/samschaap/b47b3a71ab749f17b45054502690e9e3

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/97280598/e72eb187-9fc7-4178-898f-e80b7e59e9a8)

### Map Download

[wintertime.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11508755/wintertime.zip)

**Comment by TheRealPear** [comment]
Is this a reskinned variant of an existing map?

**Comment by Guini2** [comment]
No its a new map

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since July 2023 without any major issues. Thank you for your submission!
