### ISSUE TITLE
[TDM/20v20] The Killing Floor

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/CommunityMaps#745]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

The Killing Floor

### Gamemode & Map Description

Summary

- **TNT gains a risky new use-case: a block used to pillar up and over into a scorebox.**
- Team Death Match with Scoreboxes in a nightmarish industrial setting.
- Chaos

Overview

- 2 TEAMS (Black Hearts and White Diamonds) [Symmetrical teams]
  - 50 Points for scorebox, 1 point for kill.  Most points at end of 8 minutes wins.
  - The "floor" is redstone checkerboard surrounded by lava and attackers, and each team has one killing floor they defend.
  - 42 portals for movement of classes between spawn, gallery (left/right/up/down), floor, sky areas, and scoreboxes.
  - Portals labeled with both armor stand tags, and most with "head" icons and "head" arrows.
  - Spawn floor is color-coded with respect to defensive/offensive portals, so players can memorize instead of reading every time.
  - Probably not critical, but for fairness: the heart-shaped scorebox has black wool barriers at the top to simulate entry shape like the diamond-shaped scorebox.
  - Scorebox has End Portal layer at bottom.

- 3 CLASSES (Runners, Archers and Bombers)
  - Runners attempt to cross the killing floor and make it into the score box while attacked by archers and bombers.
  - Runners must use TNT blocks to get to scorebox, but a 50% redstone floor, bomber's TNT and archer's fireballs can make that tricky.
  - Archers have bows and a fireball with 15 second cooldown to explode TNT.
  - Bombers have TNT, redstone and wood.   Bombers break the pink glass with axe, and place TNT, pressure plates, etc.
  - Classes change by returning to spawn (after death, or returning via a portal) and a new portal/class can be picked.

Design story:

- Initial concept was redstone checkerboard floor for tricky TNT pillaring
- Testing revealed only black and white provided good redstone contrast and style, so teams were black and white
- Color theme of black, white and red is like TNT, which fits, nice!
- Color theme also matches playing cards, so had idea to use suit symbols.
- Wanted symbols that were simple and looked similar (at least on the bottom half) for scoreboxes.
- Luckily, Diamonds and Hearts fit that bill perfectly.
- And luckily, the symbols/colors worked out to decent team names: Black Hearts and White Diamonds.  

### Team Sizes

20v20

### Screenshots

https://imgur.com/a/KlfnvxC

### XML

https://gist.github.com/arcadeboss/7139fbdff739835b9f4d216eb8487b30

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/778cd0db-d914-4bd4-b3a5-cdb2f0f81e5c)

### Map Download

https://www.mediafire.com/file/rxkkhochl2jh2oi/the-killing-floor-zip.zip/file

**Comment by EpicPuppy613** [comment]
After playing this map, I noticed that defense is way too overpowered, you can just have a line of defenders dropping tnt and preventing any runners from getting past and not much they can do about it.

**Comment by arcadeboss** [comment]
You're correct.  Have a few changes planned like more health for runners, and less TNT/redstone inventory for bombers.  Jump mutation seemed to improve things, but need to see what options I have.

**Comment by arcadeboss** [comment]
@TheRealPear - An update from previous testing

https://github.com/OvercastCommunity/CommunityMaps/pull/805/

In testing the Bombers were soon too strong for Runners to survive. The double-jump mutation was added at that time, and it was helpful, but not quite enough.

XML:

    Runners get 20 seconds of Regen to help them survive the floor
    Runners get Jump Boost to deal with TNT wall-effect
    Fireball gets name "TNT Exploder" to explain purpose, and fix scuffed countdown display
    Bombers get less TNT (requiring spawn trip and back to refresh) and less redstone as a nerf
    Runners get 1 stack instead of 3 stack of TNT
    Pressure plates are stone for visibility purposes

Map:

    Bombers lose 4 blocks of bombing space at the score box end
    Scorebox is raised 1 block to slightly counter jump boost assist
