### ISSUE TITLE
[Blitz/1v1] Cannon Duel Diagonal

### ISSUE THREAD

**Issue by MonstoBusta** [OvercastCommunity/CommunityMaps#746]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Cannon Duel Diagonal

### Gamemode & Map Description

- Cannon Duel, but diagonal.
- Blitz for obvious reasons
- Designed to reinforce proper diagonal cannon habits

### Team Sizes

2 Teams of One

### Screenshots

https://imgur.com/a/1ptE0CE

### XML

https://gist.github.com/MonstoBusta/aa991272d28c289a4e0c075f4412f122

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/119002070/3f62dcaa-5097-4280-b6dc-eb69ca946608)

### Map Download

https://www.dropbox.com/s/d5mdgn9k6cy2t2v/Cannon%20Duel%20Diagonal.zip?dl=0

**Comment by Strangeys** [comment]
Is this map intended for the TNT Map Contest?

**Comment by calcastor** [comment]
If this was submitted with intentions of being a contest map, it unfortunately does not qualify as it is an arcade/arcade-tangential map.

Otherwise, the XML appears to work so this is fine. The distance between the two player sides seems slightly larger than I would have expected, however I am not adept at cannoning so perhaps this is not an issue.

I'm going to load this map and close this issue. Thank you for submitting!

**Comment by MonstoBusta** [comment]
> Is this map intended for the TNT Map Contest?

No.

**Comment by MonstoBusta** [comment]
>The distance between the two player sides seems slightly larger than I would have expected, however I am not adept at cannoning so perhaps this is not an issue.

It is an issue if tnt fall is not randomized. However, given the way TNT works on OCC, the distance is just enough. Were there to be a sort of "remix" map version, then this would be the long distance, equivalent to 55 blocks in Cannon Duel Remix.
