### ISSUE TITLE
[FFA/parkour] Road to the moon

### ISSUE THREAD

**Issue by Flamiix** [OvercastCommunity/CommunityMaps#748]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Road to the moon

### Gamemode & Map Description

FFA
Parkour with checkpoints
Pools : fun / funky friday

### Team Sizes

ffa 100 

### Screenshots

https://imgur.com/a/mZxK7PK

### XML

https://gist.github.com/samschaap/9d202b7480d1c8c93d2a4c457aaa51f7

### Map Image

![2023-06-18_18 14 48](https://github.com/OvercastCommunity/CommunityMaps/assets/105971633/8d48d5c6-a7b3-457c-9a9f-4e491e497b3d)

### Map Download

https://github.com/OvercastCommunity/CommunityMaps/files/11782067/road_to_the_moon.1.zip

**Comment by arcadeboss** [comment]
I'm sure this will be very challenging, and fit right in with FF.  Which map is the boat from?

**Comment by Flamiix** [comment]
> I'm sure this will be very challenging, and fit right in with FF. Which map is the boat from?

Hey thx ! The boat is from « Celestia Island » a map i made with aaewe few months ago ! But I need to fix the layout, it wasn’t working
