### ISSUE TITLE
[DTM/16v16] The Waiting Room

### ISSUE THREAD

**Issue by Lowie375** [OvercastCommunity/CommunityMaps#749]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

The Waiting Room

### Gamemode & Map Description

Destroy the Monument + TNT
- 2 monuments on each side (emerald/gold ladder + endstone ladder)
- Indestructible central platforms (tables)
- Instead of the void, there's a deadly floor!

The Waiting Room is an enclosed DTM map with TNT, based on a build made by myself, Digitalight, and some other players during a past OCC match. The main play area is an 80 x 48 x 80 region made up of various upscaled Minecraft blocks, with each team having two monuments in the shape of ladders (both of which must be destroyed using TNT).  
This map's monuments are 16 blocks tall and one block thick, meaning players will need to aim their cannons well in order to fully destroy them. Monuments are also very close to team spawns, so incoming cannon fire will likely end up destroying cannons and platforms in addition to monuments, meaning teams will need to quickly adapt and rebuild offensive devices throughout the match.

### Team Sizes

2 teams: **16v16** (updated)

### Screenshots

https://imgur.com/gallery/eSzHcso (taken on v1.0.0)

### XML

https://gist.github.com/Lowie375/e5287c334a952e7242db87e40961225a

### Map Image

**1.2.0+** (updated)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/40923337/642c6a44-39e4-45a6-a51c-242d7bddf347)
1.0.0 - 1.1.1 (original)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/40923337/680e822d-38f6-4eb6-ac53-a19cb64e8251)

### Map Download

Via GitHub: [The Waiting Room 1.2.3.zip](https://github.com/OvercastCommunity/CommunityMaps/files/12066337/The.Waiting.Room.1.2.3.zip)
Via Google Drive: [The Waiting Room 1.2.3.zip](https://drive.google.com/file/d/1ryMXUAGmT9mg4DZq1EplU253fezCiMFD/view?usp=sharing)

**Comment by arcadeboss** [comment]
Took me a while to understand this fully.  Looking forward to seeing it in-game. good luck.

**Comment by Lowie375** [comment]
Updated to v1.1.0:

- Monuments must now be destroyed using TNT (emerald and gold blocks have different break speeds, but the same blast resistance)
- Reduced build height to 48 (from 50)
- Tweaked enchantment levels (blast protection `2 → 5`, feather falling `4 → 5`, efficiency `1 → 2`)
- Allowed various redstone items to be dropped (moved from `itemremove` to `itemkeep`)

**Comment by Lowie375** [comment]
Updated to v1.1.1:
- Increased lower bounds of `death-area` and `play-area` by 1 block to prevent block-clutching against the ground
- Updated match alerts to highlight important map info
- Added iron axe back to spawn kit + applied efficiency 1 to diamond pickaxe
- Changed team names: `Lime` → `Lime Ladder`, `Yellow` → `Yellow Sign` (this is mainly for flavour, feel free to revert it)

**Comment by Lowie375** [comment]
Updated to 1.2.0:
- Made monuments repairable (with iron blocks)
  - Added a new kill reward to make this possible: 4 iron blocks every 2 kills
  - Added a bedrock outline of each ladder into the walls behind them
- Raised upper build limit by 1 block (`48 → 49`)
- Added tripwire hooks to sides of ladders
- Updated spawn chest resources so that they better match the resources provided in the spawn kit
- Added iron shovel + shears to spawn kit
- Made various alerts repeat mid-match

**Comment by Lowie375** [comment]
Updated to v1.2.2:
- Made the map floor kill via a void portal instead of wither potions
  - This should allow snipe and knock kills to be credited
- Restricted where water can be placed around monuments (not in areas where there were previously monument blocks)
  - This is intended to discourage spamming water defensively in the late game, while still allowing water defense as a whole
- Made various spawn kit tools unbreakable (iron shovel, iron axe, shears)
- Prevented smooth double slab blocks (used in map deco) from dropping slabs

**Comment by zzufx** [comment]
```
<kit id="death" force="true">
        <clear effects="true" items="false" armor="false"/>
        <effect amplifier="-37" duration="oo">health boost</effect>
</kit>
```
I'd recommend you to use the [void-death.xml](https://github.com/OvercastCommunity/PublicMaps/blob/main/includes/void-death.xml) include instead of this custom stuff - I've had weird stuff happen with similar health boost values before. You'd just do
```
<include id="void-death"/>
<constants>
    <constant id="void-plane">the Y level you want</constant>
</constants>
```

**Comment by Lowie375** [comment]
Updated to v1.2.3:
- Refactored `map.xml` to use `void-death.xml` instead of custom void death XML (thanks zzuf!)
- Removed some obsolete commented code
