### ISSUE TITLE
[DTC/10v10] Extraterrestrial

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#752]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Extraterrestrial

### Gamemode & Map Description

this is a mix of bedwars & DTC akin to the map "Mame I shrunk the pvp-ers." I wanted resources to have value so that the map had a cool progression to work towards and also so that all resources for offensive & defensive would have some value tied to it. I’m hoping with the sone of the better items & upgrades added to the shop it helps breaks stalemates. The added bonus of making monument mode changes mess stressful with the team defensive haste upgrade.

unique & hopefully loved by all!

players are encouraged to cannon to prevent sky-bridging, mid pushes & perhaps take pot shots at the enemies defence! lots of tnt & defensive/utility items are found in the shop

I wanted to be a bit creative and tried building the map in one day, surprisingly easily. However due to limited time (external circumstances) I will not be available to update the map before or during the competition (that’s also why I rushed the submission)

feel free to tweak the xml/maps/shop in any/every way without my permission!
(as long as it doesn't remove all shop)

shout-out to @Cazadorian  a lot of my shop xml is based/built of his map!

> damn it's so late rn...

### Team Sizes

10 v 10

### Screenshots

https://imgur.com/a/2NukbDy

### XML

https://gist.github.com/technodono/6aea43921d563d80211b466cae496ff1

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/22761234/0b3dfcc4-35fa-4e33-b05f-e20bfc1512ee)

### Map Download

[extraterrestrial.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11834802/extraterrestrial.zip)
XML UPDATED! see XML link for change.

**Comment by arcadeboss** [comment]
I like the "alien" plants, looks good.

Just took a quick glance, but seems like the map and the kits don't have water.   I did see water in the store, but I can't say if that meets the contest requirements, probably does, but might want to check.

**Comment by technodono** [comment]
> I like the "alien" plants, looks good.
> 
> Just took a quick glance, but seems like the map and the kits don't have water. I did see water in the store, but I can't say if that meets the contest requirements, probably does, but might want to check.

Water buckets & extra buckets can be purchased in the store

**Comment by TheRealPear** [comment]
> I like the "alien" plants, looks good.
> 
> Just took a quick glance, but seems like the map and the kits don't have water. I did see water in the store, but I can't say if that meets the contest requirements, probably does, but might want to check.

I asked about this with another map dev; this map does technically meet contest requirements.

**Comment by technodono** [comment]
> > I like the "alien" plants, looks good.
> > Just took a quick glance, but seems like the map and the kits don't have water. I did see water in the store, but I can't say if that meets the contest requirements, probably does, but might want to check.
> 
> I asked about this with another map dev; this map does technically meet contest requirements.

That’s a relief.
My war of thinking about the shop would be like having a defensive chest with water buckets (but you pay for it)

**Comment by Strangeys** [comment]
The shop isn't actually a bad idea for this because TNT will be very powerful considering how small the islands are and the overall map. If you just gave TNT to everyone immediately, I'm not sure if there'd be anything left of the map besides void. I feel like you could maybe add some more land to the main team island around the core as right now there isn't much you can do to get to the core once you're on the enemy island because it's very small and has no vertical elements to attack from besides essentially skybridging or staircasing from an island to the core.

**Comment by technodono** [comment]
> The shop isn't actually a bad idea for this because TNT will be very powerful considering how small the islands are and the overall map. If you just gave TNT to everyone immediately, I'm not sure if there'd be anything left of the map besides void. I feel like you could maybe add some more land to the main team island around the core as right now there isn't much you can do to get to the core once you're on the enemy island because it's very small and has no vertical elements to attack from besides essentially skybridging or staircasing from an island to the core.

I wish I could implement these changes but I’m currently on summer break with no access to OCC obviously. I appreciate the positive feedback however
