### ISSUE TITLE
[Update] jupiter, 1.1.1

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#753]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

-Added gold blocks
-Added axe to spawn kit 
-Replace glass in spawn kit with wood
-Increase playersize by 2 since the map is a bit bigger now

### XML

https://gist.github.com/oafMH/7eb17293e51e4149f882a5296a9f91ca

### Download Link

https://www.dropbox.com/s/cb3pmrcac8yugiv/jupiter.zip?dl=0

**Comment by arcadeboss** [comment]
Nice tweaks
