### ISSUE TITLE
[DTC/M/24v24] Autumn Solstice

### ISSUE THREAD

**Issue by Dawthon** [OvercastCommunity/CommunityMaps#754]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Autumn Solstice

### Gamemode & Map Description

Destroy the Monument and Core

There is two monuments

And a Core

Destroy Them

Now

With TNT

### Team Sizes

2 teams, 24 players each

### XML

https://gist.github.com/Dawthon/27f42b03d21ea5e3c31d15458409568e

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/125154667/11625964-caaf-49d8-bc53-de480ca4008a)

### Map Download

[hopefully fixed autumn solstice.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11929538/hopefully.fixed.autumn.solstice.zip)

**Comment by arcadeboss** [comment]
Looks great, this map deserves an album!

**Comment by technodono** [comment]
> ### Checklist
> * [x]  I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
> * [x]  I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
> * [x]  I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
> * [x]  I have created an XML file.
> * [x]  I have created a map image.
> * [x]  I have uploaded the map zip file to a file sharing service.
> * [x]  The map has been tested locally to make sure it works.
> 
> ### Map Name
> Autumn Solstice
> 
> ### Gamemode & Map Description
> Destroy the Monument and Core
> 
> There is two monuments
> 
> And a Core
> 
> Destroy Them
> 
> Now
> 
> With TNT
> 
> ### Team Sizes
> 2 teams, 24 players each
> 
> ### Screenshots
> _No response_
> 
> ### XML
> https://gist.github.com/Dawthon/27f42b03d21ea5e3c31d15458409568e
> 
> ### Map Image
> ![map](https://user-images.githubusercontent.com/125154667/248585527-11625964-caaf-49d8-bc53-de480ca4008a.png)
> 
> ### Map Download
> [Autumn_Solstice.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11860745/Autumn_Solstice.zip)

Looks nice! More of these will have you on your way to builder. What matters though is not looks but gameplay good luck & hopefully this works out ;)
