### ISSUE TITLE
[DTC/DTM/24v24] Cannonball Cove

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/CommunityMaps#755]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Cannonball Cove

### Gamemode & Map Description

**A Pirate Island themed Core & Monument game with TNT and Cannoning supplies.**

- Teams: **Redbeard vs Bluebeard** on two sides of a "cove", separated by water.
- Match starts around sunset, with timelock off, for a variety of lighting conditions
- Ocean contains "treasure", a squid spawner, and two sunken cannonballs for decoration.

.

- Core is imagined as a giant Cannonball suspended from a hoist on the back platforms.
- Monument is a large 'Jolly Roger' flag, centrally placed on each side, must be destroyed with **TNT only**.
- Flag monuments cannot be "watered", and Cores go to "Gold" mode after 20 minutes to prevent stalemates.

.

- Spawn house has supply chests and is only part of map protected from being destroyed by TNT.
- Non-renewable Iron Mine for each team, and iron supplies around the map
- TNT/Cannon supply chests scattered around map (jungle and sea platforms, mine, boats, dock, spawn)
- Firebow with limited arrows available on the 3 Lookout Towers.  (1 per team side, plus 1 central to fight over)
- The 3 Lookout Towers include a slow arrow spawner so fire bows don't quickly become totally useless.
- A Pirate Ship with a crow's nest, platforms and many supplies is harbored at each team's beach dock
- Various loot is hidden around map in chests, like "Edward Low's Cursed Cutlass", a gold sword with fire aspect.

.

- Kits include 
   - 7 stacks of TNT
   - ladders, bucket and Pirate themed items, like a "Steel Cutlass" (iron sword) and "Boarding Axe" (iron axe, sharpness 1).
   - a few back-up cannoning supplies like redstone, in case supply chests are tapped-out.
- Kill rewards: Gapple and TNT for each kill and a strength pot named "Rum" for each 3 streak.
- Helpful color-coded armor stand signs and chat alert/tips are grouped by topic:
   - red = attacking/objectives
   - green = defense
   - black/grey = items/resources.

### Team Sizes

Two Teams, 24 each

### Screenshots

https://imgur.com/a/DM4gUBC

### XML

https://gist.github.com/arcadeboss/a22396bb60be859de45a9698e9f5f598

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/ffc8cc5c-1c74-46e6-952d-417416335834)

### Map Download

https://www.mediafire.com/file/lcnrb7nt5e149lj/cannonball-cove-zip.zip/file

![2023-06-25_00 29 25](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/09bfcef5-d636-4aca-92f9-ecf33e667c6c)

**Comment by technodono** [comment]
Very intriguing. Reminds me of an older OCN map where you had to blow up each teams flag

**Comment by arcadeboss** [comment]
Tweaks to map and XML based on play testing and suggestions:

https://github.com/OvercastCommunity/CommunityMaps/pull/775
