### ISSUE TITLE
[DTC/18v18] Incassum

### ISSUE THREAD

**Issue by cswhite2000** [OvercastCommunity/CommunityMaps#756]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Incassum

### Gamemode & Map Description

2 Team DTC with 2 cores on each side. Each side is composed of 9 cuboids each at a different height between those adjacent platforms.

The design was chosen to have several different platforms and areas to allow for more locations where cannons can be built.

Minor details:
- I've included a few punch bows without infinity, across the front of the map to slow down initial bridging.
- The build height is slightly lower between the two sides
- Both cores only require a single block destroyed to leak
- Diamond blocks drop diamond chestplates
- TNT and Cannon supplies are in chests on several platforms.
    - These can be blown up
- There is a TNT kill reward

### Team Sizes

18v18

### Screenshots

![2023-06-25_16 51 21](https://github.com/OvercastCommunity/CommunityMaps/assets/9834984/caef8912-6e13-4a70-93a6-c90d008226e3)

![2023-06-25_16 52 16](https://github.com/OvercastCommunity/CommunityMaps/assets/9834984/70ce2f02-7701-4d38-922f-5b9e8290b4a5)

### XML

https://gist.github.com/cswhite2000/195d785b3010a2c59692e4d8974ce209

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/9834984/77df718c-1f00-4ff3-9432-32cc7ecdee03)

### Map Download

[incassum.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11861289/incassum.zip)

**Comment by arcadeboss** [comment]
Looks good, like a classic OG map, wouldn't be surprised if it has great gameplay.

**Comment by calcastor** [comment]
Make the punch bows limited use (damaged) instead of non-infinite.

**Comment by cswhite2000** [comment]
Yeah, that would be a better way to do it. That way you won't be able to run out of arrows for your normal bow either.

**Comment by Strangeys** [comment]
First playtest was a bit of a rush but most of that is cause we increased team sizes for how many people were online. I think one thing I'd suggest if you do make in-game changes is to maybe add some bedrock right outside of the spawn tunnel so players have a platform to build off of if someone was to blow up that whole area.

**Comment by cswhite2000** [comment]
I actually did include a 3 wide line of obsidian 1 layer under the stone that goes from the spawn tunnel to up towards the front.

**Comment by cswhite2000** [comment]
Here is an updated version 1.0.1: [incassum.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11932729/incassum.zip)

Changes:
- I've swapped out the punch bows + arrows with damaged infinity punch bows (each bow can shoot 32 times before breaking)
- I moved the golden carrots to the far right spot
