### ISSUE TITLE
[DTM/20v20] Apollo 23

### ISSUE THREAD

**Issue by Dawthon** [OvercastCommunity/CommunityMaps#760]
### Checklist

- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [x] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [x] I have created an XML file.
- [x] I have created a map image.
- [x] I have uploaded the map zip file to a file sharing service.
- [x] The map has been tested locally to make sure it works.

### Map Name

Apollo 23

### Gamemode & Map Description

Destroy The Monument

The monument is a Spacecraft

There's also hidden items around the map

Destroy the Spacecraft with TNT

### Team Sizes

2 teams, 20 players each

### XML

https://gist.github.com/Dawthon/d4f39d55004d4d702e4f0058a1c1e637

### Map Image

![apollo_23_image](https://github.com/OvercastCommunity/CommunityMaps/assets/125154667/34cf0cbe-2bec-43ae-be7e-47a4733cb2b2)

### Map Download

[apollo 23 fix.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11924043/apollo.23.fix.zip)

**Comment by arcadeboss** [comment]
Great concept, looks good from what I can see, looking forward to seeing more of it.

Just an idea, but pretty easy to drag and drop an additional image into the bottom of the Issue, if you don't want to set up an external album.

Are there any tips that would be helpful for players to include in XML?   For example they might want to know if the monument can be destroyed only with TNT, or also with tools.

**Comment by arcadeboss** [comment]
The map has an issue because it provides an iron depot, but the iron doesn't drop because it is in item remove section.
