### ISSUE TITLE
[DTM+DTC/28v28] Monolith

### ISSUE THREAD

**Issue by xRob3** [OvercastCommunity/CommunityMaps#761]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Monolith

### Gamemode & Map Description

- Leak the enemy team's core (located at the top of the tower) and destroy their monument (located on the wizard's staff)
- Gather tnt and redstone supplies from spawn and build cannons to defend your core and monument
- Make use of the icaruses built into spawn to drop down on rushers from the skies
- Use the pre-built icarus on the side lane to reach the enemies core quicker
- Search for hidden items and locations around the map to gain a competitive edge

### Team Sizes

2 teams, 28 slots on each

### Screenshots

https://imgur.com/a/mWNHyJd

### XML

https://github.com/zzufx/zzuf/blob/main/monolith/map.xml

### Map Image

![2023-06-27_15 54 53](https://github.com/OvercastCommunity/CommunityMaps/assets/137957305/5b62e930-0941-4af7-a814-4a7265a18d31)

### Map Download

[monolith.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11887790/monolith.zip)

**Comment by arcadeboss** [comment]
This is great design with the structure around the core.  And the built-in cannons are a strong feature.

Lot going on, should be very interesting to see gameplay.

Thanks for the fat album too.

I will give you a pro tip for capturing the big picture shots.  I recommend it for everyone:  

* Use the Optifine zoom.   

This will give you big picture shots without the warping that happens, especially at the edges.   It's not very good for capturing cozy areas, but great for the overhead shot, focusing on map regions, depth shots, etc.
