### ISSUE TITLE
[Update] Jungle Arena, 1.0.1 (PrivateMaps repo)

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/CommunityMaps#762]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [ ] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

- Note: This is for Private maps repo, but no access to submit PR or Issue.
- Note: Please don't change XML without communication, thanks.

This change is XML only update.

- Reworked problematic spawning from lobby-style to instead use 50 regions selected randomly
- Fixed Fishing Rod litter
- Other tweaks

Thank you!!

### XML

https://gist.github.com/arcadeboss/18d2f8a15bfcd5c8743eb1b1a84bdc23

### Download Link

https://gist.github.com/arcadeboss/18d2f8a15bfcd5c8743eb1b1a84bdc23

**Comment by calcastor** [comment]
Pushed
