### ISSUE TITLE
[Bridge/20v20] Kihl

### ISSUE THREAD

**Issue by papayatkes** [OvercastCommunity/CommunityMaps#764]
### Checklist

- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Kihl

### Gamemode & Map Description

Kihl is a 20v20 bridge map made for public. The map has **_two bridges_** and _**two score portals per team**_ to avoid defenders stacking on the score portal. Instead of that, we made sure all the entries to the portal rooms had a region to put a wall and we also made it so enemy players can't avoid digging through them in order to get this room.

Basically we wanted defenders to actually **_defend_** using the blocks, just like you would do in the original bridge instead of stacking 10 players on the scores. In order to adapt this to the 20v20 scale we made it so there is a total of _**4 entries**_ that can be fully blocked: 2 in the front (one in top of the other) and one to right and left.

### Team Sizes

2 teams of 20 each

### Screenshots

https://imgur.com/a/yJQBAmE

### XML

https://github.com/zzufx/zzuf/blob/main/kihl/map.xml

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/46404176/a2fe42e7-5d4b-46d9-b475-00753479055b)

### Map Download

[Kihl.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11905450/Kihl.zip)

I couldn't manage to open the MCEdit program and I had a lot of trouble prunning the map so I finally kept it without prunning. I'm sorry.

**Comment by arcadeboss** [comment]
Looks like this will be a nice addition to the suite of bridge mode games.  Design is nice.

Where are the portals exactly?  I couldn't tell from the pics.

Also I liked these pics, nice angles and lack of skewing.  Any special technique used to make them, like zoom or low field of view?

**Comment by TheRealPear** [comment]
@papayatkes In the future, you can use MCASelector for pruning. It seems like the map is small enough to the point of not needing any prune.

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since July 2023 without any major issues. Thank you for your submission!
