### ISSUE TITLE
[DTM+CTW/24v24] Double Trouble

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#765]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Double Trouble

### Gamemode & Map Description

Inspired in one of our favorite maps...

Double Trouble is a DTM+CTW Map where you must destroy two endstone monuments to get into the woolrooms inside of it, giving up the chance of blow up each of the monuments using amazing tnt cannons from different angles.

### Team Sizes

24v24 Players

### Screenshots

https://imgur.com/a/92ixrnm

### XML

https://www.dropbox.com/s/kuc6gy4gmqmhwtb/map.xml?dl=0

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/1c97e143-3fe8-4e63-8c49-623c412da598)

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/164cc745-6b36-418d-9a5b-c40cb2d4a6ad)

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/258b4e55-b6e3-4891-bff8-0a99eea999ae)

### Map Download

https://www.dropbox.com/scl/fo/5rja8teejs0ilnk613nzo/h?dl=0&rlkey=2snxwron8oppsnoxwjglafsdq

**Comment by arcadeboss** [comment]
This might be a bit more than "double" trouble.

This looks like it will be pretty wild.

**Comment by technodono** [comment]
This concept is kinda crazy. I hope it plays alright!

It’d be a nice map 2 have
