### ISSUE TITLE
[DTC/M/28v28] Stone Fields

### ISSUE THREAD

**Issue by rockymine** [OvercastCommunity/CommunityMaps#770]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Stone Fields

### Gamemode & Map Description

![](https://i.imgur.com/OjTgBy0.png)

Welcome to Stone Fields, a PvP map designed for the intense Destroy the Core (DTC) or Destroy the Monument (DTM) game mode. In this map, players will engage in strategic battles, building cannons and utilizing TNT to obliterate the objectives. The monuments, constructed with precious Emerald blocks, feature cleverly placed pockets of water that aid attackers during the match. Exploring the map, you'll encounter majestic oak trees, sturdy boulders, and structures housing valuable TNT. Keep an eye out for scattered iron and diamond, as they can be used to craft superior armor, giving you an edge in this epic showdown.

### Team Sizes

Red vs. Blue (28 vs. 28)

### Screenshots

https://imgur.com/a/0giM9n0

### XML

Loaded on `/server mapdev`.

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/8013626/cde97e4f-a5fd-4f82-ae39-4a0437d047cd)

### Map Download

Loaded on `/server mapdev`.

**Comment by arcadeboss** [comment]
Looks quite nice.

Curious about placement of red side, but sure I will see it live eventually.
