### ISSUE TITLE
[TNT/DTC/M/10v10] Querelous

### ISSUE THREAD

**Issue by OhPointFive** [OvercastCommunity/CommunityMaps#772]
### Checklist

- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Querelous

### Gamemode & Map Description

This is a generic DTC/M with TNT map. I'm not very good at building those, so there are probably serious gameplay issues. Luckily, it's ugly too.

### Team Sizes

2 teams of 10

### Screenshots

[Screenshots](https://imgur.com/a/8Yc9UeL)

### XML

The XML is included in the map download

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/41559602/9f2dcc14-1b88-4c04-bd06-6fdeb3df6da1)

### Map Download

[Querelous.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11936042/Querelous.zip)

Note the map is not pruned as I haven't gotten MCASelector working yet.

**Comment by arcadeboss** [comment]
The map names are great.  The "quereling" should be interesting.

Best thing I know to prune is MCEdit, the old one.

**Comment by OhPointFive** [comment]
[Querelous.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11972814/Querelous.zip)

No actual changes to the map, but I thought I should upload my pruned version. @arcadeboss, I sadly can't run old MCEdit on my computer. MCASelector worked fairly smoothly although it was a bit of a pain to set up.
