### ISSUE TITLE
[DtM/25v25] Blast Mining II

### ISSUE THREAD

**Issue by EpicPuppy613** [OvercastCommunity/CommunityMaps#776]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Blast Mining II

### Gamemode & Map Description

The second iteration of Blast Mining (a previous map I submitted) with somewhat refined mechanics. The core gameplay is using TNT to blast through a mass of blocks and destroy the other team's monuments. Many improvements have been made from the original such as not covering the entire map in bedrock and making the entire map renewable. Additionally, there are now 2 lanes instead of 1 giant lane to make gameplay more interesting.

Note: all of the addition map information is contained in a single repository for ease of update access.

### Team Sizes

2 teams, 25v25

### Screenshots

https://github.com/EpicPuppy613/maps/blob/main/Blast%20Mining%20II.md

### XML

https://github.com/EpicPuppy613/maps/blob/main/Blast%20Mining%20II.xml

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/61771471/3eb47a07-e1ad-4d0b-8e22-aa3e45506be4)

### Map Download

https://github.com/EpicPuppy613/maps/blob/main/Blast%20Mining%20II.zip

**Comment by arcadeboss** [comment]
Cool for BM to get an upgrade.   Looking forward to seeing it in action.

**Comment by Tywnis** [comment]
Added
