### ISSUE TITLE
[DTM/24v24] Osoi

### ISSUE THREAD

**Issue by Antnecb** [OvercastCommunity/CommunityMaps#781]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Osoi

### Gamemode & Map Description

Pretty standard TNT DTM map. Inclues 2 monuments per team, a few side islands, diamond blocks that drop chestplates rather than actual blocks (à la Mars Odyssey), and plenty of TNT supplies.

(this was supposed to be a contest map but i was lazy)

Credit to Frosty for skinning the map, and Strange/mame for general advice.

### Team Sizes

24v24

### Screenshots

https://imgur.com/a/BkwFPgX

### XML

https://gist.github.com/Antnecb/11a45f7f314b933e41b88f769778e104

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/26776253/d9e55e6d-a89d-425d-a55e-7accd1b7871d)

### Map Download

https://drive.google.com/file/d/1z6eDOH9GxvRoqdALQVGKRw2TqE6GOhqk/view?usp=sharing

(edit: fixed dl link oops lmao)

**Comment by technodono** [comment]
Looks good. Excited to try it out!

**Comment by arcadeboss** [comment]
The Maneki-neko is nice touch, and I can appreciate the curved draping done with the slabs.

**Comment by Strangeys** [comment]
Loaded. Will likely throw into pools in next pool update.

**Comment by calcastor** [comment]
This has played fine in current pools. There are some updates it could use but these have already been discussed/are already known about, and its current state is more than acceptable. Thanks for submitting!
