### ISSUE TITLE
[CTW/30v30] Peloponnesia

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/CommunityMaps#787]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Peloponnesia

### Gamemode & Map Description

Peloponnesia

- This is dual CTW map with team upgrade store, based on the Peloponnesian War between Sparta and Athens.
- Teams: Sparta vs Athens
- The store has 20 possible upgrades for each team, as well as some items, all priced in emeralds
- Upgrades for armor, sword, pickaxe, axe, shovel, apple to golden apple, bucket to water bucket
- A team is not likely to be able to afford all upgrades unless game lasts over 30 minutes.
- Emerald store chest contains enough emeralds to immediately purchase Stone to Iron pickaxe upgrade
- Players can get emeralds from the 2 generators in mid, from kills, or from mining around the wool rooms.
- Regen iron supply
- Wool rooms (Garrison Houses) are destroyable, and have speed I in chests and a gapple spawner

![2023-08-02_18 56 55](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/077bf093-8263-4683-a204-7e7fb5796a07)

### Team Sizes

30v30

### Screenshots

https://imgur.com/a/3Uqgx7l

### XML

https://gist.github.com/arcadeboss/be81eb49ed48de44591a47a4b146ee01

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/bd969af0-07d6-42de-8f59-645ca049bd9c)

### Map Download

https://github.com/OvercastCommunity/CommunityMaps/pull/786

**Comment by technodono** [comment]
we got some new shop mappers up in here!

**Comment by Guini2** [comment]
wow this map looks really good

**Comment by arcadeboss** [comment]
> I'm wondering if you plan to add any other meaningful upgrades to the shop? There's a lot of weapon upgrading which is nice but may not necessarily be beneficial in the beginning

What did you have in mind?   I considered bedwars-like options and status effects, as you had done, but decided to go with the utilitarian options.

**Comment by technodono** [comment]
> > I'm wondering if you plan to add any other meaningful upgrades to the shop? There's a lot of weapon upgrading which is nice but may not necessarily be beneficial in the beginning
> 
> What did you have in mind? I considered bedwars-like options and status effects, as you had done, but decided to go with the utilitarian options.

Perhaps more defensive blocks could be purchased or simply upgrades that combat water walling n stuff. Also a water lane purchasable might be a cool idea

**Comment by technodono** [comment]
Strangely left me sone good new shop ideas so maybe ask him or other defenders

**Comment by arcadeboss** [comment]
https://github.com/OvercastCommunity/CommunityMaps/pull/811/ - Fixes

    Fixed emerald spawner areas not being protected
    Fixed breakable woolroom chests
    Tuned some regions

**Comment by arcadeboss** [comment]
https://github.com/OvercastCommunity/CommunityMaps/pull/813 - Updates

    Add sound to team upgrades messages
    Increase gapple spawner rate based on feedback from byRobo

**Comment by arcadeboss** [comment]
@TheRealPear - Thank you!

**Comment by calcastor** [comment]
This is in pools and plays well, closing
