### ISSUE TITLE
[SCOREBOX/16v16v16v16] Zap II

### ISSUE THREAD

**Issue by Brettogden** [OvercastCommunity/CommunityMaps#789]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Zap II

### Gamemode & Map Description

Falling blocks bridge map with TNT & scorebox. Most points after 12 mins wins. 

### Team Sizes

4 teams, 16 players each

### Screenshots

https://imgur.com/a/qUaXdYW

### XML

https://gist.github.com/Brettogden/8873025129a2eae9f719adabda2db76b

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/5283695/372a7db3-ae92-46a0-a2a5-07f97450eb50)

### Map Download

[Zap 2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/12307793/Zap.2.zip)

**Comment by Tywnis** [comment]
Added
