### ISSUE TITLE
[Rage/1337v1337] Charge With Bows

### ISSUE THREAD

**Issue by HydrosionMC** [OvercastCommunity/CommunityMaps#791]
### Checklist

- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [x] The map has been tested locally to make sure it works.

### Map Name

Charge with Bows

### Gamemode & Map Description

I use the gamemode rage and just want to play it like Charge, but with bows because it's funny.

### Team Sizes

2 teams of 1337

### XML

https://gist.github.com/HydrosionMC/ed6f9f30b2bcdd0aa1d2136541cd7780

### Map Image

![i01_charge](https://github.com/OvercastCommunity/CommunityMaps/assets/19337648/d3517ca5-78cb-4d76-833d-41ea86e31e29)

### Map Download

[charge_with_bows.zip](https://github.com/OvercastCommunity/CommunityMaps/files/12387063/charge_with_bows.zip)

**Comment by TheRealPear** [comment]
Thanks for your submission! However, this map is currently unusable at its current state. I would recommend finishing the XML, which you could do by [looking at similar maps](https://github.com/OvercastCommunity/CommunityMaps/blob/master/blitz/standard/charge/map.xml) or visiting https://pgm.dev/. If you need assistance, please don't hesitate to reach out in the Discord at #mapmaking.

**Comment by HydrosionMC** [comment]
Edited the XML so it can work now I just need a moderator to test it :)

**Comment by HydrosionMC** [comment]
I hvae tested the map and I updated the download link!

**Comment by zzufx** [comment]
Spoke with the author a while back
