### ISSUE TITLE
[CTW/10v10] Krager

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#792]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Krager

### Gamemode & Map Description

Small 10v10 end themed CTW map

### Team Sizes

10v10

### Screenshots

https://imgur.com/a/Qw43WAz

### XML

https://gist.github.com/oafMH/247586b6c043eb9f776d4632f3401360

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/75836128/d79503d0-5d08-470d-9fc3-dd3a68dcc475)

### Map Download

https://www.dropbox.com/scl/fi/hf0jv1gondrm0sinxs8de/krager.zip?rlkey=zuzrgjg8sgjksc6cy08knvav9&dl=0

**Comment by oafMH** [comment]
https://www.dropbox.com/scl/fo/j9ew5nc2hjadsxp6yeb4u/h?rlkey=zhse706buoirzf3wpby2j1e8e&dl=0

fixed obs spawn

**Comment by RuedigerLP** [comment]
> https://www.dropbox.com/scl/fo/j9ew5nc2hjadsxp6yeb4u/h?rlkey=zhse706buoirzf3wpby2j1e8e&dl=0
> 
> fixed obs spawn

https://github.com/OvercastCommunity/CommunityMaps/commit/451f69044b635807d5c2698de864ba0e952e1d96

**Comment by oafMH** [comment]
https://gist.github.com/oafMH/8e34a21a160b416e37e740bd71ad543b
removed devphase since it got added to pools
