### ISSUE TITLE
[Arcade/24v24] King's Conquest Redux

### ISSUE THREAD

**Issue by mitchts** [OvercastCommunity/CommunityMaps#796]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

King's Conquest: Rage Quit
King's Conquest: Porky Plains
King's Conquest: Lorikeet Lagoon
King's Conquest: Dry Outpost
King's Conquest: Rallypoint Beta

### Gamemode & Map Description

King's Conquest (or Kill the King) is where one member of the team is the King and the rest of the team must protect their King while seeking to eliminate the enemy King.

This is a set of 5 maps for a reworked King's Conquest; 1 existing and 4 brand new (see below).

- Moves King's Conquest logic into a reusable include file.
- The monument to enable blitz has been removed (no more blitz).
- The biggest difference is tracking of the progress towards "killing" the enemy king.
![image](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/180cd319-8258-48e0-b4b0-d5f976fd69b0)
- Once this reaches 0 the King is eliminated and the other team wins.
- As the King's HP reduces on the scoreboard their hearts also reduce to give the King another reference for current HP amount.
![image](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/1cf6b661-dbf6-4427-a6de-ca51321219c3)
- Each King has 3 potions that give speed, strength, and recover 5 HP (HP not recovered during sudden death).
- After 13 minutes have passed a "sudden death" mode is enabled and each King is reduced to 1 HP. The next damage wins.
- When you die you are swapped to the other team. The first time you die you are sent a tip message explaining that you switch teams.
![image](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/91cf5170-1baa-490c-979e-5bc4c0a503ec)

**_What's to stop the King from digging a hole and hiding?_**
Boredom, I hope. We could maybe use some explosives somewhere.

**_How does the King damage work?_**
It's not so much a damage tracker, but more of how many times has the King been hit by the enemy. You can hit the King for 100 hearts of damage or just 1. They'll count for the same amount (1pt).

### Team Sizes

24v24 (default, but can be changed per map via constants)

### Screenshots

https://imgur.com/a/NnfrFQV

### XML

https://gist.github.com/mitchts/fe10a5e063be893c63d91f1f2be23b6a

### Map Image

King's Conquest: Rage Quit (returning)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/8cfbe124-d29a-42a2-8457-ad6879dc2f8a)

King's Conquest: Porky Plains (new)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/f0594501-0f66-48b9-aa4a-733020a98b1b)

King's Conquest: Lorikeet Lagoon (new)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/b3269537-0515-47bb-b231-309630c47abc)

King's Conquest: Dry Outpost (new)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/88fb1db8-c37e-4c64-8654-882a03fe7152)

King's Conquest: Rallypoint Beta (new)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/49cc053d-7382-4af5-be49-3e535db8e959)

King's Conquest: Incendiary (new, inspired by the original Incendiary)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/86c23179-b992-48c3-baa6-74a185612744)

### Map Download

[kings_conquest_redux.zip](https://github.com/OvercastCommunity/CommunityMaps/files/12419080/kings_conquest_redux.zip)

**Comment by mitchts** [comment]
This has been effectively been rewritten since 2 days ago but is now ready. Just dependant on PGM#1220 being merged and updated on OCC.

Main comment updated with current behaviour.

**Comment by mitchts** [comment]
Added a 6th map - King's Conquest: Incendiary. This is inspired by the original King's Conquest Incendiary map created by pikpikmerchant.

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/30c96b4e-1783-4ee1-9ae9-480de8533160)

[The ground begins to grumble...](https://youtu.be/j5nqDoJReW8)

**Comment by calcastor** [comment]
Loaded in 1d5c3345998ebd57777cd2e355966c46315659eb, 4a3b31216ad85f9a3371512b0193f25b87196bc9

**Comment by mitchts** [comment]
**King's Conquest (include) v2.2.0**

- Added more constants to allow team name and colour customisability per map
- Team switching mechanic is now toggleable through an exposed action (default is off)
- Sudden death now triggers after 10 min (previously 13 min)
- Sudden death king HP increased to 5 (previously 1)
- Sudden death now enables blitz
- Kings are now stronger
  - Added sharpness to sword
  - Added power and infinity to bow
  - `King's Beserking Potion` changed to `King's Beserking Warhorn` 
    - Heals 16 king HP 
    - Temporarily buffs whole team 
    - Spawn with 1, gain 1 every 3 kills
- Replaced wooden axes with stone
- Added efficiency to Mason's tools
- Added double jump (8s cooldown) to Scout
- Added TNT kill reward every 2 kills
- Removed pickaxes (cannot obtain materials that require a pickaxe either)

**Porky Plains v1.0.1**

- Fixed sunflowers dropping
- Fixed TNT not breaking grasses

**Dry Outpost v1.0.1**

- Fixed blue side having red coloured blocks

**Incendiary v1.0.1**

- Adjusted lava flow on upper spawn points
- Added sound effects when lava pools are filled

**Rallypoint Beta v1.0.1**

- Fixed TNT not breaking grasses

**Lorikeet Lagoon v1.0.1**

- Fixed TNT not breaking grasses

[kings_conquest_update.zip](https://github.com/OvercastCommunity/CommunityMaps/files/12837942/kings_conquest_update.zip)

https://gist.github.com/mitchts/fe10a5e063be893c63d91f1f2be23b6a/revisions

**Comment by mitchts** [comment]
Updated the old King's Conquest maps to use the new include.

King's Conquest: Apocalyse Ensues (PrivateMaps - DM me for map)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/33638521-8984-410b-b06f-711af133d411)

King's Conquest: Easterly Meadows (formerly King's Conquest: Easter) (PublicMaps)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/ce50db2a-7b9a-40d2-a75f-d04cc388e15c)

King's Conquest: Proelium (PublicMaps)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/41297015-a651-40aa-84ad-36da148d0802)

King's Conquest: Rooted Frontier (PublicMaps)
![map](https://github.com/OvercastCommunity/CommunityMaps/assets/6386297/aa21335b-34d7-4ffa-8680-9cb2b7372c4a)


Also minor fixes to the include that I missed last night.

https://gist.github.com/mitchts/fe10a5e063be893c63d91f1f2be23b6a/revisions

[kings_conquest_redux_maps.zip](https://github.com/OvercastCommunity/CommunityMaps/files/12839611/kings_conquest_redux_maps.zip)
