### ISSUE TITLE
[CTW/24v24] Ikigai

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#799]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Ikigai

### Gamemode & Map Description

Obligatory Japanese themed 24v24 capture the wool map

### Team Sizes

24v24

### Screenshots

https://imgur.com/a/jP79YOf

### XML

https://gist.github.com/oafMH/be08ce6056f688914e22e699d93ce715

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/75836128/2d639fee-b8b5-46f9-84b0-45b280c70543)

### Map Download

https://www.dropbox.com/sh/pqyzm8s8bw0rf6y/AABw929Cd5v5Wr7A0decbhlfa?dl=0

**Comment by calcastor** [comment]
5c8ff7791f349ac8255ac682d779a1028ffed6bf

**Comment by calcastor** [comment]
Closing this for now; last I understood this map needed some fixes and wasn't ready yet. Please feel free to re-open if/when necessary.
