### ISSUE TITLE
[Update] Sakura Garden II, 1.0.2

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#816]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

- As result of adding tnt in some chest to make a quicker defense most of the time people were blowing up the defense supplies chest... We made chest and buttons inmune to tnt on this update
- We changed the height limit from 29 to 26. That way making walls would be easier and faster.
- The main kit for teams changed a little bit: Changing the amount of blocks that people get from 64 Planks and 64 Glass to 48 Planks and 32 Glass, this to prevent people to get on the enemies base faster than before and give defenders a few seconds more to defend

### XML

https://gist.github.com/Lexnardo11/d19015618e879235e803cb110929fc35

### Download Link

The update is in builders dropbox:

https://www.dropbox.com/scl/fo/c43r880w1rce0uspdl2v0/h?rlkey=hdz3repgk1a9auk5nda8z1glr&dl=0
https://www.dropbox.com/scl/fo/c43r880w1rce0uspdl2v0/h?rlkey=hdz3repgk1a9auk5nda8z1glr&dl=0
https://www.dropbox.com/scl/fo/c43r880w1rce0uspdl2v0/h?rlkey=hdz3repgk1a9auk5nda8z1glr&dl=0

**Comment by zzufx** [comment]
Pruned and loaded with changes in [5f959fa](https://github.com/OvercastCommunity/CommunityMaps/commit/5f959fa3eb8a619827ef57fbb63b29d6d8bfbdcf)
