### ISSUE TITLE
[Update] The Waiting Room, v1.3.0

### ISSUE THREAD

**Issue by Lowie375** [OvercastCommunity/CommunityMaps#826]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

- Added halloween variant (The Carving Room)

### XML

https://gist.github.com/Lowie375/e5287c334a952e7242db87e40961225a

### Download Link

Via Google Drive: [The Waiting Room v1.3.0.zip](https://drive.google.com/file/d/1xWHRCLZ-SW7nnZjUCpmL4qcmWTPa0wZY/view)
Via GitHub: [The Waiting Room 1.3.0.zip](https://github.com/OvercastCommunity/CommunityMaps/files/12773559/The.Waiting.Room.1.3.0.zip)

**Comment by TheRealPear** [comment]
I made a slight adjustment to your XML regarding colored blocks. Instead of using separate kits to set the color of stained clays, I moved them to the primary kit and used `team-color` attribute to keep it simple. I've tested on a test server and it is fully functional.
