### ISSUE TITLE
[Funky/10 Per Team] BlackBlack Reborn

### ISSUE THREAD

**Issue by Antnecb** [OvercastCommunity/CommunityMaps#827]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

BlackBlack Reborn

### Gamemode & Map Description

This map is a recreation of an old OCN map titled "BlackBlack," albeit with a few changes. The premise is similar to Dead Heat- a Blitz/CTW map wherein the objective is to either cap the wool or kill all enemies; however, BlackBlack is an 8-team Blitz map with no bows. The major change between the recreation and the original is the size; the original was significally more cramped. Max size for all teams is 10, but the map is designed specifically for Funky Friday type-events, so there isn't really a specific intended team size.

### Team Sizes

10 Per Team

### Screenshots

https://imgur.com/a/rZAKS85

### XML

https://gist.github.com/Antnecb/743217b8652b2ce73f76bdea12a45139

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/26776253/7bd1ad58-6db2-4953-80ef-7ecabbb1aa21)

### Map Download

https://drive.google.com/file/d/1XM9AXYMCao5rhOdFwU3VAjL4rOKLmet5/view?usp=sharing

**Comment by TheRealPear** [comment]
I've made some changes to your XML as I was loading this:
* Combined leather chestplate into a single item that'll automatically use your team color
* Changed spawn regions from `<block>` to `<point>` and removed the 0.5 decimal from the spawns' y coordinate
