### ISSUE TITLE
[DTM/24vs24] Meerkat Dream

### ISSUE THREAD

**Issue by minuyo** [OvercastCommunity/CommunityMaps#852]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Meerkat Dream

### Gamemode & Map Description

The map is 24vs24 DTM, hopefully adventurous, has many hidden ways and items. It's supposed to be a Mole Dream part 2.

### Team Sizes

2 Teams, 24vs24

### Screenshots

https://imgur.com/a/yV16vst

### XML

https://gist.github.com/minuyo/1f5015cd4d51c8891428c9ef3ce0ea9a

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/151182727/0a03e285-5932-4cd4-b05a-7b23d3ae214d)

### Map Download

[Meerkat Dream.zip](https://github.com/OvercastCommunity/CommunityMaps/files/13394668/Meerkat.Dream.zip)

**Comment by calcastor** [comment]
Closing as this is in pools and plays well
