### ISSUE TITLE
[KoTH/5v5] Ilios

### ISSUE THREAD

**Issue by Xenor0** [OvercastCommunity/CommunityMaps#853]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Ilios

### Gamemode & Map Description

KOTH 5V5

### Team Sizes

5V5

### XML

https://gist.github.com/Xenor0/31ca829695f2d5b4ceaf90f463287a7f

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/150296915/6f854b21-7b5b-4f61-b69d-831c32a2487c)

### Map Download

[Xenor06 (2).zip](https://github.com/OvercastCommunity/CommunityMaps/files/13399920/Xenor06.2.zip)

**Comment by technodono** [comment]
It's a bit hard to tell what the map actually looks like in-game since you have a texture pack enabled.
Would it be possible to send a screenshot of the map without it (ideally from a similar angle?)

**Comment by calcastor** [comment]
Loaded here 8df3ed1df448ea1c94607ef9dce1ce332665e750, I converted the XML to use the conquest include we have for both casual and ranked conquest.

This would probably not work well for a ranked map and I have some concerns about how isolated the hills seem for non-ranked as well but it looks nice and I am willing to try it in pools.

**Comment by Xenor0** [comment]
Ok thanks a lot if you have some requests about the Map like for the hills
, could you mp me on discord i'm a member if the differents servers (
stratus , conquest , godzilla and overcast ) . If you wanna voc it Would be
a Real pleasure my discord name and ig name is Xenor06
