### ISSUE TITLE
[Update] Witch's Potions, v1.1.1

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#867]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

Just added a region between the void gap on Magenta and Cyan woolrooms to stop people from boating in and avoiding defenses

### XML

https://gist.github.com/Lexnardo11/8b15765626e6a6762ca1c784a46a380e

### Download Link

The map didn't get any update, just the XML

**Comment by calcastor** [comment]
This is missing changes from the XML in the repo.

**Comment by Lexnardo11** [comment]
> This is missing changes from the currently used XML in the repo.
>  
> Is the bucket in the kit new as well? No issue with adding it.
>  
> edit again: This also shouldn't be a 2.0 update, just to v1.1.1 is fine

Yeah the bucket was added aswell, sorry for not adding it, I made this update a year ago and forgot to upload it so I thought the only change that I did was the unboatable region, and I was trying to implement waterlanes on it too but mapdevs told me it was not necessary so yeah, I played with the XML for a while and forgot what was different at the very end.
