### ISSUE TITLE
[CTW/32v32] Blissful Transit

### ISSUE THREAD

**Issue by PeakDominance** [OvercastCommunity/CommunityMaps#869]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Blissful Transit CTW

### Gamemode & Map Description

Since this description has to be short, it will be missing many important details, but don't worry I've created a [detailed description in a gist!](https://gist.githubusercontent.com/matthewthegymbeast/23b2e1722220665a7e623afcf7b65a57/raw/9a67514207e4882eb1bdf21d2fa12f8f3041af62/gistfile1.txt) Basically the main point of this map is that rushing gets enabled after 20 minutes. Before that players have to fight at a resources arena for resources to get more resources than their enemies and therefore make a better defense and have more gear stored for the rushing phase. Since I want this map to be team-work based there are 3 classes - attackers, defenders and resource gatherers. Attackers have to fight at the arena and defend their gatherers until rushing is enabled, then they can rush the enemy woolroom. They also get crystals for kills so they can buy useful items in the itemshop. Defenders have to build the best defense using the resources that gatherers brought to them and also defend the woolroom after rushing gets enabled. Gatherers have to gather resources at the arena and bring them back to base, optionally craft stuff for attackers/defenders like iron armors or iron bars. If u have any questions, please [read the detailed description](https://gist.githubusercontent.com/matthewthegymbeast/23b2e1722220665a7e623afcf7b65a57/raw/9a67514207e4882eb1bdf21d2fa12f8f3041af62/gistfile1.txt)

### Team Sizes

2 teams, 32 players per team

### Screenshots

https://imgur.com/a/uvG9Wft

### XML

https://gist.github.com/matthewthegymbeast/d628187e18f0de22ee38e4a1d12e8459

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/84674701/4f362cbf-1dc4-48ce-8af7-ec766d4a0596)

### Map Download

https://github.com/matthewthegymbeast/Blissful-Transit-CTW

**Comment by CrazyisCreeps** [comment]
Yo, I probably would avoid using abbreviations such as "ur" in descriptions. Also, I'm having some trouble consistently hitting the launch pad's trajectory - maybe using portals would be a better substitute?  

Otherwise, tbh I'm just a little confused on how the map works. Without adding more walls of text, what could be done to streamline the user understanding of the map? As you seem to get at in the gist, this isn't a map with classic mechanics...and unfortunately that means that there's going to be a learning curve that will probably affect the overall enjoyability of the user experience when playing this map.

**Comment by CrazyisCreeps** [comment]
I bet it looks really cool, I agree with you there. Wouldn't be so cool if someone returning from the arena hit the jump pad on the ship when trying to enter it and died in the void with a full inventory of loot though.

Could just be me, but my mind glazes over as soon as you give me a wall of text to learn how to play a map. If I can't figure it out in the first 30 seconds, I'm already starting to give up.

Anyways just my 2 cents. It can be difficult for maps to have gameplay outside the norm and do well, so best of luck to you! Maybe it'll play great.
