### ISSUE TITLE
[KotH/18v18] Turnstile

### ISSUE THREAD

**Issue by enbytedev** [OvercastCommunity/CommunityMaps#870]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Turnstile

### Gamemode & Map Description

This is a KotH map designed for a match size of around 18v18. Lots of attention went into offering different playstyles and details to make the match more interesting. For example, there are numerous places designed for a bow-oriented player to provide their team aid and various objects which melee-oriented players can use for cover. 
![controlpoint](https://github.com/OvercastCommunity/CommunityMaps/assets/103954556/2f61209a-7e66-402f-8e99-117e63c600c3)

Additional care was also put into making sure there are interesting places to hide, run around, and pop out from behind of. An example of this is the catwalks.
![catwalks](https://github.com/OvercastCommunity/CommunityMaps/assets/103954556/5940501b-8cce-4c19-af06-fb9b836da9d5)

In addition, fun custom items can be found practically everywhere (even the crashed airplanes engines.)
![hangar](https://github.com/OvercastCommunity/CommunityMaps/assets/103954556/397db398-f83d-48bf-809b-5f34707b85cf)

### Team Sizes

18v18

### XML

https://gist.github.com/enbytedev/e04dc4d5b96656685e068f3dfd575989

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/103954556/5d22fbd8-5d64-4834-85e0-7970c535c60a)

### Map Download

[Turnstile.zip](https://github.com/OvercastCommunity/CommunityMaps/files/14490002/Turnstile.zip)

**Comment by TTtie** [comment]
Hey there – this is just a tiny nitpick – but please consider merging the regions defined in `<control-point>` tags together to improve map maintainability, i. e.

```xml
<control-points capture-rule="lead" show-progress="true">
    <control-point name="Tarmac" capture-time="5s">
        <capture> <!-- Where players must stand so this control point can be captured -->
            <cuboid min="-6,1,86" max="-11,5,81" />
        </capture>
        <progress> <!-- The area where colored blocks will fade into the controlling team's color -->
            <cuboid min="-6,1,86" max="-11,5,81" />
        </progress>
        <captured> <!-- The area where colored blocks will change to match the controlling team's color -->
            <cuboid min="-6,1,86" max="-11,5,81" />
        </captured>
    </control-point>
    <!-- ... rest of control point definitions -->
</control-points>
```

to

```xml
<regions>
    <cuboid id="tarmac" min="-6,1,86" max="-11,5,81" />
    <!-- ... rest of control point regions -->
</regions>
<control-points capture-rule="lead" show-progress="true">
    <control-point name="Tarmac" capture-time="5s" capture="tarmac" progress="tarmac" captured="tarmac" />
    <!-- ... rest of control point definitions -->
</control-points>
```

Thanks!

**Comment by enbytedev** [comment]
I really appreciate the feedback!
Per @technodono's advice, I've added a small patch of textured green outside the hangar that helps in breaking up the monotony. I've also added large arrows on the interior walls above the control points. The map layout is difficult to capture in a single photo as part of it is indoors and stacked atop spawn.
Regarding the XML, I've implemented the changes mentioned by @TTtie for control points, spawn areas, and portals. I've also rearranged a few elements to be placed near related settings.
Thank you both!!
[Turnstile.zip](https://github.com/OvercastCommunity/CommunityMaps/files/14503053/Turnstile.zip)

**Comment by technodono** [comment]
> I really appreciate the feedback! Per @technodono's advice, I've added a small patch of textured green outside the hangar that helps in breaking up the monotony. I've also added large arrows on the interior walls above the control points. The map layout is difficult to capture in a single photo as part of it is indoors and stacked atop spawn. Regarding the XML, I've implemented the changes mentioned by @TTtie for control points, spawn areas, and portals. I've also rearranged a few elements to be placed near related settings. Attached is the updated version. Thank you both!! [Turnstile.zip](https://github.com/OvercastCommunity/CommunityMaps/files/14503053/Turnstile.zip)

If at any point you want me to take a closer look at the map and give some more detailed feedback, I’m happy to. My Username is the same on both discord & mc.

and thank you to listening to the feedback

**Comment by technodono** [comment]
> > If at any point you want me to take a closer look at the map and give some more detailed feedback, I’m happy to. My Username is the same on both discord & mc.
> > and thank you to listening to the feedback
> 
> The map is public on mapmaker so u can check it whenever u want, /mapls confect1on

Strange, It came up with nothing for me: 
<img width="270" alt="Screenshot 2024-03-18 at 11 31 03 pm" src="https://github.com/OvercastCommunity/CommunityMaps/assets/22761234/a29f29ac-06ae-4c86-86d1-4bf403f2c1c8">
