### ISSUE TITLE
[Update] Kingdom, 1.0.1

### ISSUE THREAD

**Issue by Scripteding** [OvercastCommunity/CommunityMaps#883]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

Removed rain metadata & added efficiency to tools

### XML

https://gist.github.com/Scripteding/fdd9b00d0bd72e1de76669004321db7f

### Download Link

https://drive.google.com/file/d/1_rd0j2SzATz0dac4CV8J-B-DjyVzwuAJ/view?usp=sharing

**Comment by calcastor** [comment]
Apologies for the delay; download link appears to just be a `.drawio` file.

**Comment by calcastor** [comment]
If the issue is just that rain and thunder are enabled, I will resolve that now and won't need a download.

**Comment by Scripteding** [comment]
Hey @calcastor,

No worries at all, thanks for the reply! I must of accidently linked the wrong file and it should be updated here:
https://drive.google.com/file/d/1_rd0j2SzATz0dac4CV8J-B-DjyVzwuAJ/view?usp=sharing

The only issue w/ the world is the rain/thunder which I removed from the worlds metadata. If there's a better way to fix it feel free to mess around with it. The only other change was adding eff 1 to all tools within the XML and that's it.

Other than that, I might take a look into making a mini version of this map since 40v40s aren't that common.

**Comment by Scripteding** [comment]
I think I might of made a few minor build changes so I'd try that new download first if possible.
