### ISSUE TITLE
[Payload/20v20] Skycastle Islands

### ISSUE THREAD

**Issue by EpicPuppy613** [OvercastCommunity/CommunityMaps#888]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Skycastle Islands

### Gamemode & Map Description

24v24 A/D Payload with 2 checkpoints (3 payloads). The map is played on a field of many different interconnected islands in a somewhat linear layout. The attackers will fight the defenders to get the payload to each checkpoint, at which the spawn points will shuffle. Games should take a maximum of 35 minutes depending on how far the attackers get. The map also includes a 15 minute "Rush Rage" version that can be played during map parties (like Funky Friday).

### Team Sizes

24v24

### Screenshots

https://github.com/EpicPuppy613/maps/blob/main/Skycastle%20Islands.md

### XML

https://gist.github.com/EpicPuppy613/75ab56c88fc3e9a446ff7feeeb6788e3

### Map Image

![map](https://github.com/user-attachments/assets/ba2c8e69-a6cd-4e07-9b56-45509b8bafcb)

### Map Download

https://github.com/EpicPuppy613/maps/blob/main/Skycastle%20Islands.zip

**Comment by EpicPuppy613** [comment]
Updated map to be bigger team sizes (30v30). All original download links should have been updated.

**Comment by calcastor** [comment]
This is loaded.

A couple notes:

1. Please remove the spaces between the XML elements for legibility purposes
2. Maybe invisibility for attackers at initial spawn would work well here, similar to what is done on Bridge maps in the spawn cage.

**Comment by EpicPuppy613** [comment]
## V1.0.3
- Fixed XML formatting
- Gave attackers invisibility on initial spawn
- Tweaked parameters of payload slightly

**Comment by EpicPuppy613** [comment]
# V1.1.0
- [Fix] Fixed golden apple rewards on kill
- Moved side desert island up a bit
- Reduced arrow count of defenders
- Reduced projectile protection level of defenders
- Gave attackers speed when leaving the spawn
- Changed the targets of some tower launchers
- Added a launcher to more easily get to the lime tower
- Added a massive speed zone outside of the attacker airship
- Moved around payload starts and ends a little
- Reduced payload decay rate

Original links have been updated

**Comment by EpicPuppy613** [comment]
## V1.1.1
- Lowered time limit a lot
- Increased arrow kill reward
- Added delay inbetween payloads
- Made a few small map changes
- Decreased team size from 20 to 16
- Fixed pushing the payload back
- Decreased defender respawn time
