### ISSUE TITLE
[CTW/7v7] Dromedary

### ISSUE THREAD

**Issue by eliminate123** [OvercastCommunity/CommunityMaps#896]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Dromedary

### Gamemode & Map Description

CTW 7v7 1 wool each side

### Team Sizes

7v7

### Screenshots

https://imgur.com/6zvYHtt

### XML

https://gist.github.com/eliminate123/d961e2ee253d28fd3827ad4c5c1fe150

### Map Image

![map](https://github.com/user-attachments/assets/f327319e-b8f1-4d73-8b4a-3d3d2236106e)

### Map Download

[Dromedary.zip](https://github.com/user-attachments/files/16352427/Dromedary.zip)

**Comment by technodono** [comment]
It’s nice to see you back again 😁

**Comment by eliminate123** [comment]
> It’s nice to see you back again 😁

im in your walls. better catch up o_o
