### ISSUE TITLE
[KotH/20v20] Beach Battles

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#91]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Beach Battles

## Gamemode & Map Description  
Inspired by the legendary map Cos(TNT), this is a KotH TNT game mode where you try to hold the points for as long as possible. The things which makes this map different is that it only has 2 teams, you cannot enter the enemy team's base and the higer balcony above each point which provides a bombing opportunity.

The map uses explosives and the terrain regenerates so go nuts firing your TNT cannons at the enemy base... you must also bridge to the Control Points, so having a secure bridge is important.

## Team Sizes
20 players per team is the current limit

## Screenshots
https://imgur.com/a/fns6gPK

# XML

as of 1st Dec xml has been updated to fix improper identation
https://gist.github.com/technodono/3eb622b976f772f77d8000530f354aa5

Splitting the 3 regions and giving them each their own renewable is intentional... so don't worry about it.

# Map Image
![map](https://user-images.githubusercontent.com/22761234/100289939-2d04f480-2fce-11eb-96a0-1764b62e274c.png)

# Download Link
[Beach Battles.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5599594/Beach.Battles.zip)

**Comment by CrazyisCreeps** [comment]
I seem to remember testing this out when I was helping with that visual material issue, and I'm interested to see how it'll play. I'll load it up for some map testing, the xml looks fine to me for the time being (other than still some improper indentation)

Ps https://gist.github.com/technodono/3eb622b976f772f77d8000530f354aa5#file-map-xml-L3 does nothing, includes don't work.

**Comment by technodono** [comment]
I'm so annoyed... I never can seem to escape the proper indentation even when I try my hardest to remove it... I'll do some xml tweaks for the next update to fix those issues

**Comment by CrazyisCreeps** [comment]
Honestly it's pretty good, it's just stuff like this. Everything else is great
https://gist.github.com/technodono/3eb622b976f772f77d8000530f354aa5#file-map-xml-L219
https://gist.github.com/technodono/3eb622b976f772f77d8000530f354aa5#file-map-xml-L161
https://gist.github.com/technodono/3eb622b976f772f77d8000530f354aa5#file-map-xml-L300

**Comment by KingOfSquares** [comment]
Enjoyed the map very much :+1:

Couple of thoughts:
- You should remove the tip that says "you can not enter the enemy teams base", since it is now possible to do so.
- I think that tnt/redstone could have a higher height limit(one extra block) to enable the possibility of blowing up bridges
- Gravity should be disabled for sand, since it will regenerate and then just fall.
- All the three islands seemed pretty identical, maybe add some visual queue(in addition to the symbol sign over the island) to either the two side islands or to the central island. Could include some more ornament stuff on the corners by the flags on tip to give it more 3d depth or maybe something under the glass floor.

These are all nitpicking though, since I think the map works great as it is when you have the playercount for it!

**Comment by technodono** [comment]
- gotcha... I'll allow red stone n TNT to be placed up there
- I'll remove that tip... thanks for the heads up
- Gravity shall be disabled... 
- I'll do something about the castles and try make the 2 side diff from the mid

**Comment by master00ofdsiware** [comment]
Fun map, I've added it to the map pools.

I also increased the score limit from 750 to 1250, as the game was a bit too short.
