### ISSUE TITLE
[Kanto] Kanto, Version 1.4.2

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#921]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

- Expand spawn and wool room regions to prevent players sneaking around the edge
- Water lane thickness increased 1 -> 4 blocks
- Increase height limit 30 -> 32 blocks
- Add 32 more wood to spawn kit, total 3 stacks of blocks
- Mid void area now buildable, should spread players out more on sky
- Change map time to be a bit brighter
- Try breakable iron armor

Note: Some people said the spawn kit armor was not unbreakable. I tried to test this on my local server but I had no issues and the armor was unbreakable.

### XML

https://gist.github.com/0uzi/25137b61078eb3fc124d9bf286f2acd6

### Download Link

[Kanto.zip](https://github.com/user-attachments/files/16940305/Kanto.zip)

**Comment by Lexnardo11** [comment]
Oh no...

**Comment by TheRealPear** [comment]
The XML edits doesn't line up with what OCC has (same issue as #922). Mame recently added an `iron-bulkcrafting` include to this map.
