### ISSUE TITLE
[Update] Sky Shot, 1.1.8

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#922]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

- Players were spawning facing the wrong side, we changed the yaw value to fix this on both teams.

### XML

https://gist.github.com/Lexnardo11/1855891bd032d622df55bb8ed49da432

### Download Link

[Sky Shot 1.1.8.zip](https://github.com/user-attachments/files/16998669/Sky.Shot.1.1.8.zip)

**Comment by TheRealPear** [comment]
Your XML edits doesn't line up with what OCC has. Seems like it's before [mame's changes with golden apple kill rewards](https://github.com/OvercastCommunity/CommunityMaps/commit/432afc2d1b5d1302ae9d58d1cbb05fbb62b2a88d).

**Comment by calcastor** [comment]
Closing because of 46a9a980e1fd4511f360d130cfb66fd50b29c690, if there were map world changes please let me know
