### ISSUE TITLE
[Update] Tom Brady, v1.0.1

### ISSUE THREAD

**Issue by TommyHillfigger** [OvercastCommunity/CommunityMaps#937]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.
- [X] Any XML updates are based on the latest version of the map on the server.

### Changes

Updated XML

- no more bridge include
- added how to play book
- flag respawns after 5 seconds instead of 3 after miss

Map aesthetic

- added stands
- people on sidelines

https://lunr.pics/jCgQbQU3.png

### XML

https://gist.github.com/TommyHillfigger/ba1119c1cbc50ecdde179efdd74fe011

### Download Link

https://www.mediafire.com/file/h71ej8o92086lbj/Tom_Brady_v.1.0.1.zip/file

**Comment by technodono** [comment]
Looks much better than it did last update. Good job.

**Comment by arcadeboss** [comment]
Good luck with your game Tommy, looking forward to seeing it play.
