### ISSUE TITLE
[KotF/20v20] Zipmas (Zipline Holiday Skin)

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#94]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Zipmas

## Gamemode & Map Description  
This map is a Christmas variant of Zipline KotF for the Christmas season rotations.
It's mainly a map facelift but 3 lines of xml have been changed to add some flair to the team names this holiday season

## Team Sizes
20v20

## Screenshots
https://imgur.com/a/MuUI24Q

# XML
https://gist.github.com/technodono/79064fad96dc79033067ab66d508ee40

# Map Image
![map](https://user-images.githubusercontent.com/22761234/101438815-452e2980-3967-11eb-8483-b97a26f6e952.png)

# Download Link
[Zipmas.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5656782/Zipmas.zip)

**Comment by CrazyisCreeps** [comment]
Awesome, thanks for reskinning the map for the holidays! I'll swap this out in the pools
