### ISSUE TITLE
[CTW/34v34] Fall of Babylon

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/CommunityMaps#941]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Fall of Babylon

### Gamemode & Map Description

Fall of Babylon
- Double Wool CTW with Stores, 34v34
- Loosely based around the historic final battle of Babylon vs Persia
- The famous Ishtar's Gate of Babylon is adapted for team spawn architecture
- Woolrooms based on Persian wind-catcher towers, an ancient air-cooled design
- Team Store: Gold Ingots buy Status Effects, Kit Items and Enchantments
     Over 20 different team upgrades
     Including Re-purchasable Defensive Webs for woolroom entrances
- Spy Alerts: Keep tabs on the enemy's Protection and Sharpness upgrades
- Player Store: Diamonds buy permanent diamond Armor, Weapons, Tools and a few Items
     9 player upgrades including a Diamond Knockback Hoe
- Wool rooms feature several areas and lots of loot
     Entry room - Gapples, wool-color glass blocks
     Wool room - Wool, Sharp Swords, Speed, exclusive Prot 1 Helmets that don't drop
     Sniper room - 1 weak Fire Bow, slow Arrow spawner, Sniper window with removeable slabs
     Loot rooms - 4 separate rooms above Wool room with loot chests
     Upper platform - Above build height, but can snipe, jump or boat out
- Wool Seals: Thunder and Alert lets entire match know when any of 4 Seals are broken
     Seals are a diamond block that blocks access to wool chest until broken
- Block drops ala Mame, but rewards are nuggets and gold ore
     Original block drop mechanic retained in some cases
     For example, dirt drops half the time instead of never
     Players can remine for more loot, but it's diminishing returns
- Diamond spawners at lower mid for player upgrade store
- Gapple spawner at sky mid
- Gold spawners at outer mid drop nuggets, ingots and ore
- Gold ore introduces smelting as important team upgrade operation
- Generous defensive pickaxes that get nerfed at mid area
- Redstone Lamps are lit above each wool monument on a wool place
     Game-winning wool in proximity will light lamps early
- Many kill rewards including gold, diamonds and player-damage auto TNT
- Renewable Iron supply
- Many loot chests some obvious, some hidden
     Most are "sealed" with a block to let players know if loot is plundered
     Several chests are visible but "hidden" from observers, until unsealed

### Team Sizes

34v34

### Screenshots

https://imgur.com/a/fall-of-babylon-C3z2j6n

### XML

https://raw.githubusercontent.com/OvercastCommunity/CommunityMaps/d22452aa577cb24d8a8e422386ce5494d9a1ee74/ctw/standard/fall_of_babylon/map.xml

### Map Image

![babylon-map](https://github.com/user-attachments/assets/6778bc26-a19f-434c-8288-9b2f85143aa9)

![YuoWwAS](https://github.com/user-attachments/assets/b998742a-c7fe-4245-83a3-75bd82eedd5d)

![WZlgZCt](https://github.com/user-attachments/assets/e89684b8-21e9-431f-b698-728d20ecbefe)

### Map Download

https://github.com/OvercastCommunity/CommunityMaps/pull/940

**Comment by 0uzi** [comment]
Oh my gosh bro this map is stunning! You have absolutely outdone yourself once again. Really looking forward to playing this 🔥🔥

**Comment by technodono** [comment]
this is the most interesting idea for a map thus far
