### ISSUE TITLE
[Update] Ringpull, 1.2.1

### ISSUE THREAD

**Issue by 0uzi** [OvercastCommunity/CommunityMaps#942]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.
- [X] Any XML updates are based on the latest version of the map on the server.

### Changes

In the CommunityMaps/ctw folder there are 3 folders: christmas, halloween, and standard. christmas and halloween only consist of map variants for Ringpull. I condensed Ringpull and its variants Ringnull and Crackerpull into one file. These are Caz's maps but he's inactive so I thought it would be nice to do it for him. Now I hope that we can remove the unnecessary subfolders in CommunityMaps/ctw.
No changes to the map and I tried not to change anything about the XML however I did add gapple kill reward include and contributor to the variants.

### XML

https://gist.github.com/0uzi/33683e0eb9cb1eaed7c273e50433e402

### Download Link

[ringpull.zip](https://github.com/user-attachments/files/17181539/ringpull.zip)

**Comment by calcastor** [comment]
The reason this had not been done previously is due to Ringnull needing physical changes to align with Ringpull

**Comment by 0uzi** [comment]
Is that because the portal to the wool?

**Comment by calcastor** [comment]
> Is that because the portal to the wool?

Bit more than that, but working on updating the map itself so I'll commit it with the xml changes. Thanks.

**Comment by 0uzi** [comment]
👍 these are all the issues i could find https://imgur.com/a/zJNDTcA
