### ISSUE TITLE
[DTM/16v16] Snowpelli (Scrapelli christmas variant)

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#969]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Snowpelli

### Gamemode & Map Description

Destroy the Monument.

Christmas has arrived on Scrapelli with a new look for this season.

### Team Sizes

16v16

### Screenshots

https://imgur.com/a/2Q1Ttze

### XML

https://gist.github.com/Lexnardo11/464a09f26130e81003193120e18dafa5

### Map Image

![image](https://github.com/user-attachments/assets/43954a86-9ae6-4c1f-aeaf-25d36542125e)

![image](https://github.com/user-attachments/assets/ae1b60a9-d775-4627-a3ea-b2d3a5dfe243)

### Map Download

[Snowpelli.zip](https://github.com/user-attachments/files/18033174/Snowpelli.zip)

**Comment by arcadeboss** [comment]
Nice work.

I know time is of the essence here, but looks like the XML will need to be variant-ized, i.e. the differences from this new XML into the existing XML with variant tags.

Someone can probably help with this, but I'm not sure how these requests are typically handled since I'm new.  Please keep in mind as you wait.

**Comment by Lexnardo11** [comment]
Aight, I can understand that <3
