### ISSUE TITLE
[CTW/24v24] Santa's Gifts

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#972]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Santa's Gifts

### Gamemode & Map Description

Capture The Wool

Now christmas has arrived on Witch's Potions

### Team Sizes

24 v 24

### Screenshots

https://imgur.com/a/E54CNot

### XML

https://gist.github.com/Lexnardo11/661e80ab253a8c35fa03e261f93b562d

### Map Image

![image](https://github.com/user-attachments/assets/9efb9c7f-9d53-495a-a054-47f95c33f0ca)
![image](https://github.com/user-attachments/assets/b361c15f-400e-4a82-8b35-8ae4c51950ae)

### Map Download

[Santa's Gifts.zip](https://github.com/user-attachments/files/18055938/Santa.s.Gifts.zip)

**Comment by 0uzi** [comment]
This is the most insane Christmas edit :o
